"""Build the fixed 512x128 room contract before any castle exterior art."""
from pathlib import Path
import json
from PIL import Image, ImageDraw, ImageEnhance

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "content/castles/modular_v2/source"
OUT = ROOT / "content/castles/modular_v4/rooms"
RUNTIME = ROOT / "Resources/res/castle_rooms_v4"
NAME_INCLUDE = ROOT / "Classes/CastleRoomV4Names.inc"
CATALOG = ROOT / "content/castles/modular_v4/room_catalog.png"
STACKS = ROOT / "content/castles/modular_v4/room_stack_contract.png"

ROOM_SIZE = (512, 128)
ROOM_BAND = (410, 595)
THEMES = (
    "food production", "forge / armory", "barracks / training",
    "alchemy laboratory", "engineering workshop", "healing infirmary",
    "command room", "crystal reactor", "shadow sanctum",
    "celestial observatory",
)


def trim(image: Image.Image, pad: int = 2) -> Image.Image:
    box = image.getchannel("A").getbbox()
    if not box:
        raise ValueError("empty room source")
    x0, y0, x1, y1 = box
    return image.crop((max(0, x0-pad), max(0, y0-pad),
                       min(image.width, x1+pad), min(image.height, y1+pad)))


def fixed_room(image: Image.Image) -> Image.Image:
    image = trim(image).resize((504, 120), Image.Resampling.LANCZOS)
    result = Image.new("RGBA", ROOM_SIZE)
    result.alpha_composite(image, (4, 4))
    return result


def build() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    RUNTIME.mkdir(parents=True, exist_ok=True)
    rooms = {}
    for floor in range(1, 11):
        sheet = Image.open(SOURCE / f"castle_{floor:02d}.png").convert("RGBA")
        for stage in range(0, 6):
            source_level = max(1, stage)
            x0 = round((source_level-1) * sheet.width / 5)
            x1 = round(source_level * sheet.width / 5)
            room = fixed_room(sheet.crop((x0, ROOM_BAND[0], x1, ROOM_BAND[1])))
            if stage == 0:
                alpha = room.getchannel("A")
                room = ImageEnhance.Brightness(room).enhance(.62)
                room.putalpha(alpha)
            name = f"floor_{floor:02d}_stage_{stage}.png"
            room.save(OUT / name, optimize=True)
            room.save(RUNTIME / name, optimize=True)
            rooms[(floor, stage)] = room

    # Full-resolution 10 x 5 audit sheet: every cell must be exactly 512x128.
    label_w, label_h = 220, 42
    catalog = Image.new("RGBA", (label_w + 6*512, label_h + 10*128), (20, 29, 35, 255))
    draw = ImageDraw.Draw(catalog)
    for stage in range(0, 6):
        draw.text((label_w+stage*512+12, 12), "BASE" if stage==0 else f"UPGRADE {stage}", fill="white")
    for floor in range(1, 11):
        y = label_h+(floor-1)*128
        draw.text((10, y+48), f"FLOOR {floor:02d}  {THEMES[floor-1]}", fill="white")
        for stage in range(0, 6):
            catalog.alpha_composite(rooms[(floor, stage)], (label_w+stage*512, y))
    catalog.save(CATALOG, optimize=True)

    # Assembly contract: castle N contains exactly floors 1..N.  Rooms remain
    # 4:1 and use one common display scale; only the number of slots changes.
    display_w, display_h = 192, 48
    gap, base_y = 28, 620
    stacks = Image.new("RGBA", (10*(display_w+gap)+gap, 690), (20, 29, 35, 255))
    draw = ImageDraw.Draw(stacks)
    for castle in range(1, 11):
        x = gap+(castle-1)*(display_w+gap)
        for floor in range(1, castle+1):
            room = rooms[(floor, 5)].resize((display_w, display_h), Image.Resampling.LANCZOS)
            stacks.alpha_composite(room, (x, base_y-floor*display_h))
        draw.text((x+65, base_y+10), f"{castle}F", fill="white")
    stacks.save(STACKS, optimize=True)

    manifest = {
        "version": 4,
        "room_size": list(ROOM_SIZE),
        "aspect_ratio": "4:1",
        "floor_count": 10,
        "upgrade_count": 5,
        "states_per_floor": 6,
        "asset_count": 60,
        "themes": list(THEMES),
        "assembly_rule": "castle N contains floors 1 through N; previous floors are level 5",
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    names = ["// Generated by tools/castles/build_v4_rooms.py.\n"]
    for floor in range(1, 11):
        for stage in range(0, 6):
            names.append(f'\t"castle_rooms_v4/floor_{floor:02d}_stage_{stage}",\n')
    NAME_INCLUDE.write_text("".join(names), encoding="utf-8")
    print(f"built 60 fixed rooms at {ROOM_SIZE[0]}x{ROOM_SIZE[1]}")
    print(CATALOG)
    print(STACKS)


if __name__ == "__main__":
    build()
