# Bake the six authored deck concepts per castle into one exact 736x144 part.
# The concept art is scaled uniformly by WIDTH only. Its lower portion is
# covered by the existing stage-specific 512x64 chassis, never distorted.
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
Add-Type -ReferencedAssemblies System.Drawing -TypeDefinition @'
using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;

public static class CastleCombatDeckBake {
    static Rectangle AlphaBounds(Bitmap bitmap, Rectangle cell) {
        int minX=cell.Right, minY=cell.Bottom, maxX=cell.Left-1, maxY=cell.Top-1;
        for(int y=cell.Top;y<cell.Bottom;y++) for(int x=cell.Left;x<cell.Right;x++) {
            if(bitmap.GetPixel(x,y).A<20) continue;
            minX=Math.Min(minX,x); minY=Math.Min(minY,y);
            maxX=Math.Max(maxX,x); maxY=Math.Max(maxY,y);
        }
        if(maxX<minX) throw new Exception("Empty deck cell: "+cell);
        return Rectangle.FromLTRB(minX,minY,maxX+1,maxY+1);
    }
    public static void Run(string root) {
        string concepts=Path.Combine(root,"tools","castles","concepts");
        string exterior=Path.Combine(root,"Resources","res","castle_exterior");
        string mobility=Path.Combine(root,"Resources","res","castle_mobility");
        Directory.CreateDirectory(exterior);
        var names=new System.Text.StringBuilder();
        for(int castle=2;castle<=10;castle++) {
            string sheetPath=Path.Combine(concepts,String.Format("castle_{0:00}_combat_deck_sheet.png",castle));
            using(var sheet=new Bitmap(sheetPath)) {
                for(int stage=0;stage<6;stage++) {
                    int col=stage%2, row=stage/2;
                    var cell=Rectangle.FromLTRB(col*sheet.Width/2,row*sheet.Height/3,
                        (col+1)*sheet.Width/2,(row+1)*sheet.Height/3);
                    Rectangle bounds=AlphaBounds(sheet,cell);
                    string basePath=Path.Combine(mobility,
                        String.Format("castle_{0:00}_base_stage_{1}.png",castle,stage));
                    using(var chassis=new Bitmap(basePath))
                    using(var deck=new Bitmap(736,144,PixelFormat.Format32bppArgb))
                    using(var g=Graphics.FromImage(deck)) {
                        if(chassis.Width!=512 || chassis.Height!=64)
                            throw new Exception("Bad chassis dimensions: "+basePath);
                        g.Clear(Color.Transparent);
                        g.InterpolationMode=InterpolationMode.HighQualityBicubic;
                        g.PixelOffsetMode=PixelOffsetMode.HighQuality;
                        // Continuous 512px joint directly under the room.
                        // Later-stage finials rise above the deck's wall and
                        // would otherwise leave transparent gaps between them.
                        g.DrawImage(chassis,new Rectangle(112,0,512,32),
                            new Rectangle(0,0,512,32),GraphicsUnit.Pixel);
                        // 640-wide upper deck sits around the 512-wide room.
                        // The authored picture keeps its own aspect ratio.
                        int artHeight=(int)Math.Round(bounds.Height*640.0/bounds.Width);
                        g.DrawImage(sheet,new Rectangle(48,0,640,artHeight),bounds,GraphicsUnit.Pixel);
                        // The old base owns the entire bottom 64 px. This
                        // overlap hides variable concept-sheet lower edges.
                        g.CompositingMode=CompositingMode.SourceCopy;
                        using(var clear=new SolidBrush(Color.Transparent))
                            g.FillRectangle(clear,0,80,736,64);
                        g.CompositingMode=CompositingMode.SourceOver;
                        g.DrawImageUnscaled(chassis,112,80);
                        string dest=Path.Combine(exterior,
                            String.Format("castle_{0:00}_combat_deck_stage_{1}.png",castle,stage));
                        deck.Save(dest,ImageFormat.Png);
                        names.AppendFormat("\t\"castle_exterior/castle_{0:00}_combat_deck_stage_{1}\",\n",castle,stage);
                    }
                }
            }
        }
        File.WriteAllText(Path.Combine(root,"Classes","CastleCombatDeckNames.inc"),
            "// Generated by tools/castles/build_castle02_10_combat_decks.ps1.\n"+names.ToString());
    }
}
'@
$root=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path
[CastleCombatDeckBake]::Run($root)
Write-Host 'Built 54 combat decks, each exactly 736x144, from castle 2-10 concepts.'
