"""Build all 120 fixed-size castle base and mobility sprites."""
from pathlib import Path
from PIL import Image, ImageChops, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parents[2]
GEN = Path(r"C:\Users\polyp\.codex\generated_images\01a0de43-6120-72f2-9314-8e5fb074b287")
SOURCE = ROOT / "content/castles/mobility_all"
RUNTIME = ROOT / "Resources/res/castle_mobility"
NAMES = ROOT / "Classes/CastleMobilityNames.inc"

BASE_SHEETS = (
    "exec-e5a11879-3c18-4766-a3ab-8129a47a5b51.png",
    "exec-9ac547ad-afe3-4482-afa1-4d8eed50cea6.png",
    "exec-47612a75-ee86-4f80-a90a-9fda486c7e13.png",
    "exec-41868f6a-88bc-49c4-8b47-4c560e821bc1.png",
    "exec-f533c65d-d313-4c3e-bae5-cce898a0f522.png",
    "exec-950ba1f7-7a54-4406-be0b-2f322666e150.png",
    "exec-e4ef523d-543e-4649-bb72-4705c699fd0a.png",
    "exec-ff6f1f4e-501f-43ff-99aa-c5c55c775380.png",
    "exec-f0a777f9-5b86-45cb-aa71-44df42645e0b.png",
    "exec-240c746f-f952-4986-8c9d-b1fbb8166f86.png",
)
WHEEL_SHEETS = (
    "exec-f662a797-486b-43d2-9aa0-1ada2852cf08.png",
    "exec-3bd4ac7a-b1c2-4b56-8166-a9123295f478.png",
    "exec-163dc04e-67cb-4537-a45f-d1f03c5676e3.png",
    "exec-49bbf08b-2256-43c9-a14e-48b187e1247f.png",
    "exec-17afe11e-0651-40a0-8590-b2783bcbb4fb.png",
    "exec-c02f8012-be00-4ebc-a7f1-b8de3cb5f301.png",
)
HOVER_SHEETS = (
    "exec-f450f244-d7aa-4efa-9c26-88f92f5fa8ea.png",
    "exec-5faa19a8-900e-47d3-8f17-ade6fbff17c2.png",
    "exec-65ec2a92-adf4-4c8a-bbb6-a06b7e80ac36.png",
    "exec-8030dfb2-204e-495b-87fb-1fc3dce64385.png",
)

def clean(image: Image.Image) -> Image.Image:
    image = image.convert("RGBA")
    alpha = image.getchannel("A").point(lambda value: 0 if value < 8 else value)
    image.putalpha(alpha)
    return image

def save(image: Image.Image, name: str, size: tuple[int, int]) -> None:
    if image.size != size:
        raise ValueError(f"{name}: {image.size}, expected {size}")
    image.save(SOURCE / name, optimize=True)
    image.save(RUNTIME / name, optimize=True)

def tight_resize(image: Image.Image, size: tuple[int, int]) -> Image.Image:
    """Remove authored transparent row padding before fitting an attachment part."""
    bbox = image.getchannel("A").getbbox()
    if not bbox:
        raise ValueError("empty authored mobility row")
    return image.crop(bbox).resize(size, Image.Resampling.LANCZOS)

def build() -> None:
    SOURCE.mkdir(parents=True, exist_ok=True)
    RUNTIME.mkdir(parents=True, exist_ok=True)
    names = []

    for castle, sheet_name in enumerate(BASE_SHEETS, 1):
        sheet = clean(Image.open(GEN / sheet_name))
        if sheet.size != (1448, 1086):
            raise ValueError(f"bad base sheet {sheet_name}: {sheet.size}")
        for stage in range(6):
            room = sheet.crop((0, stage * 181, 1448, (stage + 1) * 181))
            name = f"castle_{castle:02d}_base_stage_{stage}.png"
            save(tight_resize(room, (512, 64)), name, (512, 64))
            names.append(f'\t"castle_mobility/{name[:-4]}",\n')

    for castle, sheet_name in enumerate(WHEEL_SHEETS, 1):
        sheet = clean(Image.open(GEN / sheet_name))
        if sheet.size != (1024, 1536):
            raise ValueError(f"bad wheel sheet {sheet_name}: {sheet.size}")
        for stage in range(6):
            wheel = sheet.crop((384, stage * 256, 640, (stage + 1) * 256))
            mask = Image.new("L", (256, 256))
            ImageDraw.Draw(mask).ellipse((16, 16, 240, 240), fill=255)
            mask = mask.filter(ImageFilter.GaussianBlur(1.5))
            wheel.putalpha(ImageChops.multiply(wheel.getchannel("A"), mask))
            name = f"castle_{castle:02d}_wheel_stage_{stage}.png"
            save(wheel.resize((128, 128), Image.Resampling.LANCZOS), name, (128, 128))
            names.append(f'\t"castle_mobility/{name[:-4]}",\n')

    for castle, sheet_name in enumerate(HOVER_SHEETS, 7):
        sheet = clean(Image.open(GEN / sheet_name))
        if sheet.size != (1448, 1086):
            raise ValueError(f"bad hover sheet {sheet_name}: {sheet.size}")
        for stage in range(6):
            part = sheet.crop((0, stage * 181, 1448, (stage + 1) * 181))
            name = f"castle_{castle:02d}_hover_stage_{stage}.png"
            save(tight_resize(part, (512, 64)), name, (512, 64))
            names.append(f'\t"castle_mobility/{name[:-4]}",\n')

    expected = 60 + 36 + 24
    if len(names) != expected:
        raise ValueError(f"built {len(names)}, expected {expected}")
    NAMES.write_text("// Generated by tools/castles/build_all_castle_mobility.py.\n" + "".join(names), encoding="utf-8")
    print(f"built {expected} castle base/mobility sprites")

if __name__ == "__main__":
    build()
