# Extract the authored gun heads from the command posts. The command platform
# remains at 192x128; the separate gun is allowed to grow with castle grade.
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing
Add-Type -ReferencedAssemblies System.Drawing -TypeDefinition @'
using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
public static class CastleHeavyCannonBake {
    static Rectangle AlphaBounds(Bitmap src) {
        int l=src.Width,t=src.Height,r=-1,b=-1;
        for(int y=0;y<src.Height;y++) for(int x=0;x<src.Width;x++) {
            if(src.GetPixel(x,y).A<40) continue;
            l=Math.Min(l,x);t=Math.Min(t,y);r=Math.Max(r,x);b=Math.Max(b,y);
        }
        if(r<l) throw new Exception("Empty cannon source");
        return Rectangle.FromLTRB(l,t,r+1,b+1);
    }
    static void FitHeavyGun(Bitmap source,Bitmap target,int castle,int stage) {
        var crop=AlphaBounds(source);
        // Widen the bore and armor with every grade. Height gains more than
        // length so the cannon feels heavier without reaching across combat.
        int width=Math.Min(124,82+7*stage+2*(castle-2));
        int height=Math.Min(60,39+4*stage+castle-2);
        using(var g=Graphics.FromImage(target)) {
            g.Clear(Color.Transparent);
            g.InterpolationMode=InterpolationMode.HighQualityBicubic;
            g.PixelOffsetMode=PixelOffsetMode.HighQuality;
            g.DrawImage(source,new Rectangle(126-width,64-height,width,height),
                crop,GraphicsUnit.Pixel);
        }
    }
    public static void Run(string root) {
        string dir=Path.Combine(root,"Resources","res","castle_exterior");
        string concepts=Path.Combine(root,"tools","castles","concepts");
        int[] gunStart={0,0,103,103,100,99,88,102,101,104,67};
        for(int castle=2;castle<=10;castle++) for(int stage=0;stage<6;stage++) {
            string baseName=String.Format("castle_{0:00}",castle);
            string source=Path.Combine(dir,String.Format("{0}_balcony_stage_{1}.png",baseName,stage));
            // The high castles begin with a larger caliber even at stage 0.
            // Their stage-0 original barrel was no larger than castle 1's.
            int caliberLead=castle>=10?5:(castle>=9?3:(castle>=8?2:(castle==7?1:0)));
            int gunStage=Math.Min(5,stage+caliberLead);
            string gunSource=Path.Combine(dir,String.Format("{0}_balcony_stage_{1}.png",baseName,gunStage));
            using(var src=new Bitmap(source))
            using(var turretSrc=new Bitmap(gunSource)) {
                if(src.Width!=192||src.Height!=128) throw new Exception("Bad balcony dimensions: "+source);
                using(var rawGun=new Bitmap(128,64,PixelFormat.Format32bppArgb))
                using(var gun=new Bitmap(128,64,PixelFormat.Format32bppArgb))
                using(var platform=new Bitmap(192,128,PixelFormat.Format32bppArgb)) {
                    using(var g=Graphics.FromImage(platform)) g.DrawImage(src,0,0);
                    // The large turret projects above the rail (source y<64).
                    // Keep the balcony below intact, including its standing room.
                    for(int y=0;y<60;y++) for(int x=gunStart[castle];x<192;x++) {
                        // Lower rail plates stay on the platform and the
                        // gun's upper body gets its own scalable pass.
                        if(y>=52 && x<gunStart[castle]+15) continue;
                        rawGun.SetPixel(x-64,y,turretSrc.GetPixel(x,y));
                        platform.SetPixel(x,y,Color.Transparent);
                    }
                    if(castle>=7 && stage==5) {
                        using(var finalGun=new Bitmap(Path.Combine(concepts,
                                  String.Format("castle_{0:00}_heavy_cannon_final.png",castle))))
                            FitHeavyGun(finalGun,gun,castle,stage);
                    } else FitHeavyGun(rawGun,gun,castle,stage);
                    gun.Save(Path.Combine(dir,String.Format(
                        "{0}_heavy_cannon_stage_{1}.png",baseName,stage)),ImageFormat.Png);
                    platform.Save(Path.Combine(dir,String.Format(
                        "{0}_command_platform_stage_{1}.png",baseName,stage)),ImageFormat.Png);
                }
            }
        }
        using(var writer=new StreamWriter(Path.Combine(root,"Classes","CastleHeavyCannonNames.inc"),
                                          false,System.Text.Encoding.UTF8)) {
            writer.WriteLine("// Generated by tools/castles/build_castle02_10_heavy_cannons.ps1.");
            for(int castle=2;castle<=10;castle++) for(int stage=0;stage<6;stage++)
                writer.WriteLine(String.Format(
                    "\t\"castle_exterior/castle_{0:00}_heavy_cannon_stage_{1}\",",castle,stage));
        }
        using(var writer=new StreamWriter(Path.Combine(root,"Classes","CastleCommandPlatformNames.inc"),
                                          false,System.Text.Encoding.UTF8)) {
            writer.WriteLine("// Generated by tools/castles/build_castle02_10_heavy_cannons.ps1.");
            for(int castle=2;castle<=10;castle++) for(int stage=0;stage<6;stage++)
                writer.WriteLine(String.Format(
                    "\t\"castle_exterior/castle_{0:00}_command_platform_stage_{1}\",",castle,stage));
        }
    }
}
'@
[CastleHeavyCannonBake]::Run((Resolve-Path .).Path)
