param([switch]$AllowIncomplete)
$ErrorActionPreference = 'Stop'
$root = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$assetDir = Join-Path $root 'Resources/castles/tier01_modular'
Add-Type -AssemblyName System.Drawing
Add-Type -ReferencedAssemblies System.Drawing -TypeDefinition @'
using System;
using System.Drawing;
public static class ModularPngScan {
 public static string Read(string path, bool armor, bool wheel) {
  using(var im = new Bitmap(path)) {
   int w=im.Width,h=im.Height,x0=w,y0=h,x1=-1,y1=-1,clear=0;
   byte[] alpha=new byte[w*h];
   for(int y=0;y<h;y++) for(int x=0;x<w;x++) {
    byte a=im.GetPixel(x,y).A; alpha[y*w+x]=a;
    if(a==0)clear++;
    if(a>16){x0=Math.Min(x0,x);y0=Math.Min(y0,y);x1=Math.Max(x1,x);y1=Math.Max(y1,y);}
   }
   if(clear==0 || x1<0)throw new Exception("No transparent background / empty: "+path);
   int ox=0,oy=0,ow=0,oh=0;
   if(armor){
    int cx=(x0+x1)/2,cy=(y0+y1)/2;
    if(alpha[cy*w+cx]>16)throw new Exception("Armor opening is not transparent: "+path);
    int[] q=new int[w*h];bool[] seen=new bool[w*h];int head=0,tail=0;
    q[tail++]=cy*w+cx;seen[cy*w+cx]=true;
    int lx=cx,ly=cy,rx=cx,by=cy;
    while(head<tail){
     int p=q[head++],x=p%w,y=p/w;
     lx=Math.Min(lx,x);ly=Math.Min(ly,y);rx=Math.Max(rx,x);by=Math.Max(by,y);
     if(x<=x0 || x>=x1 || y<=y0 || y>=y1)throw new Exception("Armor window leaks outside frame: "+path);
     int[] nn={p-1,p+1,p-w,p+w};
     foreach(int n in nn)if(!seen[n] && alpha[n]<=16){seen[n]=true;q[tail++]=n;}
    }
    ox=lx;oy=ly;ow=rx-lx+1;oh=by-ly+1;
   }
   if(wheel){
    int side=Math.Max(x1-x0+1,y1-y0+1);int cx=(x0+x1+1)/2,cy=(y0+y1+1)/2;
    x0=Math.Max(0,cx-side/2);y0=Math.Max(0,cy-side/2);x1=x0+side-1;y1=y0+side-1;
    if(x1>=w || y1>=h)throw new Exception("Wheel lacks rotation padding: "+path);
   }
   // Spire foot is the center of opaque pixels in a strip above its lowest edge.
   int footY=Math.Max(y0,y1-8),footLeft=w,footRight=-1;
   for(int x=x0;x<=x1;x++)if(alpha[footY*w+x]>128){footLeft=Math.Min(footLeft,x);footRight=Math.Max(footRight,x);}
   double footX=footRight>=0?(footLeft+footRight+1)*.5:(x0+x1+1)*.5;
   return string.Format(System.Globalization.CultureInfo.InvariantCulture,
    "{{\"width\":{0},\"height\":{1},\"clearPixels\":{2},\"crop\":[{3},{4},{5},{6}],\"opening\":[{7},{8},{9},{10}],\"footX\":{11}}}",
    w,h,clear,x0,y0,x1-x0+1,y1-y0+1,ox,oy,ow,oh,footX);
  }
 }
}
'@
$parts = @('armor','cannon','wheel','spire','interior')
$records = @()
$cpp = [Collections.Generic.List[string]]::new()
$cpp.Add('#pragma once')
$cpp.Add('// Generated by tools/castles/export_modular_metadata.ps1; PNGs are not modified.')
$cpp.Add('namespace CastleParts {')
$cpp.Add('struct Asset { int x,y,w,h; int ox,oy,ow,oh; float footX; };')
$cpp.Add('static const Asset kAssets[5][5] = {')
foreach($part in $parts){
 $cpp.Add('  { // '+$part)
 for($level=1;$level -le 5;$level++){
  $file = $part+'_'+$level+'.png'
  $path = Join-Path $assetDir $file
  if(-not (Test-Path -LiteralPath $path)){
   if(-not $AllowIncomplete){throw "Missing module $file"}
   $cpp.Add('    {0,0,1,1,0,0,0,0,0.0f},')
   continue
  }
  $r = [ModularPngScan]::Read($path,($part -eq 'armor'),($part -eq 'wheel')) | ConvertFrom-Json
  $r | Add-Member -NotePropertyName file -NotePropertyValue $file
  $r | Add-Member -NotePropertyName part -NotePropertyValue $part
  $r | Add-Member -NotePropertyName level -NotePropertyValue $level
  $records += $r
  $values = @($r.crop)+@($r.opening)
  $foot = ([double]$r.footX).ToString('0.0',[Globalization.CultureInfo]::InvariantCulture)
  $cpp.Add('    {'+($values -join ',')+','+$foot+'f},')
 }
 $cpp.Add('  },')
}
$cpp.Add('};')
$cpp.Add('}')
$utf8 = [Text.UTF8Encoding]::new($false)
[IO.File]::WriteAllLines((Join-Path $root 'Classes/CastleModularAssets.h'),$cpp,$utf8)
$manifest = [ordered]@{
 version=1; tier=1; view='orthographic_side'; parts=$parts; levels=5
 scene=@{width=1760;height=1080;groundY=1000}
 armor=@{x=230;y=460;width=1300;height=380}
 spire=@{footX=1400;footY=495;heightBase=330;heightStep=18}
 cannon=@{rightX=1450;leftInnerX=310;y=572;widthBase=220;widthStep=20}
 wheel=@{radius=160;centers=@(@(480,840),@(1280,840))}
 layerOrder=@('interior','cannon','spire','armor','wheel')
 interiorBleed=4; assets=$records; generator='built-in image_gen'
}
[IO.File]::WriteAllText((Join-Path $assetDir 'manifest.json'),($manifest | ConvertTo-Json -Depth 10),$utf8)
# A script wrapper lets the standalone preview work without a local web server.
[IO.File]::WriteAllText((Join-Path $assetDir 'manifest.js'),('window.CASTLE_MANIFEST='+($manifest | ConvertTo-Json -Depth 10 -Compress)+';'),$utf8)
Write-Output ('Validated modules: '+$records.Count+'/25')
