# -*- coding: utf-8 -*-
"""시트에서 자른 조각을 성 파츠 스물다섯 자리에 넣는다.

[파츠 다섯 자리의 뜻이 바뀌었다]

전에는 장갑 / 대포 / 바퀴 / 첨탑 / 내부 였다. 새 시트에는 "가운데가 뚫린
장갑 틀" 이 없다 - 몸통 그림이 틀과 실내를 한 덩어리로 그려 놓았다. 그래서
자리를 이렇게 쓴다. 파일 이름과 이미지 번호(MODCASTLE_*)는 그대로 둔다.
이름을 바꾸면 Text.h / ImgDef.h / 매니페스트가 같이 흔들린다.

    armor     -> 몸통 (틀 + 실내)
    cannon    -> 대포
    wheel     -> 차대 (바퀴 두 짝이 붙은 한 덩어리)
    spire     -> 첨탑
    interior  -> 난간 (+ 깃발과 등불을 구워 넣는다)

깃발과 등불은 자리가 없어서 난간 그림에 합쳐 넣는다. 자리를 새로 파려면
이미지 번호부터 늘려야 하는데, 그 셋은 늘 난간과 같이 붙어 다니므로
한 장으로 묶어도 잃는 것이 없다.

    python tools/castles/install_sheet_parts.py
"""
import os
import shutil
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CUT = os.path.join(ROOT, "output", "castle-tier01-sheet")
DST = os.path.join(ROOT, "Resources", "castles", "tier01_modular")
HDR = os.path.join(ROOT, "Classes", "CastleModularAssets.h")

#단마다 어떤 조각을 쓰는가. 시트에 있는 변형만 쓴다 - 없는 단은 앞 단을
#그대로 물려받는다(차대는 시트에 한 덩어리뿐이다).
PLAN = {
    "armor":    [15, 14, 13, 13, 12],   #빈 틀 -> 가구가 들어찬 방
    "cannon":   [33, 31, 48, 44, 43],   #짧은 포 -> 포차
    "wheel":    [30, 30, 30, 30, 30],   #차대는 한 종류뿐이다
    "spire":    [17, 17, 17, 16, 16],   #작은 탑 -> 큰 탑
    "interior": [28, 28, 26, 26, 26],   #작은 난간 -> 큰 난간
}

#난간에 얹을 깃발과 등불. 단이 오르면 깃발도 커진다.
FLAG = [19, 19, 18, 18, 18]
LAMP = [None, None, 25, 25, 25]

ORDER = ["armor", "cannon", "wheel", "spire", "interior"]


def cut(n):
    return Image.open(os.path.join(CUT, "p%03d.png" % n)).convert("RGBA")


def bbox_of(im):
    b = im.getbbox()
    return b if b else (0, 0, im.width, im.height)


#차대 그림 안에서 바퀴 두 짝이 앉은 자리. 세로가 꽉 찬 구간으로 재서 나온
#값이다(378x92 짜리 p030 기준).
CHASSIS_HUB = (45.5, 331.5, 46.0, 46.0)   # 왼축 x, 오른축 x, 축 y, 반지름


def make_chassis(n):
    """빔과 바퀴를 한 장에 나눠 담는다.

    바퀴가 돌아야 하는데 차대가 한 덩어리라 돌릴 수가 없었다. 바퀴를 원으로
    도려내 빔에는 구멍을 남기고, 도려낸 바퀴는 오른쪽에 따로 붙인다. 그리는
    쪽은 왼쪽(빔)을 그대로 깔고 오른쪽(바퀴)을 축 자리에 두 번, 각도를 주어
    찍는다.

    자리는 Asset 의 x,y,w,h(빔)와 ox,oy,ow,oh(바퀴)로 넘긴다 - 뚫린 창을
    가리키던 칸인데 이 시트에는 창이 없어 비어 있었다.
    """
    src = cut(n)
    w, h = src.size
    lx, rx, cy, r = CHASSIS_HUB
    d = int(r * 2)

    px = src.load()
    beam = src.copy()
    bp = beam.load()
    disc = Image.new("RGBA", (d, d), (0, 0, 0, 0))
    dp = disc.load()

    for y in range(h):
        for x in range(w):
            for hx in (lx, rx):
                if (x - hx) ** 2 + (y - cy) ** 2 <= r * r:
                    if hx == lx:          # 바퀴 그림은 왼쪽 것 한 짝만 쓴다
                        ox, oy = int(x - lx + r), int(y - cy + r)
                        if 0 <= ox < d and 0 <= oy < d:
                            dp[ox, oy] = px[x, y]
                    bp[x, y] = (0, 0, 0, 0)
                    break

    out = Image.new("RGBA", (w + d, max(h, d)), (0, 0, 0, 0))
    out.alpha_composite(beam, (0, 0))
    out.alpha_composite(disc, (w, 0))
    return out, (0, 0, w, h), (w, 0, d, d)


def make_parapet(para, flag, lamp):
    """난간 + 깃발 + 등불을 한 장으로. 깃대 밑동이 난간에 닿아야 한다."""
    pp = cut(para)
    fl = cut(flag)
    ln = cut(lamp) if lamp is not None else None

    #깃대는 난간 오른쪽 위에 선다. 위로 솟으므로 그만큼 천장을 연다.
    top = fl.height - int(pp.height * 0.35)
    w = max(pp.width, 0)
    out = Image.new("RGBA", (w, pp.height + top), (0, 0, 0, 0))

    flx = int(pp.width * 0.62)
    out.alpha_composite(fl, (min(flx, w - fl.width), 0))

    if ln is not None:
        out.alpha_composite(ln, (max(0, pp.width - ln.width - 2), top - ln.height // 3))

    out.alpha_composite(pp, (0, top))

    return out.crop(bbox_of(out))


def main():
    made = {}

    rects = {}

    for part in ORDER:
        for lv in range(5):
            name = "%s_%d" % (part, lv + 1)

            if part == "interior":
                im = make_parapet(PLAN[part][lv], FLAG[lv], LAMP[lv])
                rects[name] = ((0, 0, im.width, im.height), (0, 0, 0, 0))
            elif part == "wheel":
                im, beam, disc = make_chassis(PLAN[part][lv])
                rects[name] = (beam, disc)
            else:
                im = cut(PLAN[part][lv])
                im = im.crop(bbox_of(im))
                rects[name] = ((0, 0, im.width, im.height), (0, 0, 0, 0))

            im.save(os.path.join(DST, name + ".png"))
            made[name] = im.size

    #---- 조립표 ----
    #
    #조각 파일은 제 경계에 맞게 잘려 있으므로 대개 x,y 는 0 이고 w,h 가
    #그림 크기다. 차대만 한 장에 빔과 바퀴를 나눠 담아서 두 사각형을 쓴다.
    lines = []
    lines.append("#pragma once")
    lines.append("// Generated by tools/castles/install_sheet_parts.py")
    lines.append("// Slots: armor=body, cannon, wheel=chassis, spire, interior=parapet.")
    lines.append("// wheel: x,y,w,h is the beam (wheels punched out);")
    lines.append("//        ox,oy,ow,oh is the loose wheel, drawn twice and spun.")
    lines.append("namespace CastleParts {")
    lines.append("struct Asset { int x,y,w,h; int ox,oy,ow,oh; float footX; };")
    lines.append("static const Asset kAssets[5][5] = {")

    for part in ORDER:
        lines.append("  { // %s" % part)
        for lv in range(5):
            name = "%s_%d" % (part, lv + 1)
            (x, y, w, h), (ox, oy, ow, oh) = rects[name]
            lines.append("    {%d,%d,%d,%d,%d,%d,%d,%d,%.1f}," %
                         (x, y, w, h, ox, oy, ow, oh, w / 2.0))
        lines.append("  },")

    lines.append("};")
    lines.append("}")

    with open(HDR, "w", encoding="utf-8", newline="") as f:
        f.write("\n".join(lines) + "\n")

    for part in ORDER:
        print(part, [made["%s_%d" % (part, i + 1)] for i in range(5)])


main()
