#pragma once
#ifndef _DATA_H_
#define _DATA_H_
//#pragma pack (1)
//x, y, w, h\jj
//Î°úÎìúÎßµÏ? ?§Ìîà?òÎäî Î©îÎâ¥??Ï°∞Í±¥???Ä???ïÎ≥¥Î•??¥Ï? Î∞∞Ïó¥?¥Îã§.
//int loadMap[] = {
//	//1. Îß®Ï≤ò?åÏóê ?¥Î¶¨??Í≤ÉÏ? ?òÏä§?∏Ïù¥??
//	//-> ?¥Î¶¨??Ï°∞Í±¥ (10Î≤àÏß∏ Î≥¥Ïä§Î•??¥Î¶¨?¥ÌïòÎ©??¥Î¶∞??)
//	//2. ?êÎ≤àÏß∏Î°ú ?¥Î¶¨??Í≤ÉÏ? PVP ?òÏä§?∏Ïù¥??
//	//-> 

//};
//
// ===== ?∞Ïù¥???§Îçî ?åÏùº Include =====

#include "Def.h"
#include "Data/AlphaData.h"
#include "Data/BattleData.h"
#include "Data/CastleData.h"
#include "Data/CollectionData.h"
#include "Data/DemoData.h"
#include "Data/DropData.h"
#include "Data/EnemyData.h"
#include "Data/FontData.h"
#include "Data/GachaData.h"
#include "Data/GameData.h"
#include "Data/imgData.h"
#include "Data/ItemData.h"
#include "Data/MapData.h"
#include "Data/HeroData.h"
#include "Data/ObjectData.h"
#include "Data/QuestData.h"
#include "Data/RewardData.h"
#include "Data/RouletteData.h"
#include "Data/ShopData.h"
#include "Data/SkillData.h"
#include "Data/TextData.h"
#include "Data/UIData.h"
#include "Data/WaveData.h"


const int getHeroLv[] = {
	//0, 4, 9,
	0, 0, 0,
};

const int getSkillSlotLv[] = {
	5, 10, 15, 20, 25,
};

const int getMonsterSlotLv[] = {
	8, 17, 28,
};

const float heroZoom[] = {
	1.0f,
	1.0f,
	1.0f,
};

const int setHeroCastlePos[] = {
	10 * TSIZE, 15 * TSIZE,
	8 * TSIZE, 13 * TSIZE,
	12 * TSIZE, 15 * TSIZE,

	//10 * TSIZE, 16 * TSIZE,
	//9 * TSIZE - TSIZE / 2, 16 * TSIZE,
	//11 * TSIZE + TSIZE / 2, 16 * TSIZE,
};

const int setHeroPos[] = {
	//stage1//?ÑÎç∏?ºÏù∏ ??
	LOBBYPOSITION_X, 14 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 14 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 14 * TSIZE,

	//stage2//?™Ï??Ä
#ifdef MOVETEST
	LOBBYPOSITION_X - 4 * TSIZE, 14 * TSIZE,
#else
	LOBBYPOSITION_X, 14 * TSIZE,
#endif
	LOBBYPOSITION_X - HEROPOSITIONGAP, 14 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 14 * TSIZE,

	//stage3//Í∏àÎã®??Í≥ÑÍ≥°
	LOBBYPOSITION_X, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 18 * TSIZE,

	//stage4//?ÑÌ??Ä?∞Ïä§
	LOBBYPOSITION_X, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 18 * TSIZE,

	//stage5//ÏßÄ?òÎèÑ
	LOBBYPOSITION_X, 18 * TSIZE + 4 * _2X,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 18 * TSIZE + 4 * _2X,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 18 * TSIZE + 4 * _2X,

	//stage6//?ÑÎç∏?âÏõê
	LOBBYPOSITION_X, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 18 * TSIZE,

	//stage7//?çÏóº???ÄÏßÄ
	LOBBYPOSITION_X, 12 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 12 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 12 * TSIZE,

	//stage8//?†Íµ¨??ÎπôÏõê
	LOBBYPOSITION_X, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 18 * TSIZE,

	//stage9//?åÏ†Ñ??Í≥µÎ∞©
	LOBBYPOSITION_X, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 18 * TSIZE,

	//stage10//?©Ìòº???±Ïó≠
	LOBBYPOSITION_X, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 18 * TSIZE,

	//stage11//Í≥®Î†ò??Í≥ÑÍ≥°
	LOBBYPOSITION_X, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 18 * TSIZE,

	//stage12//Ïπ†Ìùë???¨Ïó∞
	LOBBYPOSITION_X, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 18 * TSIZE,

	//stage13//?úÎûòÍ≥§Ïùò Î¨¥Îç§
	LOBBYPOSITION_X, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 18 * TSIZE,

	//stage14//ÎßùÏûê???ÑÏãú
	LOBBYPOSITION_X, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 18 * TSIZE,

	//stage15//ÎßàÏôï??
	LOBBYPOSITION_X, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 18 * TSIZE,

	//stage16//?∞Ï£ºÍ≥µÍ∞Ñ
	LOBBYPOSITION_X, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 18 * TSIZE,

	//stage17//?¨Í∏∞??
	LOBBYPOSITION_X, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP, 18 * TSIZE,
	LOBBYPOSITION_X - HEROPOSITIONGAP * 2, 18 * TSIZE,

};

const int setEnemyPos[] = {
	//stage1//?ÑÎç∏?ºÏù∏ ??
	BATTLEPOSITION_ENEMY_X, TSIZE * 14,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 16,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 14,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 16,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 14,

	//stage2//?™Ï??Ä
#ifdef MOVETEST
	BATTLEPOSITION_ENEMY_X + 4 * TSIZE, TSIZE * 12,
#else
	BATTLEPOSITION_ENEMY_X, TSIZE * 13 + TSIZE / 2,
#endif
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 17,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 13,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 17,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 12 + TSIZE / 2,

	//stage3//Í∏àÎã®??Í≥ÑÍ≥°
	BATTLEPOSITION_ENEMY_X, TSIZE * 17,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 17,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 17,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 17,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 17,

	//stage4//?ÑÌ??Ä?∞Ïä§
	BATTLEPOSITION_ENEMY_X, TSIZE * 17,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 17,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 17,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 17,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 17,

	//stage5//?ÑÎç∏?ºÏù∏ ÏßÄ?òÎèÑ
	BATTLEPOSITION_ENEMY_X, TSIZE * 18 + 4 * _2X,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 18,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 18 + 4 * _2X,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 18,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 18 + 4 * _2X,

	//stage6//?ÑÎç∏?ºÏù∏ ?âÏõê
	BATTLEPOSITION_ENEMY_X, TSIZE * 19,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 18,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 19,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 18,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 19,

	//stage7//?çÏóº???ÄÏßÄ
	BATTLEPOSITION_ENEMY_X, TSIZE * 12,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 16,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 12,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 16,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 12,

	//stage8//?†Íµ¨??ÎπôÏõê
	BATTLEPOSITION_ENEMY_X, TSIZE * 16,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 16,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 16,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 16,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 16,

	//stage9//?åÏ†Ñ??Í≥µÎ∞©
	BATTLEPOSITION_ENEMY_X, TSIZE * 17,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 17,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 17,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 17,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 17,

	//stage10//?©Ìòº???±Ïó≠
	BATTLEPOSITION_ENEMY_X, TSIZE * 19,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 19,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 19,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 19,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 19,

	//stage11//Í≥®Î†ò???ëÍ≥°
	BATTLEPOSITION_ENEMY_X, TSIZE * 19,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 19,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 19,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 19,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 19,

	//stage12//ÎßùÏûê???ÑÏãú
	BATTLEPOSITION_ENEMY_X, TSIZE * 16,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 16,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 16,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 16,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 16,

	//stage13//ÎßàÏôï??
	BATTLEPOSITION_ENEMY_X, TSIZE * 18,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 18,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 18,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 18,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 18,

	//stage14//?∞Ï£º
	BATTLEPOSITION_ENEMY_X, TSIZE * 18,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 18,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 18,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 18,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 18,

	//stage15//?¨Í∏∞??
	BATTLEPOSITION_ENEMY_X, TSIZE * 18,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3), TSIZE * 18,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 2, TSIZE * 18,
	//BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 3, TSIZE * 18,
	BATTLEPOSITION_ENEMY_X + (TSIZE + TSIZE / 3) * 4, TSIZE * 18,
};


//?ÑÎ†à?ÑÎ≥Ñ
const float hitNumZoom[] = {
	0.0f,//1
	0.0f,//2
	0.1f,//3
	0.2f,//4
	0.3f,//5
	0.4f,//6
	0.5f,//7
	0.6f,//8
	0.7f,//9
	0.8f,//10
	0.9f,//11
	0.89f,//12
	0.88f,//13
	0.87f,//14
	0.86f,//15
	0.85f,//16
	0.86f,//17
	0.87f,//18
	0.88f,//19
	0.89f,//20
	0.9f,//21
	0.8f,//22
	0.7f,//23
	0.6f,//24
	0.5f,//25
	0.4f,//26
	0.3f,//27
	0.2f,//28
	0.1f,//29
	0.0f,//30
	0.0f,//31
};

const int num2Off[] = {
	//dx, dy, x, y, gapx, gapy,
	63, 80, 1, 0, 0, 0,
	44, 80, 67, 0, 0, 0,
	57, 80, 120, 0, 0, 0,
	59, 80, 180, 0, 0, 0,
	66, 80, 245, 0, 0, 0,
	56, 80, 316, 0, 0, 0,
	60, 80, 379, 0, 0, 0,
	59, 80, 442, 0, 0, 0,
	62, 80, 505, 0, 0, 0,
	61, 80, 573, 0, 0, 0,
};

const float battleFrameZoom[] = {
	0.1f,//1
	0.2f,//2
	0.3f,//3
	0.4f,//4
	0.5f,//5
	0.7f,//6
	0.9f,//7
	1.2f,//8
	1.5f,//9
	1.8f,//10
	2.1f,//11
	2.5f,//12
	2.9f,//13
	3.4f,//14
	4.0f,//15
	4.7f,//16
	5.5f,//17
	6.4f,//18
	7.5f,//19
	8.6f,//20
	9.8f,//21
	11.0f,//22
	12.5f,//23
	14.0f,//24
	16.0f,//25
	18.0f,//26
	20.0f,//27
	22.0f,//28
	25.0f,//29
	30.0f,//30
};

const signed int reelBgOffset[] = {
	513, 1,//?ºÎ∞ò
	513, 1,//Í∞ÄÎ¶?
	513, 1,//Í≥†ÏÜç
};

const signed int reelPostion[] = {
	98, -160,
	260, -160,
	420, -160,
};

// Î¶¥Î≥Ñ ?úÏûë ÏßÄ???º‚ÜíÏ§ë‚Üí??
const int reelStartFrame[] = { 8, 14, 20 };
const int reelStopBegin[] = { 24, 34, 44 };    // Í≥†ÏÜç???ΩÍ∞Ñ ?ûÎãπÍ≤??ùÎÉÑ
const int reelSnapFrame[] = { 30, 42, 54 };  // Í∞êÏÜç??Í∏∏Í≤å

// ---------- STAR ?ïÎ•† ?åÏù¥Î∏?----------
static float gStarBaseProb[10] = {
	// idx 0 unused
		0.0f,
		0.35f,  // STAR1
		0.25f,  // STAR2
		0.15f,  // STAR3
		0.10f,  // STAR4
		0.07f,  // STAR5
		0.04f,  // STAR6
		0.025f, // STAR7
		0.015f, // STAR8
		0.005f  // STAR9 (0.5%)
};

// ?úÎãù ?åÎùºÎØ∏ÌÑ∞
static const int   PITY_TRIGGER = 10;   // 10Î≤??ôÏïà Í≥†Îì±Í∏?ÎØ∏Ï∂ú??
static const float PITY_BONUS = 0.20f; // Í≥†Îì±Í∏??ïÎ•† +20%
static const float REGION_PENALTY = 0.65f; // Í∞ôÏ? ÏßÄ??Î∞òÎ≥µ ???ïÎ•† Í∞êÏÜå
static const float STAR_PENALTY = 0.70f; // Í∞ôÏ? STAR Î∞òÎ≥µ ??Í∞êÏÜå


//?¨ÎùºÍ∞Ä???§ÌÖù?¥Îûë
//?¥Î†§Í∞Ä???§ÌÖù ?êÍ?ÏßÄÎ°?Î∂ÑÎ¶¨
//?¨ÎùºÍ∞Ä???ÑÎ†à?ÑÍ≥º, ?¥Î†§Í∞Ä???ÑÎ†à?ÑÏùÑ Î∂ÑÎ¶¨

//
//3Í∞úÏùò Ïª§ÏÑú?ÑÏπò, ?¥Îèô?çÎèÑ

const float coinScatterInfoRaid[20 * COINSCATTERRAIDINFOSIZE] = {
	//0
	-ITEMICONSIZE, -ITEMICONSIZE,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//1
	ITEMICONSIZE * 2,-ITEMICONSIZE * 2,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//2
	-ITEMICONSIZE * 3, -ITEMICONSIZE * 3,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//3
	ITEMICONSIZE * 4, -ITEMICONSIZE * 4,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//4
	-ITEMICONSIZE * 5, -ITEMICONSIZE * 5,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//5
	ITEMICONSIZE * 2, -ITEMICONSIZE * 4,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//6
	ITEMICONSIZE * 2, -ITEMICONSIZE * 3,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//7
	ITEMICONSIZE * 3, -ITEMICONSIZE * 2,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//8
	ITEMICONSIZE * 4, -ITEMICONSIZE * 1,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//9
	ITEMICONSIZE * 5, -ITEMICONSIZE * 0,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//10
	-ITEMICONSIZE * 1, -ITEMICONSIZE,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//11
	-ITEMICONSIZE * 2, -ITEMICONSIZE * 2,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//12
	-ITEMICONSIZE * 3, -ITEMICONSIZE * 3,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//13
	-ITEMICONSIZE * 4, -ITEMICONSIZE * 4,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//14
	-ITEMICONSIZE * 5, -ITEMICONSIZE * 5,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//15
	ITEMICONSIZE * 1, -ITEMICONSIZE * 4,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//16
	ITEMICONSIZE * 2, -ITEMICONSIZE * 3,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//17
	ITEMICONSIZE * 3, -ITEMICONSIZE * 2,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//18
	ITEMICONSIZE * 4, -ITEMICONSIZE * 1,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

	//19
	ITEMICONSIZE * 5, -ITEMICONSIZE * 1,
	8 * _2X * 2, 2 * _2X * 2, 8 * _2X * 2, 2 * _2X * 2,
	CURRENCYWAITINGFRAMEMAX, CURRENCYWAITINGFRAMEMAX,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE2, 0.3f, CURRENCYICON_ENDSIZE2, CURRENCYICON_STARTSIZE, -0.2f,

};

//targetX, targetY, targetX2, targetY2, (Í∏∞Ï??Ä DX / 2, DY / 2)
//speed, speedIncrement, speed2, sppedIncrement2,
//waitFrame, waitFrame2
//zoom, zoomEnd, zoomIncrement, zoom2, zoomEnd2, zoomIncrement2
//
const float coinScatterInfo[20 * COINSCATTERINFOSIZE] = {
	//0
	-32 * _2X - ITEMICONSIZE, 360 * _2X + ITEMICONSIZE, -32 * _2X - ITEMICONSIZE - 32 * _2X, -800 * _2X,
	(52 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//1
	64 * _2X - ITEMICONSIZE, 332 * _2X + ITEMICONSIZE, 64 * _2X - ITEMICONSIZE + 64 * _2X, -800 * _2X,
	(60 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//2
	-96 * _2X - ITEMICONSIZE, 288 * _2X + ITEMICONSIZE, -96 * _2X - ITEMICONSIZE - 96 * _2X, -800 * _2X,
	(48 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//3
	128 * _2X - ITEMICONSIZE, 320 * _2X + ITEMICONSIZE, 128 * _2X - ITEMICONSIZE + 128 * _2X, -800 * _2X,
	(44 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//4
	-160 * _2X - ITEMICONSIZE, 384 * _2X + ITEMICONSIZE, -160 * _2X - ITEMICONSIZE - 160 * _2X, -800 * _2X,
	(56 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//5
	32 * _2X - ITEMICONSIZE, 358 * _2X + ITEMICONSIZE, 32 * _2X - ITEMICONSIZE + 32 * _2X, -800 * _2X,
	(54 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//6
	64 * _2X - ITEMICONSIZE, 298 * _2X + ITEMICONSIZE, 64 * _2X - ITEMICONSIZE + 64 * _2X, -800 * _2X,
	(58 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//7
	96 * _2X - ITEMICONSIZE, 348 * _2X + ITEMICONSIZE, 96 * _2X - ITEMICONSIZE + 96 * _2X, -800 * _2X,
	(62 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//8
	128 * _2X - ITEMICONSIZE, 306 * _2X + ITEMICONSIZE, 128 * _2X - ITEMICONSIZE + 128 * _2X, -800 * _2X,
	(46 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//9
	160 * _2X - ITEMICONSIZE, 288 * _2X + ITEMICONSIZE, 160 * _2X - ITEMICONSIZE + 160 * _2, -800 * _2X,
	(50 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//10
	-32 * _2X - ITEMICONSIZE, 384 * _2X + ITEMICONSIZE, -32 * _2X - ITEMICONSIZE - 32 * _2X, -800 * _2X,
	(45 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//11
	-64 * _2X - ITEMICONSIZE, 402 * _2X + ITEMICONSIZE, -64 * _2X - ITEMICONSIZE - 64 * _2X, -800 * _2X,
	(60 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//12
	-96 * _2X - ITEMICONSIZE, 396 * _2X + ITEMICONSIZE, -96 * _2X - ITEMICONSIZE - 96 * _2X, -800 * _2X,
	(47 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//13
	-128 * _2X - ITEMICONSIZE, 412 * _2X + ITEMICONSIZE, -128 * _2X - ITEMICONSIZE - 128 * _2X, -800 * _2X,
	(63 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//14
	-160 * _2X - ITEMICONSIZE, 384 * _2X + ITEMICONSIZE, -160 * _2X - ITEMICONSIZE - 160 * _2X, -800 * _2X,
	(49 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//15
	32 * _2X - ITEMICONSIZE, 312 * _2X + ITEMICONSIZE, 32 * _2X - ITEMICONSIZE + 32 * _2X, -800 * _2X,
	(61 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//16
	64 * _2X - ITEMICONSIZE, 384 * _2X + ITEMICONSIZE, 64 * _2X - ITEMICONSIZE + 64 * _2X, -800 * _2X,
	(51 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//17
	96 * _2X - ITEMICONSIZE, 308 * _2X + ITEMICONSIZE, 96 * _2X - ITEMICONSIZE + 96 * _2X, -800 * _2X,
	(59 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//18
	128 * _2X - ITEMICONSIZE, 384 * _2X + ITEMICONSIZE, 128 * _2X - ITEMICONSIZE + 128 * _2X, -800 * _2X,
	(53 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

	//19
	160 * _2X - ITEMICONSIZE, 384 * _2X + ITEMICONSIZE, 160 * _2X - ITEMICONSIZE + 160 * _2X, -800 * _2X,
	(57 * _2X - 12 * _2X) * 2, -3 * _2X * 2, 4 * _2X * 2, 4 * _2X * 2,
	0, 0,
	CURRENCYICON_STARTSIZE, CURRENCYICON_ENDSIZE, 0.1f, CURRENCYICON_ENDSIZE, CURRENCYICON_ENDSIZE2, 0.1f,

};

#endif

