#pragma once

// Image Handling & Drawing
void NewGameImgLoad(void);
void LoadImg(int);
void LoadTexture(int);
void LoadSpriteFromTexture(int);
void LoadBuffSpriteFromTexture(int, cocos2d::Layer*);
void LoadFontLabelFromString(std::string);
void AfterSpriting(cocos2d::Sprite*);
void AfterBuffering(cocos2d::Sprite*);
int GetSpriteIndex(int);
int GetBufferSpriteIndex(int, cocos2d::Layer*);
int GetTextLabelIndex(int);
void FreeImg(int);
std::string convertToString(char*, int);
std::string GetResourceName(int, int);
int GetTypeByZoom(int, int);
void DrawBuffer(int x, int y, int w, int h, cocos2d::RenderTexture*);
void DrawArray(int, int, int, float zoom, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void RotateImage(int w, int h, int xs, int ys, int x, int y, bool flipX, float rotation, int effect, int alpha, float zoom, Vec2 anchorPoint, cocos2d::Sprite * src, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, int srcIdx, bool buffering);
void DrawImage(int w, int h, int xs, int ys, int x, int y, bool flipX, int cmfRotation, float rotation, int effect, int alpha, float zoom, cocos2d::Sprite * src, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, int srcIdx, bool buffering);
void DrawImageScale(int w, int h, int xs, int ys, int x, int y, bool flipX, int cmfRotation, float rotation, int effect, int alpha, float zoomX, float zoomY, cocos2d::Sprite* src, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, int srcIdx, bool buffering);
void BrightImage(int, int, int, int, int, int, int, float zoom, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void ShadowImage(int, int, int, int, int, int, int, float, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void ProcessWave(void);
void Waterize(int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void ZoomImage(int, int, cocos2d::RenderTexture*, cocos2d::Layer*, int, bool);
void GammaImage(int, int, float, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void InitContext(void);
void SetSectionClip(int, int, int, int, bool);
void UnSectionClip(bool);
void SetColor(int);
void SetFontColor(int);
void ScreenDarken(int);
void MemRectFrameThick(int, int, int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void MemRect(int, int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void MemRectFrame(int, int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void MemRectBoth(int, int, int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void MemRectBothThick(int, int, int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void MemRectRound(int, int, int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void MemRectGraph(int, int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawColorFrame(int, int, int, int, int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawFrame(int, int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawEquipFrame(int, int, int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawWindow5(int x, int y, int w, int h, int mapIdx, float zoom, int mapOffsetY, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawWindow4(int, int, int, int, int, float zoom, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawWindow3(int, int, int, int, int, float zoom, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawRoundBar(int x, int y, float percent, int type, int color, int alpha, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawGuage(int x, int y, int w, int h, long cur, long max, int bgCol, int fullCol, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawRouletteNum(long long, int, int, int, bool, float zoom, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawRouletteNumSmall(long long, int, int, int, bool, float zoom, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
float DrawRouletteNumIcon(long long, int, int, int, bool, int align, float zoom, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawLabelStr(int x, int y, char* str, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawLabel(int, int, int, float zoom, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawStageEnemyWave(int x, int y, int stageBossType, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawStageLabel(int x, int y, int textIdx, int stage, int room, bool label, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawDiorama(int x, int y, int type, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawDioramaEnemy(int x, int y, int stage, int room, float zoom, int dropFrame, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawDioramaCrew(HOUSE* housePtr, int x, int y, float zoom, int dropFrame, bool hand, bool star, int emoticon, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawStageDiorama(int x, int y, int stage, int room, bool label, float zoom, bool cur, bool hand, bool star, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawGrid(int, int, int, int, int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void GradiationFrame(int, int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void SetBlend(int, int);
void UnSetBlend(void);
void SetAlpha(int);
float GetAlphaWidth(int, int, float);
float GetAlphaWidth2(int, float);
float GetGoldAlphaWidth(int idx, int type, float zoom);
void DrawGoldAlpha(int x, int y, int idx, int type, float zoom, int align, bool ani, float rotation, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawAlpha(int x, int y, int idx, int type, float zoom, float rotation, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawAlpha2(int x, int y, int idx, int type, float zoom, float rotation, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void CenterAlpha(int, int, int, int, float, float, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawAlphaFrame(int, int, int, int, bool, int, float, float);
void addCommasToNumber(int number, bool showSign, char* result, size_t bufferSize);
int GetNumFigure(long long int);
float GetNumDx2(long long int num, int sign, int digit, bool comma, float zoom, bool fixed);
float GetNumDx(long long int num, int sign, int font, int digit, bool comma, float zoom, bool fixed);
float GetGoldNumDx(long long int, int, int, bool, float);
float GetBigNumGoldDx(long long int num, int sign, int font, int digit, bool comma, float width, float zoom);
float GetBigNumDxTTF(long long int num, int sign, int font, int digit, bool comma, float width, float zoom, bool fixed);
float GetBigNumDx(long long int num, int sign, int font, int digit, bool comma, float width, float zoom, bool fixed);
void DrawXNumGold(long long int num, int x, int y, bool ani, float zoom, int align, int digit, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawXNum(long long int, int, int, bool, float, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawSlashNum(int min, int max, int x, int y, float width, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
float DrawNumTTF(long long int num, int x, int y, int font, int align, int digit, bool sign, bool comma, float zoom, bool fixed, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawNum2(long long int num, int x, int y, int align, int digit, int sign, bool comma, float zoom, bool fixed, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawNum(long long int num, int x, int y, int font, int align, int digit, bool sign, bool comma, float zoom, bool fixed, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawGoldNum(long long int num, int x, int y, int align, int digit, int sign, bool comma, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawBigNumGold(long long int num, int x, int y, int font, int align, int digit, int sign, float width, bool comma, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
float DrawBigNumTTF(long long int num, int x, int y, int font, int align, int digit, int sign, float width, bool comma, float zoom, bool fixed, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawBigNum(long long int num, int x, int y, int font, int align, int digit, int sign, float width, bool comma, float zoom, bool fixed, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawNum2AutoSpaceing(long long int num, int x, int y, int align, int digit, int sign, float width, bool comma, float zoom, bool fixed, bool bold, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawBigNum2Bold(long long int num, int x, int y, int align, int digit, int sign, float width, bool comma, float zoom, bool fixed, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawBigNum2(long long int num, int x, int y, int align, int digit, int sign, float width, bool comma, float zoom, bool fixed, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawStarNum(int icon, int star, int x, int y, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawStar(int icon, int x, int y, int cnt, int curMax, int max, int align, bool bigStar, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawShield(int x, int y, int cnt, int max, int align, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawHeart(int, int, int, int, int, float zoom, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawRaidButton(float, bool, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawGoldButton(int itemType, int itemDetail, int itemGrade, int itemLv, int x, int y, float zoom, bool ani, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawCoinButton(int cnt, int x, int y, float zoom, bool ani, bool betFrame, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawHeartButton(int cnt, int x, int y, float zoom, bool ani, bool betFrame, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawBattleButton(int x, int y, float zoom, bool ani, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawAttackButton(int cnt, int x, int y, float zoom, bool ani, bool betFrame, int downFrame, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
int GetMaxShield(void);
int GetInitHeart(void);
int GetHeartAmount(void);
void LoadingBarDraw(int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawCheckBox(int x, int y, int w, int h, bool checked, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawCheckButton(int x, int y, int w, int h, int gray, bool checked, int currency, int amount, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawButtonFrame(int x, int y, int w, int h, int frameColor, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawBuyButton(int x, int y, int w, int h, int fra, int frameColor, long long amount, int currency, float zoom, bool ani, int sign, float discount, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawTextButton(int x, int y, int w, int h, int fra, int gray, float zoom, bool ani, int textIdx, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawMaxButton(int x, int y, int w, int h, int alphaIdx, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawTouchButton(int, int, const char*, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawTouchLargeButton(int, int, int, int, const char*, int, int, float zoom, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawAlarmMark(int x, int y, int count, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawPlusMark(int x, int y, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawEmptySlot(int x, int y, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawXMark(int x, int y, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawInfoMark(int x, int y, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);

// Item Showing
void DrawIcon(int idx, int x, int y, float zoom, int solid, bool ani, bool shadow, float thickness, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawSkillIcon(int, int, int, float, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawSkillCard(int skillIdx, int lv, int x, int y, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawLock(int lv, int x, int y, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawPercent(float num, int x, int y, float zoom, int align, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawXNumTTF(int num, int x, int y, float zoom, int align, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawLv(int lv, int x, int y, float zoom, int align, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawItemIcon(ITEM* it, OBJECT* pObj, int x, int y, float zoom, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawSlotIndex(int, int, int, int, float zoom, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawMedalReward(int attackTypeIdx, int x, int y, int w, int h, int step, int str, bool ani, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawRedDot(int x, int y, int color, int num, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
int GetUpgradeLv(int type);
void DrawLevelUpCard(int type, int lv, bool locked, int x, int y, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawRewardCardRange(int type, int grade, int detail, long long startCnt, long long endCnt, int x, int y, float zoom, bool cardFrame, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawRewardCard(int type, int detail, int grade, int lv, long long count, int x, int y, bool ani, float zoom, int cardFrame, bool newItem, bool showValue, int curStar, int maxStar, bool shadow, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
float GetEquipIconWidth(int itemType, int itemDetail, int itemGrade, float zoom);
void DrawEquipIcon(int itemType, int itemDetail, int itemGrade, int x, int y, float zoom, bool iconAni, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawItemValue(int itemType, int itemDetail, int itemGrade, int itemLv, int x, int y, int align, int plusLv, float zoom, float numWidth, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawRouletteCard(int actionCardIdx, int str, int x, int y, float zoom, int alpha, bool ani, int owner, int lockOpenFrame, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void HitCountCheck(OBJECT* pObj);
void DrawHitCount(OBJECT* pObj, int x, int y, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawSocket(int, int, int, float, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawCycle(int x, int y, int w, int h, int cycle, int full, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawSelect(int, int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawTime(int x, int y, int atime, int type, int align, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawDetailTimeGold(int x, int y, int atime, int font, int align, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawDate(int, int, int, float zoom, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawDateText(int, int, int, int, float zoom, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void PushButtonDraw(int betType, int x, int y, int motion, float zoom, bool autoPlayText, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawHand(int, int, int, float, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawScroll(int x, int y, int h, int type, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void YesNoDraw(int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void AccountDraw(int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void PolicyDraw(int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void CommunityDraw(int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawSelectBox(int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void DrawEmptyBox(int, int, int, int, cocos2d::RenderTexture*, cocos2d::Layer*, bool);
void BoxInfoDraw(int boxType, int x, int y, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawBox(int boxType, int x, int y, int dirX, int motion, int solid, bool ani, bool opened, bool shadow, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void BoxDraw(OBJECT* pObj, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawBoxSpecial(int x, int y, int dirX, int idx, float zoom, int solid, bool ani, bool opened, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);