#pragma once

#ifndef _FUNC_ITEM_H_
#define _FUNC_ITEM_H_
// Item & Inventory
int * GetDetailGradeFromCollectionIdx(int arr[], int collectionIdx, int type);
ITEM *GetItemPtr(int);
int DropItem(OBJECT *, int);
void MakeBoxDropPercent(void);
void MakeItem(ITEM * it, int type, int lv, int grade, int detail, int set);
void DrawQuickIcon(OBJECT * pObj, int x, int y, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void DrawQuick(OBJECT * pObj, int x, int y, int status, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
void InventoryDraw(OBJECT * pObj, int x, int y, float zoom, cocos2d::RenderTexture* cvtDest, cocos2d::Layer* cvtLayer, bool buffering);
int MakeItemType(int);
int MakeArenaItem(void);
int MakeCaveItem(void);
int MakeGachaItem(void);
int MakeItemLevel(int, int);
int MakeItemDetail(int, int);
int MakeItemGrade(int, int, int);
int MakeItemValue(int, int, int, int);
int MakeItemId(void);
int GetItem(int, int, int, int, long long, int);
void ItemSetString(std::string, int, int, int, int, int);
int GetHeroCnt(void);
int GetHeroIdx(int type);
bool IsGetHero(int type);
int GetItemName(int, int, int);
int GetItemIcon(int, int, int);
int GetItemSellPrice(int);
int GetItemIronPrice(ITEM *);
long long GetUpgradeHammer(int, int, int, int);
int GetStageBossObjectIdx(void);
int GetStageBossIdx(void);
int GetStageBossType();
long long GetStageAdmissionFee(void);
long long GetStageAdmissionHeart(int stage);
int GetItemPrice(ITEM * it);
int GetCharPrice(int);
int GetCharPow(OBJECT *);
int GetItemPow(int, int, int);
int GetItemStar(int, int, int);
int GetCurWeaponCollectionsIndex(void);
int GetNextWeaponCollectionsIndex(void);
bool EquipNextWeapon(void);
int GetHighestCollections(int);
int GetItemCount(int, int, int);
int GetItemLv(int, int, int);
int SetStrongestEquip(int, int, int);
int GetEquipSlot(int, int, int);
bool isEnemyObjActive(void);
void BackUpEnemyObj(void);
void CopyEnemyObj(void);
int RemainMonstersCnt(void);
int GetEnemyDmgIdx(int enemyObj);
int GetEnemyMomObj(int idx);
int GetObjectNumFromEnemyIdx(int idx);
int GetAttackEnemy(void);
int GetEnemyBarIdx(int idx);
bool IsBossObjActive(void);
void CopyBossObj(void);
int GetBossMomObj(void);
int GetSlotIdx(int type, int detail, int grade);
int GetInvenIdx(int type, int detail, int grade);
int CollectionCheck(void);
int GetMaxCollectionIdxFromStage(int stage);
int GetCollectionIdx(int type, int detail, int grade);
int GetCollectionActionCardIdx(int collectionIdx);
int GetRouletteIdx(int collectionIdx, int rouletteType);
bool IsCollectionFull(int collectionIdx);
bool IsCollectionFullEquiped(int collectionIdx);
int GetFullEquipedCollectionIdx(void);
int EraseCopyItem(void);
int CompareItem(ITEM * it, ITEM * nt);
void BreakItem(ITEM * it);
void RestoreItem(ITEM * it);
void EraseItem(ITEM * it);
void EraseNetItem(ITEM * it);
void ArrangeInven(void);
//void ArrangeNetInven(void);
void OrderInven(void);
int GetOrder(ITEM *, int);
void RadixSort(int *, int);
int RemainedItemCheck(void);
bool NewItemCheck(void);
bool EmptySlotCheck(int itemType);
int EquipCheck(OBJECT *, ITEM * it);
void EquipNewItem(OBJECT* pObj, ITEM * it);
void EquipItem(OBJECT *, ITEM * it);
void UnEquipItem(OBJECT *, ITEM * it);
void UnEquipEffect(OBJECT *, ITEM * it);
int UseItem(OBJECT *, int);
void UseStatue(OBJECT *, int);
void UseRing(OBJECT *, int);
void UseItemBox(ITEM * it);
void SetTestHotKey(void);
void SetHotKey(OBJECT *, int, int, int);
void FreeHotKey(OBJECT *, int);
int GetItemValue(ITEM * it);
void SetItemString(ITEM * it, int addDetail, int addCool);
void SetItemString_Gem(ITEM * it);
void SetNetString(ITEM * it);
void SetRecipeString(int, int, int, int);
void SetMaterialString(unsigned char *, int);
void SetSocketString(int, int);
void SetActiveSkillString(int index, char* str, unsigned short width, unsigned short height);
void SetActiveSkillBodyString(int);
void SetNpcEquip(ITEM * it);
void SetNpcEquipDetail(int npc, int slot, int itemType, int itemDetail, int itemGrade);
void ResurrectionEffect(OBJECT *);
void StoneRecipe(ITEM * it);
void StoneResolution(int);
void StoneSocket(int);
#endif