#pragma once

#ifndef _FUNC_ITEM_H_
#define _FUNC_ITEM_H_
// Item & Inventory
int * GetDetailGradeFromCollectionIdx(int arr[], int collectionIdx, int type);
ITEM *GetItemPtr(int);
int DropItem(OBJECT *, int);
void MakeBoxDropPercent(void);
void MakeItem(ITEM * it, int type, int lv, int grade, int detail, int set);
void DrawQuickIcon(OBJECT * pObj, int x, int y, float zoom);
void DrawQuick(OBJECT * pObj, int x, int y, int status, float zoom);
void InventoryDraw(OBJECT * pObj, int x, int y, float zoom);
int MakeItemType(int);
int GetDropLv(void);
int MakeItemLevel(int, int);
int MakeItemDetail(int, int);
int MakeItemGrade(int, int, int);
int MakeItemValue(int, int, int, int);
int MakeItemId(void);
int GetItem(int, int, int, int, long long, int);
int GetHeroCnt(void);
int GetHeroIdx(int type);
bool IsGetHero(int type);
int GetItemName(int, int, int);
int GetItemIcon(int, int, int);
int GetItemIronPrice(ITEM *);
long long GetUpgradeHammer(int, int, int, int);
int GetStageBossObjectIdx(void);
int GetStageBossIdx(void);
int GetStageBossType();
long long GetStageAdmissionFee(void);
long long GetStageAdmissionHeart(int stage);
int GetItemPrice(ITEM * it);
int GetCharPrice(int);
int GetItemPow(int, int, int);
int GetItemStar(int, int, int);
int GetCurWeaponCollectionsIndex(void);
int GetHighestCollections(int);
int GetItemCount(int, int, int);
int GetItemLv(int, int, int);
int SetStrongestEquip(int, int, int);
int GetEquipSlot(int, int, int);
void BackUpEnemyObj(void);
void CopyEnemyObj(void);
int GetAttackEnemy(void);
int GetEnemyBarIdx(int idx);
bool IsBossObjActive(void);
void CopyBossObj(void);
int GetBossMomObj(void);
int GetInvenIdx(int type, int detail, int grade);
int CollectionCheck(void);
int GetMaxCollectionIdxFromStage(int stage);
int GetCollectionIdx(int type, int detail, int grade);
int GetCollectionActionCardIdx(int collectionIdx);
int GetRouletteIdx(int collectionIdx, int rouletteType);
bool IsCollectionFull(int collectionIdx);
bool IsCollectionFullEquiped(int collectionIdx);
int GetFullEquipedCollectionIdx(void);
int EraseCopyItem(void);
void EraseItem(ITEM * it);
void ArrangeInven(void);
//void ArrangeNetInven(void);
int EquipCheck(OBJECT *, ITEM * it);
void EquipNewItem(OBJECT* pObj, ITEM * it);
void EquipItem(OBJECT *, ITEM * it);
void UnEquipItem(OBJECT *, ITEM * it);
void UnEquipEffect(OBJECT *, ITEM * it);
void UseRing(OBJECT *, int);
void SetHotKey(OBJECT* pObj, int type, int idx, int where);
void FreeHotKey(OBJECT *, int);
int GetItemValue(ITEM * it);
void SetItemString(ITEM * it, int addDetail, int addCool);
void SetItemString_Gem(ITEM * it);
void SetNetString(ITEM * it);
void SetActiveSkillBodyString(int);
void SetNpcEquip(ITEM * it);
void SetNpcEquipDetail(int npc, int slot, int itemType, int itemDetail, int itemGrade);
void ResurrectionEffect(OBJECT *);
#endif