#pragma once

#ifndef _FUNC_MOVEMENT_H_
#define _FUNC_MOVEMENT_H_
// Object 이동관련
int PxlLeft(OBJECT *);
int PxlUp(OBJECT *);
int PxlRight(OBJECT *);
int PxlDown(OBJECT *);
int GetObjFromPtr(OBJECT *);
int GetSonObjCnt(int mom);
void GetTile(OBJECT *);
int GetDistance(OBJECT *, OBJECT *);
int DistanceCheck(OBJECT *, OBJECT *, int);
int GetClosestObj(OBJECT *);
int GetClosestPlayer(OBJECT *);
int GetRaidAttackFrameCnt(int type);
int BoundaryCheck(OBJECT *);
int GetObjHeight(OBJECT *);
int GetEmptyObject(int);
int BlockObj(OBJECT *, int);
int ObjCrash(OBJECT *, OBJECT *);
int AttackCrash(OBJECT *, OBJECT *);
int TileCrash(OBJECT *);
int GetOnTile(OBJECT *);
int ClearGap(OBJECT *, int);
void PressObjCheck(OBJECT *);
void MoveBG(void);
void MoveObj(OBJECT *);
void PlayerMove(OBJECT *);
void EnemyPlayerMove(OBJECT *);
int PlayerMove_Attack(OBJECT *, int);
void PlayerMove_SkillAttack(OBJECT *, int);
void SetPlayerMotion(OBJECT *);
void OutOfSled(void);
void PlayerSledMove(OBJECT *);
void PlayerGolemMove(OBJECT *);
void PlayerHandMove(OBJECT *);
void PlayerEnemyMove(OBJECT *);
void EnemyMove(OBJECT *);
void MobiusMove(OBJECT *);
void SlingMove(OBJECT *);
void LightningMove(OBJECT *,int);
void BugMove(OBJECT *);
void SkelGuideMove(OBJECT *);
void CircleMove(OBJECT *);
void SlimeMove(OBJECT *, int);
void StuckMove(OBJECT *);
void StraightMove(OBJECT *);
void MachineManagerMove(OBJECT *);
void MachineMove(OBJECT *);
void MachineBossMove(OBJECT *);
void BahamutHeadMove(OBJECT *);
void BahamutNeckMove(OBJECT *);
void BahamutBodyMove(OBJECT *);
int BahamutReady(OBJECT *);
void ShipMainMove(OBJECT *);
void ShipSubMove(OBJECT *);
void DebrionBodyMove(OBJECT *);
void DebrionArmMove(OBJECT *);
void ShipGuideMove(OBJECT *);
void FograMove(OBJECT *);
void FograSubMove(OBJECT *, OBJECT *);
void SignMove(OBJECT *);
void GuardMove(OBJECT *);
void GoliMove(OBJECT *);
void GuardMove2(OBJECT *);
void AppearBossMove(OBJECT *);
void BoarEventMove(OBJECT *);
void Bullet3wayMove(OBJECT *);
void BulletLaserMove(OBJECT *);
void BulletBombMove(OBJECT *);
void BulletGuidedMove(OBJECT *);
void BulletSateliteMove(OBJECT *);
void BulletHealMove(OBJECT *);
void BulletBoomerangMove(OBJECT *);
void BulletTongueMove(OBJECT *);
void FollowMove(OBJECT *pObj);
void FollowMomMove(OBJECT *);
void HandMove(OBJECT *);
void BulletSpinMove(OBJECT *);
void BulletGuideMove(OBJECT *);
void Bullet3wayDirMove(OBJECT *);
void BulletItemMove(OBJECT *);
void Bullet4wayMove(OBJECT *);
void LabethMagicMove(OBJECT *);
void EnemyMove_AddObj(OBJECT *);
void EnemyMove_AddObj2(OBJECT *);
void EnemyMoveCommon(OBJECT *);
void EnemyMoveTurn(OBJECT *);
void SummonMove(OBJECT *);
void VanishMove(OBJECT *);
void RegenMove(OBJECT *);
void DemoMove(OBJECT *);
void EscortMove(OBJECT *);
void MerchantMove(OBJECT *);
void NpcMove(OBJECT *);
void RideGolem(OBJECT *);
void TakeDown(void);
void NpcShipMove(OBJECT *);
void SideMove(OBJECT *);
void UpDownMove(OBJECT *);
void DropMove(OBJECT *);
void SewageStoneMove(OBJECT *);
void PushMove(OBJECT *);
void DoorMove(OBJECT *);
void RepulsionMove(OBJECT *);
void ItemMove(OBJECT *);
void CloakingMove(OBJECT *);
void WarpMove(OBJECT *);
void LeverMove(OBJECT *);
void BoxMove(OBJECT *);
void CarpetMove(OBJECT *);
void RobinTrapMove(OBJECT *);
void DianaTrapMove(OBJECT *);
void DianaStoneMove(OBJECT *);
void MaxxTrapMove(OBJECT *);
void SunBlockMove(OBJECT *);
void BreakStoneMove(OBJECT *);
void DarkStoneMove(OBJECT *);
void DemoDarkMove(OBJECT *);
void BubbleMove(OBJECT *);
void BubbleBobbleMove(OBJECT *);
void MagmaMove(OBJECT *);
void MagmaBlockMove(OBJECT *);
void BridgeMove(OBJECT *);
void StalactiteMove(OBJECT *);
void SpikeMove(OBJECT *);
void MagnetMove(OBJECT *);
void SledMove(OBJECT *);
void IceBreakMove(OBJECT *);
void InvisibleMove(OBJECT *);
void GolemBlockMove(OBJECT *);
void BallMove(OBJECT *);
void PitcherMove(OBJECT *);
void BlackHoleMove(OBJECT *);
void WormHoleMove(OBJECT *);
void ItemGotoBoxMove(OBJECT *);
void CrewMove(OBJECT *);
void CutOffMove(OBJECT *);
void TileCheckX(OBJECT *);
void TileCheckY(OBJECT *);
void TileCheckX2(OBJECT *);
void TileCheckY2(OBJECT *);
int AlivePlayerCnt(void);
int AliveEnemyCnt(void);
bool IsHitPossible(OBJECT * pObj, OBJECT * mObj);
bool IsMaxBet(void);
bool IsMaxCoinBet(void);
bool IsRoulettePossible(int rouletteType);
int IsKnockBack(int objType);
int IsBigMonster(int);
int IsBigCmf(int);
void RegenEnemy(OBJECT *, int, int, int, int);
int CanRunPlayer(int);
#endif