#pragma once

#ifndef _DEF_ATTACKSEQUENCE_H_
#define _DEF_ATTACKSEQUENCE_H_

typedef enum _attackSequenceDef {

	CURTAINSPEED = 2 * 2,
	CURTAINFRAME = 80,
	CURTAINSTARTPOSX = -64 * _2X,

	
	//일단 설계도를 그리자
	ATTACKSEQUENCE_READY = 0,//박스를 까던 전투를 준비하던 뭔가 준비하는 화면
	ATTACKSEQUENCE_SLOT,//뭔가 랜덤한 족보가 돌아가는 화면이 존재하면 활용
	ATTACKSEQUENCE_ACTION,//여기가 티키타카 전투를 하던 박스를 때리던 뭔가를 하는 화면
	ATTACKSEQUENCE_COIN,
	ATTACKSEQUENCE_ATTACKRESULT,//전투가 최종으로 끝나면 결과를 보여주는 것
	ATTACKSEQUENCE_REWARD_BATTLE,//배틀 아이템 보여주는것
	ATTACKSEQUENCE_REWARD_RAID,//레이드 아이템 보여주는것
	ATTACKSEQUENCE_REWARD,//최종적으로 보상을 가는것
	ATTACKSEQUENCE_BOSS,//10번째 전투가 끝나서 보스전투 가는것
	ATTACKSEQUENCE_STAGECLEAR,//보스를 클리어하고 다음 전투로 가는 것
	ATTACKSEQUENCE_BOSSRAID,//골드 이벤트


	TOTAL_ATTACKSEQUENCE_TYPE,

	ATTACKSEQUENCE_CARDFRAMEDIV = FPS / 5,

	//ATTACKDELAY_COIN_START = FPS * 16 / 5,
	//ATTACKDELAY_COIN_DEFAULTVALUE = FPS * 13 / 5,
	//ATTACKDELAY_COIN_JOKBO_UP = FPS * 11 / 5,
	//ATTACKDELAY_COIN_JOKBO_RESULT = FPS * 8 / 5,
	ATTACKDELAY_COIN_JOKBO_RESULT = FPS / 5,
	ATTACKDELAY_COIN_JOKBO_UP = ATTACKDELAY_COIN_JOKBO_RESULT + FPS * 3 / 5,
	ATTACKDELAY_COIN_DEFAULTVALUE = ATTACKDELAY_COIN_JOKBO_UP + FPS * 3 / 5,
	ATTACKDELAY_COIN_START = ATTACKDELAY_COIN_DEFAULTVALUE + FPS * 2,

	ATTACKDELAY_HEART_ENERGY = FPS * 2 / 5,
	ATTACKDELAY_HEART_HEARTBAR = ATTACKDELAY_HEART_ENERGY + FPS * 2 / 5,
	ATTACKDELAY_HEART_JOKBO_RESULT = ATTACKDELAY_HEART_HEARTBAR + FPS * 4 / 5,
	ATTACKDELAY_HEART_JOKBO_UP = ATTACKDELAY_HEART_JOKBO_RESULT + FPS * 3 / 5,
	ATTACKDELAY_HEART_DEFAULT = ATTACKDELAY_HEART_JOKBO_UP + FPS * 3 / 5,
	ATTACKDELAY_HEART_START = ATTACKDELAY_HEART_DEFAULT + FPS * 2,

	ATTACKDELAY_SHIELD_END = FPS / 2 / 5,
	ATTACKDELAY_SHIELD_BAR = ATTACKDELAY_SHIELD_END + FPS / 2,
	ATTACKDELAY_SHIELD_DEFAULT = ATTACKDELAY_SHIELD_BAR + FPS / 2,
	ATTACKDELAY_SHIELD_START = ATTACKDELAY_SHIELD_DEFAULT + FPS / 2,

	ATTACKDELAY_SKILL_QUEST_TABREWARD = FPS * 2 / 5,
	ATTACKDELAY_SKILL_QUEST_REWARDGET = ATTACKDELAY_SKILL_QUEST_TABREWARD + FPS * 2 / 5,
	ATTACKDELAY_SKILL_QUEST_FILL = ATTACKDELAY_SKILL_QUEST_REWARDGET + FPS * 2 / 5,
	ATTACKDELAY_SKILL_QUEST_ITEMFILL = ATTACKDELAY_SKILL_QUEST_FILL + FPS * 2 / 5,
	ATTACKDELAY_SKILL_HEART_ENERGY = ATTACKDELAY_SKILL_QUEST_ITEMFILL + FPS * 2 / 5,
	ATTACKDELAY_SKILL_HEART_BAR = ATTACKDELAY_SKILL_HEART_ENERGY + FPS * 2 / 5,
	ATTACKDELAY_SKILL_COIN_ENEMY_ATTACK = ATTACKDELAY_SKILL_HEART_BAR + FPS * 2 / 5,
	ATTACKDELAY_SKILL_COIN_HELM_RESULT = ATTACKDELAY_SKILL_COIN_ENEMY_ATTACK + FPS * 2 / 5,
	ATTACKDELAY_SKILL_COIN_HELM_UP = ATTACKDELAY_SKILL_COIN_HELM_RESULT + FPS * 2 / 5,
	ATTACKDELAY_SKILL_DEFAULT = ATTACKDELAY_SKILL_COIN_HELM_UP + FPS * 2 / 5,
	ATTACKDELAY_SKILL_START = ATTACKDELAY_SKILL_DEFAULT + FPS * 2 / 5,

	ATTACKDELAY_QUEST_REWARDGET = FPS * 2 / 5,
	//보상이 추가되는 화면
	ATTACKDELAY_QUEST_ADDREWARD = ATTACKDELAY_QUEST_REWARDGET + FPS,
	//보상이 날라오는 화면
	ATTACKDELAY_QUEST_REWARDMOVE = ATTACKDELAY_QUEST_ADDREWARD + FPS,
	//몬스터가 죽는 화면
	ATTACKDELAY_QUEST_FILL = ATTACKDELAY_QUEST_REWARDMOVE + FPS * 2 / 5,
	ATTACKDELAY_QUEST_JOKBO_RESULT = ATTACKDELAY_QUEST_FILL + FPS * 2 / 5,
	ATTACKDELAY_QUEST_JOKBO_UP = ATTACKDELAY_QUEST_JOKBO_RESULT + FPS * 1,
	ATTACKDELAY_QUEST_DEFAULT = ATTACKDELAY_QUEST_JOKBO_UP + FPS * 1,
	ATTACKDELAY_QUEST_START = ATTACKDELAY_QUEST_DEFAULT + FPS * 1,

	//최종적으로 세팅되는 화면
	ATTACKDELAY_EQUIP_FINALSETTING = FPS,
	//레벨업 보상이 지급되는 화면
	ATTACKDELAY_EQUIP_LEVELUPREWARD = ATTACKDELAY_EQUIP_FINALSETTING + FPS,
	//경험치가 올라가서 레벨업이 되는 화면
	ATTACKDELAY_EQUIP_LEVELUP = ATTACKDELAY_EQUIP_LEVELUPREWARD + FPS,
	//분해 재화가 지급되면서 전투력이 올라가는거
	//장비가 분해되어 획득하는 화면
	ATTACKDELAY_EQUIP_DISASSEMBLE = ATTACKDELAY_EQUIP_LEVELUP + FPS * 1,
	//획득한 장비가 셋팅이 되는 화면(전투력 상승 포함)
	ATTACKDELAY_EQUIP_SETTING = ATTACKDELAY_EQUIP_DISASSEMBLE + FPS,
	//슬롯에 이미 장비가 있으면 슬롯교체를 하는 화면
	ATTACKDELAY_EQUIP_CHANGE = ATTACKDELAY_EQUIP_SETTING + FPS * 4 / 3,
	//튀어나온 카드가 반짝이고 장비 선택화면으로 넘어가는
	ATTACKDELAY_EQUIP_DEFAULT = ATTACKDELAY_EQUIP_CHANGE + FPS * 2 / 5,
	//상자에서 카드가 튀어나오는 화면
	ATTACKDELAY_EQUIP_START = ATTACKDELAY_EQUIP_DEFAULT + FPS,

	ATTACKDELAY_BATTLE_WARP = FPS * 4 / 5,
	ATTACKDELAY_BATTLE_REWARD_GOLDTIME = ATTACKDELAY_BATTLE_WARP + FPS,//
	ATTACKDELAY_BATTLE_REWARD_GOLDGET = ATTACKDELAY_BATTLE_REWARD_GOLDTIME + FPS,//
	ATTACKDELAY_BATTLE_REWARD_RESULT = ATTACKDELAY_BATTLE_REWARD_GOLDGET + FPS,//
	ATTACKDELAY_BATTLE_REWARD_VALUEUP = ATTACKDELAY_BATTLE_REWARD_RESULT + FPS,//
	ATTACKDELAY_BATTLE_REWARD_START = ATTACKDELAY_BATTLE_REWARD_VALUEUP + FPS,//
	ATTACKDELAY_BATTLE_ACTION_RESULT = ATTACKDELAY_BATTLE_REWARD_START + FPS * 1,//
	ATTACKDELAY_BATTLE_TARGET_ACTION = ATTACKDELAY_BATTLE_ACTION_RESULT + FPS * 2,
	ATTACKDELAY_BATTLE_SELECT_TARGET = ATTACKDELAY_BATTLE_TARGET_ACTION + FPS * 3,
	ATTACKDELAY_BATTLE_TEXT = ATTACKDELAY_BATTLE_SELECT_TARGET + FPS * 2 / 5,//상대방 표시해주는것
	ATTACKDELAY_BATTLE_GOLDALPHA = ATTACKDELAY_BATTLE_TEXT + FPS * 2 / 5,//상대방 표시해주는것
	ATTACKDELAY_BATTLE_PLAYER = ATTACKDELAY_BATTLE_GOLDALPHA + FPS * 2 / 5,//상대방 표시해주는것
	ATTACKDELAY_BATTLE_NPC_BOX = ATTACKDELAY_BATTLE_PLAYER + FPS * 3 / 5,//상대방 표시해주는것
	ATTACKDELAY_BATTLE_CASTLE = ATTACKDELAY_BATTLE_NPC_BOX + FPS * 4 / 5,//장비에 따라 값이 증가된 상태 
	ATTACKDELAY_BATTLE_DIAPPEAR_END = ATTACKDELAY_BATTLE_CASTLE + FPS * 3 / 5,//장비에 따라 값이 증가된 상태 
	ATTACKDELAY_BATTLE_DIAPPEAR = ATTACKDELAY_BATTLE_DIAPPEAR_END + FPS * 3 / 5,//장비에 따라 값이 증가된 상태 
	ATTACKDELAY_BATTLE_STARTALPHA = ATTACKDELAY_BATTLE_DIAPPEAR + FPS * 2 / 5,//장비에 따라 값이 증가된 상태 
	ATTACKDELAY_BATTLE_START = ATTACKDELAY_BATTLE_STARTALPHA + FPS * 2 / 5,//레이드 스타트

	TOTALJUMPUPMOTION = 56,
	//TOTALJUMPDOWNMOTION = 
	ATTACKDELAY_RAID_WARP = FPS * 4 / 5,
	ATTACKDELAY_RAID_REWARD_GOLDTIME = ATTACKDELAY_RAID_WARP + FPS,//
	ATTACKDELAY_RAID_REWARD_GOLDGET = ATTACKDELAY_RAID_REWARD_GOLDTIME + FPS,//
	ATTACKDELAY_RAID_REWARD_RESULT = ATTACKDELAY_RAID_REWARD_GOLDGET + FPS,//
	ATTACKDELAY_RAID_REWARD_VALUEUP = ATTACKDELAY_RAID_REWARD_RESULT + FPS / 2,//
	ATTACKDELAY_RAID_REWARD_START = ATTACKDELAY_RAID_REWARD_VALUEUP + FPS,//
	ATTACKDELAY_RAID_ACTION_RESULT = ATTACKDELAY_RAID_REWARD_START + FPS * 1,//
	ATTACKDELAY_RAID_TARGET_ACTION = ATTACKDELAY_RAID_ACTION_RESULT + FPS * 1,
	ATTACKDELAY_RAID_SELECT_TARGET = ATTACKDELAY_RAID_TARGET_ACTION + FPS * 3,
	ATTACKDELAY_RAID_TEXT = ATTACKDELAY_RAID_SELECT_TARGET + FPS * 2 / 5,//상대방 표시해주는것
	ATTACKDELAY_RAID_GOLDALPHA = ATTACKDELAY_RAID_TEXT + FPS * 2 / 5,//상대방 표시해주는것
	ATTACKDELAY_RAID_PLAYER = ATTACKDELAY_RAID_GOLDALPHA + FPS * 2 / 5,//상대방 표시해주는것
	ATTACKDELAY_RAID_BOX_DOWN = ATTACKDELAY_RAID_PLAYER + FPS * 3 / 5,//상대방 표시해주는것
	ATTACKDELAY_RAID_BOX_ROTATION = ATTACKDELAY_RAID_BOX_DOWN + FPS * 1,//상대방 표시해주는것
	ATTACKDELAY_RAID_BOX_LEVITATION = ATTACKDELAY_RAID_BOX_ROTATION + FPS * 2,//상대방 표시해주는것
	ATTACKDELAY_RAID_GOLDTOBOX = ATTACKDELAY_RAID_BOX_LEVITATION + FPS / 2,//상대방 표시해주는것
	ATTACKDELAY_RAID_BOX_DROP = ATTACKDELAY_RAID_GOLDTOBOX + FPS * 2,//
	ATTACKDELAY_RAID_NPC_BOX = ATTACKDELAY_RAID_BOX_DROP + FPS * 8 / 5,
	ATTACKDELAY_RAID_CASTLE = ATTACKDELAY_RAID_NPC_BOX + FPS * 8 / 5,//장비에 따라 값이 증가된 상태 
	ATTACKDELAY_RAID_DIAPPEAR_END = ATTACKDELAY_RAID_CASTLE + FPS * 3 / 5,//장비에 따라 값이 증가된 상태 
	ATTACKDELAY_RAID_DIAPPEAR = ATTACKDELAY_RAID_DIAPPEAR_END + FPS * 3 / 5,//장비에 따라 값이 증가된 상태 
	ATTACKDELAY_RAID_STARTALPHA = ATTACKDELAY_RAID_DIAPPEAR + FPS * 2 / 5,//장비에 따라 값이 증가된 상태 
	ATTACKDELAY_RAID_START = ATTACKDELAY_RAID_STARTALPHA + FPS * 2 / 5,//레이드 스타트

	ATTACKDELAY_BOSS_WARP = FPS * 4 / 5,
	ATTACKDELAY_BOSS_PLAYER = ATTACKDELAY_BOSS_WARP + FPS * 2 / 5,//상대방 표시해주는것
	ATTACKDELAY_BOSS_DUEL = ATTACKDELAY_BOSS_PLAYER + FPS * 2 / 5,//
	ATTACKDELAY_BOSS_BOSS = ATTACKDELAY_BOSS_DUEL + FPS * 2 / 5,//장비에 따라 값이 증가된 상태 
	ATTACKDELAY_BOSS_START = ATTACKDELAY_BOSS_BOSS + FPS * 3 / 5,//레이드 스타트

	ATTACKDELAY_BOSSRAID_WARP = FPS * 4 / 5,
	ATTACKDELAY_BOSSRAID_PLAYER = ATTACKDELAY_BOSSRAID_WARP + FPS * 2 / 5,//상대방 표시해주는것
	ATTACKDELAY_BOSSRAID_DUEL = ATTACKDELAY_BOSSRAID_PLAYER + FPS * 2 / 5,//
	ATTACKDELAY_BOSSRAID_BOSSRAID = ATTACKDELAY_BOSSRAID_DUEL + FPS * 2 / 5,//장비에 따라 값이 증가된 상태 
	ATTACKDELAY_BOSSRAID_START = ATTACKDELAY_BOSSRAID_BOSSRAID + FPS * 3 / 5,//레이드 스타트

	ATTACKDELAY_STAGECLEAR_WARP = FPS * 4 / 5,
	ATTACKDELAY_STAGECLEAR_PLAYER = ATTACKDELAY_BOSS_WARP + FPS * 2 / 5,//상대방 표시해주는것
	ATTACKDELAY_STAGECLEAR_DUEL = ATTACKDELAY_BOSS_PLAYER + FPS * 2 / 5,//
	ATTACKDELAY_STAGECLEAR_BOSS = ATTACKDELAY_BOSS_DUEL + FPS * 2 / 5,//장비에 따라 값이 증가된 상태 
	ATTACKDELAY_STAGECLEAR_START = ATTACKDELAY_BOSS_BOSS + FPS * 3 / 5,//레이드 스타트


	//보상
	ATTACKDELAY_REWARD_COLLECTING = 1 * FPS,//
	ATTACKDELAY_REWARD_TABTOCOLLECT = ATTACKDELAY_REWARD_COLLECTING + 1 * FPS,//보상획득
	ATTACKDELAY_REWARD_START = ATTACKDELAY_REWARD_TABTOCOLLECT + 1 * FPS,//

	//HIT, RAID 보상
	ATTACKDELAY_REWARD_BATTLE_CLOSE = FPS / 5,//바가 클로즈 되는 것
	ATTACKDELAY_REWARD_BATTLE_REWARDGET = ATTACKDELAY_REWARD_BATTLE_CLOSE + FPS,//보상을 실질적으로 획득하는 화면
	ATTACKDELAY_REWARD_BATTLE_CHANGEPVPQUEST = ATTACKDELAY_REWARD_BATTLE_REWARDGET + FPS,//보상을 실질적으로 획득하는 화면
	ATTACKDELAY_REWARD_BATTLE_BOXOPEN = ATTACKDELAY_REWARD_BATTLE_CHANGEPVPQUEST + FPS,//바가 차다가 박스가 열릴 수 있으면 박스아이콘이 확대 된 다음에 센터로 날라들어오는 것
	ATTACKDELAY_REWARD_BATTLE_FILL = ATTACKDELAY_REWARD_BATTLE_BOXOPEN + FPS,//아이템이 다 들어간 다음에 바가 차는 것
	ATTACKDELAY_REWARD_BATTLE_CURRENCY = ATTACKDELAY_REWARD_BATTLE_FILL + FPS,//게이지바에 배틀 아이템 날라가는것
	ATTACKDELAY_REWARD_BATTLE_START = ATTACKDELAY_REWARD_BATTLE_CURRENCY + FPS,//게이지바 튀어나오는 동안 레이드라서 골드가 있으면 골드는 들어감

	//MISS
	ATTACKDELAY_MISS = 1 * FPS,


	ATTACKDELAY_BATTLEREWARD_WARP = CURTAINFRAME / 2 / 2 * 1,
	ATTACKDELAY_BATTLEREWARD_COIN_GET = ATTACKDELAY_BATTLEREWARD_WARP + FPS * 3 / 2,
	ATTACKDELAY_BATTLEREWARD_COIN_PANTS_RESULT = ATTACKDELAY_BATTLEREWARD_COIN_GET + FPS * 4 / 5,
	ATTACKDELAY_BATTLEREWARD_COIN_PANTS_UP = ATTACKDELAY_BATTLEREWARD_COIN_PANTS_RESULT + FPS * 4 / 5,
	ATTACKDELAY_BATTLEREWARD_COIN = ATTACKDELAY_BATTLEREWARD_COIN_PANTS_UP + FPS / 5,
	ATTACKDELAY_BATTLEREWARD_RESULT = ATTACKDELAY_BATTLEREWARD_COIN + FPS / 5,//레이드 스타트
	ATTACKDELAY_BATTLEREWARD_START = ATTACKDELAY_BATTLEREWARD_RESULT + FPS * 2 / 5,//레이드 스타트

	ATTACKDELAY_RAIDREWARD_WARP = CURTAINFRAME / 2 / 2 * 1,
	ATTACKDELAY_RAIDREWARD_GOLDTIME = ATTACKDELAY_RAIDREWARD_WARP + FPS,
	ATTACKDELAY_RAIDREWARD_GOLDGET = ATTACKDELAY_RAIDREWARD_GOLDTIME + FPS,
	ATTACKDELAY_RAIDREWARD_COIN_BOOTS_RESULT = ATTACKDELAY_RAIDREWARD_GOLDGET + FPS,
	ATTACKDELAY_RAIDREWARD_COIN_BOOTS_UP = ATTACKDELAY_RAIDREWARD_COIN_BOOTS_RESULT + FPS,
	ATTACKDELAY_RAIDREWARD_START = ATTACKDELAY_RAIDREWARD_COIN_BOOTS_UP + FPS,

	ATTACKDELAY_BATTLEMODE_RESULTTEXT = FPS * 4 / 5,//별이 0이면 캐릭터 위에 스턴마크  
	ATTACKDELAY_BATTLEMODE_RESULTALPHA = ATTACKDELAY_BATTLEMODE_RESULTTEXT + FPS * 2 / 5,//별이 0이면 캐릭터 위에 스턴마크 
	ATTACKDELAY_BATTLEMODE_HEARTMINUS2 = ATTACKDELAY_BATTLEMODE_RESULTALPHA + FPS * 2 / 5,//별감소
	ATTACKDELAY_BATTLEMODE_HEARTMINUS1 = ATTACKDELAY_BATTLEMODE_HEARTMINUS2 + FPS * 2 / 5,//별감소
	ATTACKDELAY_BATTLEMODE_START = ATTACKDELAY_BATTLEMODE_HEARTMINUS1 + FPS * 2 / 5,//별 감소

	ATTACKDELAY_RAIDMODE_SUM = FPS * 4 / 5,//합산을 해주는 곳
	ATTACKDELAY_RAIDMODE_DEFAULT = ATTACKDELAY_RAIDMODE_SUM + FPS * 3 / 5,//올라간 최종숫자가 
	ATTACKDELAY_RAIDMODE_UP = ATTACKDELAY_RAIDMODE_DEFAULT + FPS * 2 / 5,//레이드에서 숫자가 올라가는 동안
	ATTACKDELAY_RAIDMODE_START = ATTACKDELAY_RAIDMODE_UP + FPS / 2,//레이드에서 해당 

	ATTACKDELAY_BOSSREWARD_WARP = CURTAINFRAME / 2,
	ATTACKDELAY_BOSSREWARD_GLOVE_RESULT = ATTACKDELAY_BOSSREWARD_WARP + FPS * 2 / 5,
	ATTACKDELAY_BOSSREWARD_GLOVE_UP = ATTACKDELAY_BOSSREWARD_GLOVE_RESULT + FPS * 3 / 5,
	ATTACKDELAY_BOSSREWARD_HEART_RESULT = ATTACKDELAY_BOSSREWARD_GLOVE_UP + FPS * 3 / 5,
	ATTACKDELAY_BOSSREWARD_HEART_UP = ATTACKDELAY_BOSSREWARD_HEART_RESULT + FPS * 3 / 5,
	ATTACKDELAY_BOSSREWARD_HEART_DEFAULT = ATTACKDELAY_BOSSREWARD_HEART_UP + FPS * 3 / 5,
	ATTACKDELAY_BOSSREWARD_DEFAULT = ATTACKDELAY_BOSSREWARD_HEART_DEFAULT + FPS * 3 / 5,
	ATTACKDELAY_BOSSREWARD_CURRENT = ATTACKDELAY_BOSSREWARD_DEFAULT + FPS * 2 / 5,
	ATTACKDELAY_BOSSREWARD_PERFECT = ATTACKDELAY_BOSSREWARD_CURRENT + FPS * 1 / 5,
	ATTACKDELAY_BOSSREWARD_GREAT = ATTACKDELAY_BOSSREWARD_PERFECT + FPS * 1 / 5,//상대방 표시해주는것
	ATTACKDELAY_BOSSREWARD_GOOD = ATTACKDELAY_BOSSREWARD_GREAT + FPS * 1 / 5,//
	ATTACKDELAY_BOSSREWARD_BAD = ATTACKDELAY_BOSSREWARD_GOOD + FPS * 1 / 5,//장비에 따라 값이 증가된 상태 
	ATTACKDELAY_BOSSREWARD_RESULT = ATTACKDELAY_BOSSREWARD_BAD + FPS * 1 / 5,//레이드 스타트
	ATTACKDELAY_BOSSREWARD_START = ATTACKDELAY_BOSSREWARD_RESULT + FPS * 1 / 5,//레이드 스타트

	GACHADELAY_OPENPLACE = FPS * 10 / 5,
	GACHADELAY_BOXDROP = GACHADELAY_OPENPLACE + FPS * 4 / 5,
	GACHADELAY_BOXOPEN = GACHADELAY_BOXDROP + FPS * 1 / 5,
	GACHADELAY_ITEMDROP = GACHADELAY_BOXOPEN + FPS * 7 / 5,
	GACHADELAY_TAB = GACHADELAY_ITEMDROP + FPS * 1 / 5,

	GACHADELAY_GETITEM = FPS * 3 / 2,

	GACHADELAY_CARDOPEN = FPS * 4 / 5,
	GACHADELAY_BACKTOREWARD = GACHADELAY_CARDOPEN + FPS * 3 / 5,

	REWARDDELAY_CREW_CREWDROP = FPS * 3 / 5,
	REWARDDELAY_CREW_CREWDANCE = REWARDDELAY_CREW_CREWDROP + FPS * 3 / 5,
	REWARDDELAY_CREW_BOXDROP = REWARDDELAY_CREW_CREWDANCE + FPS * 1 / 5,
	REWARDDELAY_CREW_BOXOPEN = REWARDDELAY_CREW_BOXDROP + FPS * 1 / 5,
	REWARDDELAY_CREW_GETITEM = REWARDDELAY_CREW_BOXOPEN + FPS * 1 / 5,

	ENEMYDELAY_COIN_PLAYER_ATTACK = FPS / 5,
	ENEMYDELAY_COIN_ARMOR_RESULT = ENEMYDELAY_COIN_PLAYER_ATTACK + FPS / 5,
	ENEMYDELAY_COIN_ARMOR_DOWN = ENEMYDELAY_COIN_ARMOR_RESULT + FPS * 3 / 5,//공격받은 코인을 까내리는 것
	ENEMYDELAY_COIN_DEFAULTVALUE = ENEMYDELAY_COIN_ARMOR_DOWN + FPS / 5,
	ENEMYDELAY_COIN_START = ENEMYDELAY_COIN_DEFAULTVALUE + FPS / 5,

	SKILLDELAY_SKILLBAR = FPS * 10 / 5,
	SKILLDELAY_CARDOPEN = SKILLDELAY_SKILLBAR + FPS * 3 / 5,
	SKILLDELAY_CARDEFFECT = SKILLDELAY_CARDOPEN + FPS * 3 / 5,
	SKILLDELAY_SKILLNAME = SKILLDELAY_CARDEFFECT + FPS * 3 / 5,
	SKILLDELAY_TRIGGER = SKILLDELAY_SKILLNAME + FPS * 3 / 5,
	SKILLDELAY_EFFECT = SKILLDELAY_TRIGGER + FPS * 3 / 5,
	SKILLDELAY_TIME = SKILLDELAY_EFFECT + FPS * 3 / 5,
	SKILLDELAY_START = SKILLDELAY_TIME + FPS * 3 / 5,

	STAGECLEARDELAY_APPEAR = FPS,
	STAGECLEARDELAY_BOSSAWAY = STAGECLEARDELAY_APPEAR + 3 * FPS,
	STAGECLEARDELAY_HAPPYTIME = STAGECLEARDELAY_BOSSAWAY + 1 * FPS,
	STAGECLEARDELAY_LEVITATION = STAGECLEARDELAY_HAPPYTIME + 1 * FPS,//공중부양
	STAGECLEARDELAY_ROTATION = STAGECLEARDELAY_LEVITATION + 3 * FPS,
	STAGECLEARDELAY_TOGETHER = STAGECLEARDELAY_ROTATION + 3 * FPS,
	STAGECLEARDELAY_SELECTEDCREW = STAGECLEARDELAY_TOGETHER + 2 * FPS,
	STAGECLEARDELAY_CREWAPPEAR = STAGECLEARDELAY_SELECTEDCREW + 1 * FPS,
	STAGECLEARDELAY_NEWCARD = STAGECLEARDELAY_CREWAPPEAR + 2 * FPS,
	STAGECLEARDELAY_GETCARD = STAGECLEARDELAY_NEWCARD + 2 * FPS,

	STAGECLEARDELAY_ALPHA = FPS,
	STAGECLEARDELAY_BOXDROP = STAGECLEARDELAY_ALPHA + FPS,
	STAGECLEARDELAY_CLEARREWARD = STAGECLEARDELAY_BOXDROP + FPS,
	STAGECLEARDELAY_TABREWARD = STAGECLEARDELAY_CLEARREWARD + FPS,
	STAGECLEARDELAY_GETREWARD = STAGECLEARDELAY_TABREWARD + FPS,

	HITCARD_ATTACKED = 0,
	HITCARD_RESULT,

	HITZOOM = 1,//2,
	RAIDZOOM = 1,//2,

	ROULETTE_TRANSPARENCY = 24,//작을수록 뚜렷해지고, 클수록 투명해진다.
	TRANSPARENCY_MAX = 32,

	HIT_DIFFICULTY_LEVEL1 = 0,
	HIT_DIFFICULTY_LEVEL2,
	HIT_DIFFICULTY_LEVEL3,
	HIT_DIFFICULTY_LEVEL4,
	HIT_DIFFICULTY_LEVEL5,
	HIT_DIFFICULTY_LEVEL6,
	HIT_DIFFICULTY_LEVEL7,

	MAX_HIT_DIFFICULTY_LEVEL,

} ATTACKSEQUENCEDEF;


#endif
