#pragma once

#ifndef _DEF_CASTLE_H_
#define _DEF_CASTLE_H_

typedef enum _castleDef {
	//근거지로 쓰이는 성 디오라마의 순서
	CASTLE_TOLEM = 0,//0
	CASTLE_ARENA,//1
	CASTLE_SWAMP,//2
	CASTLE_VALLEY,//3
	CASTLE_ATLANTICE,//4
	CASTLE_SEWAGE,//5
	CASTLE_ADELINE,//6
	CASTLE_PLAIN,//7
	CASTLE_ELF,//8
	CASTLE_FLAME,//9
	CASTLE_FROST,//10
	CASTLE_THUNDER,//11
	CASTLE_LIGHT,//12
	CASTLE_GOLEMVALLEY,//13
	CASTLE_DARKNESS,//14
	CASTLE_DRAGON,//15
	CASTLE_GHOST,//16
	CASTLE_DEVILCASTLE,//17
	CASTLE_SPACE,//18

	TOTALCASTLE,//19
} CASTLEDEF;

#endif
