#pragma once

#ifndef _DEF_CMF_H_
#define _DEF_CMF_H_

typedef enum _cmfDef {
	//CMF 디파인
	CMF_SNAIL = 3,//o
	CMF_TREE, //4//o
	CMF_FROG, //5//o
	CMF_ONEEYE, //6//o
	CMF_SKELETON, //7//o
	CMF_LARVA, //8//o
	CMF_JELLYFISH,//9//o
	CMF_LIZARD,//10//o
	CMF_SALAMANDER,//11//o
	CMF_SLING,//12//o
	CMF_BOAR,//13//o
	CMF_GIANT,//14//o
	CMF_FLAME,//15//o
	CMF_PHOENIX,//16//o
	CMF_IFRIT,//17//o
	CMF_SNOWMAN,//18//o
	CMF_FACE,//19//o
	CMF_ICESUN,//20//o
	CMF_MAMMOTH,//21//o
	CMF_SPARK,//22//o
	CMF_CRYSTAL,//23//o
	CMF_THUNDER,//24//o
	CMF_MACHINE,//25//o
	CMF_GOLEM,//26//o
	CMF_SPIDER,//27//o
	CMF_SHIP,//28//o
	CMF_PUMPKIN,//29//o
	CMF_GHOST,//30//o
	CMF_DEATH,//31//o
	CMF_KNIGHT,//32//o
	CMF_SLIME,//33//o
	CMF_KIMERA,//34//o
	CMF_FAIRY,//35//o
	CMF_CIRCLE,//36//o
	CMF_ANGEL,//37//o
	CMF_DARKDRAGON,//38//o
	CMF_DARKGIANT,//39//o
	CMF_FOGRA,//40//o
	CMF_DRAGON1,//41//o
	CMF_DRAGON2,//42//o
	CMF_BAHAMUT,//43//o
	CMF_CASTLE1,//44//o
	CMF_CASTLE2,//45//o
	CMF_SPACE1,//46//o
	CMF_SPACE2,//47//o
	CMF_CASTLE_BOSS1,//데브리온48//o
	CMF_CASTLE_BOSS2,//엘케인 맨티스49//o
	CMF_CASTLE_BOSS3,//테트라쿤50//o
	CMF_CASTLE_BOSS4,//다크나이트51//o

	CMF_NPC_CAPTAIN,//c52//선장 o
	CMF_NPC_CREW,//c53//선원 o
	CMF_NPC_GRANDFA,//c54//할아버지 o
	CMF_NPC_UNCLE,//c55//아저씨 o
	CMF_NPC_AUNT,//c56//아줌마 o
	CMF_NPC_MAN,//c57//자경단청년 o
	CMF_NPC_WOMAN,//c58//처녀 o
	CMF_NPC_BOY,//c59//꼬마남 o
	CMF_NPC_GIRL,//c60//꼬마녀 o
	CMF_NPC_ALMA,//c61//알마 o
	CMF_NPC_ITEM,//c62//터번 o
	CMF_NPC_FATMAN,//c63 o
	CMF_NPC_BUNNYGIRL,//c64 o
	CMF_NPC_KNIGHT,//c65//플레타 o
	CMF_NPC_DOG,//c66 o
	CMF_NPC_MERCHANT,//c67
	CMF_NPC_CRAFTMAN,//c68 o
	CMF_NPC_MAP,//c69 o
	CMF_NPC_USERQUEST,//c70//스튜어디스 o
	CMF_NPC_TRAVEL,//c71//이국의여행자 o
	CMF_NPC_GRANDMA,//c72//할머니 o
	CMF_NPC_FISHING,//c73//라피 o
	CMF_NPC_INN,//c74
	CMF_NPC_NETITEM,//c75 o
	CMF_NPC_MILESE,//c76 o
	CMF_NPC_DOBEL,//c77 o
	CMF_NPC_GAGEL,//c78 o
	CMF_NPC_MONICA,//c79 o
	CMF_NPC_SHIP,//c80

	CMF_NPC_SEASOLDIER,//c81//아틀란병사 o
	CMF_NPC_FRAUD,//c82 o
	CMF_NPC_DARIAN,//c83 o
	CMF_NPC_LUISE,//c84 o
	CMF_NPC_SEAUNCLE,//c85//아틀란아저씨 o
	CMF_NPC_SEABOY,//c86//아틀란소년 o
	CMF_NPC_DONALD,//c87//이소룡 o

	CMF_NPC_SCHOLAR,//c88//학자 o
	CMF_NPC_CHEF,//c89//요리대가 o
	CMF_NPC_BISTRO,//c90//비스트로 o
	CMF_NPC_MAID,//c91//시녀 o
	CMF_NPC_ADELKNIGHT,//c92//기사 o
	CMF_NPC_SEBASTIAN,//c93//세바스찬 o
	CMF_NPC_NOBLEMAN,//c94//귀족아저씨 o
	CMF_NPC_DELPIOS,//c95//델피오스 o
	CMF_NPC_LORA,//c96//로라 o
	CMF_NPC_WITCH,//c97//마녀 o
	CMF_NPC_ELFGRANDFA,//c98//엘프할아버지 o
	CMF_NPC_ELFUNCLE,//c99//엘프아저씨 o
	CMF_NPC_ELFAUNT,//c100//엘프아줌마 o
	CMF_NPC_ELFMAN,//c101//엘프청년 o
	CMF_NPC_ELFWOMAN,//c102//엘프처녀 o
	CMF_NPC_ELFBOY,//c103//엘프꼬마남 o
	CMF_NPC_ELFGIRL,//c104//엘프꼬마녀 o
	CMF_NPC_ELFDARK,//c105//엘프다크 o
	CMF_NPC_ELFMAGIC,//c106//엘프마법사 o
	CMF_NPC_ELFDANCER,//c107//엘프무희 o
	CMF_NPC_OWL,//c108//부엉이 o
	CMF_NPC_LABETH,//c109//라베스 o
	CMF_NPC_ELKEIN,//c110//엘케인 o
	CMF_NPC_ELEIN,//c111//엘레인 o
	CMF_NPC_EVAN,//c112//에번 o
	CMF_NPC_TABLE,//c113//테이블//o//NPC_BEAD
	CMF_NPC_FOUNTAIN,//c114//샘물//o
	CMF_NPC_NEZAR,//c115//네자르 o
	CMF_NPC_GALLAND,//c116//갈란드//o
	CMF_NPC_DURAK,//c117//듀라크 o
	CMF_NPC_KING,//c118//에드몬드 o
	CMF_NPC_WOMANGHOST,//c119//여자유령 o
	CMF_NPC_MANGHOST,//c120//남자유령 o
	CMF_NPC_AUSTIN,//c121//오스틴(유령) o
	CMF_NPC_HEART,//c122//마왕의 심장 o

	CMF_SNAIL_RED, //123//3
	CMF_SNAIL_BLUE, //124//3
	CMF_SNAIL_PURPLE, //125//3
	CMF_SNAIL_GREEN, //126//3
	CMF_SNAIL_GOLD, //127//3
	CMF_SNAIL_BLACK, //128//3

	CMF_TREE_RED, //129//4
	CMF_TREE_BLUE, //130//4
	CMF_TREE_PURPLE, //131//4
	CMF_TREE_GREEN, //132//4
	CMF_TREE_GOLD, //133//4
	CMF_TREE_BLACK, //134//4

	CMF_FROG_RED, //135//5
	CMF_FROG_BLUE, //136//5
	CMF_FROG_PURPLE, //137//5
	CMF_FROG_GREEN, //138//5
	CMF_FROG_GOLD, //139//5
	CMF_FROG_BLACK, //140//5

	CMF_ONEEYE_RED, //141//6
	CMF_ONEEYE_BLUE, //142//6
	CMF_ONEEYE_PURPLE, //143//6
	CMF_ONEEYE_GREEN, //144//6
	CMF_ONEEYE_GOLD, //145//6
	CMF_ONEEYE_BLACK, //146//6

	CMF_SKELETON_RED, //147//7
	CMF_SKELETON_BLUE, //148//7
	CMF_SKELETON_PURPLE, //149//7
	CMF_SKELETON_GREEN, //150//7
	CMF_SKELETON_GOLD, //151//7
	CMF_SKELETON_BLACK, //152//7

	CMF_LARVA_RED, //153//8
	CMF_LARVA_BLUE, //154//8
	CMF_LARVA_PURPLE, //155//8
	CMF_LARVA_GREEN, //156//8
	CMF_LARVA_GOLD, //157//8
	CMF_LARVA_BLACK, //158//8

	CMF_JELLYFISH_RED,//159//9
	CMF_JELLYFISH_BLUE,//160//9
	CMF_JELLYFISH_PURPLE,//161//9
	CMF_JELLYFISH_GREEN,//162//9
	CMF_JELLYFISH_GOLD,//163//9
	CMF_JELLYFISH_BLACK,//164//9

	CMF_LIZARD_RED,//165//10
	CMF_LIZARD_BLUE,//166//10
	CMF_LIZARD_PURPLE,//167//10
	CMF_LIZARD_GREEN,//168//10
	CMF_LIZARD_GOLD,//169//10
	CMF_LIZARD_BLACK,//170//10

	CMF_SALAMANDER_RED,//171//11
	CMF_SALAMANDER_BLUE,//172//11
	CMF_SALAMANDER_PURPLE,//173//11
	CMF_SALAMANDER_GREEN,//174//11
	CMF_SALAMANDER_GOLD,//175//11
	CMF_SALAMANDER_BLACK,//176//11

	CMF_SLING_RED,//177//12
	CMF_SLING_BLUE,//178//12
	CMF_SLING_PURPLE,//179//12
	CMF_SLING_GREEN,//180//12
	CMF_SLING_GOLD,//181//12
	CMF_SLING_BLACK,//182//12

	CMF_BOAR_RED,//183//13
	CMF_BOAR_BLUE,//184//13
	CMF_BOAR_PURPLE,//185//13
	CMF_BOAR_GREEN,//186//13
	CMF_BOAR_GOLD,//187//13
	CMF_BOAR_BLACK,//188//13

	CMF_GIANT_RED,//189//14
	CMF_GIANT_BLUE,//190//14
	CMF_GIANT_PURPLE,//191//14
	CMF_GIANT_GREEN,//192//14
	CMF_GIANT_GOLD,//193//14
	CMF_GIANT_BLACK,//194//14

	CMF_FLAME_RED,//195//15
	CMF_FLAME_BLUE,//196//15
	CMF_FLAME_PURPLE,//197//15
	CMF_FLAME_GREEN,//198//15
	CMF_FLAME_GOLD,//199//15
	CMF_FLAME_BLACK,//200//15

	CMF_PHOENIX_RED,//201//16
	CMF_PHOENIX_BLUE,//202//16
	CMF_PHOENIX_PURPLE,//203//16
	CMF_PHOENIX_GREEN,//204//16
	CMF_PHOENIX_GOLD,//205//16
	CMF_PHOENIX_BLACK,//206//16

	CMF_IFRIT_RED,//207//17
	CMF_IFRIT_BLUE,//208//17
	CMF_IFRIT_PURPLE,//209//17
	CMF_IFRIT_GREEN,//210//17
	CMF_IFRIT_GOLD,//211//17
	CMF_IFRIT_BLACK,//212//17

	CMF_SNOWMAN_RED,//213//18
	CMF_SNOWMAN_BLUE,//214//18
	CMF_SNOWMAN_PURPLE,//215//18
	CMF_SNOWMAN_GREEN,//216//18
	CMF_SNOWMAN_GOLD,//217//18
	CMF_SNOWMAN_BLACK,//218//18

	CMF_FACE_RED,//219//19
	CMF_FACE_BLUE,//220//19
	CMF_FACE_PURPLE,//221//19
	CMF_FACE_GREEN,//222//19
	CMF_FACE_GOLD,//223//19
	CMF_FACE_BLACK,//224//19

	CMF_ICESUN_RED,//225//20
	CMF_ICESUN_BLUE,//226//20
	CMF_ICESUN_PURPLE,//227//20
	CMF_ICESUN_GREEN,//228//20
	CMF_ICESUN_GOLD,//229//20
	CMF_ICESUN_BLACK,//230//20

	CMF_MAMMOTH_RED,//231//21
	CMF_MAMMOTH_BLUE,//232//21
	CMF_MAMMOTH_PURPLE,//233//21
	CMF_MAMMOTH_GREEN,//234//21
	CMF_MAMMOTH_GOLD,//235//21
	CMF_MAMMOTH_BLACK,//236//21

	CMF_SPARK_RED,//237//22
	CMF_SPARK_BLUE,//238//22
	CMF_SPARK_PURPLE,//239//22
	CMF_SPARK_GREEN,//240//22
	CMF_SPARK_GOLD,//241//22
	CMF_SPARK_BLACK,//242//22

	CMF_CRYSTAL_RED,//243//23
	CMF_CRYSTAL_BLUE,//244//23
	CMF_CRYSTAL_PURPLE,//245//23
	CMF_CRYSTAL_GREEN,//246//23
	CMF_CRYSTAL_GOLD,//247//23
	CMF_CRYSTAL_BLACK,//248//23

	CMF_THUNDER_RED,//249//24
	CMF_THUNDER_BLUE,//250//24
	CMF_THUNDER_PURPLE,//251//24
	CMF_THUNDER_GREEN,//252//24
	CMF_THUNDER_GOLD,//253//24
	CMF_THUNDER_BLACK,//254//24

	CMF_MACHINE_RED,//255//25
	CMF_MACHINE_BLUE,//256//25
	CMF_MACHINE_PURPLE,//257//25
	CMF_MACHINE_GREEN,//258//25
	CMF_MACHINE_GOLD,//259//25
	CMF_MACHINE_BLACK,//260//25

	CMF_GOLEM_RED,//261//26
	CMF_GOLEM_BLUE,//262//26
	CMF_GOLEM_PURPLE,//263//26
	CMF_GOLEM_GREEN,//264//26
	CMF_GOLEM_GOLD,//265//26
	CMF_GOLEM_BLACK,//266//26

	CMF_SPIDER_RED,//267//27
	CMF_SPIDER_BLUE,//268//27
	CMF_SPIDER_PURPLE,//269//27
	CMF_SPIDER_GREEN,//270//27
	CMF_SPIDER_GOLD,//271//27
	CMF_SPIDER_BLACK,//272//27

	CMF_SHIP_RED,//273//28
	CMF_SHIP_BLUE,//274//28
	CMF_SHIP_PURPLE,//275//28
	CMF_SHIP_GREEN,//276//28
	CMF_SHIP_GOLD,//277//28
	CMF_SHIP_BLACK,//278//28

	CMF_PUMPKIN_RED,//279//29
	CMF_PUMPKIN_BLUE,//280//29
	CMF_PUMPKIN_PURPLE,//281//29
	CMF_PUMPKIN_GREEN,//282//29
	CMF_PUMPKIN_GOLD,//283//29
	CMF_PUMPKIN_BLACK,//284//29

	CMF_GHOST_RED,//285//30
	CMF_GHOST_BLUE,//286//30
	CMF_GHOST_PURPLE,//287//30
	CMF_GHOST_GREEN,//288//30
	CMF_GHOST_GOLD,//289//30
	CMF_GHOST_BLACK,//290//30

	CMF_DEATH_RED,//291//31
	CMF_DEATH_BLUE,//292//31/
	CMF_DEATH_PURPLE,//293//31
	CMF_DEATH_GREEN,//294//31
	CMF_DEATH_GOLD,//295//31
	CMF_DEATH_BLACK,//296//31

	CMF_KNIGHT_RED,//297//32
	CMF_KNIGHT_BLUE,//298//32
	CMF_KNIGHT_PURPLE,//299//32
	CMF_KNIGHT_GREEN,//300//32
	CMF_KNIGHT_GOLD,//301//32
	CMF_KNIGHT_BLACK,//302//32

	CMF_SLIME_RED,//303//33
	CMF_SLIME_BLUE,//304//33
	CMF_SLIME_PURPLE,//305//33
	CMF_SLIME_GREEN,//306//33
	CMF_SLIME_GOLD,//307//33
	CMF_SLIME_BLACK,//308//33

	CMF_KIMERA_RED,//309//34
	CMF_KIMERA_BLUE,//310//34
	CMF_KIMERA_PURPLE,//311//34
	CMF_KIMERA_GREEN,//312//34
	CMF_KIMERA_GOLD,//313//34
	CMF_KIMERA_BLACK,//314//34

	CMF_FAIRY_RED,//315//35
	CMF_FAIRY_BLUE,//316//35
	CMF_FAIRY_PURPLE,//317//35
	CMF_FAIRY_GREEN,//318//35
	CMF_FAIRY_GOLD,//319//35
	CMF_FAIRY_BLACK,//320//35

	CMF_CIRCLE_RED,//321//36
	CMF_CIRCLE_BLUE,//322//36
	CMF_CIRCLE_PURPLE,//323//36
	CMF_CIRCLE_GREEN,//324//36
	CMF_CIRCLE_GOLD,//325//36
	CMF_CIRCLE_BLACK,//326//36

	CMF_ANGEL_RED,//327//37
	CMF_ANGEL_BLUE,//328//37
	CMF_ANGEL_PURPLE,//329//37
	CMF_ANGEL_GREEN,//330//37
	CMF_ANGEL_GOLD,//331//37
	CMF_ANGEL_BLACK,//332//37

	CMF_DARKDRAGON_RED,//333//38
	CMF_DARKDRAGON_BLUE,//334//38
	CMF_DARKDRAGON_PURPLE,//335//38
	CMF_DARKDRAGON_GREEN,//336//38
	CMF_DARKDRAGON_GOLD,//337//38
	CMF_DARKDRAGON_BLACK,//338//38

	CMF_DARKGIANT_RED,//339//39
	CMF_DARKGIANT_BLUE,//340//39
	CMF_DARKGIANT_PURPLE,//341//39
	CMF_DARKGIANT_GREEN,//342//39
	CMF_DARKGIANT_GOLD,//343//39
	CMF_DARKGIANT_BLACK,//344//39

	CMF_FOGRA_RED,//345//40
	CMF_FOGRA_BLUE,//346//40
	CMF_FOGRA_PURPLE,//347//40
	CMF_FOGRA_GREEN,//348//40
	CMF_FOGRA_GOLD,//349//40
	CMF_FOGRA_BLACK,//350//40

	CMF_DRAGON1_RED,//351//41
	CMF_DRAGON1_BLUE,//352//41
	CMF_DRAGON1_PURPLE,//353//41
	CMF_DRAGON1_GREEN,//354//41
	CMF_DRAGON1_GOLD,//355//41
	CMF_DRAGON1_BLACK,//356//41

	CMF_DRAGON2_RED,//357//42
	CMF_DRAGON2_BLUE,//358//42
	CMF_DRAGON2_PURPLE,//359//42
	CMF_DRAGON2_GREEN,//360//42
	CMF_DRAGON2_GOLD,//361//42
	CMF_DRAGON2_BLACK,//362//42

	CMF_BAHAMUT_RED,//363//43
	CMF_BAHAMUT_BLUE,//364//43
	CMF_BAHAMUT_PURPLE,//365//43
	CMF_BAHAMUT_GREEN,//366//43
	CMF_BAHAMUT_GOLD,//367//43
	CMF_BAHAMUT_BLACK,//368//43

	CMF_CASTLE1_RED,//369//44
	CMF_CASTLE1_BLUE,//370//44
	CMF_CASTLE1_PURPLE,//371//44
	CMF_CASTLE1_GREEN,//372//44
	CMF_CASTLE1_GOLD,//373//44
	CMF_CASTLE1_BLACK,//374//44

	CMF_CASTLE2_RED,//375//45
	CMF_CASTLE2_BLUE,//376//45
	CMF_CASTLE2_PURPLE,//377//45
	CMF_CASTLE2_GREEN,//378//45
	CMF_CASTLE2_GOLD,//379//45
	CMF_CASTLE2_BLACK,//380//45

	CMF_SPACE1_RED,//381//46
	CMF_SPACE1_BLUE,//382//46
	CMF_SPACE1_PURPLE,//383//46
	CMF_SPACE1_GREEN,//384//46
	CMF_SPACE1_GOLD,//385//46
	CMF_SPACE1_BLACK,//386//46

	CMF_SPACE2_RED,//387//47
	CMF_SPACE2_BLUE,//388//47
	CMF_SPACE2_PURPLE,//389//47
	CMF_SPACE2_GREEN,//390//47
	CMF_SPACE2_GOLD,//391//47
	CMF_SPACE2_BLACK,//392//47

	CMF_CASTLE_BOSS1_RED,//393//데브리온48
	CMF_CASTLE_BOSS1_BLUE,//394//데브리온48
	CMF_CASTLE_BOSS1_PURPLE,//395//데브리온48
	CMF_CASTLE_BOSS1_GREEN,//396//데브리온48
	CMF_CASTLE_BOSS1_GOLD,//397//데브리온48
	CMF_CASTLE_BOSS1_BLACK,//398//데브리온48

	CMF_CASTLE_BOSS2_RED,//399//엘케인 맨티스49
	CMF_CASTLE_BOSS2_BLUE,//400//엘케인 맨티스49
	CMF_CASTLE_BOSS2_PURPLE,//401//엘케인 맨티스49
	CMF_CASTLE_BOSS2_GREEN,//402//엘케인 맨티스49
	CMF_CASTLE_BOSS2_GOLD,//403//엘케인 맨티스49
	CMF_CASTLE_BOSS2_BLACK,//404//엘케인 맨티스49

	CMF_CASTLE_BOSS3_RED,//405//테트라쿤50
	CMF_CASTLE_BOSS3_BLUE,//406//테트라쿤50
	CMF_CASTLE_BOSS3_PURPLE,//407//테트라쿤50
	CMF_CASTLE_BOSS3_GREEN,//408//테트라쿤50
	CMF_CASTLE_BOSS3_GOLD,//409//테트라쿤50
	CMF_CASTLE_BOSS3_BLACK,//410//테트라쿤50

	CMF_CASTLE_BOSS4_RED,//411//다크나이트51
	CMF_CASTLE_BOSS4_BLUE,//412//다크나이트51
	CMF_CASTLE_BOSS4_PURPLE,//413//다크나이트51
	CMF_CASTLE_BOSS4_GREEN,//414//다크나이트51
	CMF_CASTLE_BOSS4_GOLD,//415//다크나이트51
	CMF_CASTLE_BOSS4_BLACK,//416//다크나이트51

	CMF_NPC_LABETH_RED,//417//c109//라베스
	CMF_NPC_LABETH_BLUE,//418//c109//라베스
	CMF_NPC_LABETH_PURPLE,//419//c109//라베스
	CMF_NPC_LABETH_GREEN,//420//c109//라베스
	CMF_NPC_LABETH_GOLD,//421//c109//라베스
	CMF_NPC_LABETH_BLACK,//422//c109//라베스

	CMF_NPC_ELKEIN_RED,//423//c110//엘케인
	CMF_NPC_ELKEIN_BLUE,//424//c110//엘케인
	CMF_NPC_ELKEIN_PURPLE,//425//c110//엘케인
	CMF_NPC_ELKEIN_GREEN,//426//c110//엘케인
	CMF_NPC_ELKEIN_GOLD,//427//c110//엘케인
	CMF_NPC_ELKEIN_BLACK,//428//c110//엘케인

	TOTALCMF,

	DEMO_HELPER = CMF_NPC_SEBASTIAN,
	PLAYMODE_HELPER = CMF_NPC_DOG,
	BATTLEMODE_HELPER = CMF_NPC_LUISE,
	RAIDMODE_HELPER = CMF_NPC_CAPTAIN,

	//달팽이
	SNAIL_NEUTRAL = 0,
	SNAIL_MOVE,
	SNAIL_MOVE_FAST,
	SNAIL_ATTACK,
	SNAIL_IN,
	SNAIL_HIDE,
	SNAIL_COME,

	SKILL_SNAIL_BULLET = 0,//달팽이 기본공격

	//나무
	TREE_STOP = 0,
	TREE_MOVE,
	TREE_NEUTRAL,
	TREE_ATTACK,

	// FROG
	FROG_NEUTRAL = 0,
	FROG_MOVE,
	FROG_JUMP,
	FROG_RETREAT,
	FROG_LANDING,
	FROG_ATTACK,

	//골렘
	GOLEM_STOP = 0,
	GOLEM_NEUTRAL,
	GOLEM_MOVE,
	GOLEM_MOVE_FAST,
	GOLEM_ATTACK,
	GOLEM_GUARD,
	GOLEM_COUNTER,
	GOLEM_JUMP,
	GOLEM_SPEEDATTACK,
	GOLEM_OPEN,
	GOLEM_OPENED,
	GOLEM_BACKSTEP,
	GOLEM_DIEREADY,
	GOLEM_DIEMOTION,
	GOLEM_DIE,

	//ONEEYE
	ONEEYE_NEUTRAL = 0,
	ONEEYE_MOVE,
	ONEEYE_PLAYER_MOVE,
	//ONEEYE_ATTACK,

	//SKELETON
	SKELETON_NEUTRAL = 0,
	SKELETON_MOVE,
	SKELETON_MOVE_FAST,
	SKELETON_ATTACK,
	SKELETON_RETREAT,

	//ENEMY_LARVA
	LARVA_NEUTRAL = 0,
	LARVA_APPEAR,
	LARVA_HIDE,
	LARVA_HIDED,
	LARVA_ATTACK,
	LARVA_SHOT,

	//JELLYFISH
	JELLYFISH_NEUTRAL = 0,
	JELLYFISH_MOVE,
	JELLYFISH_MOVE_FAST,

	//LIZARD
	LIZARD_NEUTRAL = 0,
	LIZARD_MOVE,
	LIZARD_MOVE_FAST,
	LIZARD_ATTACK,
	LIZARD_RETREAT,

	//SALAMANDER
	SALAMANDER_NEUTRAL = 0,
	SALAMANDER_MOVE,
	SALAMANDER_ATTACK,
	SALAMANDER_JUMPATTACK,
	SALAMANDER_RETREAT,

	//SLING
	SLING_NEUTRAL = 0,
	SLING_MOVE,
	SLING_ATTACK,
	SLING_RETREAT,
	SLING_BACK,
	SLING_SWORD,
	SLING_SWORDMOVE,
	SLING_SWORDBACK,

	//BOAR
	BOAR_NEUTRAL = 0,
	BOAR_MOVE,
	BOAR_MOVE_FAST,
	BOAR_ATTACK,
	BOAR_DASH,

	//GIANT
	GIANT_NEUTRAL = 0,
	GIANT_MOVE,
	GIANT_ATTACK,
	//GIANT_MOVE_FAST,
	GIANT_RETREAT,
	GIANT_BULLET,

	//FLAME
	FLAME_NEUTRAL = 0,
	FLAME_MOVE,
	FLAME_MOVE_FAST,
	FLAME_ATTACK,

	//PHOENIX
	PHOENIX_NEUTRAL = 0,
	PHOENIX_MOVE,
	PHOENIX_DASH,
	PHOENIX_ATTACK,

	//IFRIT
	IFRIT_NEUTRAL = 0,
	IFRIT_NEUTRAL_UP,
	IFRIT_NEUTRAL_DOWN,
	IFRIT_MOVE,
	IFRIT_ATTACK,
	IFRIT_DASH,
	IFRIT_UP,
	IFRIT_DOWN,

	//SNOWMAN
	SNOWMAN_NEUTRAL = 0,
	SNOWMAN_MOVE,
	SNOWMAN_MOVE_FAST,
	SNOWMAN_ATTACK,
	SNOWMAN_HIDE,
	SNOWMAN_HIDED,
	SNOWMAN_APPEAR,

	//FACE
	FACE_STOP = 0,
	FACE_NEUTRAL,
	FACE_MOVE,
	FACE_ATTACK,

	//ICESUN
	ICESUN_NEUTRAL = 0,
	ICESUN_MOVE,
	ICESUN_ATTACK,

	//MAMMOTH
	MAMMOTH_NEUTRAL = 0,
	MAMMOTH_MOVE,
	MAMMOTH_SHOCKWAVE,
	MAMMOTH_SHOT,
	MAMMOTH_RETURN,
	MAMMOTH_BREAK0,
	MAMMOTH_NEUTRAL0,
	MAMMOTH_BREAK0_SHOCKWAVE,
	MAMMOTH_BREAK0_SHOT,
	MAMMOTH_BREAK1,
	MAMMOTH_NEUTRAL1,
	MAMMOTH_BREAK1_SHOCKWAVE,
	MAMMOTH_BREAK2,

	//LIGHTNING
	LIGHTNING_NEUTRAL = 0,
	LIGHTNING_FASTMOVE,
	LIGHTNING_ATTACK,

	//CRYSTAL
	CRYSTAL_NEUTRAL = 0,
	CRYSTAL_STOP,
	CRYSTAL_ATTACK,
	LIGHTNING_MOVE,
	LIGHTNING_FALL,

	//THUNDER
	THUNDER_NEUTRAL = 0,
	THUNDER_MOVE,
	THUNDER_PLAYER_MOVE,
	THUNDER_ATTACK,

	// MACHINE
	MACHINE_NEUTRAL = 0,
	MACHINE_APPEAR,
	MACHINE_LASER_SIDE,
	MACHINE_LASER_CENTER,

	//라이오너
	THUNDERBOSS_NEUTRAL = 0,
	THUNDERBOSS_MOVE,
	THUNDERBOSS_ATTACK,

	//PUMPKIN
	PUMPKIN_NEUTRAL = 0,
	PUMPKIN_MOVE,
	PUMPKIN_MOVE_FAST,
	PUMPKIN_RUSH,
	PUMPKIN_RUSHATTACK,
	PUMPKIN_ATTACK,

	//SPIDER
	SPIDER_DOWN_NEUTRAL = 0,
	SPIDER_DOWN_MOVE,
	SPIDER_DOWN_LASER,
	SPIDER_GUARD,
	SPIDER_JUMP,
	SPIDER_DOWN_LANDING,
	SPIDER_DOWN_LAND,
	SPIDER_UP_NEUTRAL,
	//	SPIDER_UP_MOVE,
	SPIDER_UP_LASER,
	SPIDER_UP_LAND,
	SPIDER_UP_LANDING,
	SPIDER_DOWN,
	SPIDER_ANCHOR_CHANGE,

	//SHIP
	SHIP_NEUTRAL = 0,
	SHIP_MOVE,
	SHIP_CANNONATTACK,
	SHIP_CANNONBREAK,
	SHIP_APPEARWEAK,
	SHIP_CLOSEWEAK,
	SHIP_MOVEOUT,
	SHIP_MOVEIN,
	SHIP_WEAK,				// 보스가 에너지가 달기 시작하는 부분
	SHIP_WEAKMOVE,
	SHIP_LASER,
	SHIP_GUIDESHOT,

	//GHOST
	GHOST_NEUTRAL = 0,
	GHOST_MOVE,
	GHOST_PLAYER_MOVE,
	GHOST_INVISIBLE,
	GHOST_INVISIBLED,
	GHOST_INVISI_MOVE,
	GHOST_ATTACK,

	//DEATH
	DEATH_NEUTRAL = 0,
	DEATH_ATTACK,
	DEATH_SUMMONS,
	DEATH_FINISH,
	DEATH_SKELHEAD,
	DEATH_BREAK_READY,
	DEATH_BREAK,
	DEATH_BROKEN,
	DEATH_BROKEN_NEUTRAL,
	DEATH_BROKEN_ATTACK,
	DEATH_BROKEN_SUMMONS,
	DEATH_BROKEN_FINISH,

	//KNIGHT
	KNIGHT_NEUTRAL = 0,
	KNIGHT_MOVE,
	KNIGHT_PLAYER_MOVE,
	KNIGHT_ATTACK,
	KNIGHT_GUARD,
	KNIGHT_GUARDED,

	//SLIME
	SLIME_NEUTRAL = 0,
	SLIME_MOVE,
	SLIME_ATTACK,

	//KIMERA
	KIMERA_NEUTRAL = 0,
	KIMERA_MOVE,
	KIMERA_FIRESHOT,
	KIMERA_ICESHOT,
	KIMERA_SPIN,
	KIMERA_SPINED,
	KIMERA_LAND_READY,
	KIMERA_LANDING,

	//FAIRY
	FAIRY_NEUTRAL = 0,
	FAIRY_MOVE,
	FAIRY_ATTACK,

	//CIRCLE
	CIRCLE_NEUTRAL = 0,
	CIRCLE_PLAYER_MOVE,
	CIRCLE_RETREAT,
	CIRCLE_DASH,
	CIRCLE_STOP,

	//ANGEL
	ANGEL_NEUTRAL = 0,
	ANGEL_ATTACK,
	ANGEL_MOVE_DOWN,
	ANGEL_MOVE_READY,
	ANGEL_MOVE_CENTER,
	ANGEL_SHOT,
	ANGEL_DASHREADY,
	ANGEL_DASH,			//DASH부분은 항상 젤 밑에잇어야 그림자를 그리지 않음
	ANGEL_DASHUP,
	ANGEL_DASHDOWN,
	ANGEL_MOVE,
	ANGEL_DASHATTACK,

	//DARKDRAGON
	DARKDRAGON_HEAD = 0,
	DARKDRAGON_BODY,
	DARKDRAGON_TAIL,

	//DARKGIANT
	DARKGIANT_NEUTRAL = 0,
	DARKGIANT_MOVE,

	//ENEMY_DRAGON1	//탐욕의 살육자
	DRAGON1_NEUTRAL = 0,
	DRAGON1_MOVE,
	DRAGON1_MOVE_FAST,
	DRAGON1_ATTACK,
	DRAGON1_FALL,
	DRAGON1_LANDINGREADY,
	DRAGON1_LANDING,

	//ENEMY_DRAGON2	//드라곤 좀비
	DRAGON2_NEUTRAL = 0,
	DRAGON2_ATTACK,

	//FOGRA
	FOGRA_CLOSEEYE = 0,
	FOGRA_OPENEYE,
	FOGRA_NEUTRAL,	//기본
	FOGRA_MOVE,
	FOGRA_BULLET,
	FOGRA_LASER,
	FOGRA_SUBFOGRA,
	FOGRA_SUBFOGRA_ATTACK,

	//BAHAMUT
	BAHAMUT_NEUTRAL = 0,
	BAHAMUT_FIRE,
	BAHAMUT_BULLET,
	BAHAMUT_ATTACK,
	BAHAMUT_EVENT,
	BAHAMUT_EVENT2,
	BAHAMUT_EVENT_NEUTRAL,
	BAHAMUT_EVENT_FIRE,
	BAHAMUT_HEAD_NEUTRAL,
	BAHAMUT_HEAD_FIRE,
	BAHAMUT_HEAD_BULLET,
	BAHAMUT_HEAD_ATTACK,
	BAHAMUT_NECK,

	//ENEMY_CASTLE1
	CASTLE1_NEUTRAL = 0,
	CASTLE1_MOVE,
	CASTLE1_DISAPPEAR,
	CASTLE1_APPEAR,
	CASTLE1_ATTACK,

	//ENEMY_CASTLE2
	CASTLE2_NEUTRAL = 0,
	CASTLE2_MOVE,
	CASTLE2_ATTACK,

	//ENEMY_SPACE1
	SPACE1_NEUTRAL = 0,
	SPACE1_MOVE,
	SPACE1_ATTACK,

	//ENEMY_SPACE2
	SPACE2_NEUTRAL = 0,
	SPACE2_MOVE,
	SPACE2_ATTACK,

	//LABETH_BOSS
	LABETH_NEUTRAL = 5,
	LABETH_MOVE,
	LABETH_LASER,
	LABETH_FLAME,
	LABETH_MAGIC,

	//ENEMY_CASTLEBOSS1
	CASTLEBOSS1_BODY_NEUTRAL = 0,
	CASTLEBOSS1_BODY_BULLET,
	CASTLEBOSS1_BODY_MOVEWAIT,
	CASTLEBOSS1_BODY_BOMB,

	CASTLEBOSS1_UARM_NEUTRAL,
	CASTLEBOSS1_UARM_BULLET,
	CASTLEBOSS1_UARM_MOVE,
	CASTLEBOSS1_UARM_DIE,

	CASTLEBOSS1_DARM_NEUTRAL,
	CASTLEBOSS1_DARM_BULLET,
	CASTLEBOSS1_DARM_MOVE,
	CASTLEBOSS1_DARM_DIE,

	//ELKEIN_BOSS
	ELKEIN_NEUTRAL = 9,
	ELKEIN_MOVE,
	ELKEIN_GUARD,
	ELKEIN_JUMPATTACK,
	ELKEIN_DASH,
	ELKEIN_BULLET,

	//ENEMY_CASTLE_BOSS2
	ELKEIN2_NEUTRAL = 0,
	ELKEIN2_MOVE,
	ELKEIN2_ATTACK,
	ELKEIN2_UPATTACK,
	ELKEIN2_JUMPATTACK,
	ELKEIN2_WEAK,

	//ENEMY_CASTLE_BOSS3
	CASTLEBOSS3_NEUTRAL = 0,
	CASTLEBOSS3_LASER,
	CASTLEBOSS3_IMPALE,
	CASTLEBOSS3_BOMB,
	CASTLEBOSS3_IMPALE2,
	CASTLEBOSS3_IMPALE3,

	//ENEMY_CASTLE_BOSS4
	CASTLEBOSS4_NEUTRAL = 0,
	CASTLEBOSS4_WALK,
	CASTLEBOSS4_ATTACK,
	CASTLEBOSS4_WIND,
	CASTLEBOSS4_DEAD,

	CASTLEBOSS4_HAND_NEUTRAL,
	CASTLEBOSS4_HAND_MOVE,
	CASTLEBOSS4_HAND_DOWN,
	CASTLEBOSS4_HAND_ATTACK,
	CASTLEBOSS4_HAND_RETURN,
	CASTLEBOSS4_HAND_GRABMOVE,
	CASTLEBOSS4_HAND_GRAB,
	CASTLEBOSS4_HAND_MOMMOVE,

	//NPC_CAPTAIN//c52//잭스패너
	CAPTAIN_NEUTRAL = 0,

	//NPC_CREW//c53//선원

	//NPC_GRANDFA//c54//촌장

	//NPC_UNCLE//c55//아저씨

	//NPC_AUNT,//c56//아줌마

	//NPC_MAN
	MAN_NEUTRAL = 0,
	MAN_MOVE,
	MAN_TRUMBLE,
	MAN_DIE,

	//NPC_WOMAN//c58//처녀

	//NPC_BOY//c59//꼬마남

	//NPC_GIRL//c60//꼬마녀

	//NPC_ALMA//c61//알마

	//NPC_ITEM//c62//터번
	ITEM_NEUTRAL = 0,

	//NPC_FATMAN//c63
	FATMAN_NEUTRAL = 0,

	//NPC_BUNNYGIRL//c64
	BUNNYGIRL_NEUTRAL = 0,

	//NPC_KNIGHT//c65//플레타

	//NPC_DOG//c66
	DOG_NEUTRAL = 0,

	//NPC_MERCHANT//c67
	MERCHANT_NEUTRAL = 0,

	//NPC_CRAFTMAN//c68
	CRAFTMAN_NEUTRAL = 0,

	//NPC_MAP//c69
	MAP_NEUTRAL = 0,

	//NPC_USERQUEST//c70//스튜어디스
	USERQUEST_NEUTRAL = 0,

	//NPC_TRAVEL//c71//이국의여행자
	TRAVEL_NEUTRAL = 0,

	//NPC_GRANDMA//c72//할머니
	GRANDMA_NEUTRAL = 0,

	//NPC_FISHING
	FISHING_NEUTRAL = 0,
	FISHING_READY,
	FISHING_GETBOX,
	FISHING_GIVEBOX,
	FISHING_GETFISH,
	FISHING_GIVEFISH,

	//NPC_INN//c74

	//NPC_NETITEM//c75

	//NPC_MILESE
	MILESE_NEUTRAL = 0,
	MILESE_MOVE,
	MILESE_MOVEFAST,
	MILESE_DOWN,
	MILESE_ATTACK,
	MILESE_SHAKEHANDS,

	//NPC_DOBEL
	DOBEL_NEUTRAL = 0,
	DOBEL_MOVE,
	DOBEL_NEUTRAL_SWORD,
	DOBEL_DOWN,
	DOBEL_DOWN_HEAD,
	DOBEL_VICTORY,
	DOBEL_KNEE,
	DOBEL_SLEEP_CLOSEEYE,
	DOBEL_SLEEP_OPENEYE,

	//NPC_GAGEL
	GAGEL_NEUTRAL = 0,
	GAGEL_MOVE,
	GAGEL_NEUTRAL_SWORD,
	GAGEL_DOWN,
	GAGEL_DOWN_HEAD,
	GAGEL_VICTORY,
	GAGEL_KNEE,
	GAGEL_SLEEP_CLOSEEYE,
	GAGEL_SLEEP_OPENEYE,
	GAGEL_BOMB,

	//NPC_MONICA//c79
	MONICA_NEUTRAL = 0,

	//NPC_SHIP//c80

	//NPC_SEASOLDIER//c81//아틀란병사
	SEASOLDIER_NEUTRAL = 0,

	//NPC_FRAUD//c82
	FRAUD_NEUTRAL = 0,

	//NPC_DARIAN//c83
	DARIAN_NEUTRAL = 0,

	//NPC_LUISE
	LUISE_NEUTRAL = 0,
	LUISE_MOVE,
	LUISE_ATTACK,
	LUISE_KNEE,

	//NPC_SEAUNCLE//c85//아틀란아저씨
	SEAUNCLE_NEUTRAL = 0,

	//NPC_SEABOY//c86//아틀란소년
	SEABOY_NEUTRAL = 0,

	//NPC_DONALD//c87//이소룡
	DONALD_NEUTRAL = 0,

	//NPC_SCHOLAR//c88//학자
	SCHOLAR_NEUTRAL = 0,

	//NPC_CHEF//c89//요리대가
	CHEF_NEUTRAL = 0,

	//NPC_BISTRO//c90//비스트로
	BISTRO_NEUTRAL = 0,

	//NPC_MAID//c91//시녀
	MAID_NEUTRAL = 0,

	//NPC_ADELKNIGHT//c92//기사
	ADELKNIGHT_NEUTRAL = 0,

	//NPC_SEBASTIAN//c93//세바스찬
	SEBASTIAN_NEUTRAL = 0,

	//NPC_NOBLEMAN//c94//귀족아저씨
	NOBLEMAN_NEUTRAL = 0,//그냥 있을 때                                                            
	NOBLEMAN_CAST,

	//NPC_DELPIOS//c95//델피오스
	DELPIOS_NEUTRAL = 0,
	DELPIOS_MOVE,
	DELPIOS_ATTACK,

	//NPC_LORA//c96//로라
	LORA_NEUTRAL_DRESS = 0,
	LORA_MOVE_DRESS,
	LORA_SAD_DRESS,
	LORA_SUPRISE_DRESS,
	LORA_NEUTRAL,
	LORA_MOVE,

	//NPC_WITCH//c97//마녀

	//NPC_ELFGRANDFA//c98//엘프할아버지

	//NPC_ELFUNCLE//c99//엘프아저씨

	//NPC_ELFAUNT//c100//엘프아줌마

	//NPC_ELFMAN//c101//엘프청년

	//NPC_ELFWOMAN//c102//엘프처녀

	//NPC_ELFBOY//c103//엘프꼬마남

	//NPC_ELFGIRL//c104//엘프꼬마녀

	//NPC_ELFDARK//c105//엘프다크

	//NPC_ELFMAGIC//c106//엘프마법사

	//NPC_ELFDANCER//c107//엘프무희

	//NPC_OWL//c108//부엉이

	//NPC_LABETH//c109//라베스

	//NPC_ELKEIN//c110//엘케인

	//NPC_ELEIN//c111//엘레인
	ELEIN_NEUTRAL = 0,
	ELEIN_SWORD,
	ELEIN_DOWN,
	ELEIN_DOWNHOLD,
	ELEIN_NEUTRAL_GHOST,
	ELEIN_SAD_GHOST,
	ELEIN_SURPRISE_GHOST,
	ELEIN_HUG_GHOST,
	ELEIN_LIGHT_GHOST,
	ELEIN_DISAPPEAR_GHOST,

	//NPC_EVAN
	EVAN_NEUTRAL = 0,
	EVAN_MOVE,
	EVAN_ATTACK,
	EVAN_DOWN,
	EVAN_KNEE,
	EVAN_KNOCKBACK,
	EVAN_MOVEFAST,
	EVAN_THROW,
	EVAN_NEUTRAL_BABY,
	EVAN_GUARD,
	EVAN_GUARDBACK,
	EVAN_KNEE_SWORD,
	EVAN_COUNTERATTACK,
	EVAN_TAKEOUT_HOLYSWORD,
	EVAN_NEUTRAL_HOLYSWORD,
	EVAN_JUMPATTACK,
	EVAN_DOWN_HOLYSWORD,
	EVAN_ONLY_HOLYSWORD,
	EVAN_SHAKEHANDS,

	//NPC_BEAD//c113//테이블

	//NPC_FOUNTAIN//c114//샘물

	//NPC_NEZAR//c115//네자르

	//NPC_GALLAND//c116//갈란드

	//NPC_DURAK//c117//듀라크

	//NPC_KING//c118//에드몬드

	//NPC_WOMANGHOST//c119//여자유령

	//NPC_MANGHOST//c120//남자유령

	//NPC_AUSTIN
	AUSTIN_NEUTRAL = 0,
	AUSTIN_STATUE,
	AUSTIN_NEUTRAL_LIGHT,
	AUSTIN_DISAPPEAR,

	//NPC_SOUL
	SOUL_4_NEUTRAL = 0,
	SOUL_4_NEUTRAL_RISE,
	SOUL_DARK,
	SOUL_DARK_AWAY,
	SOUL_5_NEUTRAL,
	SOUL_6_NEUTRAL,
	SOUL_SPARK,
	SOUL_NEUTRAL,
	SOUL_BURST,
	SOUL_PART0,
	SOUL_6_ROTATION,
	SOUL_6_TOGETHER,
	SOUL_5_ROTATION,
	SOUL_FLAME,
	SOUL_ICE,
	SOUL_THUNDER,
	SOUL_LIGHT,
	SOUL_NEUTRAL2,
	SOUL_NEUTRAL3,

	//NPC들의 행동패턴
	NPCMOVE_STAND = 0,	//제자리에 서있기
	NPCMOVE_WALKSLOW,	//천천히 걷다가 섰다를 반복
	NPCMOVE_WALKFAST,	//계속 분주하게 좌우로 걸어다님
	NPCMOVE_GOTOPLAYER,	//플레이어 ?아다니기
	NPCMOVE_2FRAME,	//지정된 모션으로부터 2프레임을 반복(우는 유치원생)
	NPCMOVE_DOG,	//개들의 움직임
	NPCMOVE_BLOCK,	//블록하는 캐릭터
	NPCMOVE_CAST,//시전하는 경우

} CMFDEF;

#endif
