#pragma once

#ifndef _DEF_DEMO_H_
#define _DEF_DEMO_H_

typedef enum _demoDef {
	MAXMAPDEMO = 52,
	MAXDEMOFRAMEDATA = 78,
	MAXDEMODATA = 7 + MAXDEMOFRAMEDATA,

	//데모용 프레임시리즈
	D_STOPFRAME = 5,
	D_SETQUESTFRAME = 10,
	D_TALKFRAME = 3,
	D_QUESTFRAME = 10,
	D_EMOTICONFRAME = 12,
	D_GATHERFRAME = 16,
	D_SPREADFRAME = 10,
	D_FADEFRAME = 16,
	D_FOCUSFRAME = 10,
	D_JUMPFRAME = 10,

	DDLEN = 7,	//데모별 설정 데이터 길이
	DFLEN = 3,	//데모의 프레임 행동 데이터 길이

	MOVIE_MOVE = 0,
	MOVIE_TALK,
	MOVIE_WIN,
	MOVIE_ALPHA,
	MOVIE_NARRATION,
	MOVIE_PLAYER_PREPARE,	//캐릭터 생성
	MOVIE_SPREAD_MDR,
	MOVIE_SPREAD_MRD,
	MOVIE_SPREAD_DRM,
	MOVIE_SPREAD_DMR,
	MOVIE_SPREAD_RMD,
	MOVIE_SPREAD_RDM,
	MOVIE_GATHER_PLAYER,
	MOVIE_SETQUEST_PLAYER,
	MOVIE_WAITDARKSTONE,
	MOVIE_OBJSHAKE,
	MOVIE_WARPIN,
	MOVIE_WARPOUT,
	MOVIE_APPEAROBJ,
	MOVIE_DISAPPEAROBJ,
	MOVIE_FRAMEUNSETBLEND,
	MOVIE_GAZEAROUND,
	MOVIE_MENU,
	MOVIE_MENUTALK,
	MOVIE_MENUMOVE,


	//데모 발동 조건 데이터 형식
	TRIGGER_NONE = 0,	//발동 안되는 데모
	TRIGGER_ROOM,	//현재 방에 처음 들어왔으면
	TRIGGER_PLACE,			//특정 위치에 왔으면
	TRIGGER_TALK,			//말을 걸면
	TRIGGER_ALWAYS_PLACE,			//어디 가면 항상 나오는 이벤트
	TRIGGER_ALWAYS_TALK,			//계속 이야기를 거는 이벤트
	TRIGGER_ALWAYS_ROOM,			//어떤방에 진입하면 항상 나오는 이벤트
	TRIGGER_ITEM,			//아이템을 먹으면 나오는 이벤트
	TRIGGER_IGNORE,		//본거랑 상관없이
	TRIGGER_PLACE_LIMIT,	//x도 얼마이하, y도 얼마이하면
	TRIGGER_PLACE_LIMIT2,	//x는 얼마이하, y는 얼마이상
	TRIGGER_PLACE_LIMIT3,	//x는 얼마이상, y는 얼마이상
	TRIGGER_PLACE_LIMIT4,	//x는 얼마이상, y는 얼마이하
	TRIGGER_PLACE_SANDWICH,	//x는 a, b 사이

	EFFECT_FADEIN = 0,	//밝아짐
	EFFECT_FADEOUT,		//어두워짐
	EFFECT_BLACK,			//까만 화면
	EFFECT_WHITE,			//하얀 화면
	EFFECT_DARKFOG,			//테트라쿤 검은안개 뿌리기
	EFFECT_GRAY,			//회상 화면(회색)
	EFFECT_GRAYNULL,		//회상 화면 풀기
	EFFECT_REGENMONSTER,	//몬스터 생성시키기
	EFFECT_DEMOMOVE,		//무브핸들러변경
	EFFECT_ENEMYMOVE,		//무브핸들러변경
	EFFECT_GUARDMOVE,		//무브핸들러 변경
	EFFECT_GOLIMOVE,	//무브핸들러 변경
	EFFECT_GUARDMOVE2,	//디브와 메로 지키기
	EFFECT_ENEMYDRAW,		//몬스터 드로우핸들러 변경
	EFFECT_MENU,
	EFFECT_TALK,			//말하기
	EFFECT_MENUTALK,
	EFFECT_SHAKETALK,		//창흔들면서 말하기
	EFFECT_FOCUS,			//초점 이동
	EFFECT_FOCUS_FAST,		//초점 순간이동
	EFFECT_MOVELEFT_NPC,	//엔피씨 좌측 걷기
	EFFECT_MOVERIGHT_NPC,	//엔피씨 우측 걷기
	EFFECT_RUNLEFT_NPC,		//엔피씨 좌측 달리기
	EFFECT_RUNRIGHT_NPC,	//엔피씨 우측 달리기
	EFFECT_EMPTYFOCUS,	//빈공간에 포커스를 잡는다
	EFFECT_EMPTYFOCUS_FAST,	//빈공간에 포커스를 빠르게 잡는다
	EFFECT_JUMP,			//점프
	EFFECT_SHORTJUMP,
	EFFECT_CHANGEGHOSTDRAW,	//드로우핸들러를 고스트드로우로 바꿔줌.
	EFFECT_TIMESTART,
	EFFECT_LONGJUMP,			//롱점프
	EFFECT_LOOKLEFT,		//좌측 보기
	EFFECT_LOOKRIGHT,	//우측 보기
	EFFECT_CONTRASTDIR,	//방향전환(좌->우/우->좌)
	EFFECT_LOOKPLAYER,	//주인공쪽 보기
	EFFECT_AGAINSTPLAYER,	//주인공 반대쪽 보기
	EFFECT_DEACTIVATE,	//adtive false
	EFFECT_DEACTIVATE2,	//type이 같은 모든걸 꺼준다.
	EFFECT_ACTIVATE,		//active
	EFFECT_ESCORT,
	EFFECT_ACTIVATE2,		//type이 같은걸 모두 켜준다.
	EFFECT_STATUSON,	//status = ON
	EFFECT_MXON,			//mx = true
	EFFECT_SETROOM,			//방이동
	EFFECT_GETITEM,		//아이템먹기
	EFFECT_GIVEITEM,		//아이템주기
	EFFECT_QUEST,		//퀘스트획득
	EFFECT_CLEARQUEST,		//퀘스트완료
	EFFECT_FAILQUEST,		//퀘스트실패
	EFFECT_PLAYMUSIC,		//사운드틀기
	EFFECT_STOPMUSIC,		//사운드스탑
	EFFECT_SHAKE,			//화면흔들기
	EFFECT_BOSSROOM,		//보스룸지정
	EFFECT_FRONTROBIN,		//주인공 앞 이미지 오브젝지정
	EFFECT_ERASEOBJECT,	//OBJ MEMSET
	EFFECT_ENEMY,			//NPC를 적으로
	EFFECT_NPC,				//적으로 변했던 NPC를 다시 NPC로
	EFFECT_ROBINATTACK,		//로빈을 공격
	EFFECT_WARPIN,			//워프로 나타남
	EFFECT_WARPOUT,			//워프로 사라짐
	EFFECT_WARPSTOP,		//워프모션 제거
	EFFECT_FINALTRAP,		//마지막방 스위치 하나 제거
	EFFECT_FINALTRAPBANG,	//마지막방 장애물 부수기
	EFFECT_LASTBOSS,		//마지막 보스 세팅
	EFFECT_RETURNGYSKIL,	//마지막 보스에서 기스킬로 돌아오는것
	EFFECT_ERASEWALL,	//엔딩에서 벽정보 없애기
	EFFECT_HEADZOOMIN,
	EFFECT_OBJSHAKE,
	EFFECT_APPEAROBJ,		//슬슬등장
	EFFECT_DISAPPEAROBJ,		//슬슬사라짐
	//EFFECT_PUNISH_PLAYER,
	EFFECT_GAZEAROUND,		//두리번 거리다.PLAYERALL사용가능
	EFFECT_ATTACK,
	EFFECT_ZOOM,
	EFFECT_NARRATION,
	EFFECT_PLAYER_PREPARE,
	EFFECT_SPREAD_MDR,
	EFFECT_SPREAD_MRD,
	EFFECT_SPREAD_DRM,
	EFFECT_SPREAD_DMR,
	EFFECT_SPREAD_RMD,
	EFFECT_SPREAD_RDM,
	EFFECT_GATHER_PLAYER,
	EFFECT_SLINGMOVE,
	EFFECT_APPEARBOSSMOVE,
	EFFECT_CHANGETOLEMTILE,
	EFFECT_CHANGEADELTILE,
	EFFECT_CHANGEDEVILTILE,
	EFFECT_CHANGEDEVILTILE2,
	EFFECT_ALERT,
	EFFECT_RIDEGOLEM,		//골렘에 탑승
	EFFECT_TAKEDOWNGOLEM,	//골렘에서 내림
	EFFECT_FRAMEUNSETBLEND,
	EFFECT_GOTOTITLE,
	EFFECT_SETQUEST_PLAYER,
	EFFECT_POISON,
	EFFECT_LENZ,

	EFFECT_EQUIPALL,
	EFFECT_UNEQUIPALL,
	EFFECT_EQUIPONLYSWORD,
	EFFECT_WAVE,

	EFFECT_CHANGE_ETC = 170,		//etc를 바꿔줌
	EFFECT_ERASEICON = 190,
	EFFECT_ICON = 190,	//아이콘
	EFFECT_STOP = 210,
	EFFECT_MOVELEFT = 210,	//좌
	EFFECT_MOVERIGHT = 230,	//우
	EFFECT_MOVEUP = 250,	//상
	EFFECT_MOVEDOWN = 270,	//하
	EFFECT_MOVEDOWN2 = 330,	//하
	EFFECT_ALPHA_0 = 350,	//알파 그리기
	EFFECT_ALPHA_1,
	EFFECT_ALPHA_2,
	EFFECT_ALPHA_3,
	EFFECT_ALPHA_4,
	EFFECT_ALPHA_5,
	EFFECT_ALPHA_6,
	EFFECT_ALPHA_7,
	EFFECT_ALPHA_8,
	EFFECT_ALPHA_9,
	EFFECT_WAITDARKSTONE,
	EFFECT_SETTILEY = 1000,			//y 위치 강제 설정	//최대치 변경 X,Y,MOTION
	EFFECT_SETTILEX = 2000,			//x 위치 강제 설정
	EFFECT_MOTION = 3000,		//강제모션지정
	EFFECT_SETTYPE = 3500,//강제NPC지정


	//데모신
	//오프닝
	DEMO_OPENING_PEACEFUL = 0,//공주의 등장
	DEMO_OPENING_DARKKNIGHT,//대마왕 등장
	DEMO_OPENING_PLUNDER,//약탈
	DEMO_OPENING_WARNNING,//칼 쥐고 고고.
	DEMO_OPENING_END,//끝
	
	//도입부
	DEMO_OPENING_BEGGAR,

	//조작법
	//1층
	DEMO_TUTORIAL_SEBASTIAN,	//세바스찬의 등장(왼쪽으로 나가서 왼쪽으로 들어온다.)
	DEMO_TUTORIAL_PLAYER,	//내 캐릭터를 보여주고
	DEMO_TUTORIAL_ENEMY,		//적의 등장 및 적 체력 게이지와 남은 시간에 대한 설명
	DEMO_TUTORIAL_JOYSTICK,		//조이스틱을 터치해서 공격해보라는것(조이스틱을 슬라이드로 땡기면 자동으로 공격됩니다.)
	DEMO_TUTORIAL_JOKBO_COIN,	//족보중 코인에 대해
	DEMO_TUTORIAL_JOKBO_COINBAG,	//족보중 코인백에 대해
	DEMO_TUTORIAL_JOKBO_HEART,	//족보중 하트에 대해
	DEMO_TUTORIAL_JOKBO_QUEST,	//족보중 퀘스트 아이템에 대해
	DEMO_TUTORIAL_BOSS,			//보스
	DEMO_TUTORIAL_JOKBO_BATTLE,	//족보중 배틀에 대해
	DEMO_TUTORIAL_JOKBO_RAID,	//족보중 레이드에 대해
	DEMO_TUTORIAL_JOKBO_SKILL,	//족보중 스킬에 대해
	DEMO_TUTORIAL_GETWEAPON,	//두번째 무기를 주고

	DEMO_TUTORIAL_END,		//자 그럼 이제 성주를 물리치고 공격을 해 보자고

	TOTALDEMO,

	//DEMO_OPENING
	DEMO_OPENING_PEACEFUL_FRAME0 = 0,
	DEMO_OPENING_DARKKNIGHT_FRAME0 = DEMO_OPENING_PEACEFUL_FRAME0 + 7,
	DEMO_OPENING_PLUNDER_FRAME0 = DEMO_OPENING_DARKKNIGHT_FRAME0 + 3,
	DEMO_OPENING_WARNNING_FRAME0 = DEMO_OPENING_PLUNDER_FRAME0 + 3,
	DEMO_OPENING_END_FRAME0 = DEMO_OPENING_WARNNING_FRAME0 + 3,

	DEMO_OPENING_BEGGAR_FRAME0 = DEMO_OPENING_END_FRAME0 + 3,
	//DEMO_TUTORIAL_SEBASTIAN
	DEMO_TUTORIAL_SEBASTIAN_FRAME0 = DEMO_OPENING_BEGGAR_FRAME0 + 53,
	//DEMO_TUTORIAL_PLAYER
	DEMO_TUTORIAL_PLAYER_FRAME0 = DEMO_TUTORIAL_SEBASTIAN_FRAME0 + 1,
	//DEMO_TUTORIAL_ENEMY
	DEMO_TUTORIAL_ENEMY_FRAME0 = DEMO_TUTORIAL_PLAYER_FRAME0 + 18,
	//DEMO_TUTORIAL_JOYSTICK
	DEMO_TUTORIAL_JOYSTICK_FRAME0 = DEMO_TUTORIAL_ENEMY_FRAME0 + 18,
	//DEMO_TUTORIAL_JOKBO_COIN
	DEMO_TUTORIAL_JOKBO_COIN_FRAME0 = DEMO_TUTORIAL_ENEMY_FRAME0 + 18,
	//DEMO_TUTORIAL_JOKBO_COINBAG
	DEMO_TUTORIAL_JOKBO_COINBAG_FRAME0 = DEMO_TUTORIAL_JOKBO_COIN_FRAME0 + 18,
	//DEMO_TUTORIAL_JOKBO_HEART
	DEMO_TUTORIAL_JOKBO_HEART_FRAME0 = DEMO_TUTORIAL_JOKBO_COINBAG_FRAME0 + 18,
	//DEMO_TUTORIAL_JOKBO_QUEST
	DEMO_TUTORIAL_JOKBO_QUEST_FRAME0 = DEMO_TUTORIAL_JOKBO_HEART_FRAME0 + 18,
	//DEMO_TUTORIAL_JOKBO_HIT
	DEMO_TUTORIAL_JOKBO_HIT_FRAME0 = DEMO_TUTORIAL_JOKBO_QUEST_FRAME0 + 18,
	//DEMO_TUTORIAL_JOKBO_RAID
	DEMO_TUTORIAL_JOKBO_RAID_FRAME0 = DEMO_TUTORIAL_JOKBO_HIT_FRAME0 + 18,
	//DEMO_TUTORIAL_JOKBO_SKILL
	DEMO_TUTORIAL_JOKBO_SKILL_FRAME0 = DEMO_TUTORIAL_JOKBO_RAID_FRAME0 + 18,
	//DEMO_TUTORIAL_GETWEAPON
	DEMO_TUTORIAL_GETWEAPON_FRAME0 = DEMO_TUTORIAL_JOKBO_SKILL_FRAME0 + 18,

	TOTAL_DEMO_FRAME,

	END_DEMODEF
} DEMODEF;

typedef enum _demoSceneDef {
	//DEMO_OPENING
	//DEMO_OPENING_PEACEFUL
	DEMO_OPENING_PEACEFUL_FRAME0_SCENE = 0,
	DEMO_OPENING_PEACEFUL_FRAME1_SCENE = DEMO_OPENING_PEACEFUL_FRAME0_SCENE + FPS / 2,
	DEMO_OPENING_PEACEFUL_FRAME2_SCENE = DEMO_OPENING_PEACEFUL_FRAME1_SCENE + FPS,
	DEMO_OPENING_PEACEFUL_FRAME3_SCENE = DEMO_OPENING_PEACEFUL_FRAME2_SCENE + FPS,
	DEMO_OPENING_PEACEFUL_FRAME4_SCENE = DEMO_OPENING_PEACEFUL_FRAME3_SCENE + FPS,
	DEMO_OPENING_PEACEFUL_FRAME5_SCENE = DEMO_OPENING_PEACEFUL_FRAME4_SCENE + FPS,

	//DEMO_OPENING_DARKKNIGHT
	DEMO_OPENING_DARKKNIGHT_FRAME0_SCENE = 0,
	DEMO_OPENING_DARKKNIGHT_FRAME1_SCENE = DEMO_OPENING_DARKKNIGHT_FRAME0_SCENE + FPS,
	DEMO_OPENING_DARKKNIGHT_FRAME2_SCENE = DEMO_OPENING_DARKKNIGHT_FRAME1_SCENE + FPS,
	DEMO_OPENING_DARKKNIGHT_FRAME3_SCENE = DEMO_OPENING_DARKKNIGHT_FRAME2_SCENE + FPS,
	
	//DEMO_OPENING_PLUNDER
	DEMO_OPENING_PLUNDER_FRAME0_SCENE = 0,
	DEMO_OPENING_PLUNDER_FRAME1_SCENE = DEMO_OPENING_PLUNDER_FRAME0_SCENE + FPS,
	DEMO_OPENING_PLUNDER_FRAME2_SCENE = DEMO_OPENING_PLUNDER_FRAME1_SCENE + FPS,
	DEMO_OPENING_PLUNDER_FRAME3_SCENE = DEMO_OPENING_PLUNDER_FRAME2_SCENE + FPS,

	//DEMO_OPENING_WARNING
	DEMO_OPENING_WARNING_FRAME0_SCENE = 0,
	DEMO_OPENING_WARNING_FRAME1_SCENE = DEMO_OPENING_WARNING_FRAME0_SCENE + FPS,
	DEMO_OPENING_WARNING_FRAME2_SCENE = DEMO_OPENING_WARNING_FRAME1_SCENE + FPS,
	DEMO_OPENING_WARNING_FRAME3_SCENE = DEMO_OPENING_WARNING_FRAME2_SCENE + FPS,

	//DEMO_OPENING_END
	DEMO_OPENING_END_FRAME0_SCENE = 0,
	DEMO_OPENING_END_FRAME1_SCENE = DEMO_OPENING_END_FRAME0_SCENE + FPS,
	DEMO_OPENING_END_FRAME2_SCENE = DEMO_OPENING_END_FRAME1_SCENE + FPS,
	DEMO_OPENING_END_FRAME3_SCENE = DEMO_OPENING_END_FRAME2_SCENE + FPS,

	//기사는 검을 발견하게 되고
	//DEMO_OPENING_BEGGAR
	DEMO_OPENING_BEGGAR_FRAME0_SCENE = 0,
	DEMO_OPENING_BEGGAR_FRAME1_SCENE = DEMO_OPENING_BEGGAR_FRAME0_SCENE + FPS,
	DEMO_OPENING_BEGGAR_FRAME2_SCENE = DEMO_OPENING_BEGGAR_FRAME1_SCENE + FPS / 5 / 2,
	DEMO_OPENING_BEGGAR_FRAME3_SCENE = DEMO_OPENING_BEGGAR_FRAME2_SCENE + FPS / 5 / 2,
	DEMO_OPENING_BEGGAR_FRAME4_SCENE = DEMO_OPENING_BEGGAR_FRAME3_SCENE + FPS / 5,
	DEMO_OPENING_BEGGAR_FRAME5_SCENE = DEMO_OPENING_BEGGAR_FRAME4_SCENE + 1,
	DEMO_OPENING_BEGGAR_FRAME6_SCENE = DEMO_OPENING_BEGGAR_FRAME5_SCENE + FPS / 5,
	DEMO_OPENING_BEGGAR_FRAME7_SCENE = DEMO_OPENING_BEGGAR_FRAME6_SCENE + FPS / 5,
	DEMO_OPENING_BEGGAR_FRAME8_SCENE = DEMO_OPENING_BEGGAR_FRAME7_SCENE + 1,
	DEMO_OPENING_BEGGAR_FRAME9_SCENE = DEMO_OPENING_BEGGAR_FRAME8_SCENE + FPS / 5,
	DEMO_OPENING_BEGGAR_FRAME10_SCENE = DEMO_OPENING_BEGGAR_FRAME9_SCENE + 1,
	DEMO_OPENING_BEGGAR_FRAME11_SCENE = DEMO_OPENING_BEGGAR_FRAME10_SCENE + FPS,
	DEMO_OPENING_BEGGAR_FRAME12_SCENE = DEMO_OPENING_BEGGAR_FRAME11_SCENE + FPS / 5,
	DEMO_OPENING_BEGGAR_FRAME13_SCENE = DEMO_OPENING_BEGGAR_FRAME12_SCENE + 1,
	DEMO_OPENING_BEGGAR_FRAME14_SCENE = DEMO_OPENING_BEGGAR_FRAME13_SCENE + FPS / 5 / 2,
	DEMO_OPENING_BEGGAR_FRAME15_SCENE = DEMO_OPENING_BEGGAR_FRAME14_SCENE + 1,
	DEMO_OPENING_BEGGAR_FRAME16_SCENE = DEMO_OPENING_BEGGAR_FRAME15_SCENE + FPS / 5,
	DEMO_OPENING_BEGGAR_FRAME17_SCENE = DEMO_OPENING_BEGGAR_FRAME16_SCENE + FPS / 5 / 2,
	DEMO_OPENING_BEGGAR_FRAME18_SCENE = DEMO_OPENING_BEGGAR_FRAME17_SCENE + FPS / 5 / 2,
	DEMO_OPENING_BEGGAR_FRAME19_SCENE = DEMO_OPENING_BEGGAR_FRAME18_SCENE + FPS / 5 / 2,
	DEMO_OPENING_BEGGAR_FRAME20_SCENE = DEMO_OPENING_BEGGAR_FRAME19_SCENE + 1,
	DEMO_OPENING_BEGGAR_FRAME21_SCENE = DEMO_OPENING_BEGGAR_FRAME20_SCENE + FPS / 5,
	DEMO_OPENING_BEGGAR_FRAME22_SCENE = DEMO_OPENING_BEGGAR_FRAME21_SCENE + 1,
	DEMO_OPENING_BEGGAR_FRAME23_SCENE = DEMO_OPENING_BEGGAR_FRAME22_SCENE + FPS / 5 / 2,
	DEMO_OPENING_BEGGAR_FRAME24_SCENE = DEMO_OPENING_BEGGAR_FRAME23_SCENE + FPS / 5 / 2,
	DEMO_OPENING_BEGGAR_FRAME25_SCENE = DEMO_OPENING_BEGGAR_FRAME24_SCENE + FPS / 5 / 2,
	DEMO_OPENING_BEGGAR_FRAME26_SCENE = DEMO_OPENING_BEGGAR_FRAME25_SCENE + FPS / 5 / 2,
	DEMO_OPENING_BEGGAR_FRAME27_SCENE = DEMO_OPENING_BEGGAR_FRAME26_SCENE + FPS / 5 / 2,
	DEMO_OPENING_BEGGAR_FRAME28_SCENE = DEMO_OPENING_BEGGAR_FRAME27_SCENE + FPS / 5 / 2,
	DEMO_OPENING_BEGGAR_FRAME29_SCENE = DEMO_OPENING_BEGGAR_FRAME28_SCENE + 1,
	DEMO_OPENING_BEGGAR_FRAME30_SCENE = DEMO_OPENING_BEGGAR_FRAME29_SCENE + FPS / 5,
	DEMO_OPENING_BEGGAR_FRAME31_SCENE = DEMO_OPENING_BEGGAR_FRAME30_SCENE + FPS,
	DEMO_OPENING_BEGGAR_FRAME32_SCENE = DEMO_OPENING_BEGGAR_FRAME31_SCENE + FPS / 5,
	DEMO_OPENING_BEGGAR_FRAME33_SCENE = DEMO_OPENING_BEGGAR_FRAME32_SCENE + FPS / 5,
	DEMO_OPENING_BEGGAR_FRAME34_SCENE = DEMO_OPENING_BEGGAR_FRAME33_SCENE + FPS,

	//DEMO_TUTORIAL_SEBASTIAN
	DEMO_TUTORIAL_SEBASTIAN_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_SEBASTIAN_FRAME1_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME0_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME2_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME1_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME3_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME2_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME4_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME3_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME5_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME4_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME6_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME5_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME7_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME6_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME8_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME7_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME9_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME8_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME10_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME9_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME11_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME10_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME12_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME11_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME13_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME12_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME14_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME13_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME15_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME14_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME16_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME15_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME17_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME16_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME18_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME17_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME19_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME18_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME20_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME19_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME21_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME20_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME22_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME21_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME23_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME22_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME24_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME23_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME25_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME24_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME26_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME25_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME27_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME26_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME28_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME27_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME29_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME28_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME30_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME29_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME31_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME30_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME32_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME31_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME33_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME32_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME34_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME33_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME35_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME34_SCENE + FPS / 4,

	//DEMO_TUTORIAL_PLAYER
	DEMO_TUTORIAL_PLAYER_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_PLAYER_FRAME1_SCENE = DEMO_TUTORIAL_PLAYER_FRAME0_SCENE + 18,

	//DEMO_TUTORIAL_ENEMY
	DEMO_TUTORIAL_ENEMY_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_ENEMY_FRAME1_SCENE = DEMO_TUTORIAL_ENEMY_FRAME0_SCENE + 18,

	//DEMO_TUTORIAL_JOYSTICK
	DEMO_TUTORIAL_JOYSTICK_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_JOYSTICK_FRAME1_SCENE = DEMO_TUTORIAL_JOYSTICK_FRAME0_SCENE + 18,

	//DEMO_TUTORIAL_JOKBO_COIN
	DEMO_TUTORIAL_JOKBO_COIN_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_JOKBO_COIN_FRAME1_SCENE = DEMO_TUTORIAL_JOKBO_COIN_FRAME0_SCENE + 18,

	//DEMO_TUTORIAL_JOKBO_COINBAG
	DEMO_TUTORIAL_JOKBO_COINBAG_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_JOKBO_COINBAG_FRAME1_SCENE = DEMO_TUTORIAL_JOKBO_COINBAG_FRAME0_SCENE + 18,

	//DEMO_TUTORIAL_JOKBO_HEART
	DEMO_TUTORIAL_JOKBO_HEART_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_JOKBO_HEART_FRAME1_SCENE = DEMO_TUTORIAL_JOKBO_HEART_FRAME0_SCENE + 18,

	//DEMO_TUTORIAL_JOKBO_QUEST
	DEMO_TUTORIAL_JOKBO_QUEST_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_JOKBO_QUEST_FRAME1_SCENE = DEMO_TUTORIAL_JOKBO_QUEST_FRAME0_SCENE + 18,

	//DEMO_TUTORIAL_BOSS
	DEMO_TUTORIAL_BOSS_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_BOSS_FRAME1_SCENE = DEMO_TUTORIAL_BOSS_FRAME0_SCENE + 18,

	//DEMO_TUTORIAL_JOKBO_BATTLE
	DEMO_TUTORIAL_JOKBO_BATTLE_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_JOKBO_BATTLE_FRAME1_SCENE = DEMO_TUTORIAL_JOKBO_BATTLE_FRAME0_SCENE + 18,

	//DEMO_TUTORIAL_JOKBO_RAID
	DEMO_TUTORIAL_JOKBO_RAID_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_JOKBO_RAID_FRAME1_SCENE = DEMO_TUTORIAL_JOKBO_RAID_FRAME0_SCENE + 18,

	//DEMO_TUTORIAL_JOKBO_SKILL
	DEMO_TUTORIAL_JOKBO_SKILL_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_JOKBO_SKILL_FRAME1_SCENE = DEMO_TUTORIAL_JOKBO_SKILL_FRAME0_SCENE + 18,

	//DEMO_TUTORIAL_GETWEAPON
	DEMO_TUTORIAL_GETWEAPON_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_GETWEAPON_FRAME1_SCENE = DEMO_TUTORIAL_GETWEAPON_FRAME0_SCENE + 18,

	TOTALDEMOFRAMESCENE,

	END_DEMOSCENEDEF
} DEMOSCENEDEF;

#endif
