#pragma once

#ifndef _DEF_DEMO_H_
#define _DEF_DEMO_H_

typedef enum _demoDef {
	MAXMAPDEMO = 52,
	MAXDEMOFRAMEDATA = 78,
	MAXDEMODATA = 7 + MAXDEMOFRAMEDATA,

	//데모용 프레임시리즈
	D_STOPFRAME = 5,
	D_SETQUESTFRAME = 10,
	D_TALKFRAME = 3,
	D_QUESTFRAME = 10,
	D_EMOTICONFRAME = 12,
	D_GATHERFRAME = 16,
	D_SPREADFRAME = 10,
	D_FADEFRAME = 16,
	D_FOCUSFRAME = 10,
	D_JUMPFRAME = 10,

	DDLEN = 7,	//데모별 설정 데이터 길이
	DFLEN = 3,	//데모의 프레임 행동 데이터 길이

	MOVIE_MOVE = 0,
	MOVIE_TALK,
	MOVIE_WIN,
	MOVIE_ALPHA,
	MOVIE_NARRATION,
	MOVIE_PLAYER_PREPARE,	//캐릭터 생성
	MOVIE_SPREAD_MDR,
	MOVIE_SPREAD_MRD,
	MOVIE_SPREAD_DRM,
	MOVIE_SPREAD_DMR,
	MOVIE_SPREAD_RMD,
	MOVIE_SPREAD_RDM,
	MOVIE_GATHER_PLAYER,
	MOVIE_SETQUEST_PLAYER,
	MOVIE_WAITDARKSTONE,
	MOVIE_OBJSHAKE,
	MOVIE_WARPIN,
	MOVIE_WARPOUT,
	MOVIE_APPEAROBJ,
	MOVIE_DISAPPEAROBJ,
	MOVIE_FRAMEUNSETBLEND,
	MOVIE_GAZEAROUND,
	MOVIE_MENU,
	MOVIE_MENUTALK,
	MOVIE_MENUMOVE,


	//데모 발동 조건 데이터 형식
	TRIGGER_NONE = 0,	//발동 안되는 데모
	TRIGGER_ROOM,	//현재 방에 처음 들어왔으면
	TRIGGER_PLACE,			//특정 위치에 왔으면
	TRIGGER_TALK,			//말을 걸면
	TRIGGER_ALWAYS_PLACE,			//어디 가면 항상 나오는 이벤트
	TRIGGER_ALWAYS_TALK,			//계속 이야기를 거는 이벤트
	TRIGGER_ALWAYS_ROOM,			//어떤방에 진입하면 항상 나오는 이벤트
	TRIGGER_ITEM,			//아이템을 먹으면 나오는 이벤트
	TRIGGER_IGNORE,		//본거랑 상관없이
	TRIGGER_PLACE_LIMIT,	//x도 얼마이하, y도 얼마이하면
	TRIGGER_PLACE_LIMIT2,	//x는 얼마이하, y는 얼마이상
	TRIGGER_PLACE_LIMIT3,	//x는 얼마이상, y는 얼마이상
	TRIGGER_PLACE_LIMIT4,	//x는 얼마이상, y는 얼마이하
	TRIGGER_PLACE_SANDWICH,	//x는 a, b 사이

	EFFECT_FADEIN = 0,	//밝아짐
	EFFECT_FADEOUT,		//어두워짐
	EFFECT_BLACK,			//까만 화면
	EFFECT_WHITE,			//하얀 화면
	EFFECT_DARKFOG,			//테트라쿤 검은안개 뿌리기
	EFFECT_GRAY,			//회상 화면(회색)
	EFFECT_GRAYNULL,		//회상 화면 풀기
	EFFECT_REGENMONSTER,	//몬스터 생성시키기
	EFFECT_DEMOMOVE,		//무브핸들러변경
	EFFECT_ENEMYMOVE,		//무브핸들러변경
	EFFECT_GUARDMOVE,		//무브핸들러 변경
	EFFECT_GOLIMOVE,	//무브핸들러 변경
	EFFECT_GUARDMOVE2,	//디브와 메로 지키기
	EFFECT_ENEMYDRAW,		//몬스터 드로우핸들러 변경
	EFFECT_MENU,
	EFFECT_TALK,			//말하기
	EFFECT_MENUTALK,
	EFFECT_SHAKETALK,		//창흔들면서 말하기
	EFFECT_FOCUS,			//초점 이동
	EFFECT_FOCUS_FAST,		//초점 순간이동
	EFFECT_MOVELEFT_NPC,	//엔피씨 좌측 걷기
	EFFECT_MOVERIGHT_NPC,	//엔피씨 우측 걷기
	EFFECT_RUNLEFT_NPC,		//엔피씨 좌측 달리기
	EFFECT_RUNRIGHT_NPC,	//엔피씨 우측 달리기
	EFFECT_EMPTYFOCUS,	//빈공간에 포커스를 잡는다
	EFFECT_EMPTYFOCUS_FAST,	//빈공간에 포커스를 빠르게 잡는다
	EFFECT_JUMP,			//점프
	EFFECT_SHORTJUMP,
	EFFECT_CHANGEGHOSTDRAW,	//드로우핸들러를 고스트드로우로 바꿔줌.
	EFFECT_TIMESTART,
	EFFECT_LONGJUMP,			//롱점프
	EFFECT_LOOKLEFT,		//좌측 보기
	EFFECT_LOOKRIGHT,	//우측 보기
	EFFECT_CONTRASTDIR,	//방향전환(좌->우/우->좌)
	EFFECT_LOOKPLAYER,	//주인공쪽 보기
	EFFECT_AGAINSTPLAYER,	//주인공 반대쪽 보기
	EFFECT_DEACTIVATE,	//adtive false
	EFFECT_DEACTIVATE2,	//type이 같은 모든걸 꺼준다.
	EFFECT_ACTIVATE,		//active
	EFFECT_ESCORT,
	EFFECT_ACTIVATE2,		//type이 같은걸 모두 켜준다.
	EFFECT_STATUSON,	//status = ON
	EFFECT_MXON,			//mx = true
	EFFECT_SETROOM,			//방이동
	EFFECT_GETITEM,		//아이템먹기
	EFFECT_GIVEITEM,		//아이템주기
	EFFECT_QUEST,		//퀘스트획득
	EFFECT_CLEARQUEST,		//퀘스트완료
	EFFECT_FAILQUEST,		//퀘스트실패
	EFFECT_PLAYMUSIC,		//사운드틀기
	EFFECT_STOPMUSIC,		//사운드스탑
	EFFECT_SHAKE,			//화면흔들기
	EFFECT_BOSSROOM,		//보스룸지정
	EFFECT_FRONTROBIN,		//주인공 앞 이미지 오브젝지정
	EFFECT_ERASEOBJECT,	//OBJ MEMSET
	EFFECT_ENEMY,			//NPC를 적으로
	EFFECT_NPC,				//적으로 변했던 NPC를 다시 NPC로
	EFFECT_ROBINATTACK,		//로빈을 공격
	EFFECT_WARPIN,			//워프로 나타남
	EFFECT_WARPOUT,			//워프로 사라짐
	EFFECT_WARPSTOP,		//워프모션 제거
	EFFECT_FINALTRAP,		//마지막방 스위치 하나 제거
	EFFECT_FINALTRAPBANG,	//마지막방 장애물 부수기
	EFFECT_LASTBOSS,		//마지막 보스 세팅
	EFFECT_RETURNGYSKIL,	//마지막 보스에서 기스킬로 돌아오는것
	EFFECT_ERASEWALL,	//엔딩에서 벽정보 없애기
	EFFECT_HEADZOOMIN,
	EFFECT_OBJSHAKE,
	EFFECT_APPEAROBJ,		//슬슬등장
	EFFECT_DISAPPEAROBJ,		//슬슬사라짐
	//EFFECT_PUNISH_PLAYER,
	EFFECT_GAZEAROUND,		//두리번 거리다.PLAYERALL사용가능
	EFFECT_ATTACK,
	EFFECT_ZOOM,
	EFFECT_NARRATION,
	EFFECT_PLAYER_PREPARE,
	EFFECT_SPREAD_MDR,
	EFFECT_SPREAD_MRD,
	EFFECT_SPREAD_DRM,
	EFFECT_SPREAD_DMR,
	EFFECT_SPREAD_RMD,
	EFFECT_SPREAD_RDM,
	EFFECT_GATHER_PLAYER,
	EFFECT_SLINGMOVE,
	EFFECT_APPEARBOSSMOVE,
	EFFECT_CHANGETOLEMTILE,
	EFFECT_CHANGEADELTILE,
	EFFECT_CHANGEDEVILTILE,
	EFFECT_CHANGEDEVILTILE2,
	EFFECT_ALERT,
	EFFECT_RIDEGOLEM,		//골렘에 탑승
	EFFECT_TAKEDOWNGOLEM,	//골렘에서 내림
	EFFECT_FRAMEUNSETBLEND,
	EFFECT_GOTOTITLE,
	EFFECT_SETQUEST_PLAYER,
	EFFECT_POISON,
	EFFECT_LENZ,

	EFFECT_EQUIPALL,
	EFFECT_UNEQUIPALL,
	EFFECT_EQUIPONLYSWORD,
	EFFECT_WAVE,
	EFFECT_TUTORIAL_REWARD,	//demoItem[] 인덱스를 받아 GetItem()으로 확정 보상을 지급(랜덤 상자 연출 없음)
	EFFECT_TUTORIAL_INITBAR,	//인터랙티브 전투 튜토리얼용 하트/베팅/플레이/룰렛 바를 컷씬 도중에 초기화

	EFFECT_CHANGE_ETC = 170,		//etc를 바꿔줌
	EFFECT_ERASEICON = 190,
	EFFECT_ICON = 190,	//아이콘
	EFFECT_STOP = 210,
	EFFECT_MOVELEFT = 210,	//좌
	EFFECT_MOVERIGHT = 230,	//우
	EFFECT_MOVEUP = 250,	//상
	EFFECT_MOVEDOWN = 270,	//하
	EFFECT_MOVEDOWN2 = 330,	//하
	EFFECT_ALPHA_0 = 350,	//알파 그리기
	EFFECT_ALPHA_1,
	EFFECT_ALPHA_2,
	EFFECT_ALPHA_3,
	EFFECT_ALPHA_4,
	EFFECT_ALPHA_5,
	EFFECT_ALPHA_6,
	EFFECT_ALPHA_7,
	EFFECT_ALPHA_8,
	EFFECT_ALPHA_9,
	EFFECT_WAITDARKSTONE,
	EFFECT_SETTILEY = 1000,			//y 위치 강제 설정	//최대치 변경 X,Y,MOTION
	EFFECT_SETTILEX = 2000,			//x 위치 강제 설정
	EFFECT_MOTION = 3000,		//강제모션지정
	EFFECT_SETTYPE = 3500,//강제NPC지정


	//데모신
	//오프닝
	DEMO_OPENING_PEACEFUL = 0,//공주의 등장
	DEMO_OPENING_DARKKNIGHT,//대마왕 등장
	DEMO_OPENING_PLUNDER,//약탈
	DEMO_OPENING_WARNNING,//칼 쥐고 고고.
	DEMO_OPENING_END,//끝

	//튜토리얼 도입부 세팅(구 DEMO_OPENING_BEGGAR, 이름만 변경)
	DEMO_TUTORIAL_INIT,

	//조작법
	//1층
	//인터랙티브 전투 튜토리얼(설명 컷씬 <-> 실전투를 번갈아 진행한다. AfterDemo()에서 GotoPlay()로 빠지는 지점과
	//실전투 중 SetDemo()로 되돌아오는 지점은 Func_Demo.cpp를 참고)
	DEMO_TUTORIAL_SEBASTIAN,	//세바스찬의 등장 + 대사(TEXT_OPENING_5_0) -> 몬스터 스폰 -> 주인공 놀람 리액션 -> 바 활성화 -> 공격 안내 대사(TEXT_OPENING_5_1) -> 실전투로 진입
	DEMO_TUTORIAL_FIRSTKILL,	//2: 첫 몬스터 처치 보상 설명(1등급 상자 + 하트 + 지정 동료)
	DEMO_TUTORIAL_CREWMENU,	//3: 동료 메뉴에서 장착해보기 안내 -> 실제 메뉴 조작으로 핸드오프
	DEMO_TUTORIAL_SECONDKILL,	//4: 재공격 보상 설명(하트 + 동료 + 장비)
	DEMO_TUTORIAL_EQUIP,		//5: 동료 자동장착 안내 + 장비 수동장착 유도 -> 실제 장착으로 핸드오프
	DEMO_TUTORIAL_HEARTBET,	//6: 하트 베팅 설명(3배 공격) -> 실전투로 진입(중간 HP 몬스터)
	DEMO_TUTORIAL_ROULETTE,	//7: 룰렛 개방 연출 + 설명(크루 6마리 도달로 자연 개방)
	DEMO_TUTORIAL_ROULETTE_LIVE,	//8: 룰렛이 3명을 뽑아 공격하는 것을 실전투로 관전
	DEMO_TUTORIAL_BOSS,			//9: 보스전 + 하트 맥스베팅 + 룰렛 강제결과(최강 동료 히어로 스킬)로 한방킷

	DEMO_TUTORIAL_END,		//튜토리얼 종료, 이후 자유 플레이로 전환

	TOTALDEMO,

	//DEMO_OPENING
	DEMO_OPENING_PEACEFUL_FRAME0 = 0,
	DEMO_OPENING_DARKKNIGHT_FRAME0 = DEMO_OPENING_PEACEFUL_FRAME0 + 7,
	DEMO_OPENING_PLUNDER_FRAME0 = DEMO_OPENING_DARKKNIGHT_FRAME0 + 3,
	DEMO_OPENING_WARNNING_FRAME0 = DEMO_OPENING_PLUNDER_FRAME0 + 3,
	DEMO_OPENING_END_FRAME0 = DEMO_OPENING_WARNNING_FRAME0 + 3,

	DEMO_TUTORIAL_INIT_FRAME0 = DEMO_OPENING_END_FRAME0 + 3,
	//DEMO_TUTORIAL_INIT은 13행(FRAME0~FRAME12, 방 세팅 + 세바스찬 TALK 1줄(=TEXT_OPENING_5_0) +
	//전체 UI 바 초기화)으로 끝난다. 몬스터 스폰용 EFFECT_WAVE는 DEMO_TUTORIAL_SEBASTIAN으로 옮겨서
	//여기엔 없다(여기 있으면 몬스터가 너무 일찍 튀어나옴). 뒤에 붙어있던 옛 DEMO_OPENING_BEGGAR
	//잔재(TALK 2줄 더 + 아이콘들 + 재사용된 TEXT_OPENING_3_0 나레이션 + 영혼변신 연출 + 상자에서 검
	//획득)는 인터랙티브 튜토리얼과 무관한 옛 오프닝 콘텐츠라 제거.
	//DEMO_TUTORIAL_SEBASTIAN	11행: 크루(세바스찬) 재활성화(SetDemo()가 블록 진입 시 꺼버리는 걸 복구) ->
	//놀람 아이콘 -> 모션리셋 -> 몬스터 스폰(EFFECT_WAVE, 정식 wave[] 데이터) -> 주인공 우측 주시 ->
	//줌/포커스(몬스터->플레이어) -> 놀람 아이콘 제거(바 활성화 대기 겸용) -> TALK(movie.text가 이어져서
	//TEXT_OPENING_5_1이 나옴). 이 11행이 다 끝나야 AfterDemo()가 호출되어 실전투 복귀(GotoPlay)로 넘어간다.
	DEMO_TUTORIAL_SEBASTIAN_FRAME0 = DEMO_TUTORIAL_INIT_FRAME0 + 13,
	//DEMO_TUTORIAL_FIRSTKILL	4행: 보상지급x3 + 나레이션
	DEMO_TUTORIAL_FIRSTKILL_FRAME0 = DEMO_TUTORIAL_SEBASTIAN_FRAME0 + 11,
	//DEMO_TUTORIAL_CREWMENU	1행: 나레이션
	DEMO_TUTORIAL_CREWMENU_FRAME0 = DEMO_TUTORIAL_FIRSTKILL_FRAME0 + 1,
	//DEMO_TUTORIAL_SECONDKILL	4행: 보상지급x3 + 나레이션
	DEMO_TUTORIAL_SECONDKILL_FRAME0 = DEMO_TUTORIAL_CREWMENU_FRAME0 + 1,
	//DEMO_TUTORIAL_EQUIP	1행: 나레이션(스폰 없음, 몬스터가 필요없는 구간)
	DEMO_TUTORIAL_EQUIP_FRAME0 = DEMO_TUTORIAL_SECONDKILL_FRAME0 + 1,
	//DEMO_TUTORIAL_HEARTBET	1행: 나레이션
	DEMO_TUTORIAL_HEARTBET_FRAME0 = DEMO_TUTORIAL_EQUIP_FRAME0 + 1,
	//DEMO_TUTORIAL_ROULETTE	5행: 보상지급x4 + 나레이션
	DEMO_TUTORIAL_ROULETTE_FRAME0 = DEMO_TUTORIAL_HEARTBET_FRAME0 + 1,
	//DEMO_TUTORIAL_ROULETTE_LIVE	1행: 나레이션
	DEMO_TUTORIAL_ROULETTE_LIVE_FRAME0 = DEMO_TUTORIAL_ROULETTE_FRAME0 + 1,
	//DEMO_TUTORIAL_BOSS	1행: 나레이션
	DEMO_TUTORIAL_BOSS_FRAME0 = DEMO_TUTORIAL_ROULETTE_LIVE_FRAME0 + 1,

	TOTAL_DEMO_FRAME,

	END_DEMODEF
} DEMODEF;

typedef enum _demoSceneDef {
	//DEMO_OPENING
	//DEMO_OPENING_PEACEFUL
	DEMO_OPENING_PEACEFUL_FRAME0_SCENE = 0,
	DEMO_OPENING_PEACEFUL_FRAME1_SCENE = DEMO_OPENING_PEACEFUL_FRAME0_SCENE + FPS / 2,
	DEMO_OPENING_PEACEFUL_FRAME2_SCENE = DEMO_OPENING_PEACEFUL_FRAME1_SCENE + FPS,
	DEMO_OPENING_PEACEFUL_FRAME3_SCENE = DEMO_OPENING_PEACEFUL_FRAME2_SCENE + FPS,
	DEMO_OPENING_PEACEFUL_FRAME4_SCENE = DEMO_OPENING_PEACEFUL_FRAME3_SCENE + FPS,
	DEMO_OPENING_PEACEFUL_FRAME5_SCENE = DEMO_OPENING_PEACEFUL_FRAME4_SCENE + FPS,

	//DEMO_OPENING_DARKKNIGHT
	DEMO_OPENING_DARKKNIGHT_FRAME0_SCENE = 0,
	DEMO_OPENING_DARKKNIGHT_FRAME1_SCENE = DEMO_OPENING_DARKKNIGHT_FRAME0_SCENE + FPS,
	DEMO_OPENING_DARKKNIGHT_FRAME2_SCENE = DEMO_OPENING_DARKKNIGHT_FRAME1_SCENE + FPS,
	DEMO_OPENING_DARKKNIGHT_FRAME3_SCENE = DEMO_OPENING_DARKKNIGHT_FRAME2_SCENE + FPS,
	
	//DEMO_OPENING_PLUNDER
	DEMO_OPENING_PLUNDER_FRAME0_SCENE = 0,
	DEMO_OPENING_PLUNDER_FRAME1_SCENE = DEMO_OPENING_PLUNDER_FRAME0_SCENE + FPS,
	DEMO_OPENING_PLUNDER_FRAME2_SCENE = DEMO_OPENING_PLUNDER_FRAME1_SCENE + FPS,
	DEMO_OPENING_PLUNDER_FRAME3_SCENE = DEMO_OPENING_PLUNDER_FRAME2_SCENE + FPS,

	//DEMO_OPENING_WARNING
	DEMO_OPENING_WARNING_FRAME0_SCENE = 0,
	DEMO_OPENING_WARNING_FRAME1_SCENE = DEMO_OPENING_WARNING_FRAME0_SCENE + FPS,
	DEMO_OPENING_WARNING_FRAME2_SCENE = DEMO_OPENING_WARNING_FRAME1_SCENE + FPS,
	DEMO_OPENING_WARNING_FRAME3_SCENE = DEMO_OPENING_WARNING_FRAME2_SCENE + FPS,

	//DEMO_OPENING_END
	DEMO_OPENING_END_FRAME0_SCENE = 0,
	DEMO_OPENING_END_FRAME1_SCENE = DEMO_OPENING_END_FRAME0_SCENE + FPS,
	DEMO_OPENING_END_FRAME2_SCENE = DEMO_OPENING_END_FRAME1_SCENE + FPS,
	DEMO_OPENING_END_FRAME3_SCENE = DEMO_OPENING_END_FRAME2_SCENE + FPS,

	//DEMO_TUTORIAL_INIT
	DEMO_TUTORIAL_INIT_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_INIT_FRAME1_SCENE = DEMO_TUTORIAL_INIT_FRAME0_SCENE + FPS,
	DEMO_TUTORIAL_INIT_FRAME2_SCENE = DEMO_TUTORIAL_INIT_FRAME1_SCENE + FPS / 5 / 2,
	DEMO_TUTORIAL_INIT_FRAME3_SCENE = DEMO_TUTORIAL_INIT_FRAME2_SCENE + FPS / 5 / 2,
	DEMO_TUTORIAL_INIT_FRAME4_SCENE = DEMO_TUTORIAL_INIT_FRAME3_SCENE + FPS / 5,
	DEMO_TUTORIAL_INIT_FRAME5_SCENE = DEMO_TUTORIAL_INIT_FRAME4_SCENE + 1,
	DEMO_TUTORIAL_INIT_FRAME6_SCENE = DEMO_TUTORIAL_INIT_FRAME5_SCENE + FPS / 5,
	DEMO_TUTORIAL_INIT_FRAME7_SCENE = DEMO_TUTORIAL_INIT_FRAME6_SCENE + FPS / 5,
	DEMO_TUTORIAL_INIT_FRAME8_SCENE = DEMO_TUTORIAL_INIT_FRAME7_SCENE + 1,
	DEMO_TUTORIAL_INIT_FRAME9_SCENE = DEMO_TUTORIAL_INIT_FRAME8_SCENE + FPS / 5,
	DEMO_TUTORIAL_INIT_FRAME10_SCENE = DEMO_TUTORIAL_INIT_FRAME9_SCENE + 1,
	DEMO_TUTORIAL_INIT_FRAME11_SCENE = DEMO_TUTORIAL_INIT_FRAME10_SCENE + FPS,
	DEMO_TUTORIAL_INIT_FRAME12_SCENE = DEMO_TUTORIAL_INIT_FRAME11_SCENE + FPS / 5,
	DEMO_TUTORIAL_INIT_FRAME13_SCENE = DEMO_TUTORIAL_INIT_FRAME12_SCENE + 1,
	DEMO_TUTORIAL_INIT_FRAME14_SCENE = DEMO_TUTORIAL_INIT_FRAME13_SCENE + FPS / 5 / 2,
	DEMO_TUTORIAL_INIT_FRAME15_SCENE = DEMO_TUTORIAL_INIT_FRAME14_SCENE + 1,
	DEMO_TUTORIAL_INIT_FRAME16_SCENE = DEMO_TUTORIAL_INIT_FRAME15_SCENE + FPS / 5,
	DEMO_TUTORIAL_INIT_FRAME17_SCENE = DEMO_TUTORIAL_INIT_FRAME16_SCENE + FPS / 5 / 2,
	DEMO_TUTORIAL_INIT_FRAME18_SCENE = DEMO_TUTORIAL_INIT_FRAME17_SCENE + FPS / 5 / 2,
	DEMO_TUTORIAL_INIT_FRAME19_SCENE = DEMO_TUTORIAL_INIT_FRAME18_SCENE + FPS / 5 / 2,
	DEMO_TUTORIAL_INIT_FRAME20_SCENE = DEMO_TUTORIAL_INIT_FRAME19_SCENE + 1,
	DEMO_TUTORIAL_INIT_FRAME21_SCENE = DEMO_TUTORIAL_INIT_FRAME20_SCENE + FPS / 5,
	DEMO_TUTORIAL_INIT_FRAME22_SCENE = DEMO_TUTORIAL_INIT_FRAME21_SCENE + 1,
	DEMO_TUTORIAL_INIT_FRAME23_SCENE = DEMO_TUTORIAL_INIT_FRAME22_SCENE + FPS / 5 / 2,
	DEMO_TUTORIAL_INIT_FRAME24_SCENE = DEMO_TUTORIAL_INIT_FRAME23_SCENE + FPS / 5 / 2,
	DEMO_TUTORIAL_INIT_FRAME25_SCENE = DEMO_TUTORIAL_INIT_FRAME24_SCENE + FPS / 5 / 2,
	DEMO_TUTORIAL_INIT_FRAME26_SCENE = DEMO_TUTORIAL_INIT_FRAME25_SCENE + FPS / 5 / 2,
	DEMO_TUTORIAL_INIT_FRAME27_SCENE = DEMO_TUTORIAL_INIT_FRAME26_SCENE + FPS / 5 / 2,
	DEMO_TUTORIAL_INIT_FRAME28_SCENE = DEMO_TUTORIAL_INIT_FRAME27_SCENE + FPS / 5 / 2,
	DEMO_TUTORIAL_INIT_FRAME29_SCENE = DEMO_TUTORIAL_INIT_FRAME28_SCENE + 1,
	DEMO_TUTORIAL_INIT_FRAME30_SCENE = DEMO_TUTORIAL_INIT_FRAME29_SCENE + FPS / 5,
	DEMO_TUTORIAL_INIT_FRAME31_SCENE = DEMO_TUTORIAL_INIT_FRAME30_SCENE + FPS,
	DEMO_TUTORIAL_INIT_FRAME32_SCENE = DEMO_TUTORIAL_INIT_FRAME31_SCENE + FPS / 5,
	DEMO_TUTORIAL_INIT_FRAME33_SCENE = DEMO_TUTORIAL_INIT_FRAME32_SCENE + FPS / 5,
	DEMO_TUTORIAL_INIT_FRAME34_SCENE = DEMO_TUTORIAL_INIT_FRAME33_SCENE + FPS,

	//DEMO_TUTORIAL_SEBASTIAN
	DEMO_TUTORIAL_SEBASTIAN_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_SEBASTIAN_FRAME1_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME0_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME2_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME1_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME3_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME2_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME4_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME3_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME5_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME4_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME6_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME5_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME7_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME6_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME8_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME7_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME9_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME8_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME10_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME9_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME11_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME10_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME12_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME11_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME13_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME12_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME14_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME13_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME15_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME14_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME16_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME15_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME17_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME16_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME18_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME17_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME19_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME18_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME20_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME19_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME21_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME20_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME22_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME21_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME23_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME22_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME24_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME23_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME25_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME24_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME26_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME25_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME27_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME26_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME28_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME27_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME29_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME28_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME30_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME29_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME31_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME30_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME32_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME31_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME33_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME32_SCENE + FPS / 10,
	DEMO_TUTORIAL_SEBASTIAN_FRAME34_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME33_SCENE + FPS / 4,
	DEMO_TUTORIAL_SEBASTIAN_FRAME35_SCENE = DEMO_TUTORIAL_SEBASTIAN_FRAME34_SCENE + FPS / 4,

	//DEMO_TUTORIAL_FIRSTKILL	4행: 보상x3(즉시) + 나레이션
	DEMO_TUTORIAL_FIRSTKILL_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_FIRSTKILL_FRAME1_SCENE = DEMO_TUTORIAL_FIRSTKILL_FRAME0_SCENE,
	DEMO_TUTORIAL_FIRSTKILL_FRAME2_SCENE = DEMO_TUTORIAL_FIRSTKILL_FRAME1_SCENE,
	DEMO_TUTORIAL_FIRSTKILL_FRAME3_SCENE = DEMO_TUTORIAL_FIRSTKILL_FRAME2_SCENE + FPS / 4,

	//DEMO_TUTORIAL_CREWMENU	1행
	DEMO_TUTORIAL_CREWMENU_FRAME0_SCENE = 0,

	//DEMO_TUTORIAL_SECONDKILL	4행: 보상x3(즉시) + 나레이션
	DEMO_TUTORIAL_SECONDKILL_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_SECONDKILL_FRAME1_SCENE = DEMO_TUTORIAL_SECONDKILL_FRAME0_SCENE,
	DEMO_TUTORIAL_SECONDKILL_FRAME2_SCENE = DEMO_TUTORIAL_SECONDKILL_FRAME1_SCENE,
	DEMO_TUTORIAL_SECONDKILL_FRAME3_SCENE = DEMO_TUTORIAL_SECONDKILL_FRAME2_SCENE + FPS / 4,

	//DEMO_TUTORIAL_EQUIP	1행
	DEMO_TUTORIAL_EQUIP_FRAME0_SCENE = 0,

	//DEMO_TUTORIAL_HEARTBET	1행
	DEMO_TUTORIAL_HEARTBET_FRAME0_SCENE = 0,

	//DEMO_TUTORIAL_ROULETTE	5행: 보상x4(즉시) + 나레이션
	DEMO_TUTORIAL_ROULETTE_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_ROULETTE_FRAME1_SCENE = DEMO_TUTORIAL_ROULETTE_FRAME0_SCENE,
	DEMO_TUTORIAL_ROULETTE_FRAME2_SCENE = DEMO_TUTORIAL_ROULETTE_FRAME1_SCENE,
	DEMO_TUTORIAL_ROULETTE_FRAME3_SCENE = DEMO_TUTORIAL_ROULETTE_FRAME2_SCENE,
	DEMO_TUTORIAL_ROULETTE_FRAME4_SCENE = DEMO_TUTORIAL_ROULETTE_FRAME3_SCENE + FPS / 4,

	//DEMO_TUTORIAL_ROULETTE_LIVE	1행
	DEMO_TUTORIAL_ROULETTE_LIVE_FRAME0_SCENE = 0,

	//DEMO_TUTORIAL_BOSS	1행
	DEMO_TUTORIAL_BOSS_FRAME0_SCENE = 0,
	DEMO_TUTORIAL_BOSS_FRAME1_SCENE = DEMO_TUTORIAL_BOSS_FRAME0_SCENE,

	TOTALDEMOFRAMESCENE,

	END_DEMOSCENEDEF
} DEMOSCENEDEF;

#endif
