#pragma once

#ifndef _DEF_HANDLER_H_
#define _DEF_HANDLER_H_

typedef enum _handlerInfo {
	//드로우 핸들
	MD_LOGO = 1,//빅픽셀 로고 그리기
	MD_TITLE,//타이틀화면, 
	MD_OPENING,//오프닝
	MD_PLAY,//메인진행
	MD_BATTLE,//장비공격
	MD_RAID,//레이드
	MD_BOSSRAID,//보스레이드
	MD_DEMO,
	MD_GAMEMENU,
	MD_ALERT,
	MD_GACHA,
	MD_NEWCOLLECTION,
	MD_NEWCARD,
	MD_NEWSKILL,
	MD_STAGECLEAR,
	MD_BATTLELOADING,
	MD_PVP,//다른 유저의 성을 공략하는 비동기 PVP

	MK_TITLE = 1,
	MK_PLAY,
	MK_BATTLE,
	MK_RAID,
	MK_BOSSRAID,
	MK_DEMO,
	MK_TALK,
	MK_GAMEMENU,
	MK_GAMEOVER,
	MK_ALERT,
	MK_GACHA,
	MK_NEWCOLLECTION,
	MK_NEWCARD,
	MK_STAGECLEAR,
	MK_PVP,
	//릴리즈 핸들
	MR_PLAY = 1,

	//무브핸들러
	//플레이어 관련
	PLAYERMOVE = 1,
	PLAYERSLEDMOVE,
	PLAYERGOLEMMOVE,
	PLAYERHANDMOVE,//여기 추가해도 되는지요?
	PLAYERENEMYMOVE,//적을 동료로 쓰는 경우
	ENEMYMOVE,
	ENEMYMOVETURN,
	SUMMONMOVE,
	ENEMYPLAYERMOVE,//히어로를 적으로 사용하는 경우
	MOBIUSMOVE,
	DEMOMOVE,
	ESCORTMOVE,
	MERCHANTMOVE,
	NPCMOVE,
	NPCSHIPMOVE,
	CREWMOVE,
	CUTOFFMOVE,

	//몬스터
	SLINGMOVE,
	LIGHTNINGMOVE,
	BUGMOVE,
	SKELGUIDEMOVE,
	CIRCLEMOVE,
	SLIMEMOVE,
	STRAIGHTMOVE,
	MACHINEMANAGERMOVE,	//메니저
	MACHINEMOVE, //이동없이 프레임변경
	MACHINEBOSSMOVE,
	BAHAMUTHEADMOVE,
	BAHAMUTNECKMOVE,
	BAHAMUTBODYMOVE,
	SHIPMAINMOVE,
	SHIPSUBMOVE,
	DEBRIONBODYMOVE,
	DEBRIONARMMOVE,
	SHIPGUIDEMOVE,
	FOGRAMOVE,
	FOGRASUBMOVE,
	SIGNMOVE,
	GUARDMOVE,
	GOLIMOVE,
	GUARDMOVE2,
	APPEARBOSSMOVE,
	BOAREVENTMOVE,

	//총알
	BULLET3WAYMOVE,
	BULLETLASERMOVE,
	BULLETBOMBMOVE,
	BULLETGUIDEDMOVE,
	BULLETSATELLITEMOVE,
	BULLETHEALMOVE,
	BULLETBOOMERANGMOVE,
	BULLETTONGUEMOVE,		//혓바닥
	FOLLOWMOMMOVE,
	HANDMOVE,
	BULLETSPINMOVE,	//34보스회전
	BULLETGUIDEMOVE,
	BULLET3WAYDIRMOVE,
	BULLETITEMMOVE,
	BULLET4WAYMOVE,
	LABETHMAGICMOVE,//라베스 마법진 무브핸들러

	VANISHMOVE,
	REGENMOVE,

	//NEUTRAL
	SIDEMOVE,
	UPDOWNMOVE,
	DROPMOVE,
	SEWAGESTONEMOVE,
	DOORMOVE,
	REPULSIONMOVE,
	ITEMMOVE,
	CLOAKINGMOVE,
	WARPMOVE,
	LEVERMOVE,
	PUSHMOVE,
	BOXMOVE,
	CARPETMOVE,
	ROBINTRAPMOVE,
	DIANATRAPMOVE,
	DIANASTONEMOVE,
	MAXXTRAPMOVE,
	SUNBLOCKMOVE,
	BREAKSTONEMOVE,
	DARKSTONEMOVE,
	DEMODARKMOVE,
	BUBBLEMOVE,
	BUBBLEBOBBLEMOVE,
	MAGMAMOVE,
	MAGMABLOCKMOVE,
	BRIDGEMOVE,
	STALACTITEMOVE,
	SPIKEMOVE,
	MAGNETMOVE,
	SLEDMOVE,
	ICEBREAKMOVE,
	INVISIBLEMOVE,
	GOLEMBLOCKMOVE,
	BALLMOVE,
	PITCHERMOVE,
	BLACKHOLEMOVE,
	WORMHOLEMOVE,
	ITEMGOTOBOXMOVE,
	FOLLOWMOVE,
	TREEMOVE,

	//PVP 수비측이 쏘는 총알.
	//
	//기존 총알은 전부 "아군이 적을 친다" 방향이다. AttackEnemyCheck 가
	//언제나 ENEMYUSEROBJ..NEUTRAL 만 훑기 때문에, 적 칸의 개체가 쏜 총알도
	//적만 때린다. 수비측 총알이 우리 히어로를 못 때리던 까닭이다.
	//
	//반대 방향이 없어서 하나 만든다. 맞으면 AttackRobin 을 부른다.
	PVPFOEBULLETMOVE,

	//드로우핸들러
	PLAYERDRAW = 1,
	NORMALDRAW,
	BULLETLASERDRAW,
	BULLETGUIDEDDRAW,
	BULLETSATELITEDRAW,
	BULLETHEALDRAW,
	BULLETBOOMERANGDRAW,
	BULLETITEMDRAW,
	BULLETCREWDRAW,

	//몬스터
	ENEMYDRAW,
	CLOUDDRAW,
	SPIDERDRAW,
	SKELDRAW,
	MACHINEDRAW,
	LASERDRAW,
	GHOSTDRAW,
	VANISHDRAW,
	REGENDRAW,
	CREWDRAW,

	//NEUTRAL
	NEUTRALDRAW,
	BOXDRAW,

} BARINFO;

#endif
