#pragma once

#ifndef _DEF_ROULETTE_H_
#define _DEF_ROULETTE_H_

typedef enum _rouletteInfo {
	// 
	//보상 룰렛의 타입
	ROULETTE_COIN = 0,//코인획득
	ROULETTE_EQUIP,//장비획득
	ROULETTE_HEART,//하트획득
	ROULETTE_QUEST,//퀘스트획득
	ROULETTE_BATTLE,//전투
	ROULETTE_RAID,//보스레이드
	ROULETTE_SKILL,//스킬
	ROULETTE_SHIELD,//방패

	//위에까지는 디폴트고, 여기서부터는 추가스킬
	//스킬이 나올 확률에서 세분화해서 최고 스킬까지 처리한다.

	ROULETTE_MISS,//미스가 났을 때

	TOTALROULETTETYPE,

	//MAXROULETTE = ROULETTE_SHIELD + 1,
	TOTALROULETTECHANCE = 3,

	//보스레이드에서 룰렛종류
	ROULETTE_BOSSRAID_1 = 0,//1/4
	ROULETTE_BOSSRAID_2,//1/2
	ROULETTE_BOSSRAID_3,//1
	ROULETTE_BOSSRAID_4,//스킬
	ROULETTE_BOSSRAID_5,//2
	ROULETTE_BOSSRAID_6,//5
	ROULETTE_BOSSRAID_7,//20  
	ROULETTE_BOSSRAID_MISS,

	TOTALBOSSRAIDROULETTETYPE,

	ROULETTE_BOSSRAIDRESULT_MISS = 0,
	ROULETTE_BOSSRAIDRESULT_0_2,
	ROULETTE_BOSSRAIDRESULT_0_5,
	ROULETTE_BOSSRAIDRESULT_1,
	ROULETTE_BOSSRAIDRESULT_2,
	ROULETTE_BOSSRAIDRESULT_5,
	ROULETTE_BOSSRAIDRESULT_10,
	ROULETTE_BOSSRAIDRESULT_15,
	ROULETTE_BOSSRAIDRESULT_20,
	ROULETTE_BOSSRAIDRESULT_40,

	TOTALBOSSRAIDROULETTERESULT,

	PROB_BOSS_0_2 = 500,//6개 = 3000
	PROB_BOSS_0_5 = 2000,//1개 = 2000
	PROB_BOSS_1 = 1500,//1개 = 1500
	PROB_BOSS_SKILL = 500,//1개 = 500
	PROB_BOSS_2 = 1000,//1개 = 1000
	PROB_BOSS_5 = 1,//104개 = 104
	PROB_BOSS_10 = 50,//1개 = 50
	PROB_BOSS_15 = 1,//16개 = 16
	PROB_BOSS_20 = 5,//1개 = 5
	PROB_BOSS_40 = 1,//1개 = 1
	PROB_BOSS_MISS = 1,//210개
	PROB_BOSS_ZERO = 0,

	ROULETTE_BATTLE_MISS = 0,//MISS - 적이 나오면 적을 공격하지 아니한다.
	ROULETTE_BATTLE_GOOD,//HIT - HIT가 하나라도 나오면 적을 공격하는거고
	ROULETTE_BATTLE_PERFECT,//ITEM - 아이템이 3개 나오면 아이템을 가져오는거고

	TOTAL_ROULETTE_BATTLE,

	ROULETTE_RAID_MISS = 0,//MISS - 적이 나오면 적을 공격하지 아니한다.
	ROULETTE_RAID_GOOD,//HIT - HIT가 하나라도 나오면 적을 공격하는거고
	ROULETTE_RAID_PERFECT,//ITEM - 아이템이 3개 나오면 아이템을 가져오는거고

	TOTAL_ROULETTE_RAID,

	ROULETTEMAXITEM = 4,

	ROULETTEQUESTDATASIZE = 6,

	ROULETTEQUEST0 = 0,
	ROULETTEQUEST1,
	ROULETTEQUEST2,

	TOTALROULETTEQUEST,

	PROB_VERYHIGH = 1000,
	PROB_HIGH = 300,
	PROB_MID = 100,
	PROB_LOW = 50,
	PROB_VERYLOW = 10,

	JOKBODATASIZE = 6,

	PROB_COIN = 1700,
	PROB_COINBAG = 1600,
	PROB_HEART = 1100,
	PROB_SKILL = 1200,
	PROB_QUEST = 1500,
	PROB_HIT = 1400,
	PROB_RAID = 1300,

	TOTALJOKBO = (TOTALROULETTETYPE - 1) * (TOTALROULETTETYPE - 1) * (TOTALROULETTETYPE - 1),

	TOTALBATTLEJOKBO = (TOTAL_ROULETTE_BATTLE - 1) * (TOTAL_ROULETTE_BATTLE - 1) * (TOTAL_ROULETTE_BATTLE - 1),

	TOTALBOSSRAIDJOKBO = (ROULETTE_BOSSRAID_7 + 1) * (ROULETTE_BOSSRAID_7 + 1) * (ROULETTE_BOSSRAID_7 + 1),

	//1000번 단위로 리셋
	MAXROULETTELOG = 1000,

	ROULETTE_HEART_MAXCNT = 3,//MAXROULETTELOG 회수중에 3번을 넘기지 못한다는거
	ROULETTE_RAID_MAXCNT = 5,//MAXROULETTELOG 회수중에 5번을 넘기지 못한다는거

	GOLDICONFRAME = 10,
	STARICONFRAME = 9,
} ROULETTEINFO;

#endif
