#pragma once

#ifndef _DEF_SKILL_H_
#define _DEF_SKILL_H_
typedef enum _skillDef {
	//몬스터 공격 이외의 공격형태들
	ATTACKTYPE_NORMAL = 0,
	ATTACKTYPE_TILE = TOTALOBJECT,
	ATTACKTYPE_WATER,
	ATTACKTYPE_SPACE,
	ATTACKTYPE_MAGMA,
	ATTACKTYPE_MAGMA2,
	ATTACKTYPE_STALACTITE,
	ATTACKTYPE_ICICLE,
	ATTACKTYPE_POISON,
	ATTACKTYPE_DARKBALL,

	//공격종류
	ATTACK_NORMAL = 1,
	ATTACK_DASH,
	ATTACK_AIR,
	ATTACK_DOWN,
	ATTACK_AFTERDOWN,
	ATTACK_MAGIC,
	ATTACK_SQUIRELL,
	ATTACK_SQUIRELL2,
	ATTACK_WARP,
	ATTACK_ITEM,
	ATTACK_SKILL,

	//ROBIN
	ROBIN_SKILL_AIRCRASH = ATTACK_SKILL,//너무 타수가 많아
	ROBIN_SKILL_STAB,//너무 타수가 많아
	ROBIN_SKILL_BOOSTSLASH,//앞으로 돌진한다.
	ROBIN_SKILL_HYPERCHARGE,//앞으로 돌진한다.
	ROBIN_SKILL_SOULCRASH,//너무 타수가 많아.
	ROBIN_SKILL_ABSOLUTEPIERCE,//너무 타수가 많아
	ROBIN_SKILL_KILLALL,//너무 타수가 많고 빨라
	ROBIN_SKILL_DEFENSE,//이 이하 스킬들은 사용한 뒤에 
	ROBIN_SKILL_BARRIER,
	ROBIN_SKILL_HPRESTORE,
	ROBIN_SKILL_MPRESTORE,
	ROBIN_SKILL_REFLECTOR,
	ROBIN_TOTAL_SKILL,

	//DIANA
	DIANA_SKILL_3WAY = ATTACK_SKILL,//너무 느리고 연타수가 많음. 그리고 3way일 필요가 없음
	DIANA_SKILL_LASER,//레이저가 너무 굵고 타수가 많음
	DIANA_SKILL_FLAMER,//화염이 안나간다.
	DIANA_SKILL_BOMBSHOT,//총알이 나가고 터져야 하는데
	DIANA_SKILL_GUIDEDSHOT,//미사일이 너무 많이 나가고 미사일이 터졌을 때 숫자가 보이지 않는다.
	DIANA_SKILL_SPRAYSHOT,//동작이 제대로 보이지 않는다.
	DIANA_SKILL_SATELLITESHOT,//위성이미지가 가림
	DIANA_SKILL_HEALSHOT,//
	DIANA_SKILL_FEELUP,
	DIANA_SKILL_VAMPIRE,
	DIANA_SKILL_FOCUS,
	DIANA_SKILL_FAMAS,

	DIANA_TOTAL_SKILL,

	//MAXX
	MAXX_SKILL_KICK = ATTACK_SKILL,//앞으로 전진하지 않음.
	MAXX_SKILL_SHORT,//공격이 닿지 않는다.
	MAXX_SKILL_AIR,//대각선으로 공격하는데 공중적이 없으면 공격불가
	MAXX_SKILL_CAMPING,//캠핑시간이 짧다.
	MAXX_SKILL_HORMING,//공격한 다음에 주인공한테 안가고 엉뚱한데 날라간다.
	MAXX_SKILL_CIRCLE,//나간뒤에 부메랑이 주인공 뒤를 돌지 않고 사라진다.
	MAXX_SKILL_MEGA,//부메랑과 이펙트가 따로 논다.
	MAXX_SKILL_BLOOD,//
	MAXX_SKILL_DAZZLE,
	MAXX_SKILL_SIGH,
	MAXX_SKILL_SPLIT,

	MAXX_TOTAL_SKILL,

	//여기서 크류스킬들을 정리하자.
	//그런데 모션들을 세팅하는 것은 여기지.




	//스킬 지속 프레임 및 시작프레임 정의
#ifdef ATTACK_INIT_DELAY
	ROBIN_ATTACK_DELAY = 2,	//60프레임용으로 2배
#else
	ROBIN_ATTACK_DELAY = 0,
#endif

	//ROBIN
	ROBIN_ATTACK_HIT_MISS_CNT = 0,
	ROBIN_ATTACK_HIT_HIT_CNT = 3,
	ROBIN_ATTACK_HIT_ITEM_CNT = 10,

	ROBIN_ATTACK_RAID_PERFECT_CNT = 14,
	ROBIN_ATTACK_RAID_GOOD_CNT = 3,
	//ROBINMAXSTING = 106,
	ROBINMAXSTING = 69,	//60프레임용으로 2배
	ROBIN_ATTACK_NORMAL_CNT = ROBIN_ATTACK_DELAY + ROBINMAXSTING,
	ROBIN_ATTACK_DASH_CNT = 19,	//60프레임용으로 2배
	ROBIN_ATTACK_AIR_CNT = 11,	//60프레임용으로 2배
	ROBIN_ATTACK_DOWN_CNT = 0,
	ROBIN_ATTACK_AFTER_CNT = 12,	//60프레임용으로 2배
	ROBIN_ATTACK_MAGIC_CNT = 30,	//60프레임용으로 2배
	ROBIN_ATTACK_SQUIRREL_CNT = 20,	//60프레임용으로 2배
	ROBIN_ATTACK_SQUIRREL2_CNT = 20,	//60프레임용으로 2배
	ROBIN_ATTACK_WARP_CNT = 64,	//60프레임용으로 2배
	ROBIN_ATTACK_ITEM_CNT = 16,	//60프레임용으로 2배
	ROBIN_ATTACK_AIRCRASH_CNT = 230,	//60프레임용으로 2배
	ROBIN_ATTACK_STAB_CNT = 254,	//60프레임용으로 2배
	ROBIN_ATTACK_BOOSTSLASH_CNT = 222,	//60프레임용으로 2배
	ROBIN_ATTACK_HYPERCHARGE_CNT = 236,	//60프레임용으로 2배
	ROBIN_ATTACK_SOULCRASH_CNT = 235,	//60프레임용으로 2배
	ROBIN_ATTACK_ABSOLUTEPIERCE_CNT = 270,	//회전공격 1사이클(21프레임) 추가
	ROBIN_ATTACK_KILLALL_CNT = 261,	//60프레임용으로 2배
	ROBIN_ATTACK_DEFENSE_CNT = 36,	//60프레임용으로 2배
	ROBIN_ATTACK_BARRIER_CNT = 36,	//60프레임용으로 2배
	ROBIN_ATTACK_HPRESTORE_CNT = 36,	//60프레임용으로 2배
	ROBIN_ATTACK_MPRESTORE_CNT = 36,	//60프레임용으로 2배
	ROBIN_ATTACK_REFLECTOR_CNT = 36,	//60프레임용으로 2배

	ROBIN_ATTACK_NORMAL_START = 0,
	ROBIN_ATTACK_DASH_START = ROBIN_ATTACK_NORMAL_START + ROBIN_ATTACK_NORMAL_CNT,
	ROBIN_ATTACK_AIR_START = ROBIN_ATTACK_DASH_START + ROBIN_ATTACK_DASH_CNT,
	ROBIN_ATTACK_DOWN_START = ROBIN_ATTACK_AIR_START + ROBIN_ATTACK_AIR_CNT,
	ROBIN_ATTACK_AFTER_START = ROBIN_ATTACK_DOWN_START + ROBIN_ATTACK_DOWN_CNT,
	ROBIN_ATTACK_MAGIC_START = ROBIN_ATTACK_AFTER_START + ROBIN_ATTACK_AFTER_CNT,
	ROBIN_ATTACK_SQUIRREL_START = ROBIN_ATTACK_MAGIC_START + ROBIN_ATTACK_MAGIC_CNT,
	ROBIN_ATTACK_SQUIRREL2_START = ROBIN_ATTACK_SQUIRREL_START + ROBIN_ATTACK_SQUIRREL_CNT,
	ROBIN_ATTACK_WARP_START = ROBIN_ATTACK_SQUIRREL2_START + ROBIN_ATTACK_SQUIRREL2_CNT,
	ROBIN_ATTACK_ITEM_START = ROBIN_ATTACK_WARP_START + ROBIN_ATTACK_WARP_CNT,
	ROBIN_ATTACK_AIRCRASH_START = ROBIN_ATTACK_ITEM_START + ROBIN_ATTACK_ITEM_CNT,
	ROBIN_ATTACK_STAB_START = ROBIN_ATTACK_AIRCRASH_START + ROBIN_ATTACK_AIRCRASH_CNT,
	ROBIN_ATTACK_BOOSTSLASH_START = ROBIN_ATTACK_STAB_START + ROBIN_ATTACK_STAB_CNT,
	ROBIN_ATTACK_HYPERCHARGE_START = ROBIN_ATTACK_BOOSTSLASH_START + ROBIN_ATTACK_BOOSTSLASH_CNT,
	ROBIN_ATTACK_SOULCRASH_START = ROBIN_ATTACK_HYPERCHARGE_START + ROBIN_ATTACK_HYPERCHARGE_CNT,
	ROBIN_ATTACK_ABSOLUTEPIERCE_START = ROBIN_ATTACK_SOULCRASH_START + ROBIN_ATTACK_SOULCRASH_CNT,
	ROBIN_ATTACK_KILLALL_START = ROBIN_ATTACK_ABSOLUTEPIERCE_START + ROBIN_ATTACK_ABSOLUTEPIERCE_CNT,
	ROBIN_ATTACK_DEFENSE_START = ROBIN_ATTACK_KILLALL_START + ROBIN_ATTACK_KILLALL_CNT,
	ROBIN_ATTACK_BARRIER_START = ROBIN_ATTACK_DEFENSE_START + ROBIN_ATTACK_DEFENSE_CNT,
	ROBIN_ATTACK_HPRESTORE_START = ROBIN_ATTACK_BARRIER_START + ROBIN_ATTACK_BARRIER_CNT,
	ROBIN_ATTACK_MPRESTORE_START = ROBIN_ATTACK_HPRESTORE_START + ROBIN_ATTACK_HPRESTORE_CNT,
	ROBIN_ATTACK_REFLECTOR_START = ROBIN_ATTACK_MPRESTORE_START + ROBIN_ATTACK_MPRESTORE_CNT,
	ROBIN_TOTAL_ATTACK_FRAME = ROBIN_ATTACK_REFLECTOR_START + ROBIN_ATTACK_REFLECTOR_CNT,

	//DIANA
#ifdef ATTACK_INIT_DELAY
	DIANA_ATTACK_DELAY = 8,	//60프레임용으로 2배
#else
	DIANA_ATTACK_DELAY = 0,
#endif
	DIANA_ATTACK_NORMAL_CNT = DIANA_ATTACK_DELAY + 123,	//60프레임용으로 2배
	DIANA_ATTACK_DASH_CNT = 24,	//60프레임용으로 2배
	DIANA_ATTACK_AIR_CNT = 15,	//60프레임용으로 2배
	DIANA_ATTACK_DOWN_CNT = 27,	//60프레임용으로 2배
	DIANA_ATTACK_AFTER_CNT = 0,
	DIANA_ATTACK_MAGIC_CNT = 14,	//60프레임용으로 2배
	DIANA_ATTACK_SQUIRREL_CNT = 14,	//60프레임용으로 2배
	DIANA_ATTACK_SQUIRREL2_CNT = 14,	//60프레임용으로 2배
	DIANA_ATTACK_WARP_CNT = 64,	//60프레임용으로 2배
	DIANA_ATTACK_ITEM_CNT = 16,	//60프레임용으로 2배
	DIANA_SKILL_3WAY_CNT = 212,	//60프레임용으로 2배
	DIANA_SKILL_LASER_CNT = 308,	//60프레임용으로 2배
	DIANA_SKILL_FLAMER_CNT = 0,
	DIANA_SKILL_BOMBSHOT_CNT = 203,	//60프레임용으로 2배
	//실제 데이터는 238행이다. 242로 선언돼 있어 이 뒤의 블록이 전부 4행씩
	//밀려 있었다(버프 4종은 배열 끝 0 패딩을 읽고 있었다). 실측값으로 맞춘다.
	DIANA_SKILL_GUIDEDSHOT_CNT = 476,	//60프레임용으로 2배
	DIANA_SKILL_SPRAYSHOT_CNT = 152,	//60프레임용으로 2배
	DIANA_SKILL_SATELLITESHOT_CNT = 224,	//60프레임용으로 2배
	DIANA_SKILL_HEALSHOT_CNT = 41,	//60프레임용으로 2배
	DIANA_SKILL_FEELUP_CNT = 14,	//60프레임용으로 2배
	DIANA_SKILL_VAMPIRE_CNT = 14,	//60프레임용으로 2배
	DIANA_SKILL_FOCUS_CNT = 14,	//60프레임용으로 2배
	DIANA_SKILL_FAMAS_CNT = 14,	//60프레임용으로 2배

	DIANA_ATTACK_NORMAL_START = 0,
	DIANA_ATTACK_DASH_START = DIANA_ATTACK_NORMAL_START + DIANA_ATTACK_NORMAL_CNT,
	DIANA_ATTACK_AIR_START = DIANA_ATTACK_DASH_START + DIANA_ATTACK_DASH_CNT,
	DIANA_ATTACK_DOWN_START = DIANA_ATTACK_AIR_START + DIANA_ATTACK_AIR_CNT,
	DIANA_ATTACK_AFTER_START = DIANA_ATTACK_DOWN_START + DIANA_ATTACK_DOWN_CNT,
	DIANA_ATTACK_MAGIC_START = DIANA_ATTACK_AFTER_START + DIANA_ATTACK_AFTER_CNT,
	DIANA_ATTACK_SQUIRREL_START = DIANA_ATTACK_MAGIC_START + DIANA_ATTACK_MAGIC_CNT,
	DIANA_ATTACK_SQUIRREL2_START = DIANA_ATTACK_SQUIRREL_START + DIANA_ATTACK_SQUIRREL_CNT,
	DIANA_ATTACK_WARP_START = DIANA_ATTACK_SQUIRREL2_START + DIANA_ATTACK_SQUIRREL2_CNT,
	DIANA_ATTACK_ITEM_START = DIANA_ATTACK_WARP_START + DIANA_ATTACK_WARP_CNT,
	DIANA_SKILL_3WAY_START = DIANA_ATTACK_ITEM_START + DIANA_ATTACK_ITEM_CNT,
	DIANA_SKILL_LASER_START = DIANA_SKILL_3WAY_START + DIANA_SKILL_3WAY_CNT,
	DIANA_SKILL_FLAMER_START = DIANA_SKILL_LASER_START + DIANA_SKILL_LASER_CNT,
	DIANA_SKILL_BOMBSHOT_START = DIANA_SKILL_FLAMER_START + DIANA_SKILL_FLAMER_CNT,
	DIANA_SKILL_GUIDEDSHOT_START = DIANA_SKILL_BOMBSHOT_START + DIANA_SKILL_BOMBSHOT_CNT,
	DIANA_SKILL_SPRAYSHOT_START = DIANA_SKILL_GUIDEDSHOT_START + DIANA_SKILL_GUIDEDSHOT_CNT,
	DIANA_SKILL_SATELLITESHOT_START = DIANA_SKILL_SPRAYSHOT_START + DIANA_SKILL_SPRAYSHOT_CNT,
	DIANA_SKILL_HEALSHOT_START = DIANA_SKILL_SATELLITESHOT_START + DIANA_SKILL_SATELLITESHOT_CNT,
	DIANA_SKILL_FEELUP_START = DIANA_SKILL_HEALSHOT_START + DIANA_SKILL_HEALSHOT_CNT,
	DIANA_SKILL_VAMPIRE_START = DIANA_SKILL_FEELUP_START + DIANA_SKILL_FEELUP_CNT,
	DIANA_SKILL_FOCUS_START = DIANA_SKILL_VAMPIRE_START + DIANA_SKILL_VAMPIRE_CNT,
	DIANA_SKILL_FAMAS_START = DIANA_SKILL_FOCUS_START + DIANA_SKILL_FOCUS_CNT,
	DIANA_TOTAL_ATTACK_FRAME = DIANA_SKILL_FAMAS_START + DIANA_SKILL_FAMAS_CNT,

	//MAXX
#ifdef ATTACK_INIT_DELAY
	MAXX_ATTACK_DELAY = 10,	//60프레임용으로 2배
#else
	MAXX_ATTACK_DELAY = 0,
#endif
	MAXX_ATTACK_NORMAL_CNT = MAXX_ATTACK_DELAY + 28,	//60프레임용으로 2배
	MAXX_ATTACK_DASH_CNT = 27,	//60프레임용으로 2배
	MAXX_ATTACK_AIR_CNT = 14,	//60프레임용으로 2배
	MAXX_ATTACK_DOWN_CNT = 30,	//60프레임용으로 2배
	MAXX_ATTACK_AFTER_CNT = 0,
	MAXX_ATTACK_MAGIC_CNT = 14,	//60프레임용으로 2배
	MAXX_ATTACK_SQUIRREL_CNT = 14,	//60프레임용으로 2배
	MAXX_ATTACK_SQUIRREL2_CNT = 14,	//60프레임용으로 2배
	MAXX_ATTACK_WARP_CNT = 38,	//60프레임용으로 2배
	MAXX_ATTACK_ITEM_CNT = 16,	//60프레임용으로 2배
	MAXX_SKILL_KICK_CNT = 76,	//60프레임용으로 2배
	MAXX_SKILL_SHORT_CNT = 104,	//60프레임용으로 2배
	MAXX_SKILL_AIR_CNT = 62,	//60프레임용으로 2배
	MAXX_SKILL_CAMPING_CNT = 30,	//60프레임용으로 2배
	MAXX_SKILL_HORMING_CNT = 78,	//60프레임용으로 2배
	MAXX_SKILL_CIRCLE_CNT = 184,	//60프레임용으로 2배
	MAXX_SKILL_MEGA_CNT = 118,	//60프레임용으로 2배
	MAXX_SKILL_BLOOD_CNT = 14,	//60프레임용으로 2배
	MAXX_SKILL_DAZZLE_CNT = 14,	//60프레임용으로 2배
	MAXX_SKILL_SIGH_CNT = 14,	//60프레임용으로 2배
	MAXX_SKILL_SPLIT_CNT = 14,	//60프레임용으로 2배

	MAXX_ATTACK_NORMAL_START = 0,
	MAXX_ATTACK_DASH_START = MAXX_ATTACK_NORMAL_START + MAXX_ATTACK_NORMAL_CNT,
	MAXX_ATTACK_AIR_START = MAXX_ATTACK_DASH_START + MAXX_ATTACK_DASH_CNT,
	MAXX_ATTACK_DOWN_START = MAXX_ATTACK_AIR_START + MAXX_ATTACK_AIR_CNT,
	MAXX_ATTACK_AFTER_START = MAXX_ATTACK_DOWN_START + MAXX_ATTACK_DOWN_CNT,
	MAXX_ATTACK_MAGIC_START = MAXX_ATTACK_AFTER_START + MAXX_ATTACK_AFTER_CNT,
	MAXX_ATTACK_SQUIRREL_START = MAXX_ATTACK_MAGIC_START + MAXX_ATTACK_MAGIC_CNT,
	MAXX_ATTACK_SQUIRREL2_START = MAXX_ATTACK_SQUIRREL_START + MAXX_ATTACK_SQUIRREL_CNT,
	MAXX_ATTACK_WARP_START = MAXX_ATTACK_SQUIRREL2_START + MAXX_ATTACK_SQUIRREL2_CNT,
	MAXX_ATTACK_ITEM_START = MAXX_ATTACK_WARP_START + MAXX_ATTACK_WARP_CNT,
	MAXX_SKILL_KICK_START = MAXX_ATTACK_ITEM_START + MAXX_ATTACK_ITEM_CNT,
	MAXX_SKILL_SHORT_START = MAXX_SKILL_KICK_START + MAXX_SKILL_KICK_CNT,
	MAXX_SKILL_AIR_START = MAXX_SKILL_SHORT_START + MAXX_SKILL_SHORT_CNT,
	MAXX_SKILL_CAMPING_START = MAXX_SKILL_AIR_START + MAXX_SKILL_AIR_CNT,
	MAXX_SKILL_HORMING_START = MAXX_SKILL_CAMPING_START + MAXX_SKILL_CAMPING_CNT,
	MAXX_SKILL_CIRCLE_START = MAXX_SKILL_HORMING_START + MAXX_SKILL_HORMING_CNT,
	MAXX_SKILL_MEGA_START = MAXX_SKILL_CIRCLE_START + MAXX_SKILL_CIRCLE_CNT,
	MAXX_SKILL_BLOOD_START = MAXX_SKILL_MEGA_START + MAXX_SKILL_MEGA_CNT,
	MAXX_SKILL_DAZZLE_START = MAXX_SKILL_BLOOD_START + MAXX_SKILL_BLOOD_CNT,
	MAXX_SKILL_SIGH_START = MAXX_SKILL_DAZZLE_START + MAXX_SKILL_DAZZLE_CNT,
	MAXX_SKILL_SPLIT_START = MAXX_SKILL_SIGH_START + MAXX_SKILL_SIGH_CNT,
	MAXX_TOTAL_ATTACK_FRAME = MAXX_SKILL_SPLIT_START + MAXX_SKILL_SPLIT_CNT,

	//스킬 프레임 XY 및 효과 정의
	_DIROPPOSITE = 16,
	_DIRDOWN = 32,
	_JUMP0 = 64,
	_JUMP1 = 128,
	_JUMP2 = 192,

	_WAIT1 = 1,
	_WAIT2,
	_WAIT3,
	_END,
	_ENDTOFALL,
	_ADDBUFF,
	_CONTINUE,
	_EDGE3,//일반공격시
	_HLINE_RED1,//로빈대쉬어택시(Lighten 100%)
	_HLINE_RED2,//로빈대쉬어택시(Lighten 50%)
	_VLINE_RED1,//로빈찍기공격시(Lighten 100%)
	_VLINE_RED2,//로빈찍기공격시(Lighten 50%)
	_VLINE_BLUE1,//로빈에어크래쉬(Lighten 100%)
	_VLINE_BLUE2,//로빈에어크래쉬(Lighten 50%)
	_EDGE_YELLOW1,//로빈마구찌르기(Lighten 100%)
	_EDGE_YELLOW2,//로빈마구찌르기(Lighten 50%)
	_EDGE_VIOLET1,//로빈부스트슬래쉬/앱솔루트피어스(Lighten 100%)
	_EDGE_VIOLET2,//로빈부스트슬래쉬(Lighten 50%)
	_HLINE_GREEN1,//로빈하이퍼차지(Lighten 100%)
	_HLINE_GREEN2,//로빈하이퍼차지(Lighten 50%)
	_HLINE_LENZ1,//로빈하이퍼차지(반경 48)
	_HLINE_LENZ2,//로빈하이퍼차지(반경 32)
	_EDGE_BLUE1,//로빈소울크래쉬(Lighten 100%)
	_EDGE_BLUE2,//로빈소울크래쉬(Lighten 50%)
	_EDGE_RED1,//로빈멸살연참(Lighten 100%)
	_EDGE_RED2,//로빈멸살연참(Lighten 50%)
	_SETFRAMEBYDX,
	_SETFRAMEBYDX2,
	_DXDECREASE4,
	_WALKTOEND,
	_ADDJUMPFRAME,
	_ADDJUMPFRAME2,
	_MINUSJUMPFRAME,
	_FACEOPPOSITE,
	_ADDBULLET,
	_ADDHEAL,
	_ADDBOOMERANG,
	_SETSQUIRREL,
	_SETHUMAN,
	_USERING,
	_GOTOWARP,
	_REALWARP,
	_ADDITEMBULLET,
	_ADDBULLETROBIN,
	_DIRECTHEAL,
	_ADDMON,
	//60프레임용으로 프레임 수를 2배로 늘린 대시가 쓴다.
	//_DXDECREASE4를 그대로 쓰면 두 배 빨리 멈춰버린다.
	_DXDECREASE2,

	//캐릭터별 필요 데이터 디파인
	WAIT1FRAME = 0,
	WAIT2FRAME,
	TOTALETCDATA,

	//총알 이동속도 디파인
	BULLET_3WAY_DX = 30 * _2X,
	BULLET_3WAY_DY = 15 * _2X,
	BULLET_LASER_DX = TSIZE,
	BULLET_BOMB_DX = TSIZE * 2,

	//레벨업 모션 디파인
	LEVELUP_BACK0 = 0,
	LEVELUP_BACK1 = 1,
	LEVELUP_BACK2 = 2,
	LEVELUP_BACK3 = 3,
	LEVELUP_BACK4 = 4,
	LEVELUP_BACK5 = 5,
	LEVELUP_BACK6 = 6,
	LEVELUP_BACK7 = 7,
	LEVELUP_BACK8 = 8,
	LEVELUP_BACK9 = 9,
	LEVELUP_FRONT0 = 10,
	LEVELUP_FRONT1 = 11,
	LEVELUP_FRONT2 = 12,
	LEVELUP_FRONT3 = 13,
	LEVELUP_FRONT4 = 14,
	LEVELUP_FRONT5 = 15,
	LEVELUP_FRONT6 = 16,
	LEVELUP_FRONT7 = 17,
	LEVELUP_FRONT8 = 18,
	LEVELUP_FRONT9 = 19,

	TOTALLEVELUPMOTION,

	//액티브스킬인지, 패시브스킬인지, 몬스터를 소환하는건지, 히어로 스킬을 사용하는건지.
	//실제값 ACTIVE / PASSIVE / CREWBULLET / CREWSUMMON / HEROSKILL
//SUMMONHERO 가 소환 히어로에게 입히는 장비 부위 수.
#define SKILL_SUMMON_EQUIP_CNT	6

//CREWSUMMON 전용 진입 연출. skillData의 hero_type 칸을 이 종류에서만
//재사용한다. 이 파일의 해당 영역은 큰 enum 내부이므로 매크로 상수로 둔다.
#define CREWSUMMON_ENTRY_WARP 0
#define CREWSUMMON_ENTRY_JUMP 1

//아이콘이 어느 그림판에서 오는가.
//
//판마다 칸 크기와 줄당 개수가 달라서 번호 하나로는 못 가리킨다.
//그래서 번호(icon)와 판(icon_kind)을 같이 둔다.
	ICONKIND_SKILL = 0,	//스킬 아이콘판  DrawSkillIcon
	ICONKIND_BULLET,		//총알 아이콘판  DrawCrewBulletIcon
	ICONKIND_MONSTER,	//몬스터 그림     enemyBigIconPos

//---- skillData 의 칸 ----
//
//칸 하나에 뜻 하나다. 전에는 29 칸이었는데 같은 칸이 kind 마다 다른
//것을 뜻했다 - target 하나가 연타수이기도 하고 총알 그림이기도 하고
//오브젝트 번호이기도 했다. 그래서 표를 봐도 무엇인지 알 수 없었고,
//실제로 두 곳이 SUMMON 의 몬스터를 엉뚱한 칸에서 읽고 있었다.
//
//지금은 갈래를 다 펴서 칸을 나눴다. 안 쓰는 줄에서는 0 이다. 빈 칸이
//늘어난 대신, 어느 줄이든 같은 칸이 같은 것을 뜻한다.
//
//없앤 것
//    lv2~lv15   레벨별 값. 읽는 곳이 없었다. 동료의 세기는 이제
//               crewData 의 str 이 말한다.
//    r3~r7      5 단짜리 곡선을 만들려던 자리. 읽는 곳이 없었다.
//    obj_detail 이것도 kind 마다 달랐다. 총알 오브젝트(CREWBULLET)와
//               히어로 스킬(SUMMONHERO)만 읽히고 있어서 그 둘은
//               bullet_obj 와 hero_skill 로 옮겼다. 나머지 kind 에
//               들어 있던 것 - ACTIVE/PASSIVE 는 다른 스킬 이름,
//               CREWSUMMON 은 TSIZE * 3 같은 거리, SUMMON 은 ENEMY -
//               는 읽는 곳이 없어 버렸다.
//
//폭(SKILLDATASIZE)은 DATAPACK_ABI_LIST 에 들어 있다. 바뀌면 옛 팩은
//거부되고 내장본이 쓰인다(Data/DataPack.h).
	SKILLDATA_KIND = 0,		//0  ACTIVE PASSIVE CREWBULLET ...
	SKILLDATA_VALUE,			//1  효능 수치 (히어로 스킬)
	SKILLDATA_HITMAX,			//2  한 번에 몇 대까지 (ACTIVE)
	SKILLDATA_COOLDOWN,			//3  재사용 대기 (히어로 스킬)
	SKILLDATA_ICON,				//4  아이콘 번호
	SKILLDATA_ICONKIND,			//5  어느 그림판 (ICONKIND_*)
	SKILLDATA_STAR,				//6  카드의 별
	SKILLDATA_ATTACKTYPE,		//7  어떤 공격으로 나가는가
	SKILLDATA_HOSTOBJ,			//8  어느 오브젝트 칸에서
	SKILLDATA_SUMMONENEMY,		//9  불러낼 몬스터 (SUMMON)
	SKILLDATA_HEROTYPE,			//10  불러낼 히어로 (SUMMONHERO), 진입 타입 (CREWSUMMON)
	SKILLDATA_HEROSKILL,		//11 발동시킬 히어로 스킬
	SKILLDATA_SUMMONX,			//12 소환체/난입 동료가 설 x
	SKILLDATA_BULLETOBJ,		//13 총알 오브젝트 (CREWBULLET)
	SKILLDATA_BULLETICON,		//14 총알 그림 (CREWBULLET)

	//소환 히어로에게 입힐 장비 여섯 부위. SUMMONHERO 만 쓴다.
	SKILLDATA_EQUIP1,			//15
	SKILLDATA_EQUIP2,			//16
	SKILLDATA_EQUIP3,			//17
	SKILLDATA_EQUIP4,			//18
	SKILLDATA_EQUIP5,			//19
	SKILLDATA_EQUIP6,			//20

	//기본공격의 몇 %. 100 이 기본공격 그대로다.
	//
	//동료는 슬롯에 몇 개 떴는지로 skill1/2/3 이 갈린다(Func_Roulette).
	//1 개면 skill1, 2 개면 skill2 다. 둘 다 한 발로 끝나고 세기만
	//다르다 - 지금은 skill2 가 3 배다. 연타로 세게 하는 것이 아니라
	//한 대가 세다.
	SKILLDATA_DMGPCT,			//21

	SKILLDATASIZE,				//22
	SKILLINFODATASIZE = 2,

	SKILL_COMMON_ROBIN1 = 0,	//힘단련 : STR 상승
	SKILL_COMMON_ROBIN2,	//체력단련 : VIT 상승
	SKILL_COMMON_ROBIN3,	//민첩단련 : AGI 상승
	SKILL_COMMON_ROBIN4,	//정신단련 : INT 상승
	SKILL_COMMON_ROBIN5,	//생명력강화 : HP 최대치 상승
	SKILL_COMMON_ROBIN6,	//기력강화 : MP 최대치 상승
	SKILL_COMMON_ROBIN7,	//무기숙련 : 공격력 증가
	SKILL_COMMON_ROBIN8,	//방어구숙련: 방어력 증가
	SKILL_COMMON_ROBIN9,	//약점파악 : 크리티컬 확률 상승
	SKILL_COMMON_ROBIN10,	//약점공격 : 크리티컬 데미지 상승
	SKILL_COMMON_ROBIN11,	//뚝심 : 데미지 경감
	SKILL_COMMON_ROBIN12,	//정조준 : 명중 증가
	SKILL_COMMON_ROBIN13,	//신속회피 : 회피 증가

	SKILL_ROBIN1,	//검술숙련 : 관통 발생 확률 상승
	SKILL_ROBIN2,	//긴급방어 : 방어 발동 확률이 올라감(1레벨이면 방어 발동이 시작, 점점 확률 상승)
	SKILL_ROBIN3,	//방어숙련 : 방어 발동시 경감되는 데미지 퍼센트 상승
	SKILL_ROBIN4,	//면역력 : 상태이상에 대한 저항력 상승
	SKILL_ROBIN5,	//지구전 : INT가 높을수록 VIT 상승
	SKILL_ROBIN6,	//에어크래쉬 : 몹 뛰우기
	SKILL_ROBIN7,	//마구찌르기 : 난타
	SKILL_ROBIN8,	//부스트슬래쉬 : 가로로 크게 배기, 기절공격
	SKILL_ROBIN9,	//하이퍼차지 : 돌격공격, 적을 뒤로 날려버림
	SKILL_ROBIN10,	//소울크래쉬 : 기절
	SKILL_ROBIN11,	//앱솔루트피어스 : 찔러서회전
	SKILL_ROBIN12,	//멸살연참 : 연속기
	SKILL_ROBIN13,	//방어태세 : //방어력 올려서 데미지 줄이는것으로 변경//일정시간 VIT 상승
	SKILL_ROBIN14,	//정신소모 : //방어력 올려서 데미지 줄이는것으로 변경//MP 소모하여 데미지 경감
	SKILL_ROBIN15,	//여유포착 : 적 공격 회피시 HP 상승//데미지 2배 상승
	SKILL_ROBIN16,	//냉정침착 : 데미지 입으면 MP 회복//HP회복
	SKILL_ROBIN17,	//리플렉션 : 확률로데미지 반사//반사

	SKILL_COMMON_DIANA1,	//힘단련 : STR 상승
	SKILL_COMMON_DIANA2,	//체력단련 : VIT 상승
	SKILL_COMMON_DIANA3,	//민첩단련 : AGI 상승
	SKILL_COMMON_DIANA4,	//정신단련 : INT 상승
	SKILL_COMMON_DIANA5,	//생명력강화 : HP 최대치 상승
	SKILL_COMMON_DIANA6,	//기력강화 : MP 최대치 상승
	SKILL_COMMON_DIANA7,	//무기숙련 : 공격력 증가
	SKILL_COMMON_DIANA8,	//방어구숙련: 방어력 증가
	SKILL_COMMON_DIANA9,	//약점파악 : 크리티컬 확률 상승
	SKILL_COMMON_DIANA10,	//약점공격 : 크리티컬 데미지 상승
	SKILL_COMMON_DIANA11,	//뚝심 : 데미지 경감
	SKILL_COMMON_DIANA12,	//정조준 : 명중 증가
	SKILL_COMMON_DIANA13,	//신속회피 : 회피 증가

	SKILL_DIANA1,	//매의눈 : 공격 거리 상승
	SKILL_DIANA2,	//사격숙련 : 기절공격이 발생할 확률이 상승
	SKILL_DIANA3,	//아드레날린 : 기절공격 성공시 MP 회복량 상승
	SKILL_DIANA4,	//활성화 : 스킬 재사용 시간 감소
	SKILL_DIANA5,	//집중력유지 : STR이 높을수록 INT 상승
	SKILL_DIANA6,	//3way : 3방향으로 총 발사
	SKILL_DIANA7,	//리플렉션빔 : 레이져가 벽에 튕김
	SKILL_DIANA8,	//헬파이어 : 화염 방사기
	SKILL_DIANA9,	//로켓런쳐 : 로켓 발사되어 폭발
	SKILL_DIANA10,	//호밍미사일 : 유도탄 3개
	SKILL_DIANA11,	//킬링존 : 난사
	SKILL_DIANA12,	//오비탈레이져 : 인공위성
	SKILL_DIANA13,	//리커버리 : 회복탄
	SKILL_DIANA14,	//흥분고조 : 방어력 저하 공격력 상승
	SKILL_DIANA15,	//흡마의마탄 : 공격시 MP 흡수
	SKILL_DIANA16,	//필살집중 : 크리 상승
	SKILL_DIANA17,	//파마의직격 : 일정시간 적 방어 무시

	SKILL_COMMON_MAXX1,	//힘단련 : STR 상승
	SKILL_COMMON_MAXX2,	//체력단련 : VIT 상승
	SKILL_COMMON_MAXX3,	//민첩단련 : AGI 상승
	SKILL_COMMON_MAXX4,	//정신단련 : INT 상승
	SKILL_COMMON_MAXX5,	//생명력강화 : HP 최대치 상승
	SKILL_COMMON_MAXX6,	//기력강화 : MP 최대치 상승
	SKILL_COMMON_MAXX7,	//무기숙련 : 공격력 증가
	SKILL_COMMON_MAXX8,	//방어구숙련: 방어력 증가
	SKILL_COMMON_MAXX9,	//약점파악 : 크리티컬 확률 상승
	SKILL_COMMON_MAXX10,	//약점공격 : 크리티컬 데미지 상승
	SKILL_COMMON_MAXX11,	//뚝심 : 데미지 경감
	SKILL_COMMON_MAXX12,	//정조준 : 명중 증가
	SKILL_COMMON_MAXX13,	//신속회피 : 회피 증가

	SKILL_MAXX1,	//관통력숙련 : 적을 공격했을 때 부메랑의 판정이 남아있을 확률이 상승한다.
	SKILL_MAXX2,	//투척숙련 : 부메랑 속도 상승
	SKILL_MAXX3,	//연속공격 : 추가 공격 확률 증가
	SKILL_MAXX4,	//회전력상승 : 추가 공격 성공시 해당 공격에 대해서 데미지 상승
	SKILL_MAXX5,	//탄력성 : VIT 높을수록 AGI 상승
	SKILL_MAXX6,	//효율적사고 : INT가 높을수록 AGI가 올라감
	SKILL_MAXX7,	//돌려차기 : 회전, 기절공격
	SKILL_MAXX8,	//숏헌트 : 관통, 사거리 짧음
	SKILL_MAXX9,	//에어헌트 : 수직 상승 공격
	SKILL_MAXX10,	//캠핑헌트 : 앞으로 날라가서 제자리회전
	SKILL_MAXX11,	//호밍헌트 : 가장 가까운 적 때리고 되돌아옴
	SKILL_MAXX12,	//써클헌트 : 주인공 주변 보호
	SKILL_MAXX13,	//메가헌트 : 관통후 뒤에서 돌아옴
	SKILL_MAXX14,	//블러드헌트 : 적 공격시 HP 회복
	SKILL_MAXX15,	//현란무도 : 일정시간 회피율 증가
	SKILL_MAXX16,	//안도의한숨 : 적 공격 회피시 MP 회복
	SKILL_MAXX17,	//혼신분리 : 기절 확률 상승







	NPC_CAPTAIN_SKILL1,//c52//잭스패너//x
	NPC_CAPTAIN_SKILL2,
	NPC_CAPTAIN_SKILL3,
	NPC_CREW_SKILL1,//c53//선원//x
	NPC_CREW_SKILL2,
	NPC_CREW_SKILL3,
	NPC_GRANDFA_SKILL1,//c54//촌장//x
	NPC_GRANDFA_SKILL2,
	NPC_GRANDFA_SKILL3,
	NPC_UNCLE_SKILL1,//c55//아저씨
	NPC_UNCLE_SKILL2,
	NPC_UNCLE_SKILL3,
	NPC_AUNT_SKILL1,//c56//아줌마//x
	NPC_AUNT_SKILL2,
	NPC_AUNT_SKILL3,
	NPC_MAN_SKILL1,//c57//자경단청년//x
	NPC_MAN_SKILL2,
	NPC_MAN_SKILL3,
	NPC_WOMAN_SKILL1,//c58//처녀//x
	NPC_WOMAN_SKILL2,
	NPC_WOMAN_SKILL3,
	NPC_BOY_SKILL1,//c59//꼬마남//x
	NPC_BOY_SKILL2,
	NPC_BOY_SKILL3,
	NPC_GIRL_SKILL1,//c60//꼬마녀//x
	NPC_GIRL_SKILL2,
	NPC_GIRL_SKILL3,
	NPC_ALMA_SKILL1,//c61//알마//x
	NPC_ALMA_SKILL2,
	NPC_ALMA_SKILL3,
	NPC_ITEM_SKILL1,//c62//터번//x
	NPC_ITEM_SKILL2,
	NPC_ITEM_SKILL3,
	NPC_FATMAN_SKILL1,//c63//x
	NPC_FATMAN_SKILL2,
	NPC_FATMAN_SKILL3,
	NPC_BUNNYGIRL_SKILL1,//c64//x
	NPC_BUNNYGIRL_SKILL2,
	NPC_BUNNYGIRL_SKILL3,
	NPC_KNIGHT_SKILL1,//c65//플레타//x
	NPC_KNIGHT_SKILL2,
	NPC_KNIGHT_SKILL3,
	NPC_DOG_SKILL1,//c66//x
	NPC_DOG_SKILL2,
	NPC_DOG_SKILL3,
	NPC_MERCHANT_SKILL1,//c67
	NPC_MERCHANT_SKILL2,
	NPC_MERCHANT_SKILL3,
	NPC_CRAFTMAN_SKILL1,//c68//x
	NPC_CRAFTMAN_SKILL2,
	NPC_CRAFTMAN_SKILL3,
	NPC_MAP_SKILL1,//c69//x
	NPC_MAP_SKILL2,
	NPC_MAP_SKILL3,
	NPC_USERQUEST_SKILL1,//c70//스튜어디스//x
	NPC_USERQUEST_SKILL2,
	NPC_USERQUEST_SKILL3,
	NPC_TRAVEL_SKILL1,//c71//이국의여행자//x
	NPC_TRAVEL_SKILL2,
	NPC_TRAVEL_SKILL3,
	NPC_GRANDMA_SKILL1,//c72//할머니//x
	NPC_GRANDMA_SKILL2,
	NPC_GRANDMA_SKILL3,
	NPC_FISHING_SKILL1,//c73//라피//x
	NPC_FISHING_SKILL2,
	NPC_FISHING_SKILL3,
	NPC_INN_SKILL1,//c74
	NPC_INN_SKILL2,
	NPC_INN_SKILL3,
	NPC_NETITEM_SKILL1,//c75//x
	NPC_NETITEM_SKILL2,
	NPC_NETITEM_SKILL3,
	NPC_MILESE_SKILL1,//c76//x
	NPC_MILESE_SKILL2,
	NPC_MILESE_SKILL3,
	NPC_DOBEL_SKILL1,//c77//x
	NPC_DOBEL_SKILL2,
	NPC_DOBEL_SKILL3,
	NPC_GAGEL_SKILL1,//c78//x
	NPC_GAGEL_SKILL2,
	NPC_GAGEL_SKILL3,
	NPC_MONICA_SKILL1,//c79//x
	NPC_MONICA_SKILL2,
	NPC_MONICA_SKILL3,
	NPC_SHIP_SKILL1,//c80
	NPC_SHIP_SKILL2,
	NPC_SHIP_SKILL3,
	NPC_SEASOLDIER_SKILL1,//c81//아틀란병사//x
	NPC_SEASOLDIER_SKILL2,
	NPC_SEASOLDIER_SKILL3,
	NPC_FRAUD_SKILL1,//c82//x
	NPC_FRAUD_SKILL2,
	NPC_FRAUD_SKILL3,
	NPC_DARIAN_SKILL1,//c83//x
	NPC_DARIAN_SKILL2,
	NPC_DARIAN_SKILL3,
	NPC_LUISE_SKILL1,//c84//x
	NPC_LUISE_SKILL2,
	NPC_LUISE_SKILL3,
	NPC_SEAUNCLE_SKILL1,//c85//아틀란아저씨//x
	NPC_SEAUNCLE_SKILL2,
	NPC_SEAUNCLE_SKILL3,
	NPC_SEABOY_SKILL1,//c86//아틀란소년//x
	NPC_SEABOY_SKILL2,
	NPC_SEABOY_SKILL3,
	NPC_DONALD_SKILL1,//c87//이소룡//x
	NPC_DONALD_SKILL2,
	NPC_DONALD_SKILL3,
	NPC_SCHOLAR_SKILL1,//c88//학자//x
	NPC_SCHOLAR_SKILL2,
	NPC_SCHOLAR_SKILL3,
	NPC_CHEF_SKILL1,//c89//요리대가//x
	NPC_CHEF_SKILL2,
	NPC_CHEF_SKILL3,
	NPC_BISTRO_SKILL1,//c90//비스트로//x
	NPC_BISTRO_SKILL2,
	NPC_BISTRO_SKILL3,
	NPC_MAID_SKILL1,//c91//시녀//x
	NPC_MAID_SKILL2,
	NPC_MAID_SKILL3,
	NPC_ADELKNIGHT_SKILL1,//c92//기사//x
	NPC_ADELKNIGHT_SKILL2,
	NPC_ADELKNIGHT_SKILL3,
	NPC_SEBASTIAN_SKILL1,//c93//세바스찬//x
	NPC_SEBASTIAN_SKILL2,
	NPC_SEBASTIAN_SKILL3,
	NPC_NOBLEMAN_SKILL1,//c94//귀족아저씨//x
	NPC_NOBLEMAN_SKILL2,
	NPC_NOBLEMAN_SKILL3,
	NPC_DELPIOS_SKILL1,//c95//델피오스//x
	NPC_DELPIOS_SKILL2,
	NPC_DELPIOS_SKILL3,
	NPC_LORA_SKILL1,//c96//로라//x
	NPC_LORA_SKILL2,
	NPC_LORA_SKILL3,
	NPC_WITCH_SKILL1,//c97//마녀//x
	NPC_WITCH_SKILL2,
	NPC_WITCH_SKILL3,
	NPC_ELFGRANDFA_SKILL1,//c98//엘프할아버지//x
	NPC_ELFGRANDFA_SKILL2,
	NPC_ELFGRANDFA_SKILL3,
	NPC_ELFUNCLE_SKILL1,//c99//엘프아저씨//x
	NPC_ELFUNCLE_SKILL2,
	NPC_ELFUNCLE_SKILL3,
	NPC_ELFAUNT_SKILL1,//c100//엘프아줌마//x
	NPC_ELFAUNT_SKILL2,
	NPC_ELFAUNT_SKILL3,
	NPC_ELFMAN_SKILL1,//c101//엘프청년//x
	NPC_ELFMAN_SKILL2,
	NPC_ELFMAN_SKILL3,
	NPC_ELFWOMAN_SKILL1,//c102//엘프처녀//x
	NPC_ELFWOMAN_SKILL2,
	NPC_ELFWOMAN_SKILL3,
	NPC_ELFBOY_SKILL1,//c103//엘프꼬마남//x
	NPC_ELFBOY_SKILL2,
	NPC_ELFBOY_SKILL3,
	NPC_ELFGIRL_SKILL1,//c104//엘프꼬마녀//x
	NPC_ELFGIRL_SKILL2,
	NPC_ELFGIRL_SKILL3,
	NPC_ELFDARK_SKILL1,//c105//엘프다크//x
	NPC_ELFDARK_SKILL2,
	NPC_ELFDARK_SKILL3,
	NPC_ELFMAGIC_SKILL1,//c106//엘프마법사//x
	NPC_ELFMAGIC_SKILL2,
	NPC_ELFMAGIC_SKILL3,
	NPC_ELFDANCER_SKILL1,//c107//엘프무희//x
	NPC_ELFDANCER_SKILL2,
	NPC_ELFDANCER_SKILL3,
	NPC_OWL_SKILL1,//c108//부엉이//x
	NPC_OWL_SKILL2,
	NPC_OWL_SKILL3,
	NPC_LABETH_SKILL1,//c109//라베스//x
	NPC_LABETH_SKILL2,
	NPC_LABETH_SKILL3,
	NPC_ELKEIN_SKILL1,//c110//엘케인//x
	NPC_ELKEIN_SKILL2,
	NPC_ELKEIN_SKILL3,
	NPC_ELEIN_SKILL1,//c111//엘레인//x
	NPC_ELEIN_SKILL2,
	NPC_ELEIN_SKILL3,
	NPC_EVAN_SKILL1,//c112//에번//x
	NPC_EVAN_SKILL2,
	NPC_EVAN_SKILL3,
	NPC_BEAD_SKILL1,//c113//테이블//x
	NPC_BEAD_SKILL2,
	NPC_BEAD_SKILL3,
	NPC_FOUNTAIN_SKILL1,//c114//샘물//x
	NPC_FOUNTAIN_SKILL2,
	NPC_FOUNTAIN_SKILL3,
	NPC_NEZAR_SKILL1,//c115//네자르//x
	NPC_NEZAR_SKILL2,
	NPC_NEZAR_SKILL3,
	NPC_GALLAND_SKILL1,//c116//갈란드//x
	NPC_GALLAND_SKILL2,
	NPC_GALLAND_SKILL3,
	NPC_DURAK_SKILL1,//c117//듀라크//x
	NPC_DURAK_SKILL2,
	NPC_DURAK_SKILL3,
	NPC_KING_SKILL1,//c118//에드몬드//x
	NPC_KING_SKILL2,
	NPC_KING_SKILL3,
	NPC_WOMANGHOST_SKILL1,//c119//여자유령//x
	NPC_WOMANGHOST_SKILL2,
	NPC_WOMANGHOST_SKILL3,
	NPC_MANGHOST_SKILL1,//c120//남자유령//x
	NPC_MANGHOST_SKILL2,
	NPC_MANGHOST_SKILL3,
	NPC_AUSTIN_SKILL1,//c121//오스틴(유령)//x
	NPC_AUSTIN_SKILL2,
	NPC_AUSTIN_SKILL3,
	NPC_SOUL_SKILL1,//c122//마왕의 심장//x
	NPC_SOUL_SKILL2,
	NPC_SOUL_SKILL3,

	TOTAL_SKILL,

	TOTALCHARSKILL = 30,

	MAXSKILLLV = 15,

	MAXSKILLLV_5 = 5,

#ifdef SKILLBUYUSEMODE
	MAXCHARSKILL = 9,
	//MAXCHARSKILL = 11,
	//SKILLICONSIZE = 16 * _2X,
	SKILLICONSIZE = 24 * _2X,
	MAXSKILLCOUNT = 41,
#else
	//MAXCHARSKILL = 19,
	SKILLICONSIZE = 32 * _2X,
	MAXCHARSKILL = 7,
	//MAXCHARSKILL = 11,
	//SKILLICONSIZE = 16 * _2X,
	MAXSKILLCOUNT = 41,
#endif
	CREWBULLETICONSIZE = 32 * _2X,
	//총탄 이미지(crewBullet.png)는 가로로 16개씩 늘어서 있다.
	CREWBULLETICONPERLINE = 16,

	//총탄이 날아가는 모양. crewBulletAni[]가 아이콘마다 하나씩 들고 있다.
	CREWBULLETANI_NONE = 0,	//그냥 날아간다
	CREWBULLETANI_SPIN,		//360도 회전하며 날아간다
	CREWBULLETANI_PULSE,	//살짝 커졌다 원래대로 돌아오기를 반복하며 쫀득하게 날아간다
	TOTAL_CREWBULLETANI,

	//SPIN: 한 바퀴 도는 데 걸리는 프레임
	CREWBULLET_SPINFRAME = 24,
	//PULSE: 커졌다 작아졌다 한 번 하는 데 걸리는 프레임
	CREWBULLET_PULSEFRAME = 20,
	//PULSE로 커지는 최대 비율(%). 아래 CREWBULLET_PULSEAMP가 이 값을 쓴다.
	CREWBULLET_PULSEPERCENT = 18,

	SKILLPERCENTDATASIZE = 8,
	ITEMICONSIZE = 16 * _2X,

	BOXSIZE_X = 64 * _2X,
	BOXSIZE_Y = 64 * _2X,

	BOXRESCNT = 4,



	SKILLEFFECTFRAME = 20,//스킬사용시 암전되는 프레임
	BUFFITEMEFFECTFRAME = 16,//스킬사용시 암전되는 프레임
	RINGEFFECTFRAME = 8,//반지를 사용했을 때 프레임
	BUFFINITSECONDS = 10,
	DEADSTARTFRAME = FPS,
	DEADFRAME = FPS * 5,
	ATTACKEDFRAME = FPS,
	BOXATTACKEDFRAME = ATTACKEDFRAME / 5,
	TOUCHIDLEFRAME = FPS * 10,
	//터치 포인터(DrawTouchPoint)가 남아 있는 프레임. 1초는 너무 길어 절반으로 줄였다.
	TOUCHPOINTFRAME = FPS / 2,
	TABMENUFRAME = 8,

	POPUPFRAME = 5,

	//MOTION
	HIT_LARGE1 = 0,
	HIT_LARGE2 = 1,
	HIT_LARGE3 = 2,
	HIT_DEAD1 = 3,
	HIT_DEAD2 = 4,
	HIT_DEAD3 = 5,
	HIT_DEAD4 = 6,
	HIT_DEAD5 = 7,
	DEBUF_POISON0 = 8,
	DEBUF_POISON1 = 9,
	DEBUF_POISON2 = 10,
	DEBUF_POISON3 = 11,
	DEBUF_POISON4 = 12,
	DEBUF_POISON5 = 13,
	DEBUF_SLOW0 = 14,
	DEBUF_SLOW1 = 15,
	DEBUF_SLOW2 = 16,
	DEBUF_SLOW3 = 17,
	DEBUF_SLOW4 = 18,
	DEBUF_BLIND0 = 19,
	DEBUF_BLIND1 = 20,
	DEBUF_BLIND2 = 21,
	DEBUF_BLIND3 = 22,
	DEBUF_BLIND4 = 23,
	DEBUF_BLIND5 = 24,
	DEBUF_CURSE0 = 25,
	DEBUF_CURSE1 = 26,
	DEBUF_CURSE2 = 27,
	DEBUF_CURSE3 = 28,
	DEBUF_CURSE4 = 29,
	DEBUF_CURSE5 = 30,
	DEBUF_STUN0 = 31,
	DEBUF_STUN1 = 32,
	DEBUF_STUN2 = 33,
	DEBUF_STUN3 = 34,
	DEBUF_STUN4 = 35,
	DEBUF_STUN5 = 36,
	DEBUF_KNOCKBACK0 = 37,
	DEBUF_KNOCKBACK1 = 38,
	DEBUF_KNOCKBACK2 = 39,
	DEBUF_KNOCKBACK3 = 40,
	EMOTICON_ZZZ0 = 41,
	EMOTICON_ZZZ1 = 42,
	EMOTICON_ZZZ2 = 43,
	EMOTICON_ZZZ3 = 44,
	EMOTICON_ZZZ4 = 45,
	EMOTICON_ZZZ5 = 46,
	EMOTICON_ZZZ6 = 47,
	EMOTICON_ZZZ7 = 48,
	EMOTICON_ZZZ8 = 49,
	EMOTICON_ZZZ9 = 50,
	EMOTICON_ZZZ10 = 51,
	EMOTICON_ZZZ11 = 52,
	EMOTICON_TALK0 = 53,
	EMOTICON_TALK1 = 54,
	EMOTICON_TALK2 = 55,
	EMOTICON_TALK3 = 56,
	EMOTICON_TALK4 = 57,
	EMOTICON_TALK5 = 58,
	EMOTICON_TALK6 = 59,
	EMOTICON_TALK7 = 60,
	EMOTICON_TALK8 = 61,
	EMOTICON_TALK9 = 62,
	EMOTICON_TALK10 = 63,
	EMOTICON_TALK11 = 64,
	EMOTICON_TALK12 = 65,
	EMOTICON_TALK13 = 66,
	EMOTICON_TALK14 = 67,
	EMOTICON_TALK15 = 68,
	EMOTICON_FLASH0 = 69,
	EMOTICON_FLASH1 = 70,
	EMOTICON_FLASH2 = 71,
	EMOTICON_FLASH3 = 72,
	EMOTICON_FLASH4 = 73,
	EMOTICON_SCOWL0 = 74,
	EMOTICON_SCOWL1 = 75,
	EMOTICON_SCOWL2 = 76,
	EMOTICON_SWEAT0 = 77,
	EMOTICON_SWEAT1 = 78,
	EMOTICON_SWEAT2 = 79,
	EMOTICON_SWEAT3 = 80,
	EMOTICON_SWEAT4 = 81,
	EMOTICON_MUNG0 = 82,
	EMOTICON_MUNG1 = 83,
	EMOTICON_MUNG2 = 84,
	EMOTICON_MUNG3 = 85,
	EMOTICON_QUESTION0 = 86,
	EMOTICON_QUESTION1 = 87,
	EMOTICON_QUESTION2 = 88,
	EMOTICON_QUESTION3 = 89,
	EMOTICON_QUESTION4 = 90,
	EMOTICON_QUESTION5 = 91,
	EMOTICON_SURPRISE0 = 92,
	EMOTICON_SURPRISE1 = 93,
	EMOTICON_SURPRISE2 = 94,
	EMOTICON_HEART0 = 95,
	EMOTICON_HEART1 = 96,
	EMOTICON_HEART2 = 97,
	EMOTICON_HAPPY0 = 98,
	EMOTICON_HAPPY1 = 99,
	EMOTICON_HAPPY2 = 100,
	EMOTICON_CRY0 = 101,
	EMOTICON_CRY1 = 102,
	EMOTICON_CRY2 = 103,
	EMOTICON_CRY3 = 104,
	EFFECT_LEVELUP_TEXT0 = 105,
	EFFECT_LEVELUP_TEXT1 = 106,
	EFFECT_LEVELUP_TEXT2 = 107,
	EFFECT_LEVELUP_TEXT3 = 108,
	EFFECT_LEVELUP_TEXT4 = 109,
	EFFECT_LEVELUP_TEXT5 = 110,
	EFFECT_LEVELUP_TEXT6 = 111,
	EFFECT_LEVELUP_TEXT7 = 112,
	EFFECT_LEVELUP_TEXT8 = 113,
	EFFECT_LEVELUP_TEXT9 = 114,
	EFFECT_LEVELUP_TEXT10 = 115,
	EFFECT_LEVELUP_TEXT10_COPY = 116,
	EFFECT_LEVELUP_TEXT12 = 117,
	EFFECT_LEVELUP_TEXT13 = 118,
	EFFECT_CRITICAL_TEXT0 = 119,
	EFFECT_CRITICAL_TEXT1 = 120,
	EFFECT_CRITICAL_TEXT2 = 121,
	EFFECT_CRITICAL_TEXT3 = 122,
	EFFECT_PIERCE0 = 123,
	EFFECT_PIERCE1 = 124,
	EFFECT_PIERCE2 = 125,
	EFFECT_PIERCE3 = 126,
	EFFECT_EXTRA0 = 127,
	EFFECT_EXTRA1 = 128,
	EFFECT_EXTRA2 = 129,
	EFFECT_EXTRA3 = 130,
	EFFECT_GUARD0 = 131,
	EFFECT_GUARD1 = 132,
	EFFECT_GUARD2 = 133,
	EFFECT_GUARD3 = 134,
	BUFF_DMG0 = 135,
	BUFF_DMG1 = 136,
	BUFF_DMG2 = 137,
	BUFF_DMG3 = 138,
	BUFF_DMG4 = 139,
	BUFF_ARMOR0 = 140,
	BUFF_ARMOR1 = 141,
	BUFF_ARMOR2 = 142,
	BUFF_ARMOR3 = 143,
	BUFF_ARMOR4 = 144,
	BUFF_ARMOR5 = 145,
	BUFF_ARMOR6 = 146,
	BUFF_ARMOR7 = 147,
	BUFF_ARMOR8 = 148,
	BUFF_ARMOR9 = 149,
	BUFF_ARMOR10 = 150,
	BUFF_ARMOR11 = 151,
	MAGNET_ACTIVE0 = 152,
	MAGNET_ACTIVE1 = 153,
	MAGNET_ACTIVE2 = 154,
	MAGNET_ACTIVE3 = 155,
	MAGNET_ACTIVE4 = 156,
	MAGNET_ACTIVE5 = 157,
	MAGNET_DEACTIVE0 = 158,
	MAGNET_DEACTIVE1 = 159,
	MAGNET_DEACTIVE2 = 160,
	MAGNET_DEACTIVE3 = 161,
	MAGNET_DEACTIVE4 = 162,
	MAGNET_DEACTIVE5 = 163,
	MAGNET_DEACTIVE6 = 164,
	MAGNET_DEACTIVE7 = 165,
	MAGNET_DEACTIVE8 = 166,
	MAGNET_DEACTIVE9 = 167,
	MAGNET_DEACTIVE10 = 168,
	MAGNET_DEACTIVE11 = 169,
	EFFECT_FIRE0 = 170,
	EFFECT_FIRE1 = 171,
	EFFECT_FIRE2 = 172,
	EFFECT_FIRE3 = 173,
	EFFECT_FIRE4 = 174,
	EFFECT_FIRE5 = 175,
	EFFECT_FIRE6 = 176,
	EFFECT_FIRE7 = 177,
	EFFECT_ICE0 = 178,
	EFFECT_ICE1 = 179,
	EFFECT_ICE2 = 180,
	EFFECT_ICE3 = 181,
	EFFECT_ICE4 = 182,
	EFFECT_ICE5 = 183,
	EFFECT_ICE6 = 184,
	EFFECT_ICE7 = 185,
	EFFECT_ICE8 = 186,
	EFFECT_THUNDER0 = 187,
	EFFECT_THUNDER1 = 188,
	EFFECT_THUNDER2 = 189,
	EFFECT_THUNDER3 = 190,
	EFFECT_THUNDER4 = 191,
	EFFECT_THUNDER5 = 192,
	EFFECT_THUNDER6 = 193,
	EFFECT_THUNDER7 = 194,
	EFFECT_THUNDER8 = 195,
	EFFECT_HOLY0 = 196,
	EFFECT_HOLY1 = 197,
	EFFECT_HOLY2 = 198,
	EFFECT_HOLY3 = 199,
	EFFECT_HOLY4 = 200,
	EFFECT_HOLY5 = 201,
	EFFECT_HOLY6 = 202,
	EFFECT_HOLY7 = 203,
	EFFECT_HOLY8 = 204,
	EFFECT_HOLY9 = 205,
	EFFECT_DARK0 = 206,
	EFFECT_DARK1 = 207,
	EFFECT_DARK2 = 208,
	EFFECT_DARK3 = 209,
	EFFECT_DARK4 = 210,
	EFFECT_DARK5 = 211,
	EFFECT_RESTORE0 = 212,
	EFFECT_RESTORE1 = 213,
	EFFECT_RESTORE2 = 214,
	EFFECT_RESTORE3 = 215,
	EFFECT_RESTORE4 = 216,
	EFFECT_RESTORE5 = 217,
	EFFECT_RESTORE6 = 218,
	EFFECT_RESTORE7 = 219,
	EFFECT_RESTORE8 = 220,
	EFFECT_RESTORE9 = 221,
	EFFECT_RESTORE10 = 222,
	EFFECT_CURE0 = 223,
	EFFECT_CURE1 = 224,
	EFFECT_CURE2 = 225,
	EFFECT_CURE3 = 226,
	EFFECT_CURE4 = 227,
	EFFECT_CURE5 = 228,
	EFFECT_CURE6 = 229,
	EFFECT_CURE7 = 230,
	EFFECT_CURE8 = 231,
	EFFECT_CURE9 = 232,
	EFFECT_CURE10 = 233,
	EFFECT_DRAIN0 = 234,
	EFFECT_DRAIN1 = 235,
	EFFECT_DRAIN2 = 236,
	EFFECT_DRAIN3 = 237,
	EFFECT_DRAIN4 = 238,
	EFFECT_QUEST0_0 = 239,
	EFFECT_QUEST0_1 = 240,
	EFFECT_QUEST0_2 = 241,
	EFFECT_QUEST0_3 = 242,
	EFFECT_QUEST0_4 = 243,
	EFFECT_QUEST1_0 = 244,
	EFFECT_QUEST1_1 = 245,
	EFFECT_QUEST1_2 = 246,
	EFFECT_QUEST1_3 = 247,
	EFFECT_QUEST1_4 = 248,
	EFFECT_QUEST2_0 = 249,
	EFFECT_QUEST2_1 = 250,
	EFFECT_QUEST2_2 = 251,
	EFFECT_QUEST2_3 = 252,
	EFFECT_QUEST2_4 = 253,
	EFFECT_DEMOTALK_ARROW0 = 254,
	EFFECT_DEMOTALK_ARROW1 = 255,
	EFFECT_DEMOTALK_ARROW2 = 256,
	EFFECT_DEMOTALK_ARROW3 = 257,
	EFFECT_DEMOTALK_ARROW4 = 258,
	EFFECT_UP0 = 259,
	EFFECT_UP1 = 260,
	EFFECT_UP2 = 261,
	EFFECT_UP3 = 262,
	EFFECT_UP4 = 263,
	EFFECT_UP5 = 264,
	EFFECT_UP6 = 265,
	EFFECT_SLOT0 = 266,
	EFFECT_SLOT1 = 267,
	EFFECT_SLOT2 = 268,
	EFFECT_SLOT3 = 269,
	EFFECT_SLOT4 = 270,
	EFFECT_SLOT5 = 271,
	EFFECT_SLOT6 = 272,
	EFFECT_INSIDE_ARROW0 = 273,
	EFFECT_INSIDE_ARROW1 = 274,
	EFFECT_INSIDE_ARROW2 = 275,
	EFFECT_INSIDE_ARROW3 = 276,
	EFFECT_INSIDE_ARROW4 = 277,

	TOTALEFFECTMOTION,

	//IMAGE
	IMG_EFFECT_0 = 0,
	IMG_EFFECT_1 = 1,
	IMG_EFFECT_2 = 2,
	IMG_EFFECT_3 = 3,
	IMG_EFFECT_4 = 4,
	IMG_EFFECT_5 = 5,
	IMG_EFFECT_6 = 6,
	IMG_EFFECT_7 = 7,
	IMG_EFFECT_8 = 8,
	IMG_EFFECT_9 = 9,
	IMG_EFFECT_10 = 10,
	IMG_EFFECT_11 = 11,
	IMG_EFFECT_12 = 12,
	IMG_EFFECT_13 = 13,
	IMG_EFFECT_14 = 14,
	IMG_EFFECT_15 = 15,
	IMG_EFFECT_16 = 16,
	IMG_EFFECT_17 = 17,
	IMG_EFFECT_18 = 18,
	IMG_EFFECT_19 = 19,
	IMG_EFFECT_20 = 20,
	IMG_EFFECT_21 = 21,
	IMG_EFFECT_22 = 22,
	IMG_EFFECT_23 = 23,
	IMG_EFFECT_24 = 24,
	IMG_EFFECT_25 = 25,
	IMG_EFFECT_26 = 26,
	IMG_EFFECT_27 = 27,
	IMG_EFFECT_28 = 28,
	IMG_EFFECT_29 = 29,
	IMG_EFFECT_30 = 30,
	IMG_EFFECT_31 = 31,
	IMG_EFFECT_32 = 32,
	IMG_EFFECT_33 = 33,
	IMG_EFFECT_34 = 34,
	IMG_EFFECT_35 = 35,
	IMG_EFFECT_36 = 36,
	IMG_EFFECT_37 = 37,
	IMG_EFFECT_38 = 38,
	IMG_EFFECT_39 = 39,
	IMG_EFFECT_40 = 40,
	IMG_EFFECT_41 = 41,
	IMG_EFFECT_42 = 42,
	IMG_EFFECT_43 = 43,
	IMG_EFFECT_44 = 44,
	IMG_EFFECT_45 = 45,
	IMG_EFFECT_46 = 46,
	IMG_EFFECT_47 = 47,
	IMG_EFFECT_48 = 48,
	IMG_EFFECT_49 = 49,
	IMG_EFFECT_50 = 50,
	IMG_EFFECT_51 = 51,
	IMG_EFFECT_52 = 52,
	IMG_EFFECT_53 = 53,
	IMG_EFFECT_54 = 54,
	IMG_EFFECT_55 = 55,
	IMG_EFFECT_56 = 56,
	IMG_EFFECT_57 = 57,
	IMG_EFFECT_58 = 58,
	IMG_EFFECT_59 = 59,
	IMG_EFFECT_60 = 60,
	IMG_EFFECT_61 = 61,
	IMG_EFFECT_62 = 62,
	IMG_EFFECT_63 = 63,
	IMG_EFFECT_64 = 64,
	IMG_EFFECT_65 = 65,
	IMG_EFFECT_66 = 66,
	IMG_EFFECT_67 = 67,
	IMG_EFFECT_68 = 68,
	IMG_EFFECT_69 = 69,
	IMG_EFFECT_70 = 70,
	IMG_EFFECT_71 = 71,
	IMG_EFFECT_72 = 72,
	IMG_EFFECT_73 = 73,
	IMG_EFFECT_74 = 74,
	IMG_EFFECT_75 = 75,
	IMG_EFFECT_76 = 76,
	IMG_EFFECT_77 = 77,
	IMG_EFFECT_78 = 78,
	IMG_EFFECT_79 = 79,
	IMG_EFFECT_80 = 80,
	IMG_EFFECT_81 = 81,
	IMG_EFFECT_82 = 82,
	IMG_EFFECT_83 = 83,
	IMG_EFFECT_84 = 84,
	IMG_EFFECT_85 = 85,
	IMG_EFFECT_86 = 86,
	IMG_EFFECT_87 = 87,
	IMG_EFFECT_88 = 88,
	IMG_EFFECT_89 = 89,
	IMG_EFFECT_90 = 90,
	IMG_EFFECT_91 = 91,
	IMG_EFFECT_92 = 92,
	IMG_EFFECT_93 = 93,
	IMG_EFFECT_94 = 94,
	IMG_EFFECT_95 = 95,
	IMG_EFFECT_96 = 96,
	IMG_EFFECT_97 = 97,
	IMG_EFFECT_98 = 98,
	IMG_EFFECT_99 = 99,
	IMG_EFFECT_100 = 100,
	IMG_EFFECT_101 = 101,
	IMG_EFFECT_102 = 102,
	IMG_EFFECT_103 = 103,
	IMG_EFFECT_104 = 104,
	IMG_EFFECT_105 = 105,
	IMG_EFFECT_106 = 106,
	IMG_EFFECT_107 = 107,
	IMG_EFFECT_108 = 108,
	IMG_EFFECT_109 = 109,
	IMG_EFFECT_110 = 110,
	IMG_EFFECT_111 = 111,
	IMG_EFFECT_112 = 112,
	IMG_EFFECT_113 = 113,
	IMG_EFFECT_114 = 114,
	IMG_EFFECT_115 = 115,
	IMG_EFFECT_116 = 116,
	IMG_EFFECT_117 = 117,
	IMG_EFFECT_118 = 118,
	IMG_EFFECT_119 = 119,
	IMG_EFFECT_120 = 120,
	IMG_EFFECT_121 = 121,
	IMG_EFFECT_122 = 122,
	IMG_EFFECT_123 = 123,
	IMG_EFFECT_124 = 124,
	IMG_EFFECT_125 = 125,
	IMG_EFFECT_126 = 126,
	IMG_EFFECT_127 = 127,
	IMG_EFFECT_128 = 128,
	IMG_EFFECT_129 = 129,
	IMG_EFFECT_130 = 130,
	IMG_EFFECT_131 = 131,
	IMG_EFFECT_132 = 132,
	IMG_EFFECT_133 = 133,
	IMG_EFFECT_134 = 134,
	IMG_EFFECT_135 = 135,
	IMG_EFFECT_136 = 136,
	IMG_EFFECT_137 = 137,
	IMG_EFFECT_138 = 138,
	IMG_EFFECT_139 = 139,
	IMG_EFFECT_140 = 140,
	IMG_EFFECT_141 = 141,
	IMG_EFFECT_142 = 142,
	IMG_EFFECT_143 = 143,
	IMG_EFFECT_144 = 144,
	IMG_EFFECT_145 = 145,
	IMG_EFFECT_146 = 146,
	IMG_EFFECT_147 = 147,
	IMG_EFFECT_148 = 148,
	IMG_EFFECT_149 = 149,
	IMG_EFFECT_150 = 150,
	IMG_EFFECT_151 = 151,
	IMG_EFFECT_152 = 152,
	IMG_EFFECT_153 = 153,
	IMG_EFFECT_154 = 154,
	IMG_EFFECT_155 = 155,

	TOTALEFFECTOFF,

	PO_C1_SATLASER_SHOT0 = 0,
	PO_C1_SATLASER_SHOT1,
	PO_C1_SATLASER_SHOT2,
	PO_C1_SATLASER_SHOT3,
	PO_C1_SATLASER_SHOT4,
	PO_C1_SATLASER_SHOT5,
	PO_C1_SATLASER_SHOT6,
	PO_C1_SATLASER_SHOT7,
	PO_C1_SATLASER_SHOT8,
	PO_C1_SATLASER_SHOT9,

	PO_C1_SATLASER_SAT0,
	PO_C1_SATLASER_SAT1,
	PO_C1_SATLASER_SAT2,
	PO_C1_SATLASER_SAT3,
	PO_C1_SATLASER_SAT4,
	PO_C1_SATLASER_SAT5,
	PO_C1_SATLASER_SAT6,
	PO_C1_SATLASER_SAT7,
	PO_C1_SATLASER_SAT8,
	PO_C1_SATLASER_SAT9,
	PO_C1_SATLASER_SAT10,
	PO_C1_SATLASER_SAT11,
	PO_C1_SATLASER_SAT12,
	PO_C1_SATLASER_SAT13,
	PO_C1_SATLASER_SAT14,
	PO_C1_SATLASER_SAT15,
	PO_C1_SATLASER_SAT16,
	PO_C1_SATLASER_SAT17,
	PO_C1_SATLASER_SAT18,
	PO_C1_SATLASER_SAT19,
	PO_C1_SATLASER_SAT20,

	//MOTION
	HIT_MYSELF0 = 0,
	HIT_MYSELF1 = 1,
	HIT_MYSELF2 = 2,
	HIT_PIERCE0 = 3,
	HIT_PIERCE1 = 4,
	HIT_PIERCE2 = 5,
	HIT_PIERCE3 = 6,
	HIT_PIERCE4 = 7,
	HIT_EXTRA0 = 8,
	HIT_EXTRA1 = 9,
	HIT_EXTRA2 = 10,
	HIT_EXTRA3 = 11,
	HIT_EXTRA4 = 12,
	HIT_ROBIN_SMALL1 = 13,
	HIT_ROBIN_SMALL2 = 14,
	HIT_ROBIN_SMALL3 = 15,
	HIT_ROBIN_MEDIUM1 = 16,
	HIT_ROBIN_MEDIUM2 = 17,
	HIT_ROBIN_MEDIUM3 = 18,
	HIT_DIANA_SMALL1 = 19,
	HIT_DIANA_SMALL2 = 20,
	HIT_DIANA_SMALL3 = 21,
	HIT_DIANA_SMALL4 = 22,
	HIT_DIANA_SMALL5 = 23,
	HIT_DIANA_SMALL6 = 24,
	HIT_DIANA_SMALL7 = 25,
	HIT_DIANA_MEDIUM1 = 26,
	HIT_DIANA_MEDIUM2 = 27,
	HIT_DIANA_MEDIUM3 = 28,
	HIT_DIANA_MEDIUM4 = 29,
	HIT_DIANA_MEDIUM5 = 30,
	HIT_DIANA_MEDIUM6 = 31,
	HIT_DIANA_MEDIUM7 = 32,
	HIT_MAXX_SMALL1 = 33,
	HIT_MAXX_SMALL2 = 34,
	HIT_MAXX_SMALL3 = 35,
	HIT_MAXX_SMALL4 = 36,
	HIT_MAXX_MEDIUM1 = 37,
	HIT_MAXX_MEDIUM2 = 38,
	HIT_MAXX_MEDIUM3 = 39,
	HIT_MAXX_MEDIUM4 = 40,
	HIT_ITEM_SMALL0 = 41,
	HIT_ITEM_SMALL1 = 42,
	HIT_ITEM_SMALL2 = 43,
	HIT_ITEM_SMALL3 = 44,
	HIT_ITEM_SMALL4 = 45,
	HIT_ITEM_LARGE0 = 46,
	HIT_ITEM_LARGE1 = 47,
	HIT_ITEM_LARGE2 = 48,
	HIT_ITEM_LARGE3 = 49,
	HIT_ITEM_LARGE4 = 50,

	TOTALHITMOTION,

	//IMAGEf
	IMG_HIT_0 = 0,
	IMG_HIT_1 = 1,
	IMG_HIT_2 = 2,
	IMG_HIT_3 = 3,
	IMG_HIT_4 = 4,
	IMG_HIT_5 = 5,
	IMG_HIT_6 = 6,
	IMG_HIT_7 = 7,
	IMG_HIT_8 = 8,
	IMG_HIT_9 = 9,
	IMG_HIT_10 = 10,
	IMG_HIT_11 = 11,
	IMG_HIT_12 = 12,
	IMG_HIT_13 = 13,
	IMG_HIT_14 = 14,
	IMG_HIT_49 = 15,
	IMG_HIT_15 = 16,
	IMG_HIT_16 = 17,
	IMG_HIT_17 = 18,
	IMG_HIT_18 = 19,
	IMG_HIT_19 = 20,
	IMG_HIT_20 = 21,
	IMG_HIT_21 = 22,
	IMG_HIT_22 = 23,
	IMG_HIT_23 = 24,
	IMG_HIT_24 = 25,
	IMG_HIT_25 = 26,
	IMG_HIT_26 = 27,
	IMG_HIT_27 = 28,
	IMG_HIT_28 = 29,
	IMG_HIT_29 = 30,
	IMG_HIT_30 = 31,
	IMG_HIT_31 = 32,
	IMG_HIT_32 = 33,
	IMG_HIT_33 = 34,
	IMG_HIT_34 = 35,
	IMG_HIT_35 = 36,
	IMG_HIT_36 = 37,
	IMG_HIT_37 = 38,
	IMG_HIT_38 = 39,
	IMG_HIT_39 = 40,
	IMG_HIT_40 = 41,
	IMG_HIT_41 = 42,
	IMG_HIT_42 = 43,
	IMG_HIT_43 = 44,
	IMG_HIT_44 = 45,
	IMG_HIT_45 = 46,
	IMG_HIT_46 = 47,
	IMG_HIT_47 = 48,
	IMG_HIT_48 = 49,
	IMG_HIT_50 = 50,
	IMG_HIT_51 = 51,
	IMG_HIT_52 = 52,
	IMG_HIT_53 = 53,
	IMG_HIT_54 = 54,

	TOTALHITOFF,

	END_SKILLDEF
} SKILLDEF;

//PULSE 총탄이 커지는 최대 비율. enum은 정수만 담을 수 있어 여기서 실수로 만든다.
#define CREWBULLET_PULSEAMP		((float)CREWBULLET_PULSEPERCENT / 100.0f)

#endif
