#pragma once

#ifndef _DEF_TIME_H_
#define _DEF_TIME_H_

typedef enum _timeDef {
	FPS_INIT = 60,
	FPS = FPS_INIT,
	FPS_SKILL = FPS_INIT,
	FPSDOWN_HIT = 10,
	FPSDOWN_CRITICAL = 5,
	FPSDOWN_STUN = 5,
	FPSDOWN_PIERCE = 5,
	FPSDOWN_IGNORE = 5,
	FPSDOWN_EXTRA = 5,

	LOGTIME = FPS * 2,
	AUTOPLAYFRAME = FPS,
	HURRYUPSPEED = FPS_INIT,
	TOUCHCANCELFRAME = FPS * 10,
	MOVEAWAYFRAME = FPS / 2,
	SKILLSELECTFRAME = 3 * FPS,

	PVPQUESTTIME = 8 * 60 * 60,
	MAINQUESTTIME = 24 * 60 * 60 * 2,

	RECOVERYFRAME = FPS,
	POSIONFRAME = FPS * 10,
	HELPANIMATIONTERM = 2,
	IMGTEXTFRAME = FPS * 3,
	BARFRAME = FPS * 3,

	EVENTFRAME_START = FPS,
	EVENTFRAME_FINISH = FPS,

	REGENFRAME = FPS,
	SHOPEVENTTIME = 8 * 60 * 60,
	INFINITETIME = 43200,

	SLOW_START_FRAME = FPS * 3,
	BLIND_START_FRAME = FPS * 3,
	POISON_START_FRAME = FPS * 3,
	STUN_START_FRAME = FPS * 3,
	CURSE_START_FRAME = FPS * 3,
	KNOCKBACK_DELAY = 8,
	KNOCKBACK_START_FRAME = 10 * 2 + KNOCKBACK_DELAY,
	FLAMER_START_FRAME = FPS * 3,
	DEFENSEDOWN_START_FRAME = FPS * 3,
	GOLDDRAIN_START_FRAME = FPS * 3,
	GOLDMOD_START_FRAME = FPS * 3,
	EVASION_START_FRAME = FPS * 3,
} TIMEINFO;

#endif
