#pragma once

#ifndef _DEF_TOUCHKEY_H_
#define _DEF_TOUCHKEY_H_

typedef enum _touchFuncDef {

	BOSSRAID_ROYALFAMILY = 0,	//로얄패밀리

	TOTALBOSSRAID,

	BOSSRAIDSIZE = 10,


	//TOUCH_MODE
	TOUCH_OK = 1,        //어딜누르든지 ok버튼으로, (경고창, 확인창 등)
	TOUCH_TITLE,        //메인화면 터치
	TOUCH_TITLEMENU,	//타이틀메뉴 터치
	TOUCH_TITLE_HELP,    //도움말 터치
	TOUCH_LOAD,            //load된 캐릭터 선택화면
	TOUCH_NEW,            //새로운 캐릭터 선택화면
	TOUCH_YESNO,        //YesNo선택화면
	TOUCH_GAMEMENU,        //게임메뉴창(4방향 및 선택)
	TOUCH_PLAY,
	TOUCH_GIFT,
	TOUCH_GAMEOVER,
	TOUCH_STARTAPP,
	TOUCH_TALKHELP,
	TOUCH_TALK,
	TOUCH_RECOMMEND,

#ifdef GXGPLAYER2
	TOUCH_GXG,
#endif

	//#ifdef EXPVERSION        //무료체험판 TOUCH Ver. 일 경우 사용
	TOUCH_EXP,

	TOUCHBUTTON_1 = 0,
	TOUCHBUTTON_2,
	TOUCHBUTTON_3,
	TOUCHBUTTON_4,
	TOUCHBUTTON_6,
	TOUCHBUTTON_7,
	TOUCHBUTTON_8,
	TOUCHBUTTON_9,
	TOUCHBUTTON_SHOP,
	TOUCHBUTTON_MAP,
	TOUCHBUTTON_CANCEL,
	TOUCHBUTTON_STAR,
	TOUCHBUTTON_0,
	TOUCHBUTTON_POUND,
	TOUCHBUTTON_OK,

	TOTALTOUCHBUTTON,

	HOTKEY_NOTHING = 0,
	HOTKEY_SKILL,
	HOTKEY_ITEM,
	HOTKEY_STATUE,//상을 장착했을 경우f
	HOTKEY_RING,//반지를 장착했을 경우
	HOTKEY_SCREEN,	//스크린샷 아이콘

	TOUCH_FUNC_OPENING = 0,
	TOUCH_FUNC_TITLE,

	TOUCH_FUNC_TITLE_LOGIN_FACEBOOK,
	TOUCH_FUNC_TITLE_LOGIN_GOOGLE,
	TOUCH_FUNC_TITLE_LOGIN_APPLE,
	TOUCH_FUNC_TITLE_LOGIN_GUEST,

	TOUCH_FUNC_TITLE_NEWGAME,

	TOUCH_FUNC_PLAY,//플레이//MENU_PLAY
	TOUCH_FUNC_COLLECTIONS,//컬렉션//MENU_HERO
	TOUCH_FUNC_FRIENDS,////MENU_CREW
	TOUCH_FUNC_SHOP,//상점//MENU_COLLECTIONS
	TOUCH_FUNC_STARSHOP,//스타상점//MENU_SHOP
	TOUCH_FUNC_NEWS,//뉴스
	TOUCH_FUNC_GIFTS,//선물
	TOUCH_FUNC_LEADERBOARD,//
	TOUCH_FUNC_INVITEFRIENDS,//
	TOUCH_FUNC_CALENDAR,//
	TOUCH_FUNC_SETTING,//
	TOUCH_FUNC_LIST,
	TOUCH_FUNC_DAILYQUEST,
	TOUCH_FUNC_EVENT_QUEST,
	TOUCH_FUNC_EVENT_PVP,
	TOUCH_FUNC_EVENT_SHOP,
	TOUCH_FUNC_EVENT_DEBTDISCOUNT,
	TOUCH_FUNC_EVENT_DOUBLE,
	TOUCH_FUNC_EVENT_BOSSRAID,
	TOUCH_FUNC_EVENT_TOUCHGAME,

	TOUCH_FUNC_STAGE_POPUP,

	TOUCH_FUNC_EVENT_BOSSRAID_REWARDINFO,

	TOUCH_FUNC_GAMEMENU = TOUCH_FUNC_EVENT_BOSSRAID_REWARDINFO + BOSSRAIDSIZE,
	TOUCH_FUNC_GAMEMENU_OUT,
	TOUCH_FUNC_BOSSRAID_OUT,

	TOUCH_FUNC_ITEMDETAIL,
	TOUCH_FUNC_EQUIPDETAIL = TOUCH_FUNC_ITEMDETAIL + TOTALINVENTORY,

	TOUCH_FUNC_HOME_LEFT = TOUCH_FUNC_EQUIPDETAIL + TOTALEQUIP,
	TOUCH_FUNC_HOME_RIGHT,

	TOUCH_FUNC_STAGE_LEFT,
	TOUCH_FUNC_STAGE_RIGHT,
	TOUCH_FUNC_STAGEINFO,

	TOUCH_FUNC_BUYHOME,

	TOUCH_FUNC_HOUSE_CREWREWARD,

	TOUCH_FUNC_CREW_DETAIL = TOUCH_FUNC_HOUSE_CREWREWARD + MAXCREW,

	TOUCH_FUNC_CREW_REWARD = TOUCH_FUNC_CREW_DETAIL + TOTAL_CREW,//가챠버튼

	TOUCH_FUNC_OPTION_BGM = TOUCH_FUNC_CREW_REWARD + TOTAL_CREW,
	TOUCH_FUNC_OPTION_SE,
	TOUCH_FUNC_OPTION_VIBRATION,
	TOUCH_FUNC_OPTION_LANGUAGE,
	TOUCH_FUNC_OPTION_NICKNAME,
	TOUCH_FUNC_OPTION_FACEBOOK,
	TOUCH_FUNC_OPTION_GOOGLE,
	TOUCH_FUNC_OPTION_GAMECENTER,
	TOUCH_FUNC_OPTION_GUEST,
	TOUCH_FUNC_OPTION_VOICE,
	TOUCH_FUNC_OPTION_SCREENEFFECT,
	TOUCH_FUNC_OPTION_PUSHALARM,
	TOUCH_FUNC_OPTION_HELP,
	TOUCH_FUNC_OPTION_HELP_MAIL,

	//언어 하나마다 하나씩 쓴다. TOTALLANGUAGE개를 잡아둔다.
	TOUCH_FUNC_OPTION_LANGUAGE_SELECT,
	TOUCH_FUNC_OPTION_LANGUAGE_SELECT_END = TOUCH_FUNC_OPTION_LANGUAGE_SELECT + 11,

	//알림 종류마다 하나씩.
	TOUCH_FUNC_OPTION_PUSHALARM_TYPE,
	TOUCH_FUNC_OPTION_PUSHALARM_TYPE_END = TOUCH_FUNC_OPTION_PUSHALARM_TYPE + 4,

	TOUCH_FUNC_OPTION_ACCOUNT,
	TOUCH_FUNC_OPTION_POLICY,
	TOUCH_FUNC_OPTION_COMMUNITY,

	TOUCH_FUNC_TABMENU1,
	TOUCH_FUNC_TABMENU2,
	TOUCH_FUNC_TABMENU3,
	TOUCH_FUNC_TABMENU4,

	TOUCH_FUNC_TABMENUX_1,
	TOUCH_FUNC_TABMENUX_2,
	TOUCH_FUNC_TABMENUX_3,

	TOUCH_FUNC_EQUIP_ENCHANT,
	TOUCH_FUNC_EQUIP_HAMMER,
	TOUCH_FUNC_EQUIP_NEWITEM,
	TOUCH_FUNC_DISASSEMBLE_NEWITEM,

	TOUCH_FUNC_GAMEMENU_NEWS,
	TOUCH_FUNC_GAMEMENU_RANKING,
	TOUCH_FUNC_GAMEMENU_MAIL,
	TOUCH_FUNC_GAMEMENU_SETTING,

	TOUCH_FUNC_GAMEMENU_NEWS_CLR,//게임메뉴화면에서 클리어키를 눌렀을 때
	TOUCH_FUNC_GAMEMENU_RANKING_CLR,
	TOUCH_FUNC_GAMEMENU_MAIL_CLR,
	TOUCH_FUNC_GAMEMENU_SETTING_CLR,

	TOUCH_FUNC_GAMEMENU_OUTOFGAME,

	TOUCH_FUNC_COLLECTIONS_DETAIL,

	TOUCH_FUNC_COLLECTIONS_ITEMDETAIL = TOUCH_FUNC_COLLECTIONS_DETAIL + TOTAL_COLLECTIONS,
	TOUCH_FUNC_COLLECTIONS_REWARD = TOUCH_FUNC_COLLECTIONS_ITEMDETAIL + COLLECTIONSITEMCNT,

	TOUCH_FUNC_BOXINFO = TOUCH_FUNC_COLLECTIONS_REWARD + TOTAL_COLLECTIONS,

	TOUCH_FUNC_HIT_ATTACK,

	TOUCH_FUNC_HIT = TOUCH_FUNC_HIT_ATTACK + MAXCREW,

	TOUCH_FUNC_ITEM_UPGRADE,
	TOUCH_FUNC_ITEM_HAMMER,
	TOUCH_FUNC_EQUIP_INVENTORY,//그냥 인벤토리

	TOUCH_FUNC_SKILL_UPGRADE = TOUCH_FUNC_EQUIP_INVENTORY + TOTALINVENTORY,//그냥 인벤토리

	TOUCH_FUNC_INGAME_AUTO,
	TOUCH_FUNC_INGAME_AUTOOFF,
	TOUCH_FUNC_INGAME_VOICEOFF,

	TOUCH_FUNC_INGAME_RESULTSKIP_TOP10,
	TOUCH_FUNC_INGAME_RESULTSKIP_MY,
	TOUCH_FUNC_INGAME_OUTGAME,

	TOUCH_FUNC_INGAME_MOVE,

	TOUCH_FUNC_USE_HEART,
	TOUCH_FUNC_ROULETTESTART,
	TOUCH_FUNC_HEARTAMOUNT,
	TOUCH_FUNC_COINAMOUNT,
	TOUCH_FUNC_TARGETENEMY,
	TOUCH_FUNC_TARGETENEMY2,
	TOUCH_FUNC_TARGETENEMY3,
	TOUCH_FUNC_TARGETENEMY4,
	TOUCH_FUNC_TARGETENEMY5,
	TOUCH_FUNC_ATTACK,
	TOUCH_FUNC_MOVE,
	TOUCH_FUNC_JUMP,

	TOUCH_FUNC_HEROCHECK_DIANA,
	TOUCH_FUNC_HEROCHECK_MAXX,

	TOUCH_FUNC_INGAME_CLOSEWINDOW,

	TOUCH_FUNC_TOOLTIP_CLOSE,

	TOUCH_FUNC_CHARINFOPAGE,

	TOUCH_FUNC_DEBUG_RESETGAME,
	TOUCH_FUNC_DEBUG_MAXSTATUS,
	TOUCH_FUNC_DEBUG_ENEMYATTACK,
	TOUCH_FUNC_DEBUG_CHANGEMODE,
	TOUCH_FUNC_DEBUG_STARTFROMONEPLAYER,
	TOUCH_FUNC_DEBUG_CUTOFF,
	TOUCH_FUNC_DEBUG_HEADZOOM,
	TOUCH_FUNC_DEBUG_EFFECTONLYPLAYER,
	TOUCH_FUNC_DEBUG_PLAYERDMGNUMBIG,
	TOUCH_FUNC_DEBUG_GAMESPEED,

	TOUCH_FUNC_CLOSEALERT,

	TOUCH_FUNC_BACKTOSUBREWARD,
	TOUCH_FUNC_OUTOFSUBREWARD,

	TOUCH_FUNC_OUTOFMINIGACHA,

	TOUCH_FUNC_OUTOFBATTLERESULT,
	TOUCH_FUNC_OUTOFRAIDRESULT,

	TOUCH_FUNC_RAID_RANKING1,
	TOUCH_FUNC_RAID_RANKING2,
	TOUCH_FUNC_RAID_RANKING3,

	TOUCH_ALERT_INVENTORYFULL_YES,
	TOUCH_ALERT_INVENTORYFULL_NO,

	TOUCH_ALERT_ITEMSELL,

	TOUCH_ALERT_NO,

	TOUCH_ATTACK_REWARD,
	TOUCH_HIT_REWARD,
	TOUCH_RAID_REWARD,

	TOUCH_FUNC_SKIPDEMO,

	TOUCH_FUNC_GOTODEMO,
	TOUCH_FUNC_GOTOPLAY,
	TOUCH_FUNC_GOTOGACHA,
	TOUCH_FUNC_GOTOBOSSRAID,
	TOUCH_FUNC_GOTOBATTLE,
	TOUCH_FUNC_GOTONEWCARD,
	TOUCH_FUNC_GOTONEXTSTAGE,
	TOUCH_FUNC_GOTOHOUSE,
	TOUCH_FUNC_GOTOSHOP,
	
	TOUCH_FUNC_OUTOFHOUSE,
	TOUCH_FUNC_OUTOFGACHA,
	TOUCH_FUNC_OUTOFNEWCARD,
	TOUCH_FUNC_OUTOFBOSS,

	TOUCH_FUNC_GETREWARDSTART,
	TOUCH_FUNC_NEXTREWARD,

	TOUCH_FUNC_GETDEMOREWARD,

	TOUCH_FUNC_NEWITEM,
	TOUCH_FUNC_NEXTNEWITEM,

	TOUCH_FUNC_NEWDEMOITEMREWARD,

	TOUCH_FUNC_NEWCOLLECTIONREWARDGET,
	TOUCH_FUNC_NEWCARDREWARDGET,

	TOUCH_FUNC_GETGACHACARD,
	TOUCH_FUNC_GETRAIDGOLD,

	TOUCH_FUNC_POPUP_HOWTOGETHEROES,
	TOUCH_FUNC_POPUP_HOWTOGETCREWS,
	TOUCH_FUNC_POPUP_LVUPREWARD,
	TOUCH_FUNC_POPUP_STAGEREWARD,
	TOUCH_FUNC_POPUP_HEROSTAT,
	TOUCH_FUNC_SELECT_HERO = TOUCH_FUNC_POPUP_HEROSTAT + TOTALCHAR,
	TOUCH_FUNC_POPUP_CREWUPGRADE = TOUCH_FUNC_SELECT_HERO + TOTALCHAR,
	TOUCH_FUNC_POPUP_CREWLIST,
	TOUCH_FUNC_POPUP_CASTLEMENU,
	TOUCH_FUNC_POPUP_CLOSE,

	TOUCH_FUNC_JOKBO,
	TOUCH_FUNC_GETCREW,
	TOUCH_FUNC_STAGEREWARD,
	TOUCH_FUNC_STAGEFAILED,
	TOUCH_FUNC_NEWSTAGE,

	TOUCH_FUNC_SHOP_BUYBOX1,
	TOUCH_FUNC_SHOP_BUYBOX2,
	TOUCH_FUNC_SHOP_BUYBOX3,

	TOUCH_FUNC_HOTKEYPRESS1,
	TOUCH_FUNC_HOTKEYPRESS2,
	TOUCH_FUNC_HOTKEYPRESS3,

	TOUCH_FUNC_MENUCUR_CREW1,
	TOUCH_FUNC_MENUCUR_CREW2,
	TOUCH_FUNC_MENUCUR_CREW3,
	TOUCH_FUNC_MENUCUR_CREW4,
	TOUCH_FUNC_MENUCUR_CREW5,
	TOUCH_FUNC_MENUCUR_CREW6,

	TOUCH_FUNC_MENUX_1,
	TOUCH_FUNC_MENUX_2,
	TOUCH_FUNC_MENUX_3,
	TOUCH_FUNC_MENUX_4,
	TOUCH_FUNC_MENUX_5,
	TOUCH_FUNC_MENUX_6,

	TOUCH_FUNC_MENUCUR_CREWSET,

	TOUCH_FUNC_COLLECTIONS_EQUIP = TOUCH_FUNC_MENUCUR_CREWSET + TOTAL_CREW,

	TOUCH_FUNC_BATTLE_TARGET = TOUCH_FUNC_COLLECTIONS_EQUIP + TOTALEQUIP,
	TOUCH_FUNC_RAID_TARGET = TOUCH_FUNC_BATTLE_TARGET + MAXCREW,

	TOUCH_FUNC_EQUIPALL = TOUCH_FUNC_RAID_TARGET + TOTALRAIDBOX,

	//동료 상세보기의 업그레이드 버튼.
	//기존 값이 하나도 밀리지 않도록 맨 끝에 붙인다.
	TOUCH_FUNC_CREW_LEVELUP = TOUCH_FUNC_EQUIPALL + TOTAL_COLLECTIONS,

	TOTALTOUCHCNT = TOUCH_FUNC_CREW_LEVELUP + 1,

	END_TOUCHFUNCDEF
} TOUCHFUNCDEF;

typedef enum _swipeFuncDef {
	SWIPE_FUNC_HOME = 0,
	SWIPE_FUNC_MAINMENU,

	SWIPE_FUNC_CREW,
	SWIPE_FUNC_EQUIP_CHAR,
	SWIPE_FUNC_EQUIP_INVENTORY,
	SWIPE_FUNC_EQUIP_ENCHANT_INVENTORY,
	SWIPE_FUNC_EQUIP_RECIPE_INVENTORY,
	SWIPE_FUNC_EQUIP_SOCKET_INVENTORY,

	TOTALSWIPECNT,

	RAPIDSWIPE_NULL = 0,
	RAPIDSWIPE_HORIZONTAL,
	RAPIDSWIPE_VERTICAL_UP,
	RAPIDSWIPE_VERTICAL_DOWN,
	RAPIDSWIPE_BOTH,

	RAPIDSWIPE_DX = 16 * _2X,
	RAPIDSWIPE_DY = 0 * _2X,

	END_SWIPEFUNCDEF
} SWIPEFUNCDEF;



typedef enum _voiceDef {
	VOICE_NOVOICE = 0,
	VOICE_BIGMOUTH,
	VOICE_SKILLANNOUNCER,
	VOICE_SOLDIER,
	VOICE_TITLE,

	TOTALVOICETYPE,

} VOICEDEF;

typedef enum _touchKeyDef {
	//키버튼 매핑
	AVK_0 = 1,// = MC_KEY_0,
	AVK_1,// = MC_KEY_1,
	AVK_2,// = MC_KEY_2,
	AVK_3,// = MC_KEY_3,
	AVK_4,// = MC_KEY_4,
	AVK_5,// = MC_KEY_5,
	AVK_6,// = MC_KEY_6,
	AVK_7,// = MC_KEY_7,
	AVK_8,// = MC_KEY_8,
	AVK_9,// = MC_KEY_9,
	AVK_STAR,// = MC_KEY_ASTERISK,
	AVK_POUND,// = MC_KEY_POUND,
	AVK_CLR,// = MC_KEY_CLEAR,
	AVK_SEND,// = MC_KEY_SEND,
	AVK_SELECT,// = MC_KEY_SELECT,
	AVK_SOFT1,// = MC_KEY_SOFT2,
	AVK_DOWN,// = MC_KEY_DOWN,
	AVK_UP,// = MC_KEY_UP,
	AVK_LEFT,// = MC_KEY_LEFT,
	AVK_RIGHT,// = MC_KEY_RIGHT,
	AVK_MENU,// = MC_KEY_SOFT1,
	AVK_SIDEUP,// = MC_KEY_SIDE_UP,
	AVK_SIDEDOWN,// = MC_KEY_SIDE_DOWN,

	AVK_LOGIN_FACEBOOK,
	AVK_LOGIN_GOOGLE,
	AVK_LOGIN_APPLE,
	AVK_LOGIN_GUEST,

	AVK_NEWGAME,
	AVK_MAXGAME,
	AVK_ENEMYATTACK,

	AVK_PLAY,
	AVK_COLLECTIONS,
	AVK_FRIENDS,
	AVK_SHOP,
	AVK_STARSHOP,
	AVK_NEWS,
	AVK_GIFTS,
	AVK_LEADERBOARD,
	AVK_INVITEFRIENDS,
	AVK_CALENDAR,
	AVK_SETTING,
	AVK_LIST,
	AVK_DAILYQUEST,
	AVK_EVENT_QUEST,
	AVK_EVENT_PVP,
	AVK_EVENT_SHOP,
	AVK_EVENT_DEBTDISCOUNT,
	AVK_EVENT_DOUBLE,
	AVK_EVENT_BOSSRAID,
	AVK_EVENT_TOUCHGAME,

	AVK_STAGE_POPUP,

	AVK_COLLECTIONS_DETAIL,

	AVK_COLLECTIONS_ITEMDETAIL = AVK_COLLECTIONS_DETAIL + TOTAL_COLLECTIONS,
	AVK_COLLECTIONS_REWARD = AVK_COLLECTIONS_ITEMDETAIL + COLLECTIONSITEMCNT,

	AVK_BOXINFO = AVK_COLLECTIONS_REWARD + TOTAL_COLLECTIONS,

	AVK_HIT_ATTACK,

	AVK_ATTACK_REWARD = AVK_HIT_ATTACK + MAXCREW,

	AVK_HIT_REWARD,
	AVK_RAID_REWARD,

	AVK_DEMOSKIP,

	AVK_GOTODEMO,
	AVK_GOTOPLAY,
	AVK_GOTOGACHA,//뽑기화면으로 이동 
	AVK_GOTOBOSSRAID,
	AVK_GOTOBATTLE,
	AVK_GOTONEWCARD,
	AVK_GOTONEXTSTAGE,
	AVK_GOTOHOUSE,
	AVK_GOTOSHOP,
	AVK_OUTOFHOUSE,
	AVK_OUTOFNEWCARD,
	AVK_OUTOFBOSS,
	AVK_OUTOFBATTLERESLUT,
	AVK_OUTOFRAIDRESULT,

	AVK_GETREWARDSTART,
	AVK_NEXTREWARD,

	AVK_NEWDEMOITEMREWARD,
	AVK_GETDEMOREWARD,

	AVK_NEWCOLLECTIONREWARDGET,
	AVK_NEWCARDREWARDGET,

	AVK_GETGACHACARD,
	AVK_GETRAIDGOLD,

	AVK_POPUP_HOWTOGETHEROES,
	AVK_POPUP_HOWTOGETCREWS,
	AVK_POPUP_LVUPREWARD,
	AVK_POPUP_STAGEREWARD,
	AVK_POPUP_HEROSTAT,
	AVK_SELECT_HERO = AVK_POPUP_HEROSTAT + TOTALCHAR,
	AVK_POPUP_CREWUPGRADE = AVK_SELECT_HERO + TOTALCHAR,
	AVK_POPUP_CREWLIST,
	AVK_POPUP_CASTLEMENU,
	AVK_POPUP_CLOSE,

	AVK_JOKBO,
	AVK_GETCREW,
	AVK_STAGEREWARD,
	AVK_STAGEFAILED,
	AVK_NEWSTAGE,

	AVK_SHOP_BUYBOX1,
	AVK_SHOP_BUYBOX2,
	AVK_SHOP_BUYBOX3,

	AVK_HOTKEYPRESS1,
	AVK_HOTKEYPRESS2,
	AVK_HOTKEYPRESS3,

	AVK_MENUCUR_CREW1,
	AVK_MENUCUR_CREW2,
	AVK_MENUCUR_CREW3,
	AVK_MENUCUR_CREW4,
	AVK_MENUCUR_CREW5,
	AVK_MENUCUR_CREW6,

	AVK_MENUX_1,
	AVK_MENUX_2,
	AVK_MENUX_3,
	AVK_MENUX_4,
	AVK_MENUX_5,
	AVK_MENUX_6,

	AVK_MENUCUR_CREWSET,

	AVK_COLLECTIONS_EQUIP = AVK_MENUCUR_CREWSET + TOTAL_CREW,

	AVK_BATTLE_TARGET = AVK_COLLECTIONS_EQUIP + TOTALEQUIP,
	AVK_RAID_TARGET = AVK_BATTLE_TARGET + MAXCREW,

	AVK_GETITEMSUBREWARD = AVK_RAID_TARGET + TOTALRAIDBOX,

	AVK_GETITEMREWARD,

	AVK_GAMEMENU,

	AVK_EQUIP_ENCHANT_SELECT,
	AVK_EQUIP_HAMMER_SELECT,
	AVK_EQUIP_NEWITEM,
	AVK_DISASSEMBLE_NEWITEM,

	AVK_ITEMDETAIL,
	AVK_EQUIPDETAIL = AVK_ITEMDETAIL + TOTALINVENTORY,

	AVK_OPTION_BGM = AVK_EQUIPDETAIL + TOTALEQUIP,
	AVK_OPTION_SE,
	AVK_OPTION_VIBRATION,
	AVK_OPTION_LANGUAGE,
	AVK_OPTION_NICKNAME,
	AVK_OPTION_FACEBOOK,
	AVK_OPTION_GOOGLE,
	AVK_OPTION_GAMECENTER,
	AVK_OPTION_GUEST,
	AVK_OPTION_VOICE,

	AVK_OPTION_EFFECT,
	AVK_OPTION_PUSHALARM,
	AVK_OPTION_ACCOUNT,
	AVK_OPTION_POLICY,
	AVK_OPTION_HELP,
	AVK_OPTION_HELP_MAIL,

	AVK_OPTION_LANGUAGE_SELECT,
	AVK_OPTION_LANGUAGE_SELECT_END = AVK_OPTION_LANGUAGE_SELECT + 11,

	AVK_OPTION_PUSHALARM_TYPE,
	AVK_OPTION_PUSHALARM_TYPE_END = AVK_OPTION_PUSHALARM_TYPE + 4,

	AVK_OPTION_COMMNUNITY,

	AVK_GAMEMENU_NEWS,
	AVK_GAMEMENU_RANKING,
	AVK_GAMEMENU_MAIL,
	AVK_GAMEMENU_SETTING,

	AVK_GAMEMENU_NEWS_CLR,
	AVK_GAMEMENU_RANKING_CLR,
	AVK_GAMEMENU_MAIL_CLR,
	AVK_GAMEMENU_SETTTING_CLR,

	AVK_GAMEMENU_OUTOFGAME,

	AVK_TABMENU1,
	AVK_TABMENU2,
	AVK_TABMENU3,
	AVK_TABMENU4,

	AVK_TABMENUX_1,
	AVK_TABMENUX_2,
	AVK_TABMENUX_3,

	AVK_BOSSRAID_REWARDINFO,
	AVK_BOSSRAIDOUT = AVK_BOSSRAID_REWARDINFO + BOSSRAIDSIZE,

	AVK_BOSS,
	AVK_RESURRECTION,
	AVK_AUTOOFF,
	AVK_AUTO,
	AVK_HEART,
	AVK_ROULETTESTART,
	AVK_HEARTAMOUNT,
	AVK_COINAMOUNT,
	AVK_TARGETENEMY,
	AVK_TARGETENEMY2,
	AVK_TARGETENEMY3,
	AVK_TARGETENEMY4,
	AVK_TARGETENEMY5,
	AVK_ATTACK,
	AVK_MOVE,
	AVK_JUMP,

	AVK_HEROCHECK_DIANA,
	AVK_HEROCHECK_MAXX,

	AVK_HOME_LEFT,
	AVK_HOME_RIGHT,
	AVK_STAGE_LEFT,
	AVK_STAGE_RIGHT,
	AVK_STAGEINFO,
	AVK_BUYHOME,
	AVK_CREW_DETAIL,
	AVK_CREW_REWARD = AVK_CREW_DETAIL + TOTAL_CREW,
	AVK_HERO = AVK_CREW_REWARD + TOTAL_CREW,
	AVK_ITEMEQUIP,
	AVK_ERASESOCKET,
	AVK_EQUIPSLOT,
	AVK_EQUIP_INVENTORY = AVK_EQUIPSLOT + TOTALEQUIP,//그냥 인벤토리
	AVK_SELLITEM = AVK_EQUIP_INVENTORY + TOTALINVENTORY,
	AVK_ENCHANTSLOT,

	AVK_UPGRADE,
	AVK_HAMMER,
	AVK_INVENTORY_SELECTITEM,
	AVK_SKILLUPGRADE = AVK_INVENTORY_SELECTITEM + TOTALINVENTORY,

	AVK_BOXOPEN,
	AVK_OPTIONOPEN,
	AVK_SKILLMENUHIDDEN,
	AVK_SKILLMENUOPEN,

	//동료 상세보기의 업그레이드
	AVK_CREW_LEVELUP,

	TOTALAVK,

	MAXKEYPRESSED = 10,

	ATTACKMOVESEPFRAME = 5,
} TOUCHKEYDEF;
#endif
