#pragma once

#ifndef _DEF_UI_H_
#define _DEF_UI_H_

typedef enum _uiDef {
	FRAME_TALK = 0,
	FRAME_NAME,
	FRAME_INFO,
	FRAME_EDGE,
	FRAME_NONE,

	FRAME_NORMAL = 0,
	FRAME_MONSTER,
	FRAME_MENUWIN,//메뉴�?처음
	FRAME_MENUWIN_QUICK,//메뉴�??�단???�아?�템???�는경우
	FRAME_MENUWIN_INFO,//메뉴�?중간??막�?바로 가�?막는 경우
	FRAME_BUTTON,//?�자?�기
	FRAME_CHOICEBUTTON,//?�택버튼
	FRAME_CHOICEBUTTON2,//?�택버튼 ?��???
	FRAME_CHOICEBUTTON_BEIGE,//브라???�자?�기
	FRAME_TALKWIN,//?�?�신
	FRAME_SHOPBALLOON,//?�점?�에??
	FRAME_ANIINFO,//?�니메이?�으�?커�???�?
	FRAME_MENUDAILY,
	FRAME_GAMEOVER,
	FRAME_NOFRAME,
	FRAME_GREEN,//초록??
	FRAME_RED,//빨간??
	FRAME_BLUE,//?�늘??
	FRAME_GREY,//?�색
	FRAME_GNB,//?�반?�인 ?��???
	FRAME_GREEN_OPTION,
	FRAME_RED_OPTION,
	FRAME_BLUE_OPTION,
	FRAME_GREY_OPTION,
	FRAME_GREEN_STAGE,
	FRAME_GREY_STAGE,
	FRAME_WHITEROUND,

	//?�모 관??
	TEXTLINEPERPAGE = 3,

	INFOTYPE_GETITEM = 0,
	INFOTYPE_GIVEITEM,
	INFOTYPE_QUEST,
	INFOTYPE_CLEARQUEST,
	INFOTYPE_FAILQUEST,
	INFOTYPE_GETITEMSTATUE,


	BAR_GOLD = 1,
	BAR_CROWN,
	BAR_BOX,
	BAR_PLAYERHP,
	BAR_ENEMYHP = BAR_PLAYERHP + MAXPLAYER,
	BAR_COIN = BAR_ENEMYHP + MAXENEMY,
	BAR_ITEM,
	BAR_CASTLE,
	BAR_CREW,
	BAR_HEART,
	BAR_HEARTBET,//?�트베팅 버튼
	BAR_BATTLECOIN,
	BAR_HAMMER,
	BAR_SHIELD,
	BAR_MEDAL,
	BAR_INVENTORY,
	BAR_SKILL = BAR_INVENTORY + TOTALCHAR,
	BAR_ENEMYUSER = BAR_SKILL + TOTALCHAR,//?��?�??��?
	BAR_ENEMYUSER_BOX,//박스?�서 ?�?�나?�는 ?��?�??��?
	BAR_MAINSHOP,//메인??
	BAR_DAILYQUEST,//?�일?�스??
	BAR_CREWUPGRADE,//?�류(?�기???�료?�을 ?�그?�이???�주?�곳)
	BAR_EQUIP,//컬렉???�어로별 ?�비, ?�킬, 별상??
	BAR_FRIENDS,//친구
	BAR_QUEST,
	BAR_NPC,
	BAR_RAIDGOLD,//
	BAR_RAIDCOIN,//배�??�서 ?�일 ?�번???�턴 + ?�턴) ?�득??
	BAR_BOSSHP,//보스 HP
	BAR_HITCOUNT,
	BAR_COMBATPOWER,
	BAR_COMBATPOWERALL,
	BAR_STAR,
	BAR_STAGEPROGRESS,
	BAR_REMAINEDTURN,
	BAR_DAY,              // Day ?�시�?
	BAR_WAVE,             // Life ?�시�?
	BAR_ROULETTE,//룰렛
	BAR_PLAY,//?�레??버튼
	BAR_JOYSTICK,//?�직임 컨트롤러
	BAR_JUMP,//?�프버튼

	TOTAL_BAR,

	PLAYERHPBARCOLOR = COLOR_REALGREEN,
	ENEMYHPBARCOLOR = 0xFF0000,

	ROUNDBAR_BIG = 0,
	ROUNDBAR_SMALL,

	BARCOLOR_RED = 0,
	BARCOLOR_YELLOW,
	BARCOLOR_BLUE,
	BARCOLOR_GREEN,
	BARCOLOR_PURPLE,

	//menuResult
	RESULT_NOGOLD = 1,	//골드가 부족합?�다.
	RESULT_INVENTORYFULL,//?�벤?�리가 가??찼습?�다.
	RESULT_NOSOCKET,	//?�켓???�는 ?�비?�니??
	RESULT_CANNOTSELLITEM,	//?�매?????�는 ?�이?�입?�다.
	RESULT_ITEMLIMIT,//?�당 ?�이?�을 ?�이???��??????�습?�다.
	RESULT_NOORE,	//?�료가 부족합?�다.
	RESULT_NOMOREENCHANT,	//?�이??강화?�실 ???�습?�다.
	RESULT_NOENCHANTITEM,//강화?????�는 ?�이?�이 ?�습?�다.
	RESULT_NORECIPE,	//?�작가?�한 조합?��? 가지�??��? ?�습?�다.
	RESULT_NOGEM,
	RESULT_NOGEMITEM,//보석???�착?????�는 ?�비가 ?�습?�다.
	RESULT_BROKENITEM,	//부?�진 ?�이?��? 강화?�실 ???�습?�다.
	RESULT_ENCHANTSUCCESS,	//강화???�공?��??�니??
	RESULT_RECIPESUCCESS,	//?�로???�이?�이 ?�성?�었?�니??
	RESULT_SOCKETSUCCESS,	//보석 ?�착???�공?��??�니??
	RESULT_NOSTONE,
	RESULT_ENCHANTFAILURE,
	RESULT_ENCHANTFAILURE2,

	POPUPTYPE_COLLECTIONS = 0,
	POPUPTYPE_BOXINFO,
	POPUPTYPE_BOXREWARD,
	POPUPTYPE_QUESTINFO,
	POPUPTYPE_PVPQUESTINFO,
	POPUPTYPE_SHOPINFO,
	POPUPTYPE_DAILYQUEST,
	POPUPTYPE_EVENTSHOP,
	POPUPTYPE_NEWS,
	POPUPTYPE_CALENDAR,
	POPUPTYPE_CREWUPGRADE,
	POPUPTYPE_CREWLIST,
	POPUPTYPE_CASTLEMENU,
	POPUPTYPE_STAGE,
	POPUPTYPE_BOSSRAID,
	POPUPTYPE_JOKBO,
	POPUPTYPE_DEPTDISCOUNT,
	POPUPTYPE_DOUBLE,
	POPUPTYPE_ITEMCOMPARE,
	POPUPTYPE_ITEMDETAIL,
	POPUPTYPE_LEVELUP,
	POPUPTYPE_HEROSTAT,
	POPUPTYPE_FRIENDS,
	POPUPTYPE_OPTION,
	POPUPTYPE_GIFT,
	POPUPTYPE_READERBOARD,
	POPUPTYPE_ENEMYUSER,
	POPUPTYPE_GAMEOVER,
	POPUPTYPE_HOWTOGETHEROES,
	POPUPTYPE_HOWTOGETCREWS,

	TOTALPOPUPTYPE,

	TOTALPOPUPSTORE = 5,

	MAXPOPUP = 10,

	INVEN_HCNT = 4,
	INVEN_HCNT_2X = 5,//?�벤?�리 가�?몇개?��?
	INVEN_VCNT_MIN = 5,
	INVEN_VCNT_MIN_2X = 4,

	INVEN_ICON_SIZE_2X = 52 * _2X,
	INVEN_ICON_HGAP_2X = 10 * _2X,
	INVEN_ICON_VGAP_2X = 8 * _2X,

	INVEN_ICON_SIZE = 116,
	INVEN_ICON_HGAP = 8,
	INVEN_ICON_VGAP = 24,
	
	INVENTORY_X = 16,
	INVENTORY_GAP_X = 148,
	INVENTORY_GAP_Y = 180,

	CREW_GAP_Y = 208,
	CASTLE_GAP_Y = 160,

	BUYBUTTON_X = 84 * _2X,
	BUYBUTTON_Y = 31 * _2X,
	BUYSMALLBUTTON_X = 64 * _2X,
	BUYSMALLBUTTON_Y = 31 * _2X,

	OPTIONBUTTONSIZE_X = 84 * _2X,
	OPTIONBUTTONSIZE_Y = 31 * _2X,

	CREWUPGRADEBUTTONSIZE_X = 84 * _2X,
	CREWUPGRADEBUTTONSIZE_Y = 31 * _2X,

	CARDSIZE_X = 242,
	CARDSIZE_Y = 340,

	ITEMCARDSIZE_X = 76 * _2X,
	ITEMCARDSIZE_Y = 80 * _2X,

	COLLECTIONCARDSIZE_X = 102 * _2X,
	COLLECTIONCARDSIZE_Y = 102 * _2X,

	MAINMENU_X = 48 * _2X,
	MAINMENU_Y = 48 * _2X,

	HEROBUTTON_X = 36 * _2X,
	HEROBUTTON_Y = 36 * _2X,

	COLLECTIONMENU_X = 36 * _2X,
	COLLECTIONMENU_Y = 36 * _2X,

	REWARDCARDSIZE_X = 240,
	REWARDCARDSIZE_Y = 332,

	CREWLISTSIZE_Y = 152 * _2X,

	MEDALREWARDSIZESMALL_X = 208 * _2X,
	MEDALREWARDSIZESMALL_Y = 40 * _2X,

	DIORAMASIZE_X = 512 * _2X,
	DIORAMASIZE_Y = 512 * _2X,
	DIORAMA_GAPY = 80 * _2X,
	DIORAMA_BATTLE_GAPY = -128 * _2X,
	DIORAMA_NAMETAG_GAPY = 100 * _2X,

	ITEMINVENTORY_XCOUNT = 4,

	COLLECTION_XCOUNT = 3,
	COLLECTION_YGAP = 88 * _2X,

	REWARDITEM_XCOUNT = 4,

	ARENASKILLSLOTCNT = 2,

	ARENASKILLSLOTSIZE_X = 120 * _2X,
	ARENASKILLSLOTSIZE_Y = 120 * _2X,

	BATTLETEXTGAP = -REWARDCARDSIZE_Y - 24 * _2X,//8 * _2X,

	BATTLEREWARDSTART_Y = -222 * _2X,
	BATTLEREWARDGAP = 60 * _2X,
	BATTLEREWARDBOX_Y = 46 * _2X,

	ROULETTECARDSIZE_X = (40 + 4 * 2) * _2X,
	ROULETTECARDSIZE_Y = (48 + 4 * 2) * _2X,
	//ROULETTECARDSIZE_X = (64 + 4 * 2) * _2X,
	//ROULETTECARDSIZE_Y = (96 + 4 * 2) * _2X,

	CHARCARD_WIDTH = 128 * _2X,
	CHARCARD_HEIGHT = 192 * _2X,

	SKILLCARDSIZE_X = ITEMICONSIZE * 2 + 16 * _2X,
	SKILLCARDSIZE_Y = ITEMICONSIZE * 2 + 16 * _2X,

	POPUPWINDOWSIZE_X = 320 * _2X,
	POPUPWINDOWSIZE_Y = 420 * _2X,

	ITEMDETAILWINDOWSIZE_X = 640 - 32,
	ITEMDETAILWINDOWSIZE_Y = 620,

	POPUPSTORE_Y = 64 * _2X,

	ITEMCARD_WIDTH = 108 * _2X,
	ITEMCARD_HEIGHT = 128 * _2X,

	SHOPMENUCARD_WIDTH = 94 * _2X,
	SHOPMENUCARD_HEIGHT = 88 * _2X,

	LOGWIDTH = 128 * _2X,
	LOGHEIGHT = 20 * _2X,

	COLLECTIONS_X = ROULETTECARDSIZE_X,
	COLLECTIONS_Y = ITEMCARDSIZE_Y,
} UIDEF;

#endif
