#pragma once

//환경설정 하위 창에서 쓰는 개수. 값이 정해진 상수라 아래 큰 enum 안에
//끼우면 그 자리부터 뒤따르는 번호가 전부 다시 매겨진다(POPUPTYPE 뒤에
//FRAME_ 들이 같은 enum으로 이어져 있어서 실제로 충돌했다).
enum {
	//알림 설정에 들어가는 줄 수. 0번은 전체 스위치다.
	TOTAL_PUSHALARM = 5,

	//언어 개수. 국기 표와 이름 표의 길이다.
	TOTALLANGUAGE = 12,
};

#ifndef _DEF_UI_H_
#define _DEF_UI_H_

typedef enum _uiDef {
	FRAME_TALK = 0,
	FRAME_NAME,
	FRAME_INFO,
	FRAME_EDGE,
	FRAME_NONE,

	FRAME_NORMAL = 0,
	FRAME_MONSTER,
	FRAME_MENUWIN,//메뉴창 처음
	FRAME_MENUWIN_QUICK,//메뉴창 하단에 퀵아이템이 있는경우
	FRAME_MENUWIN_INFO,//메뉴창 중간에 막대바로 가로 막는 경우
	FRAME_BUTTON,//판자때기
	FRAME_CHOICEBUTTON,//선택버튼
	FRAME_CHOICEBUTTON2,//선택버튼 옅은색
	FRAME_CHOICEBUTTON_BEIGE,//브라운 판자때기
	FRAME_TALKWIN,//대화신
	FRAME_SHOPBALLOON,//상점등에서
	FRAME_ANIINFO,//애니메이션으로 커지는 창
	FRAME_MENUDAILY,
	FRAME_GAMEOVER,
	FRAME_NOFRAME,
	FRAME_GREEN,//초록색
	FRAME_RED,//빨간색
	FRAME_BLUE,//하늘색
	FRAME_GREY,//회색
	FRAME_GNB,//일반적인 노멀한 
	FRAME_GREEN_OPTION,
	FRAME_RED_OPTION,
	FRAME_BLUE_OPTION,
	FRAME_GREY_OPTION,
	FRAME_GREEN_STAGE,
	FRAME_GREY_STAGE,
	FRAME_WHITEROUND,

	//데모 관련
	TEXTLINEPERPAGE = 3,

	INFOTYPE_GETITEM = 0,
	INFOTYPE_GIVEITEM,
	INFOTYPE_QUEST,
	INFOTYPE_CLEARQUEST,
	INFOTYPE_FAILQUEST,
	INFOTYPE_GETITEMSTATUE,


	BAR_GOLD = 1,
	BAR_CROWN,
	BAR_BOX,
	BAR_PLAYERHP,
	BAR_ENEMYHP = BAR_PLAYERHP + MAXPLAYER,
	BAR_COIN = BAR_ENEMYHP + MAXENEMY,
	BAR_ITEM,
	BAR_CASTLE,
	BAR_CREW,
	BAR_HEART,
	BAR_HEARTBET,//하트베팅 버튼
	BAR_BATTLECOIN,
	BAR_HAMMER,
	BAR_SHIELD,
	BAR_MEDAL,
	BAR_INVENTORY,
	BAR_SKILL = BAR_INVENTORY + TOTALCHAR,
	BAR_ENEMYUSER = BAR_SKILL + TOTALCHAR,//상대방 유저
	BAR_ENEMYUSER_BOX,//박스에서 튀어나오는 상대방 유저
	BAR_MAINSHOP,//메인샵
	BAR_DAILYQUEST,//일일퀘스트
	BAR_CREWUPGRADE,//크류(여기는 동료들을 업그레이드 해주는곳)
	BAR_EQUIP,//컬렉션(히어로별 장비, 스킬, 별상점)
	BAR_FRIENDS,//친구
	BAR_QUEST,
	BAR_NPC,
	BAR_RAIDGOLD,//
	BAR_RAIDCOIN,//배틀에서 쓰일 이번턴(내턴 + 적턴) 획득량
	BAR_BOSSHP,//보스 HP
	BAR_HITCOUNT,
	BAR_COMBATPOWER,
	BAR_COMBATPOWERALL,
	BAR_STAR,
	BAR_STAGEPROGRESS,
	BAR_REMAINEDTURN,
	BAR_DAY,              // Day 표시만
	BAR_WAVE,             // Life 표시만
	BAR_ROULETTE,//룰렛
	BAR_PLAY,//플레이 버튼
	BAR_JOYSTICK,//움직임 컨트롤러
	BAR_JUMP,//점프버튼

	TOTAL_BAR,

	PLAYERHPBARCOLOR = COLOR_REALGREEN,
	ENEMYHPBARCOLOR = 0xFF0000,

	ROUNDBAR_BIG = 0,
	ROUNDBAR_SMALL,

	BARCOLOR_RED = 0,
	BARCOLOR_YELLOW,
	BARCOLOR_BLUE,
	BARCOLOR_GREEN,
	BARCOLOR_PURPLE,

	//menuResult
	RESULT_NOGOLD = 1,	//골드가 부족합니다.
	RESULT_INVENTORYFULL,//인벤토리가 가득 찼습니다.
	RESULT_NOSOCKET,	//소켓이 없는 장비입니다.
	RESULT_CANNOTSELLITEM,	//판매할 수 없는 아이템입니다.
	RESULT_ITEMLIMIT,//해당 아이템을 더이상 소지할 수 없습니다.
	RESULT_NOORE,	//재료가 부족합니다.
	RESULT_NOMOREENCHANT,	//더이상 강화하실 수 없습니다.
	RESULT_NOENCHANTITEM,//강화할 수 있는 아이템이 없습니다.
	RESULT_NORECIPE,	//제작가능한 조합서를 가지고 있지 않습니다.
	RESULT_NOGEM,
	RESULT_NOGEMITEM,//보석을 장착할 수 있는 장비가 없습니다.
	RESULT_BROKENITEM,	//부서진 아이템은 강화하실 수 없습니다.
	RESULT_ENCHANTSUCCESS,	//강화에 성공하였습니다.
	RESULT_RECIPESUCCESS,	//새로운 아이템이 생성되었습니다.
	RESULT_SOCKETSUCCESS,	//보석 장착에 성공하였습니다.
	RESULT_NOSTONE,
	RESULT_ENCHANTFAILURE,
	RESULT_ENCHANTFAILURE2,

	POPUPTYPE_COLLECTIONS = 0,
	POPUPTYPE_BOXINFO,
	POPUPTYPE_BOXREWARD,
	POPUPTYPE_QUESTINFO,
	POPUPTYPE_PVPQUESTINFO,
	POPUPTYPE_SHOPINFO,
	POPUPTYPE_DAILYQUEST,
	POPUPTYPE_EVENTSHOP,
	POPUPTYPE_NEWS,
	POPUPTYPE_CALENDAR,
	POPUPTYPE_CREWUPGRADE,
	POPUPTYPE_CREWLIST,
	POPUPTYPE_CASTLEMENU,
	POPUPTYPE_STAGE,
	POPUPTYPE_BOSSRAID,
	POPUPTYPE_JOKBO,
	POPUPTYPE_DEPTDISCOUNT,
	POPUPTYPE_DOUBLE,
	POPUPTYPE_ITEMCOMPARE,
	POPUPTYPE_ITEMDETAIL,
	POPUPTYPE_LEVELUP,
	POPUPTYPE_HEROSTAT,
	POPUPTYPE_FRIENDS,
	POPUPTYPE_OPTION,
	POPUPTYPE_GIFT,
	POPUPTYPE_READERBOARD,
	POPUPTYPE_ENEMYUSER,
	POPUPTYPE_GAMEOVER,
	POPUPTYPE_HOWTOGETHEROES,
	POPUPTYPE_HOWTOGETCREWS,

	//환경설정에서 갈라져 나오는 창들
	POPUPTYPE_OPTION_LANGUAGE,
	POPUPTYPE_OPTION_PUSHALARM,
	POPUPTYPE_OPTION_HELP,
	POPUPTYPE_IAP_CONFIRM,
	POPUPTYPE_GACHA_RATES,

	TOTALPOPUPTYPE,

	TOTALPOPUPSTORE = 5,

	MAXPOPUP = 10,

	INVEN_HCNT = 4,
	INVEN_HCNT_2X = 5,//인벤토리 가로 몇개인가
	INVEN_VCNT_MIN = 5,
	INVEN_VCNT_MIN_2X = 4,

	INVEN_ICON_SIZE_2X = 52 * _2X,
	INVEN_ICON_HGAP_2X = 10 * _2X,
	INVEN_ICON_VGAP_2X = 8 * _2X,

	INVEN_ICON_SIZE = 116,
	INVEN_ICON_HGAP = 8,
	INVEN_ICON_VGAP = 24,
	
	INVENTORY_X = 16,
	INVENTORY_GAP_X = 148,
	INVENTORY_GAP_Y = 180,

	CREW_GAP_Y = 208,
	CASTLE_GAP_Y = 160,

	BUYBUTTON_X = 84 * _2X,
	BUYBUTTON_Y = 31 * _2X,
	BUYSMALLBUTTON_X = 64 * _2X,
	BUYSMALLBUTTON_Y = 31 * _2X,

	OPTIONBUTTONSIZE_X = 84 * _2X,
	OPTIONBUTTONSIZE_Y = 31 * _2X,

	CREWUPGRADEBUTTONSIZE_X = 84 * _2X,
	CREWUPGRADEBUTTONSIZE_Y = 31 * _2X,

	CARDSIZE_X = 242,
	CARDSIZE_Y = 340,

	ITEMCARDSIZE_X = 76 * _2X,
	ITEMCARDSIZE_Y = 80 * _2X,

	COLLECTIONCARDSIZE_X = 102 * _2X,
	COLLECTIONCARDSIZE_Y = 102 * _2X,

	MAINMENU_X = 48 * _2X,
	MAINMENU_Y = 48 * _2X,

	HEROBUTTON_X = 36 * _2X,
	HEROBUTTON_Y = 36 * _2X,

	COLLECTIONMENU_X = 36 * _2X,
	COLLECTIONMENU_Y = 36 * _2X,

	REWARDCARDSIZE_X = 240,
	REWARDCARDSIZE_Y = 332,

	CREWLISTSIZE_Y = 152 * _2X,

	MEDALREWARDSIZESMALL_X = 208 * _2X,
	MEDALREWARDSIZESMALL_Y = 40 * _2X,

	DIORAMASIZE_X = 512 * _2X,
	DIORAMASIZE_Y = 512 * _2X,
	DIORAMA_GAPY = 80 * _2X,
	DIORAMA_BATTLE_GAPY = -128 * _2X,
	DIORAMA_NAMETAG_GAPY = 100 * _2X,

	ITEMINVENTORY_XCOUNT = 4,

	COLLECTION_XCOUNT = 3,
	COLLECTION_YGAP = 88 * _2X,

	REWARDITEM_XCOUNT = 4,

	ARENASKILLSLOTCNT = 2,

	ARENASKILLSLOTSIZE_X = 120 * _2X,
	ARENASKILLSLOTSIZE_Y = 120 * _2X,

	BATTLETEXTGAP = -REWARDCARDSIZE_Y - 24 * _2X,//8 * _2X,

	BATTLEREWARDSTART_Y = -222 * _2X,
	BATTLEREWARDGAP = 60 * _2X,
	BATTLEREWARDBOX_Y = 46 * _2X,

	//룰렛이 돈 뒤 나오는 controlMark 카드. 안쪽에 64픽셀짜리 아이콘이
	//통째로 들어가야 해서 (64 + 테두리 4*2)로 잡는다. 예전 값(40x48)은
	//SKILLICONSIZE(32*_2X)를 2배로 그리면 카드 밖으로 삐져나왔다.
	//아이콘이 정사각형이므로 카드도 정사각형이라야 꽉 찬다. 세로로 길면
	//위아래에 빈 테두리가 남는다.
	ROULETTECARDSIZE_X = (64 + 4 * 2) * _2X,
	ROULETTECARDSIZE_Y = ROULETTECARDSIZE_X,

	CHARCARD_WIDTH = 128 * _2X,
	CHARCARD_HEIGHT = 192 * _2X,

	//카드 테두리(DrawSkillCard)와 위치 계산(controlMark)이 같은 값을 봐야
	//카드가 가운데 놓인다. DrawSkillCard는 controlMark 전용이다.
	SKILLCARDSIZE_X = ROULETTECARDSIZE_X,
	SKILLCARDSIZE_Y = ROULETTECARDSIZE_Y,

	POPUPWINDOWSIZE_X = 320 * _2X,
	POPUPWINDOWSIZE_Y = 420 * _2X,

	ITEMDETAILWINDOWSIZE_X = 640 - 32,
	ITEMDETAILWINDOWSIZE_Y = 620,

	POPUPSTORE_Y = 64 * _2X,

	ITEMCARD_WIDTH = 108 * _2X,
	ITEMCARD_HEIGHT = 128 * _2X,

	SHOPMENUCARD_WIDTH = 94 * _2X,
	SHOPMENUCARD_HEIGHT = 88 * _2X,

	LOGWIDTH = 128 * _2X,
	LOGHEIGHT = 20 * _2X,

	COLLECTIONS_X = ROULETTECARDSIZE_X,
	COLLECTIONS_Y = ITEMCARDSIZE_Y,
} UIDEF;

#endif
