#pragma once

#ifndef _DEF_UI_H_
#define _DEF_UI_H_

typedef enum _uiDef {
	FRAME_TALK = 0,
	FRAME_NAME,
	FRAME_INFO,
	FRAME_EDGE,
	FRAME_NONE,

	FRAME_NORMAL = 0,
	FRAME_MONSTER,
	FRAME_MENUWIN,//메뉴창 처음
	FRAME_MENUWIN_QUICK,//메뉴창 하단에 퀵아이템이 있는경우
	FRAME_MENUWIN_INFO,//메뉴창 중간에 막대바로 가로 막는 경우
	FRAME_BUTTON,//판자때기
	FRAME_CHOICEBUTTON,//선택버튼
	FRAME_CHOICEBUTTON2,//선택버튼 옅은색
	FRAME_CHOICEBUTTON_BEIGE,//브라운 판자때기
	FRAME_TALKWIN,//대화신
	FRAME_SHOPBALLOON,//상점등에서
	FRAME_ANIINFO,//애니메이션으로 커지는 창
	FRAME_MENUDAILY,
	FRAME_GAMEOVER,
	FRAME_NOFRAME,
	FRAME_GREEN,//초록색
	FRAME_RED,//빨간색
	FRAME_BLUE,//하늘색
	FRAME_GREY,//회색
	FRAME_GNB,//일반적인 노멀한 
	FRAME_GREEN_OPTION,
	FRAME_RED_OPTION,
	FRAME_BLUE_OPTION,
	FRAME_GREY_OPTION,
	FRAME_GREEN_STAGE,
	FRAME_GREY_STAGE,
	FRAME_WHITEROUND,

	//데모 관련
	TEXTLINEPERPAGE = 3,

	INFOTYPE_GETITEM = 0,
	INFOTYPE_GIVEITEM,
	INFOTYPE_QUEST,
	INFOTYPE_CLEARQUEST,
	INFOTYPE_FAILQUEST,
	INFOTYPE_GETITEMSTATUE,


	BAR_GOLD = 1,
	BAR_CROWN,
	BAR_BOX,
	BAR_PLAYERHP,
	BAR_ENEMYHP = BAR_PLAYERHP + MAXPLAYER,
	BAR_COIN = BAR_ENEMYHP + MAXENEMY,
	BAR_ITEM,
	BAR_HERO,
	BAR_CREW,
	BAR_HEART,
	BAR_BATTLECOIN,
	BAR_HAMMER,
	BAR_SHIELD,
	BAR_MEDAL,
	BAR_INVENTORY,
	BAR_SKILL = BAR_INVENTORY + TOTALCHAR,
	BAR_ENEMYUSER = BAR_SKILL + TOTALCHAR,//상대방 유저
	BAR_ENEMYUSER_BOX,//박스에서 튀어나오는 상대방 유저
	BAR_MAINSHOP,//메인샵
	BAR_DAILYQUEST,//일일퀘스트
	BAR_CREWUPGRADE,//크류(여기는 동료들을 업그레이드 해주는곳)
	BAR_COLLECTIONS,//컬렉션(히어로별 장비, 스킬, 별상점)
	BAR_FRIENDS,//친구
	BAR_QUEST,
	BAR_NPC,
	BAR_RAIDGOLD,//
	BAR_RAIDCOIN,//배틀에서 쓰일 이번턴(내턴 + 적턴) 획득량
	BAR_BOSSHP,//보스 HP
	BAR_HITCOUNT,
	BAR_COMBATPOWER,
	BAR_COMBATPOWERALL,
	BAR_STAGEPROGRESS,
	BAR_REMAINEDTURN,

	TOTAL_BAR,

	PLAYERHPBARCOLOR = COLOR_REALGREEN,
	ENEMYHPBARCOLOR = 0xFF0000,

	ROUNDBAR_BIG = 0,
	ROUNDBAR_SMALL,

	BARCOLOR_RED = 0,
	BARCOLOR_YELLOW,
	BARCOLOR_BLUE,
	BARCOLOR_GREEN,
	BARCOLOR_PURPLE,

	//menuResult
	RESULT_NOGOLD = 1,	//골드가 부족합니다.
	RESULT_INVENTORYFULL,//인벤토리가 가득 찼습니다.
	RESULT_NOSOCKET,	//소켓이 없는 장비입니다.
	RESULT_CANNOTSELLITEM,	//판매할 수 없는 아이템입니다.
	RESULT_ITEMLIMIT,//해당 아이템을 더이상 소지할 수 없습니다.
	RESULT_NOORE,	//재료가 부족합니다.
	RESULT_NOMOREENCHANT,	//더이상 강화하실 수 없습니다.
	RESULT_NOENCHANTITEM,//강화할 수 있는 아이템이 없습니다.
	RESULT_NORECIPE,	//제작가능한 조합서를 가지고 있지 않습니다.
	RESULT_NOGEM,
	RESULT_NOGEMITEM,//보석을 장착할 수 있는 장비가 없습니다.
	RESULT_BROKENITEM,	//부서진 아이템은 강화하실 수 없습니다.
	RESULT_ENCHANTSUCCESS,	//강화에 성공하였습니다.
	RESULT_RECIPESUCCESS,	//새로운 아이템이 생성되었습니다.
	RESULT_SOCKETSUCCESS,	//보석 장착에 성공하였습니다.
	RESULT_NOSTONE,
	RESULT_ENCHANTFAILURE,
	RESULT_ENCHANTFAILURE2,

	INVEN_HCNT = 5,
	INVEN_HCNT_2X = 5,//인벤토리 가로 몇개인가
	INVEN_VCNT_MIN = 5,
	INVEN_VCNT_MIN_2X = 4,

	INVEN_ICON_SIZE_2X = 52 * _2X,
	INVEN_ICON_HGAP_2X = 10 * _2X,
	INVEN_ICON_VGAP_2X = 8 * _2X,

	INVEN_ICON_SIZE = 42 * _2X,
	INVEN_ICON_HGAP = 16 * _2X,
	INVEN_ICON_VGAP = 12 * _2X,

	BUYBUTTON_X = 84 * _2X,
	BUYBUTTON_Y = 31 * _2X,
	BUYSMALLBUTTON_X = 64 * _2X,
	BUYSMALLBUTTON_Y = 31 * _2X,

	OPTIONBUTTONSIZE_X = 84 * _2X,
	OPTIONBUTTONSIZE_Y = 31 * _2X,

	CREWUPGRADEBUTTONSIZE_X = 84 * _2X,
	CREWUPGRADEBUTTONSIZE_Y = 31 * _2X,

	ITEMCARD_WIDTH = 108 * _2X,
	ITEMCARD_HEIGHT = 128 * _2X,

	SHOPMENUCARD_WIDTH = 94 * _2X,
	SHOPMENUCARD_HEIGHT = 88 * _2X,

	LOGWIDTH = 128 * _2X,
	LOGHEIGHT = 20 * _2X,
} UIDEF;

#endif
