"""Rebuild Diana's gun line with a single right-side hand anchor convention.

The eight legacy milestone guns are cut from the approved concept sheet.  The
remaining guns keep their artwork, but are mirrored when their old grip lies
on the left half of the visible silhouette.  Every exported grip is then set
from the visible bounds, so runtime placement never depends on transparent
canvas padding.
"""

from pathlib import Path
import re

import numpy as np
from PIL import Image, ImageFilter


ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / "Resources" / "res"
HEADER = ROOT / "Classes" / "Data" / "DianaGunData.h"
SHEET = Path(
    r"C:\Users\polyp\.codex\generated_images\01a0ad19-e9c6-79c3-9634-d83b8c4e5d36"
    r"\exec-0140d5f8-b5c4-4a80-b811-b2818ce7ce84.png"
)
MILESTONES = (1, 4, 7, 10, 13, 16, 19, 22)
MILESTONE_HEIGHTS = (48, 54, 60, 66, 72, 78, 84, 90)
ROW = re.compile(r"\{\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+)\s*\}, // w1_(\d+)([^\r\n]*)")


def alpha_bounds(image: Image.Image) -> tuple[int, int, int, int]:
    box = image.getchannel("A").getbbox()
    if box is None:
        raise ValueError("empty gun image")
    return box


def expand(mask: np.ndarray, radius: int) -> np.ndarray:
    image = Image.fromarray((mask * 255).astype("uint8"), "L")
    return np.asarray(image.filter(ImageFilter.MaxFilter(radius * 2 + 1))) > 0


def extract_sheet_cell(sheet: Image.Image, index: int) -> Image.Image:
    cell_w, cell_h = sheet.width // 4, sheet.height // 2
    col, row = index % 4, index // 4
    cell = sheet.crop((col * cell_w, row * cell_h,
                       (col + 1) * cell_w, (row + 1) * cell_h)).convert("RGBA")
    rgb = np.asarray(cell)[..., :3].astype(np.int16)
    hi = rgb.max(axis=2)
    lo = rgb.min(axis=2)
    # Bright/colorful cores describe the sprite. A small expansion restores
    # its deliberately dark pixel outline without retaining the soft glow.
    core = (hi > 105) & (((hi - lo) > 24) | (hi > 170))
    mask = expand(core, 7)
    rgba = np.asarray(cell).copy()
    rgba[..., 3] = np.where(mask, 255, 0).astype(np.uint8)
    cut = Image.fromarray(rgba, "RGBA")
    return cut.crop(alpha_bounds(cut))


def fit(image: Image.Image, canvas: tuple[int, int], target_h: int) -> Image.Image:
    w, h = canvas
    scale = min(target_h / image.height, (w - 4) / image.width)
    size = (max(1, round(image.width * scale)), max(1, round(image.height * scale)))
    art = image.resize(size, Image.Resampling.LANCZOS)
    art = art.filter(ImageFilter.UnsharpMask(radius=0.7, percent=145, threshold=2))
    out = Image.new("RGBA", canvas)
    out.alpha_composite(art, ((w - art.width) // 2, (h - art.height) // 2))
    return out


def grip_from_art(image: Image.Image) -> tuple[int, int]:
    left, top, right, bottom = alpha_bounds(image)
    # All source art now carries its grip on the lower-right. Anchor the hand
    # inside that grip, never at the sprite center or transparent padding.
    x = round(left + (right - left - 1) * 0.78)
    y = round(top + (bottom - top - 1) * 0.79)
    return x, y


def main() -> None:
    old_text = HEADER.read_text(encoding="utf-8")
    old = {int(m.group(5)): tuple(map(int, m.group(1, 2, 3, 4))) for m in ROW.finditer(old_text)}
    names = {int(m.group(5)): m.group(6) for m in ROW.finditer(old_text)}
    sheet = Image.open(SHEET).convert("RGBA")
    milestone_art = {n: extract_sheet_cell(sheet, i) for i, n in enumerate(MILESTONES)}
    milestone_height = dict(zip(MILESTONES, MILESTONE_HEIGHTS))
    rows = []

    for n in range(1, 36):
        canvas = (32, 64) if n in (1, 4) else (64, 64) if n <= 5 else (64, 96)
        if n in milestone_art:
            image = fit(milestone_art[n], canvas, milestone_height[n])
        else:
            image = Image.open(RES / f"w1_{n}.png").convert("RGBA")
            if image.size != canvas:
                fitted_h = round(50 + (n - 1) * 40 / 34)
                image = fit(image.crop(alpha_bounds(image)), canvas, fitted_h)
            left, _, right, _ = alpha_bounds(image)
            _, _, old_x, _ = old[n]
            if old_x < (left + right) / 2:
                image = image.transpose(Image.Transpose.FLIP_LEFT_RIGHT)

        grip_x, grip_y = grip_from_art(image)
        image.save(RES / f"w1_{n}.png", optimize=True)
        rows.append((image.width, image.height, grip_x, grip_y, n, names.get(n, "")))

    header = [
        "#pragma once",
        "// Generated by tools/guns/rebuild_diana_guns_right_grip.py.",
        "struct DianaGunInfo {",
        "    int width, height;",
        "    int gripX, gripY;",
        "};",
        "",
        "// Every gun points upward and has its hand grip on the right side.",
        "static const DianaGunInfo kDianaGuns[35] = {",
    ]
    for w, h, gx, gy, n, name in rows:
        header.append(f"    {{ {w:2d}, {h:2d}, {gx:2d}, {gy:2d} }}, // w1_{n}{name}")
    header.extend(("};", ""))
    HEADER.write_text("\n".join(header), encoding="utf-8")


if __name__ == "__main__":
    main()
