//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C100_DATA_H_
#define _C100_DATA_H_

//60프레임 대응 : 원본 키모션(0~3)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C100_DEF {
	//MOTION
	PO_C100_N0	= 0,
	PO_C100_N1	= 1,
	PO_C100_N2	= 2,
	PO_C100_N3	= 3,
	PO_C100_N0_1	= 4,
	PO_C100_N0_2	= 5,
	PO_C100_N0_3	= 6,
	PO_C100_N1_1	= 7,
	PO_C100_N1_2	= 8,
	PO_C100_N1_3	= 9,
	PO_C100_N2_1	= 10,
	PO_C100_N2_2	= 11,
	PO_C100_N2_3	= 12,
	PO_C100_N3_1	= 13,
	PO_C100_N3_2	= 14,
	PO_C100_N3_3	= 15,

	TOTALC100MOTION	= 16,

	//IMAGE
	IMG_C100_0	= 0,
	IMG_C100_1	= 1,
	IMG_C100_2	= 2,
	IMG_C100_3	= 3,
	IMG_C100_4	= 4,
	IMG_C100_5	= 5,
	IMG_C100_6	= 6,
	IMG_C100_7	= 7,
	IMG_C100_8	= 8,
	IMG_C100_9	= 9,
	IMG_C100_10	= 10,
	IMG_C100_11	= 11,
	IMG_C100_12	= 12,

	TOTALC100OFF	= 13
} C100_DEF;

#endif
