//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C104_DATA_H_
#define _C104_DATA_H_

typedef enum _C104_DEF {
	//MOTION
	PO_C104_N0	= 0,
	PO_C104_N1	= 1,
	PO_C104_N2	= 2,
	PO_C104_N3	= 3,

	TOTALC104MOTION	= 4,

	//IMAGE
	IMG_C104_0	= 0,
	IMG_C104_1	= 1,
	IMG_C104_2	= 2,
	IMG_C104_3	= 3,
	IMG_C104_4	= 4,
	IMG_C104_5	= 5,
	IMG_C104_6	= 6,
	IMG_C104_7	= 7,
	IMG_C104_8	= 8,
	IMG_C104_9	= 9,
	IMG_C104_10	= 10,
	IMG_C104_11	= 11,
	IMG_C104_12	= 12,

	TOTALC104OFF	= 13
} C104_DEF;

static const unsigned short c104Off[] = {
	//BMP : C:\SktWipi\Projects\Mos5\Resource\cc.bmp
	114 * _2X, 58 * _2X, 12 * _2X, 11 * _2X,	//0
	76 * _2X, 82 * _2X, 28 * _2X, 1 * _2X,	//1
	51 * _2X, 39 * _2X, 40 * _2X, 20 * _2X,	//2
	91 * _2X, 12 * _2X, 24 * _2X, 12 * _2X,	//3
	91 * _2X, 0 * _2X, 24 * _2X, 12 * _2X,	//4
	0 * _2X, 0 * _2X, 51 * _2X, 49 * _2X,	//5
	51 * _2X, 0 * _2X, 40 * _2X, 39 * _2X,	//6
	0 * _2X, 49 * _2X, 35 * _2X, 34 * _2X,	//7

	//BMP : C:\SKTWIPI\Projects\Mos5\Resource\c104.bmp
	0 * _2X, 0 * _2X, 15 * _2X, 20 * _2X,	//8
	15 * _2X, 0 * _2X, 14 * _2X, 12 * _2X,	//9
	29 * _2X, 0 * _2X, 10 * _2X, 12 * _2X,	//10
	15 * _2X, 12 * _2X, 11 * _2X, 5 * _2X,	//11
	26 * _2X, 12 * _2X, 5 * _2X, 8 * _2X,	//12
};

static const signed short c104MI[] = {
	//PO_C104_N0
	IMG_C104_11, -6 * _2X, -1 * _2X, N00T0X1,	//0
	IMG_C104_9, -7 * _2X, -13 * _2X, N00T0X1,	//1
	IMG_C104_12, 3 * _2X, -12 * _2X, N00T0X1,	//2
	IMG_C104_8, -8 * _2X, -25 * _2X, N00T0X1,	//3
	IMG_C104_10, -13 * _2X, -16 * _2X, N00T0X1,	//4

	//PO_C104_N1
	IMG_C104_11, -6 * _2X, -1 * _2X, N00T0X1,	//5
	IMG_C104_9, -7 * _2X, -13 * _2X, N00T0X1,	//6
	IMG_C104_12, 3 * _2X, -12 * _2X, N00T0X1,	//7
	IMG_C104_8, -8 * _2X, -24 * _2X, N00T0X1,	//8
	IMG_C104_10, -13 * _2X, -16 * _2X, N00T0X1,	//9

	//PO_C104_N2
	IMG_C104_11, -6 * _2X, -1 * _2X, N00T0X1,	//10
	IMG_C104_9, -7 * _2X, -12 * _2X, N00T0X1,	//11
	IMG_C104_12, 3 * _2X, -11 * _2X, N00T0X1,	//12
	IMG_C104_8, -8 * _2X, -23 * _2X, N00T0X1,	//13
	IMG_C104_10, -13 * _2X, -15 * _2X, N00T0X1,	//14

	//PO_C104_N3
	IMG_C104_11, -6 * _2X, -1 * _2X, N00T0X1,	//15
	IMG_C104_9, -7 * _2X, -12 * _2X, N00T0X1,	//16
	IMG_C104_12, 3 * _2X, -11 * _2X, N00T0X1,	//17
	IMG_C104_8, -8 * _2X, -24 * _2X, N00T0X1,	//18
	IMG_C104_10, -13 * _2X, -15 * _2X, N00T0X1,	//19

};

static const unsigned short c104MIC[] = {
	0, 5,	//0
	5, 5,	//1
	10, 5,	//2
	15, 5,	//3
};

static const signed short c104MIS[] = {
	-13 * _2X, -25 * _2X, 21 * _2X, 29 * _2X,	//0
	-13 * _2X, -24 * _2X, 21 * _2X, 28 * _2X,	//1
	-13 * _2X, -23 * _2X, 21 * _2X, 27 * _2X,	//2
	-13 * _2X, -24 * _2X, 21 * _2X, 28 * _2X,	//3
};

static const signed short c104CS[] = {
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//0
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//1
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//2
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//3
};

#endif