//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C105_DATA_H_
#define _C105_DATA_H_

//60프레임 대응 : 원본 키모션(0~6)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C105_DEF {
	//MOTION
	PO_C105_N0	= 0,
	PO_C105_N1	= 1,
	PO_C105_N2	= 2,
	PO_C105_N3	= 3,
	PO_C105_W0	= 4,
	PO_C105_W1	= 5,
	PO_C105_W2	= 6,
	PO_C105_N0_1	= 7,
	PO_C105_N0_2	= 8,
	PO_C105_N0_3	= 9,
	PO_C105_N1_1	= 10,
	PO_C105_N1_2	= 11,
	PO_C105_N1_3	= 12,
	PO_C105_N2_1	= 13,
	PO_C105_N2_2	= 14,
	PO_C105_N2_3	= 15,
	PO_C105_N3_1	= 16,
	PO_C105_N3_2	= 17,
	PO_C105_N3_3	= 18,
	PO_C105_W0_1	= 19,
	PO_C105_W0_2	= 20,
	PO_C105_W0_3	= 21,
	PO_C105_W1_W2_1	= 22,
	PO_C105_W1_W2_2	= 23,
	PO_C105_W1_W2_3	= 24,
	PO_C105_W2_1	= 25,
	PO_C105_W2_2	= 26,
	PO_C105_W2_3	= 27,
	PO_C105_W1_W0_1	= 28,
	PO_C105_W1_W0_2	= 29,
	PO_C105_W1_W0_3	= 30,

	TOTALC105MOTION	= 31,

	//IMAGE
	IMG_C105_0	= 0,
	IMG_C105_1	= 1,
	IMG_C105_2	= 2,
	IMG_C105_3	= 3,
	IMG_C105_4	= 4,
	IMG_C105_5	= 5,
	IMG_C105_6	= 6,
	IMG_C105_7	= 7,
	IMG_C105_8	= 8,
	IMG_C105_9	= 9,
	IMG_C105_10	= 10,
	IMG_C105_11	= 11,
	IMG_C105_12	= 12,
	IMG_C105_13	= 13,
	IMG_C105_14	= 14,
	IMG_C105_15	= 15,
	IMG_C105_16	= 16,
	IMG_C105_17	= 17,
	IMG_C105_18	= 18,
	IMG_C105_19	= 19,
	IMG_C105_20	= 20,

	TOTALC105OFF	= 21
} C105_DEF;

#endif
