//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C107_DATA_H_
#define _C107_DATA_H_

//60프레임 대응 : 원본 키모션(0~10)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C107_DEF {
	//MOTION
	PO_C107_N0	= 0,
	PO_C107_N1	= 1,
	PO_C107_N2	= 2,
	PO_C107_N3	= 3,
	PO_C107_M0	= 4,
	PO_C107_M1	= 5,
	PO_C107_M2	= 6,
	PO_C107_M3	= 7,
	PO_C107_M4	= 8,
	PO_C107_M5	= 9,
	PO_C107_M6	= 10,
	PO_C107_N0_1	= 11,
	PO_C107_N0_2	= 12,
	PO_C107_N0_3	= 13,
	PO_C107_N1_1	= 14,
	PO_C107_N1_2	= 15,
	PO_C107_N1_3	= 16,
	PO_C107_N2_1	= 17,
	PO_C107_N2_2	= 18,
	PO_C107_N2_3	= 19,
	PO_C107_N3_1	= 20,
	PO_C107_N3_2	= 21,
	PO_C107_N3_3	= 22,
	PO_C107_M0_1	= 23,
	PO_C107_M0_2	= 24,
	PO_C107_M0_3	= 25,
	PO_C107_M1_M2_1	= 26,
	PO_C107_M1_M2_2	= 27,
	PO_C107_M1_M2_3	= 28,
	PO_C107_M2_1	= 29,
	PO_C107_M2_2	= 30,
	PO_C107_M2_3	= 31,
	PO_C107_M1_M0_1	= 32,
	PO_C107_M1_M0_2	= 33,
	PO_C107_M1_M0_3	= 34,

	TOTALC107MOTION	= 35,

	//IMAGE
	IMG_C107_0	= 0,
	IMG_C107_1	= 1,
	IMG_C107_2	= 2,
	IMG_C107_3	= 3,
	IMG_C107_4	= 4,
	IMG_C107_5	= 5,
	IMG_C107_6	= 6,
	IMG_C107_7	= 7,
	IMG_C107_8	= 8,
	IMG_C107_9	= 9,
	IMG_C107_10	= 10,
	IMG_C107_11	= 11,
	IMG_C107_12	= 12,
	IMG_C107_13	= 13,
	IMG_C107_14	= 14,
	IMG_C107_15	= 15,
	IMG_C107_16	= 16,
	IMG_C107_17	= 17,
	IMG_C107_18	= 18,

	TOTALC107OFF	= 19
} C107_DEF;

#endif
