//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C108_DATA_H_
#define _C108_DATA_H_

//60프레임 대응 : 원본 키모션(0~7)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C108_DEF {
	//MOTION
	PO_C108_N0	= 0,
	PO_C108_N1	= 1,
	PO_C108_N2	= 2,
	PO_C108_N3	= 3,
	PO_C108_LOOK0	= 4,
	PO_C108_LOOK1	= 5,
	PO_C108_LOOK2	= 6,
	PO_C108_LOOK3	= 7,
	PO_C108_N0_1	= 8,
	PO_C108_N0_2	= 9,
	PO_C108_N0_3	= 10,
	PO_C108_N1_1	= 11,
	PO_C108_N1_2	= 12,
	PO_C108_N1_3	= 13,
	PO_C108_N2_1	= 14,
	PO_C108_N2_2	= 15,
	PO_C108_N2_3	= 16,
	PO_C108_N3_1	= 17,
	PO_C108_N3_2	= 18,
	PO_C108_N3_3	= 19,
	PO_C108_LOOK0_1	= 20,
	PO_C108_LOOK0_2	= 21,
	PO_C108_LOOK0_3	= 22,
	PO_C108_LOOK1_1	= 23,
	PO_C108_LOOK1_2	= 24,
	PO_C108_LOOK1_3	= 25,
	PO_C108_LOOK2_1	= 26,
	PO_C108_LOOK2_2	= 27,
	PO_C108_LOOK2_3	= 28,
	PO_C108_LOOK3_1	= 29,
	PO_C108_LOOK3_2	= 30,
	PO_C108_LOOK3_3	= 31,

	TOTALC108MOTION	= 32,

	//IMAGE
	IMG_C108_0	= 0,
	IMG_C108_1	= 1,
	IMG_C108_2	= 2,
	IMG_C108_3	= 3,
	IMG_C108_4	= 4,
	IMG_C108_5	= 5,
	IMG_C108_6	= 6,
	IMG_C108_7	= 7,
	IMG_C108_8	= 8,
	IMG_C108_9	= 9,
	IMG_C108_10	= 10,
	IMG_C108_11	= 11,
	IMG_C108_12	= 12,
	IMG_C108_13	= 13,
	IMG_C108_14	= 14,

	TOTALC108OFF	= 15
} C108_DEF;

#endif
