//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C113_DATA_H_
#define _C113_DATA_H_

//60프레임 대응 : 원본 키모션(0~1)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C113_DEF {
	//MOTION
	PO_C113_N0	= 0,
	PO_C113_N1	= 1,

	TOTALC113MOTION	= 2,

	//IMAGE
	IMG_C113_0	= 0,
	IMG_C113_1	= 1,
	IMG_C113_2	= 2,
	IMG_C113_3	= 3,
	IMG_C113_4	= 4,
	IMG_C113_5	= 5,
	IMG_C113_6	= 6,
	IMG_C113_7	= 7,
	IMG_C113_8	= 8,
	IMG_C113_9	= 9,
	IMG_C113_10	= 10,

	TOTALC113OFF	= 11
} C113_DEF;

static const unsigned short c113Off[] = {
	//BMP : C:\SktWipi\Projects\Mos5\Resource\cc.bmp
	114 * _2X, 58 * _2X, 12 * _2X, 11 * _2X,	//0
	76 * _2X, 82 * _2X, 28 * _2X, 1 * _2X,	//1
	51 * _2X, 39 * _2X, 40 * _2X, 20 * _2X,	//2
	91 * _2X, 12 * _2X, 24 * _2X, 12 * _2X,	//3
	91 * _2X, 0 * _2X, 24 * _2X, 12 * _2X,	//4
	0 * _2X, 0 * _2X, 51 * _2X, 49 * _2X,	//5
	51 * _2X, 0 * _2X, 40 * _2X, 39 * _2X,	//6
	0 * _2X, 49 * _2X, 35 * _2X, 34 * _2X,	//7

	//BMP : C:\SKTWIPI\Projects\Mos5\Resource\c113.bmp
	0 * _2X, 0 * _2X, 16 * _2X, 13 * _2X,	//8
	16 * _2X, 0 * _2X, 15 * _2X, 10 * _2X,	//9
	31 * _2X, 0 * _2X, 10 * _2X, 10 * _2X,	//10
};

static const signed short c113MI[] = {
	//PO_C113_N0
	IMG_C113_8, -8 * _2X, -10 * _2X, N00T0X1,	//0
	IMG_C113_10, -5 * _2X, -16 * _2X, N00T0X1,	//1

	//PO_C113_N1
	IMG_C113_8, -8 * _2X, -10 * _2X, N00T0X1,	//2
	IMG_C113_9, -7 * _2X, -13 * _2X, N00T0X1,	//3

};

static const unsigned short c113MIC[] = {
	0, 2,	//0
	2, 2,	//1
};

static const signed short c113MIS[] = {
	-8 * _2X, -16 * _2X, 16 * _2X, 19 * _2X,	//0
	-8 * _2X, -13 * _2X, 16 * _2X, 16 * _2X,	//1
};

static const signed short c113CS[] = {
	-8 * _2X, -16 * _2X, 16 * _2X, 16 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//0
	-8 * _2X, -16 * _2X, 16 * _2X, 16 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//1
};
#endif
