//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C113_DATA_H_
#define _C113_DATA_H_

//60프레임 대응 : 원본 키모션(0~1)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C113_DEF {
	//MOTION
	PO_C113_N0	= 0,
	PO_C113_N1	= 1,

	TOTALC113MOTION	= 2,

	//IMAGE
	IMG_C113_0	= 0,
	IMG_C113_1	= 1,
	IMG_C113_2	= 2,
	IMG_C113_3	= 3,
	IMG_C113_4	= 4,
	IMG_C113_5	= 5,
	IMG_C113_6	= 6,
	IMG_C113_7	= 7,
	IMG_C113_8	= 8,
	IMG_C113_9	= 9,
	IMG_C113_10	= 10,

	TOTALC113OFF	= 11
} C113_DEF;

#endif
