//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C118_DATA_H_
#define _C118_DATA_H_

//60프레임 대응 : 원본 키모션(0~8)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C118_DEF {
	//MOTION
	PO_C118_N0	= 0,
	PO_C118_N1	= 1,
	PO_C118_N2	= 2,
	PO_C118_N3	= 3,
	PO_C118_W0	= 4,
	PO_C118_W1	= 5,
	PO_C118_W2	= 6,
	PO_C118_CHAIR	= 7,
	PO_C118_WEAK	= 8,
	PO_C118_N0_1	= 9,
	PO_C118_N0_2	= 10,
	PO_C118_N0_3	= 11,
	PO_C118_N1_1	= 12,
	PO_C118_N1_2	= 13,
	PO_C118_N1_3	= 14,
	PO_C118_N2_1	= 15,
	PO_C118_N2_2	= 16,
	PO_C118_N2_3	= 17,
	PO_C118_N3_1	= 18,
	PO_C118_N3_2	= 19,
	PO_C118_N3_3	= 20,
	PO_C118_W0_1	= 21,
	PO_C118_W0_2	= 22,
	PO_C118_W0_3	= 23,
	PO_C118_W1_W2_1	= 24,
	PO_C118_W1_W2_2	= 25,
	PO_C118_W1_W2_3	= 26,
	PO_C118_W2_1	= 27,
	PO_C118_W2_2	= 28,
	PO_C118_W2_3	= 29,
	PO_C118_W1_W0_1	= 30,
	PO_C118_W1_W0_2	= 31,
	PO_C118_W1_W0_3	= 32,

	TOTALC118MOTION	= 33,

	//IMAGE
	IMG_C118_0	= 0,
	IMG_C118_1	= 1,
	IMG_C118_2	= 2,
	IMG_C118_3	= 3,
	IMG_C118_4	= 4,
	IMG_C118_5	= 5,
	IMG_C118_6	= 6,
	IMG_C118_7	= 7,
	IMG_C118_8	= 8,
	IMG_C118_9	= 9,
	IMG_C118_10	= 10,
	IMG_C118_11	= 11,
	IMG_C118_12	= 12,
	IMG_C118_13	= 13,
	IMG_C118_14	= 14,
	IMG_C118_15	= 15,
	IMG_C118_16	= 16,
	IMG_C118_17	= 17,
	IMG_C118_18	= 18,
	IMG_C118_19	= 19,
	IMG_C118_20	= 20,
	IMG_C118_21	= 21,

	TOTALC118OFF	= 22
} C118_DEF;

#endif
