//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C119_DATA_H_
#define _C119_DATA_H_

//60프레임 대응 : 원본 키모션(0~3)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C119_DEF {
	//MOTION
	PO_C119_N0	= 0,
	PO_C119_N1	= 1,
	PO_C119_N2	= 2,
	PO_C119_N3	= 3,
	PO_C119_N0_1	= 4,
	PO_C119_N0_2	= 5,
	PO_C119_N0_3	= 6,
	PO_C119_N1_1	= 7,
	PO_C119_N1_2	= 8,
	PO_C119_N1_3	= 9,
	PO_C119_N2_1	= 10,
	PO_C119_N2_2	= 11,
	PO_C119_N2_3	= 12,
	PO_C119_N3_1	= 13,
	PO_C119_N3_2	= 14,
	PO_C119_N3_3	= 15,

	TOTALC119MOTION	= 16,

	//IMAGE
	IMG_C119_0	= 0,
	IMG_C119_1	= 1,
	IMG_C119_2	= 2,
	IMG_C119_3	= 3,
	IMG_C119_4	= 4,
	IMG_C119_5	= 5,
	IMG_C119_6	= 6,
	IMG_C119_7	= 7,
	IMG_C119_8	= 8,
	IMG_C119_9	= 9,
	IMG_C119_10	= 10,
	IMG_C119_11	= 11,
	IMG_C119_12	= 12,
	IMG_C119_13	= 13,
	IMG_C119_14	= 14,
	IMG_C119_15	= 15,
	IMG_C119_16	= 16,

	TOTALC119OFF	= 17
} C119_DEF;

#endif
