//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C15_DATA_H_
#define _C15_DATA_H_

//60프레임 대응 : 원본 키모션(0~9)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C15_DEF {
	//MOTION
	PO_C15_N0	= 0,
	PO_C15_N1	= 1,
	PO_C15_N2	= 2,
	PO_C15_N3	= 3,
	PO_C15_A0	= 4,
	PO_C15_A1	= 5,
	PO_C15_A2	= 6,
	PO_C15_A3	= 7,
	PO_C15_A4	= 8,
	PO_C15_A5	= 9,
	PO_C15_N0_1	= 10,
	PO_C15_N0_2	= 11,
	PO_C15_N0_3	= 12,
	PO_C15_N1_1	= 13,
	PO_C15_N1_2	= 14,
	PO_C15_N1_3	= 15,
	PO_C15_N2_N3_1	= 16,
	PO_C15_N2_N3_2	= 17,
	PO_C15_N2_N3_3	= 18,
	PO_C15_N3_1	= 19,
	PO_C15_N3_2	= 20,
	PO_C15_N3_3	= 21,
	PO_C15_A0_1	= 22,
	PO_C15_A0_2	= 23,
	PO_C15_A0_3	= 24,
	PO_C15_A1_1	= 25,
	PO_C15_A1_2	= 26,
	PO_C15_A1_3	= 27,
	PO_C15_A2_2	= 28,
	PO_C15_A3_A4_2	= 29,
	PO_C15_A4_A5_2	= 30,
	PO_C15_A5_A4_1	= 31,
	PO_C15_A5_A4_2	= 32,
	PO_C15_A5_A4_3	= 33,
	PO_C15_A4_A3_2	= 34,
	PO_C15_A3_A2_2	= 35,
	PO_C15_A2_1	= 36,
	PO_C15_A2_3	= 37,
	PO_C15_A5_N0_2	= 38,
	PO_C15_N2_N0_1	= 39,
	PO_C15_N2_N0_2	= 40,
	PO_C15_N2_N0_3	= 41,

	TOTALC15MOTION	= 42,

	//IMAGE
	IMG_C15_0	= 0,
	IMG_C15_1	= 1,
	IMG_C15_2	= 2,
	IMG_C15_3	= 3,
	IMG_C15_4	= 4,
	IMG_C15_5	= 5,
	IMG_C15_6	= 6,
	IMG_C15_7	= 7,
	IMG_C15_8	= 8,
	IMG_C15_9	= 9,
	IMG_C15_10	= 10,
	IMG_C15_11	= 11,
	IMG_C15_12	= 12,
	IMG_C15_13	= 13,
	IMG_C15_14	= 14,

	TOTALC15OFF	= 15
} C15_DEF;

#endif
