//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C19_DATA_H_
#define _C19_DATA_H_

//60프레임 대응 : 원본 키모션(0~13)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C19_DEF {
	//MOTION
	PO_C19_N0	= 0,
	PO_C19_N1	= 1,
	PO_C19_N2	= 2,
	PO_C19_N3	= 3,
	PO_C19_A0	= 4,
	PO_C19_A1	= 5,
	PO_C19_A2	= 6,
	PO_C19_A3	= 7,
	PO_C19_A4	= 8,
	PO_C19_A5	= 9,
	PO_C19_A6	= 10,
	PO_C19_A7	= 11,
	PO_C19_A8	= 12,
	PO_C19_A9	= 13,
	PO_C19_N0_1	= 14,
	PO_C19_N0_2	= 15,
	PO_C19_N0_3	= 16,
	PO_C19_N1_N2_1	= 17,
	PO_C19_N1_N2_2	= 18,
	PO_C19_N1_N2_3	= 19,
	PO_C19_N2_N3_1	= 20,
	PO_C19_N2_N3_2	= 21,
	PO_C19_N2_N3_3	= 22,
	PO_C19_N3_1	= 23,
	PO_C19_N3_2	= 24,
	PO_C19_N3_3	= 25,
	PO_C19_N2_N1_1	= 26,
	PO_C19_N2_N1_2	= 27,
	PO_C19_N2_N1_3	= 28,
	PO_C19_N1_N0_1	= 29,
	PO_C19_N1_N0_2	= 30,
	PO_C19_N1_N0_3	= 31,
	PO_C19_A0_1	= 32,
	PO_C19_A0_2	= 33,
	PO_C19_A0_3	= 34,
	PO_C19_A1_2	= 35,
	PO_C19_A2_2	= 36,
	PO_C19_A3_2	= 37,
	PO_C19_A4_2	= 38,
	PO_C19_A5_2	= 39,
	PO_C19_A6_2	= 40,
	PO_C19_A7_2	= 41,
	PO_C19_A8_2	= 42,

	TOTALC19MOTION	= 43,

	//IMAGE
	IMG_C19_0	= 0,
	IMG_C19_1	= 1,
	IMG_C19_2	= 2,
	IMG_C19_3	= 3,
	IMG_C19_4	= 4,
	IMG_C19_5	= 5,
	IMG_C19_6	= 6,
	IMG_C19_7	= 7,
	IMG_C19_8	= 8,
	IMG_C19_9	= 9,
	IMG_C19_10	= 10,
	IMG_C19_11	= 11,
	IMG_C19_12	= 12,
	IMG_C19_13	= 13,
	IMG_C19_14	= 14,
	IMG_C19_15	= 15,
	IMG_C19_16	= 16,
	IMG_C19_17	= 17,
	IMG_C19_18	= 18,
	IMG_C19_19	= 19,
	IMG_C19_20	= 20,
	IMG_C19_21	= 21,
	IMG_C19_22	= 22,
	IMG_C19_23	= 23,

	TOTALC19OFF	= 24
} C19_DEF;

#endif
