//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C20_DATA_H_
#define _C20_DATA_H_

//60프레임 대응 : 원본 키모션(0~11)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C20_DEF {
	//MOTION
	PO_C20_N0	= 0,
	PO_C20_N1	= 1,
	PO_C20_N2	= 2,
	PO_C20_N3	= 3,
	PO_C20_A0	= 4,
	PO_C20_A1	= 5,
	PO_C20_A2	= 6,
	PO_C20_A3	= 7,
	PO_C20_A4	= 8,
	PO_C20_A5	= 9,
	PO_C20_A6	= 10,
	PO_C20_A7	= 11,
	PO_C20_N0_1	= 12,
	PO_C20_N0_2	= 13,
	PO_C20_N0_3	= 14,
	PO_C20_N1_N2_1	= 15,
	PO_C20_N1_N2_2	= 16,
	PO_C20_N1_N2_3	= 17,
	PO_C20_N2_N3_1	= 18,
	PO_C20_N2_N3_2	= 19,
	PO_C20_N2_N3_3	= 20,
	PO_C20_N3_1	= 21,
	PO_C20_N3_2	= 22,
	PO_C20_N3_3	= 23,
	PO_C20_N2_N1_1	= 24,
	PO_C20_N2_N1_2	= 25,
	PO_C20_N2_N1_3	= 26,
	PO_C20_N1_N0_1	= 27,
	PO_C20_N1_N0_2	= 28,
	PO_C20_N1_N0_3	= 29,
	PO_C20_A0_1	= 30,
	PO_C20_A0_2	= 31,
	PO_C20_A0_3	= 32,
	PO_C20_A1_A0_1	= 33,
	PO_C20_A1_A0_2	= 34,
	PO_C20_A1_A0_3	= 35,
	PO_C20_A1_A2_1	= 36,
	PO_C20_A1_A2_2	= 37,
	PO_C20_A1_A2_3	= 38,
	PO_C20_A2_1	= 39,
	PO_C20_A2_2	= 40,
	PO_C20_A2_3	= 41,
	PO_C20_A3_1	= 42,
	PO_C20_A3_2	= 43,
	PO_C20_A3_3	= 44,
	PO_C20_A4_1	= 45,
	PO_C20_A4_2	= 46,
	PO_C20_A4_3	= 47,
	PO_C20_A5_1	= 48,
	PO_C20_A5_2	= 49,
	PO_C20_A5_3	= 50,
	PO_C20_A6_1	= 51,
	PO_C20_A6_2	= 52,
	PO_C20_A6_3	= 53,

	TOTALC20MOTION	= 54,

	//IMAGE
	IMG_C20_0	= 0,
	IMG_C20_1	= 1,
	IMG_C20_2	= 2,
	IMG_C20_3	= 3,
	IMG_C20_4	= 4,
	IMG_C20_5	= 5,
	IMG_C20_6	= 6,
	IMG_C20_7	= 7,
	IMG_C20_8	= 8,
	IMG_C20_9	= 9,
	IMG_C20_10	= 10,
	IMG_C20_11	= 11,
	IMG_C20_12	= 12,
	IMG_C20_13	= 13,
	IMG_C20_14	= 14,
	IMG_C20_15	= 15,
	IMG_C20_16	= 16,
	IMG_C20_17	= 17,
	IMG_C20_18	= 18,

	TOTALC20OFF	= 19
} C20_DEF;

#endif
