//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C22_DATA_H_
#define _C22_DATA_H_

typedef enum _C22_DEF {
	//MOTION
	PO_C22_N0	= 0,
	PO_C22_N1	= 1,
	PO_C22_N2	= 2,
	PO_C22_N3	= 3,

	TOTALC22MOTION	= 4,

	//IMAGE
	IMG_C22_0	= 0,
	IMG_C22_1	= 1,
	IMG_C22_2	= 2,
	IMG_C22_3	= 3,
	IMG_C22_4	= 4,
	IMG_C22_5	= 5,
	IMG_C22_6	= 6,
	IMG_C22_7	= 7,
	IMG_C22_8	= 8,
	IMG_C22_9	= 9,
	IMG_C22_10	= 10,
	IMG_C22_11	= 11,
	IMG_C22_12	= 12,

	TOTALC22OFF	= 13
} C22_DEF;

static const unsigned short c22Off[] = {
	//BMP : C:\SktWipi\Projects\Mos5\Resource\cc.bmp
	114 * _2X, 58 * _2X, 12 * _2X, 11 * _2X,	//0
	76 * _2X, 82 * _2X, 28 * _2X, 1 * _2X,	//1
	51 * _2X, 39 * _2X, 40 * _2X, 20 * _2X,	//2
	91 * _2X, 12 * _2X, 24 * _2X, 12 * _2X,	//3
	91 * _2X, 0 * _2X, 24 * _2X, 12 * _2X,	//4
	0 * _2X, 0 * _2X, 51 * _2X, 49 * _2X,	//5
	51 * _2X, 0 * _2X, 40 * _2X, 39 * _2X,	//6
	0 * _2X, 49 * _2X, 35 * _2X, 34 * _2X,	//7

	//BMP : C:\SktWipi\Projects\Mos5\Resource\c22.bmp
	0 * _2X, 0 * _2X, 42 * _2X, 36 * _2X,	//8
	42 * _2X, 0 * _2X, 40 * _2X, 34 * _2X,	//9
	33 * _2X, 34 * _2X, 39 * _2X, 35 * _2X,	//10
	0 * _2X, 36 * _2X, 33 * _2X, 32 * _2X,	//11
	72 * _2X, 34 * _2X, 9 * _2X, 7 * _2X,	//12
};

static const signed short c22MI[] = {
	//PO_C22_N0
	IMG_C22_11, -17 * _2X, -25 * _2X, N00T0X1,	//0
	IMG_C22_12, -12 * _2X, -11 * _2X, N00T0X1,	//1

	//PO_C22_N1
	IMG_C22_8, -20 * _2X, -28 * _2X, N00T0X1,	//2
	IMG_C22_12, -12 * _2X, -11 * _2X, N00T0X1,	//3

	//PO_C22_N2
	IMG_C22_9, -20 * _2X, -26 * _2X, N00T0X1,	//4
	IMG_C22_12, -12 * _2X, -11 * _2X, N00T0X1,	//5

	//PO_C22_N3
	IMG_C22_10, -20 * _2X, -27 * _2X, N00T0X1,	//6
	IMG_C22_12, -12 * _2X, -11 * _2X, N00T0X1,	//7

};

static const unsigned short c22MIC[] = {
	0, 2,	//0
	2, 2,	//1
	4, 2,	//2
	6, 2,	//3
};

static const signed short c22MIS[] = {
	-17 * _2X, -25 * _2X, 33 * _2X, 32 * _2X,	//0
	-20 * _2X, -28 * _2X, 42 * _2X, 36 * _2X,	//1
	-20 * _2X, -26 * _2X, 40 * _2X, 34 * _2X,	//2
	-20 * _2X, -27 * _2X, 39 * _2X, 35 * _2X,	//3
};

static const signed short c22CS[] = {
	-12 * _2X, -24 * _2X, 24 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//0
	-12 * _2X, -24 * _2X, 24 * _2X, 24 * _2X,		-24 * _2X, -32 * _2X, 48 * _2X, 32 * _2X,	//1
	-12 * _2X, -24 * _2X, 24 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//2
	-12 * _2X, -24 * _2X, 24 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//3
};

#endif