//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C23_DATA_H_
#define _C23_DATA_H_

//60프레임 대응 : 원본 키모션(0~17)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C23_DEF {
	//MOTION
	PO_C23_N0	= 0,
	PO_C23_N1	= 1,
	PO_C23_N2	= 2,
	PO_C23_N3	= 3,
	PO_C23_N4	= 4,
	PO_C23_N5	= 5,
	PO_C23_N6	= 6,
	PO_C23_N7	= 7,
	PO_C23_A0	= 8,
	PO_C23_A1	= 9,
	PO_C23_LIGHTNING0	= 10,
	PO_C23_LIGHTNING1	= 11,
	PO_C23_LIGHTNING2	= 12,
	PO_C23_LIGHTNING3	= 13,
	PO_C22_LIGHTNING0	= 14,
	PO_C22_LIGHTNING1	= 15,
	PO_C22_LIGHTNING2	= 16,
	PO_C22_LIGHTNING3	= 17,
	PO_C23_N0_1	= 18,
	PO_C23_N0_2	= 19,
	PO_C23_N0_3	= 20,
	PO_C23_N1_1	= 21,
	PO_C23_N1_2	= 22,
	PO_C23_N1_3	= 23,
	PO_C23_N2_1	= 24,
	PO_C23_N2_2	= 25,
	PO_C23_N2_3	= 26,
	PO_C23_N3_1	= 27,
	PO_C23_N3_2	= 28,
	PO_C23_N3_3	= 29,
	PO_C23_N4_1	= 30,
	PO_C23_N4_2	= 31,
	PO_C23_N4_3	= 32,
	PO_C23_N5_1	= 33,
	PO_C23_N5_2	= 34,
	PO_C23_N5_3	= 35,
	PO_C23_N6_1	= 36,
	PO_C23_N6_2	= 37,
	PO_C23_N6_3	= 38,
	PO_C23_N7_1	= 39,
	PO_C23_N7_2	= 40,
	PO_C23_N7_3	= 41,
	PO_C23_A0_1	= 42,
	PO_C23_A0_2	= 43,
	PO_C23_A0_3	= 44,

	TOTALC23MOTION	= 45,

	//IMAGE
	IMG_C23_0	= 0,
	IMG_C23_1	= 1,
	IMG_C23_2	= 2,
	IMG_C23_3	= 3,
	IMG_C23_4	= 4,
	IMG_C23_5	= 5,
	IMG_C23_6	= 6,
	IMG_C23_7	= 7,
	IMG_C23_8	= 8,
	IMG_C23_9	= 9,
	IMG_C23_10	= 10,
	IMG_C23_11	= 11,
	IMG_C23_12	= 12,
	IMG_C23_13	= 13,
	IMG_C23_14	= 14,
	IMG_C23_15	= 15,
	IMG_C23_16	= 16,
	IMG_C23_17	= 17,
	IMG_C23_18	= 18,
	IMG_C23_19	= 19,
	IMG_C23_20	= 20,
	IMG_C23_21	= 21,
	IMG_C23_22	= 22,
	IMG_C23_23	= 23,
	IMG_C23_24	= 24,

	TOTALC23OFF	= 25
} C23_DEF;

#endif
