//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C35_DATA_H_
#define _C35_DATA_H_

//60프레임 대응 : 원본 키모션(0~11)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C35_DEF {
	//MOTION
	PO_C35_N0	= 0,
	PO_C35_N1	= 1,
	PO_C35_N2	= 2,
	PO_C35_N3	= 3,
	PO_C35_STAR0	= 4,
	PO_C35_STAR1	= 5,
	PO_C35_STAR2	= 6,
	PO_C35_STAR3	= 7,
	PO_C35_W0	= 8,
	PO_C35_W1	= 9,
	PO_C35_W2	= 10,
	PO_C35_W3	= 11,
	PO_C35_N0_1	= 12,
	PO_C35_N0_2	= 13,
	PO_C35_N0_3	= 14,
	PO_C35_N1_1	= 15,
	PO_C35_N1_2	= 16,
	PO_C35_N1_3	= 17,
	PO_C35_N2_1	= 18,
	PO_C35_N2_2	= 19,
	PO_C35_N2_3	= 20,
	PO_C35_N3_1	= 21,
	PO_C35_N3_2	= 22,
	PO_C35_N3_3	= 23,
	PO_C35_W0_1	= 24,
	PO_C35_W0_2	= 25,
	PO_C35_W0_3	= 26,
	PO_C35_W1_1	= 27,
	PO_C35_W1_2	= 28,
	PO_C35_W1_3	= 29,
	PO_C35_W2_1	= 30,
	PO_C35_W2_2	= 31,
	PO_C35_W2_3	= 32,
	PO_C35_W3_1	= 33,
	PO_C35_W3_2	= 34,
	PO_C35_W3_3	= 35,

	TOTALC35MOTION	= 36,

	//IMAGE
	IMG_C35_0	= 0,
	IMG_C35_1	= 1,
	IMG_C35_2	= 2,
	IMG_C35_3	= 3,
	IMG_C35_4	= 4,
	IMG_C35_5	= 5,
	IMG_C35_6	= 6,
	IMG_C35_7	= 7,
	IMG_C35_8	= 8,
	IMG_C35_9	= 9,
	IMG_C35_10	= 10,
	IMG_C35_11	= 11,
	IMG_C35_12	= 12,
	IMG_C35_13	= 13,
	IMG_C35_14	= 14,
	IMG_C35_15	= 15,
	IMG_C35_16	= 16,
	IMG_C35_17	= 17,
	IMG_C35_18	= 18,
	IMG_C35_19	= 19,
	IMG_C35_20	= 20,
	IMG_C35_21	= 21,
	IMG_C35_22	= 22,
	IMG_C35_23	= 23,
	IMG_C35_24	= 24,
	IMG_C35_25	= 25,
	IMG_C35_26	= 26,
	IMG_C35_27	= 27,

	TOTALC35OFF	= 28
} C35_DEF;

#endif
