//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C36_DATA_H_
#define _C36_DATA_H_

typedef enum _C36_DEF {
	//MOTION
	PO_C36_N0	= 0,
	PO_C36_N1	= 1,
	PO_C36_N2	= 2,
	PO_C36_N3	= 3,

	TOTALC36MOTION	= 4,

	//IMAGE
	IMG_C36_0	= 0,
	IMG_C36_1	= 1,
	IMG_C36_2	= 2,
	IMG_C36_3	= 3,
	IMG_C36_4	= 4,
	IMG_C36_5	= 5,
	IMG_C36_6	= 6,
	IMG_C36_7	= 7,
	IMG_C36_8	= 8,
	IMG_C36_9	= 9,
	IMG_C36_10	= 10,
	IMG_C36_11	= 11,
	IMG_C36_12	= 12,

	TOTALC36OFF	= 13
} C36_DEF;

static const unsigned short c36Off[] = {
	//BMP : C:\SktWipi\Projects\Mos5\Resource\cc.bmp
	114 * _2X, 58 * _2X, 12 * _2X, 11 * _2X,	//0
	76 * _2X, 82 * _2X, 28 * _2X, 1 * _2X,	//1
	51 * _2X, 39 * _2X, 40 * _2X, 20 * _2X,	//2
	91 * _2X, 12 * _2X, 24 * _2X, 12 * _2X,	//3
	91 * _2X, 0 * _2X, 24 * _2X, 12 * _2X,	//4
	0 * _2X, 0 * _2X, 51 * _2X, 49 * _2X,	//5
	51 * _2X, 0 * _2X, 40 * _2X, 39 * _2X,	//6
	0 * _2X, 49 * _2X, 35 * _2X, 34 * _2X,	//7
	76 * _2X, 62 * _2X, 20 * _2X, 20 * _2X,	//8

	//BMP : C:\sktwipi\Projects\Mos5\Resource\c36.bmp
	0 * _2X, 0 * _2X, 64 * _2X, 64 * _2X,	//9
	64 * _2X, 0 * _2X, 64 * _2X, 64 * _2X,	//10
	0 * _2X, 64 * _2X, 64 * _2X, 64 * _2X,	//11
	64 * _2X, 64 * _2X, 64 * _2X, 64 * _2X,	//12
};

static const signed short c36MI[] = {
	//PO_C36_N0
	IMG_C36_10, -32 * _2X, -32 * _2X - 16 * _2X,  N00T0X1,	//0
	IMG_C36_8, -20 * _2X, -20 * _2X - 16 * _2X,  N00E2X2,	//1

	//PO_C36_N1
	IMG_C36_9, -32 * _2X, -32 * _2X - 16 * _2X,  N00T0X1,	//2
	IMG_C36_8, -20 * _2X, -20 * _2X - 16 * _2X,  N00E3X2,	//3

	//PO_C36_N2
	IMG_C36_11, -32 * _2X, -32 * _2X - 16 * _2X,  N00T0X1,	//4
	IMG_C36_8, -20 * _2X, -20 * _2X - 16 * _2X,  N00E2X2,	//5

	//PO_C36_N3
	IMG_C36_12, -32 * _2X, -32 * _2X - 16 * _2X,  N00T0X1,	//6
	IMG_C36_8, -20 * _2X, -20 * _2X - 16 * _2X,  N00E3X2,	//7

};

static const unsigned short c36MIC[] = {
	0, 2,	//0
	2, 2,	//1
	4, 2,	//2
	6, 2,	//3
};

static const signed short c36MIS[] = {
	-32 * _2X, -32 * _2X - 16 * _2X, 64 * _2X, 64 * _2X,	//0
	-32 * _2X, -32 * _2X - 16 * _2X, 64 * _2X, 64 * _2X,	//1
	-32 * _2X, -32 * _2X - 16 * _2X, 64 * _2X, 64 * _2X,	//2
	-32 * _2X, -32 * _2X - 16 * _2X, 64 * _2X, 64 * _2X,	//3
};

static const signed short c36CS[] = {
	-32 * _2X, -32 * _2X - 16 * _2X, 64 * _2X, 64 * _2X,		-32 * _2X, -32 * _2X - 16 * _2X, 64 * _2X, 64 * _2X,	//0
	-32 * _2X, -32 * _2X - 16 * _2X, 64 * _2X, 64 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//1
	-32 * _2X, -32 * _2X - 16 * _2X, 64 * _2X, 64 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//2
	-32 * _2X, -32 * _2X - 16 * _2X, 64 * _2X, 64 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//3
};

#endif