//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C38_DATA_H_
#define _C38_DATA_H_

//60프레임 대응 : 원본 키모션(0~15)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C38_DEF {
	//MOTION
	PO_C38_NHEAD0	= 0,
	PO_C38_NHEAD1	= 1,
	PO_C38_NHEAD2	= 2,
	PO_C38_NHEAD3	= 3,
	PO_C38_NBODY0	= 4,
	PO_C38_NBODY1	= 5,
	PO_C38_NBODY2	= 6,
	PO_C38_NBODY3	= 7,
	PO_C38_NTAIL0	= 8,
	PO_C38_NTAIL1	= 9,
	PO_C38_NTAIL2	= 10,
	PO_C38_NTAIL3	= 11,
	PO_C38_N0	= 12,
	PO_C38_N1	= 13,
	PO_C38_N2	= 14,
	PO_C38_N3	= 15,
	PO_C38_NHEAD0_2	= 16,
	PO_C38_NHEAD1_2	= 17,
	PO_C38_NHEAD2_2	= 18,
	PO_C38_NHEAD3_2	= 19,
	PO_C38_NBODY0_2	= 20,
	PO_C38_NBODY1_2	= 21,
	PO_C38_NBODY2_2	= 22,
	PO_C38_NBODY3_2	= 23,
	PO_C38_NTAIL0_2	= 24,
	PO_C38_NTAIL1_2	= 25,
	PO_C38_NTAIL2_2	= 26,
	PO_C38_NTAIL3_2	= 27,

	TOTALC38MOTION	= 28,

	//IMAGE
	IMG_C38_0	= 0,
	IMG_C38_1	= 1,
	IMG_C38_2	= 2,
	IMG_C38_3	= 3,
	IMG_C38_4	= 4,
	IMG_C38_5	= 5,
	IMG_C38_6	= 6,
	IMG_C38_7	= 7,
	IMG_C38_8	= 8,
	IMG_C38_9	= 9,
	IMG_C38_10	= 10,
	IMG_C38_11	= 11,
	IMG_C38_12	= 12,
	IMG_C38_13	= 13,
	IMG_C38_14	= 14,
	IMG_C38_15	= 15,
	IMG_C38_16	= 16,
	IMG_C38_17	= 17,
	IMG_C38_18	= 18,
	IMG_C38_19	= 19,
	IMG_C38_20	= 20,
	IMG_C38_21	= 21,
	IMG_C38_22	= 22,

	TOTALC38OFF	= 23
} C38_DEF;

#endif
