//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C41_DATA_H_
#define _C41_DATA_H_

//60프레임 대응 : 원본 키모션(0~14)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C41_DEF {
	//MOTION
	PO_C41_N0	= 0,
	PO_C41_N1	= 1,
	PO_C41_N2	= 2,
	PO_C41_N3	= 3,
	PO_C41_W0	= 4,
	PO_C41_W1	= 5,
	PO_C41_W2	= 6,
	PO_C41_W3	= 7,
	PO_C41_A0	= 8,
	PO_C41_A1	= 9,
	PO_C41_A2	= 10,
	PO_C41_A3	= 11,
	PO_C41_A4	= 12,
	PO_C41_A5	= 13,
	PO_C41_A6	= 14,
	PO_C41_N0_1	= 15,
	PO_C41_N0_2	= 16,
	PO_C41_N0_3	= 17,
	PO_C41_N1_1	= 18,
	PO_C41_N1_2	= 19,
	PO_C41_N1_3	= 20,
	PO_C41_N2_1	= 21,
	PO_C41_N2_2	= 22,
	PO_C41_N2_3	= 23,
	PO_C41_N3_1	= 24,
	PO_C41_N3_2	= 25,
	PO_C41_N3_3	= 26,
	PO_C41_W0_1	= 27,
	PO_C41_W0_2	= 28,
	PO_C41_W0_3	= 29,
	PO_C41_W1_1	= 30,
	PO_C41_W1_2	= 31,
	PO_C41_W1_3	= 32,
	PO_C41_W2_1	= 33,
	PO_C41_W2_2	= 34,
	PO_C41_W2_3	= 35,
	PO_C41_W3_1	= 36,
	PO_C41_W3_2	= 37,
	PO_C41_W3_3	= 38,
	PO_C41_A0_2	= 39,
	PO_C41_A1_1	= 40,
	PO_C41_A1_2	= 41,
	PO_C41_A1_3	= 42,
	PO_C41_A2_1	= 43,
	PO_C41_A2_2	= 44,
	PO_C41_A2_3	= 45,
	PO_C41_A5_2	= 46,
	PO_C41_A6_1	= 47,
	PO_C41_A6_2	= 48,
	PO_C41_A6_3	= 49,

	TOTALC41MOTION	= 50,

	//IMAGE
	IMG_C41_0	= 0,
	IMG_C41_1	= 1,
	IMG_C41_2	= 2,
	IMG_C41_3	= 3,
	IMG_C41_4	= 4,
	IMG_C41_5	= 5,
	IMG_C41_6	= 6,
	IMG_C41_7	= 7,
	IMG_C41_8	= 8,
	IMG_C41_9	= 9,
	IMG_C41_10	= 10,
	IMG_C41_11	= 11,
	IMG_C41_12	= 12,
	IMG_C41_13	= 13,
	IMG_C41_14	= 14,
	IMG_C41_15	= 15,
	IMG_C41_16	= 16,
	IMG_C41_17	= 17,
	IMG_C41_18	= 18,
	IMG_C41_19	= 19,
	IMG_C41_20	= 20,
	IMG_C41_21	= 21,
	IMG_C41_22	= 22,
	IMG_C41_23	= 23,

	TOTALC41OFF	= 24
} C41_DEF;

#endif
