//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C42_DATA_H_
#define _C42_DATA_H_

//60프레임 대응 : 원본 키모션(0~19)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C42_DEF {
	//MOTION
	PO_C42_N0	= 0,
	PO_C42_N1	= 1,
	PO_C42_N2	= 2,
	PO_C42_N3	= 3,
	PO_C42_A0	= 4,
	PO_C42_A1	= 5,
	PO_C42_A2	= 6,
	PO_C42_A3	= 7,
	PO_C42_A4	= 8,
	PO_C42_A5	= 9,
	PO_C42_FIRE0	= 10,
	PO_C42_FIRE1	= 11,
	PO_C42_FIRE2	= 12,
	PO_C42_FIRE3	= 13,
	PO_C42_FIRE4	= 14,
	PO_C42_FIRE5	= 15,
	PO_C42_FIRE6	= 16,
	PO_C42_FIRE7	= 17,
	PO_C42_FIRE8	= 18,
	PO_C42_FIRE9	= 19,
	PO_C42_N0_1	= 20,
	PO_C42_N0_2	= 21,
	PO_C42_N0_3	= 22,
	PO_C42_N1_1	= 23,
	PO_C42_N1_2	= 24,
	PO_C42_N1_3	= 25,
	PO_C42_N2_1	= 26,
	PO_C42_N2_2	= 27,
	PO_C42_N2_3	= 28,
	PO_C42_N3_1	= 29,
	PO_C42_N3_2	= 30,
	PO_C42_N3_3	= 31,
	PO_C42_A0_1	= 32,
	PO_C42_A0_2	= 33,
	PO_C42_A0_3	= 34,
	PO_C42_A1_1	= 35,
	PO_C42_A1_2	= 36,
	PO_C42_A1_3	= 37,
	PO_C42_A2_2	= 38,
	PO_C42_A3_1	= 39,
	PO_C42_A3_2	= 40,
	PO_C42_A3_3	= 41,
	PO_C42_A4_A3_1	= 42,
	PO_C42_A4_A3_2	= 43,
	PO_C42_A4_A3_3	= 44,
	PO_C42_A4_A5_1	= 45,
	PO_C42_A4_A5_2	= 46,
	PO_C42_A4_A5_3	= 47,

	TOTALC42MOTION	= 48,

	//IMAGE
	IMG_C42_0	= 0,
	IMG_C42_1	= 1,
	IMG_C42_2	= 2,
	IMG_C42_3	= 3,
	IMG_C42_4	= 4,
	IMG_C42_5	= 5,
	IMG_C42_6	= 6,
	IMG_C42_7	= 7,
	IMG_C42_8	= 8,
	IMG_C42_9	= 9,
	IMG_C42_10	= 10,
	IMG_C42_11	= 11,
	IMG_C42_12	= 12,
	IMG_C42_13	= 13,
	IMG_C42_14	= 14,
	IMG_C42_15	= 15,
	IMG_C42_16	= 16,
	IMG_C42_17	= 17,
	IMG_C42_18	= 18,

	TOTALC42OFF	= 19
} C42_DEF;

#endif
