//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C46_DATA_H_
#define _C46_DATA_H_

//60프레임 대응 : 원본 키모션(0~6)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C46_DEF {
	//MOTION
	PO_C46_N0	= 0,
	PO_C46_A0	= 1,
	PO_C46_A1	= 2,
	PO_C46_A2	= 3,
	PO_C46_A3	= 4,
	PO_C46_A4	= 5,
	PO_C46_A5	= 6,
	PO_C46_A0_1	= 7,
	PO_C46_A0_2	= 8,
	PO_C46_A0_3	= 9,
	PO_C46_A1_1	= 10,
	PO_C46_A1_2	= 11,
	PO_C46_A1_3	= 12,
	PO_C46_A2_1	= 13,
	PO_C46_A2_2	= 14,
	PO_C46_A2_3	= 15,
	PO_C46_A3_1	= 16,
	PO_C46_A3_2	= 17,
	PO_C46_A3_3	= 18,
	PO_C46_A4_1	= 19,
	PO_C46_A4_2	= 20,
	PO_C46_A4_3	= 21,
	PO_C46_A5_1	= 22,
	PO_C46_A5_2	= 23,
	PO_C46_A5_3	= 24,

	TOTALC46MOTION	= 25,

	//IMAGE
	IMG_C46_0	= 0,
	IMG_C46_1	= 1,
	IMG_C46_2	= 2,
	IMG_C46_3	= 3,
	IMG_C46_4	= 4,
	IMG_C46_5	= 5,
	IMG_C46_6	= 6,
	IMG_C46_7	= 7,
	IMG_C46_8	= 8,
	IMG_C46_9	= 9,
	IMG_C46_10	= 10,
	IMG_C46_11	= 11,
	IMG_C46_12	= 12,
	IMG_C46_13	= 13,
	IMG_C46_14	= 14,

	TOTALC46OFF	= 15
} C46_DEF;

#endif
