//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C52_DATA_H_
#define _C52_DATA_H_

typedef enum _C52_DEF {
	//MOTION
	PO_C52_N0	= 0,
	PO_C52_N1	= 1,
	PO_C52_N2	= 2,
	PO_C52_N3	= 3,

	TOTALC52MOTION	= 4,

	//IMAGE
	IMG_C52_0	= 0,
	IMG_C52_1	= 1,
	IMG_C52_2	= 2,
	IMG_C52_3	= 3,
	IMG_C52_4	= 4,
	IMG_C52_5	= 5,
	IMG_C52_6	= 6,
	IMG_C52_7	= 7,
	IMG_C52_8	= 8,
	IMG_C52_9	= 9,
	IMG_C52_10	= 10,
	IMG_C52_11	= 11,
	IMG_C52_12	= 12,
	IMG_C52_13	= 13,

	TOTALC52OFF	= 14
} C52_DEF;

static const unsigned short c52Off[] = {
	//BMP : C:\SktWipi\Projects\Mos5\Resource\cc.bmp
	114 * _2X, 58 * _2X, 12 * _2X, 11 * _2X,	//0
	76 * _2X, 82 * _2X, 28 * _2X, 1 * _2X,	//1
	51 * _2X, 39 * _2X, 40 * _2X, 20 * _2X,	//2
	91 * _2X, 12 * _2X, 24 * _2X, 12 * _2X,	//3
	91 * _2X, 0 * _2X, 24 * _2X, 12 * _2X,	//4
	0 * _2X, 0 * _2X, 51 * _2X, 49 * _2X,	//5
	51 * _2X, 0 * _2X, 40 * _2X, 39 * _2X,	//6
	0 * _2X, 49 * _2X, 35 * _2X, 34 * _2X,	//7

	//BMP : C:\sktwipi\Projects\Mos5\Resource\c52.bmp
	0 * _2X, 0 * _2X, 25 * _2X, 20 * _2X,	//8
	25 * _2X, 0 * _2X, 14 * _2X, 16 * _2X,	//9
	0 * _2X, 20 * _2X, 8 * _2X, 9 * _2X,	//10
	8 * _2X, 20 * _2X, 9 * _2X, 9 * _2X,	//11
	17 * _2X, 20 * _2X, 6 * _2X, 8 * _2X,	//12
	23 * _2X, 17 * _2X, 17 * _2X, 11 * _2X,	//13
};

static const signed short c52MI[] = {
	//PO_C52_N0
	IMG_C52_12, -13 * _2X, -9 * _2X, N00T0X1,	//0
	IMG_C52_10, -12 * _2X, -16 * _2X, N00T0X1,	//1
	IMG_C52_13, -10 * _2X, -7 * _2X, N00T0X1,	//2
	IMG_C52_9, -7 * _2X, -17 * _2X, N00T0X1,	//3
	IMG_C52_8, -10 * _2X, -34 * _2X, N00T0X1,	//4
	IMG_C52_11, 0 * _2X, -12 * _2X, N00T0X1,	//5

	//PO_C52_N1
	IMG_C52_12, -13 * _2X, -9 * _2X, N00T0X1,	//6
	IMG_C52_10, -12 * _2X, -16 * _2X, N00T0X1,	//7
	IMG_C52_13, -10 * _2X, -7 * _2X, N00T0X1,	//8
	IMG_C52_9, -7 * _2X, -17 * _2X, N00T0X1,	//9
	IMG_C52_8, -10 * _2X, -33 * _2X, N00T0X1,	//10
	IMG_C52_11, 0 * _2X, -13 * _2X, N00T0X1,	//11

	//PO_C52_N2
	IMG_C52_12, -13 * _2X, -9 * _2X, N00T0X1,	//12
	IMG_C52_10, -12 * _2X, -15 * _2X, N00T0X1,	//13
	IMG_C52_13, -10 * _2X, -7 * _2X, N00T0X1,	//14
	IMG_C52_9, -7 * _2X, -16 * _2X, N00T0X1,	//15
	IMG_C52_8, -10 * _2X, -32 * _2X, N00T0X1,	//16
	IMG_C52_11, 0 * _2X, -12 * _2X, N00T0X1,	//17

	//PO_C52_N3
	IMG_C52_12, -13 * _2X, -9 * _2X, N00T0X1,	//18
	IMG_C52_10, -12 * _2X, -15 * _2X, N00T0X1,	//19
	IMG_C52_13, -10 * _2X, -7 * _2X, N00T0X1,	//20
	IMG_C52_9, -7 * _2X, -16 * _2X, N00T0X1,	//21
	IMG_C52_8, -10 * _2X, -33 * _2X, N00T0X1,	//22
	IMG_C52_11, 0 * _2X, -11 * _2X, N00T0X1,	//23

};

static const unsigned short c52MIC[] = {
	0, 6,	//0
	6, 6,	//1
	12, 6,	//2
	18, 6,	//3
};

static const signed short c52MIS[] = {
	-13 * _2X, -34 * _2X, 28 * _2X, 38 * _2X,	//0
	-13 * _2X, -33 * _2X, 28 * _2X, 37 * _2X,	//1
	-13 * _2X, -32 * _2X, 28 * _2X, 36 * _2X,	//2
	-13 * _2X, -33 * _2X, 28 * _2X, 37 * _2X,	//3
};

static const signed short c52CS[] = {
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//0
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//1
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//2
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//3
};

#endif