//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C52_DATA_H_
#define _C52_DATA_H_

//60프레임 대응 : 원본 키모션(0~3)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C52_DEF {
	//MOTION
	PO_C52_N0	= 0,
	PO_C52_N1	= 1,
	PO_C52_N2	= 2,
	PO_C52_N3	= 3,
	PO_C52_N0_1	= 4,
	PO_C52_N0_2	= 5,
	PO_C52_N0_3	= 6,
	PO_C52_N1_1	= 7,
	PO_C52_N1_2	= 8,
	PO_C52_N1_3	= 9,
	PO_C52_N2_1	= 10,
	PO_C52_N2_2	= 11,
	PO_C52_N2_3	= 12,
	PO_C52_N3_1	= 13,
	PO_C52_N3_2	= 14,
	PO_C52_N3_3	= 15,

	TOTALC52MOTION	= 16,

	//IMAGE
	IMG_C52_0	= 0,
	IMG_C52_1	= 1,
	IMG_C52_2	= 2,
	IMG_C52_3	= 3,
	IMG_C52_4	= 4,
	IMG_C52_5	= 5,
	IMG_C52_6	= 6,
	IMG_C52_7	= 7,
	IMG_C52_8	= 8,
	IMG_C52_9	= 9,
	IMG_C52_10	= 10,
	IMG_C52_11	= 11,
	IMG_C52_12	= 12,
	IMG_C52_13	= 13,

	TOTALC52OFF	= 14
} C52_DEF;

#endif
