//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C55_DATA_H_
#define _C55_DATA_H_

//60프레임 대응 : 원본 키모션(0~7)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C55_DEF {
	//MOTION
	PO_C55_N0	= 0,
	PO_C55_N1	= 1,
	PO_C55_N2	= 2,
	PO_C55_N3	= 3,
	PO_C55_W0	= 4,
	PO_C55_W1	= 5,
	PO_C55_W2	= 6,
	PO_C55_D	= 7,
	PO_C55_N0_1	= 8,
	PO_C55_N0_2	= 9,
	PO_C55_N0_3	= 10,
	PO_C55_N1_1	= 11,
	PO_C55_N1_2	= 12,
	PO_C55_N1_3	= 13,
	PO_C55_N2_1	= 14,
	PO_C55_N2_2	= 15,
	PO_C55_N2_3	= 16,
	PO_C55_N3_1	= 17,
	PO_C55_N3_2	= 18,
	PO_C55_N3_3	= 19,
	PO_C55_W0_1	= 20,
	PO_C55_W0_2	= 21,
	PO_C55_W0_3	= 22,
	PO_C55_W1_W2_1	= 23,
	PO_C55_W1_W2_2	= 24,
	PO_C55_W1_W2_3	= 25,
	PO_C55_W2_1	= 26,
	PO_C55_W2_2	= 27,
	PO_C55_W2_3	= 28,
	PO_C55_W1_W0_1	= 29,
	PO_C55_W1_W0_2	= 30,
	PO_C55_W1_W0_3	= 31,

	TOTALC55MOTION	= 32,

	//IMAGE
	IMG_C55_0	= 0,
	IMG_C55_1	= 1,
	IMG_C55_2	= 2,
	IMG_C55_3	= 3,
	IMG_C55_4	= 4,
	IMG_C55_5	= 5,
	IMG_C55_6	= 6,
	IMG_C55_7	= 7,
	IMG_C55_8	= 8,
	IMG_C55_9	= 9,
	IMG_C55_10	= 10,
	IMG_C55_11	= 11,
	IMG_C55_12	= 12,
	IMG_C55_13	= 13,
	IMG_C55_14	= 14,
	IMG_C55_15	= 15,
	IMG_C55_16	= 16,
	IMG_C55_17	= 17,
	IMG_C55_18	= 18,
	IMG_C55_19	= 19,
	IMG_C55_20	= 20,
	IMG_C55_21	= 21,
	IMG_C55_22	= 22,
	IMG_C55_23	= 23,

	TOTALC55OFF	= 24
} C55_DEF;

#endif
