//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C62_DATA_H_
#define _C62_DATA_H_

//60프레임 대응 : 원본 키모션(0~7)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C62_DEF {
	//MOTION
	PO_C62_N0	= 0,
	PO_C62_N1	= 1,
	PO_C62_N2	= 2,
	PO_C62_N3	= 3,
	PO_C62_W0	= 4,
	PO_C62_W1	= 5,
	PO_C62_W2	= 6,
	PO_C62_D	= 7,
	PO_C62_N0_1	= 8,
	PO_C62_N0_2	= 9,
	PO_C62_N0_3	= 10,
	PO_C62_N1_1	= 11,
	PO_C62_N1_2	= 12,
	PO_C62_N1_3	= 13,
	PO_C62_N2_1	= 14,
	PO_C62_N2_2	= 15,
	PO_C62_N2_3	= 16,
	PO_C62_N3_1	= 17,
	PO_C62_N3_2	= 18,
	PO_C62_N3_3	= 19,
	PO_C62_W0_1	= 20,
	PO_C62_W0_2	= 21,
	PO_C62_W0_3	= 22,
	PO_C62_W1_W2_1	= 23,
	PO_C62_W1_W2_2	= 24,
	PO_C62_W1_W2_3	= 25,
	PO_C62_W2_1	= 26,
	PO_C62_W2_2	= 27,
	PO_C62_W2_3	= 28,
	PO_C62_W1_W0_1	= 29,
	PO_C62_W1_W0_2	= 30,
	PO_C62_W1_W0_3	= 31,

	TOTALC62MOTION	= 32,

	//IMAGE
	IMG_C62_0	= 0,
	IMG_C62_1	= 1,
	IMG_C62_2	= 2,
	IMG_C62_3	= 3,
	IMG_C62_4	= 4,
	IMG_C62_5	= 5,
	IMG_C62_6	= 6,
	IMG_C62_7	= 7,
	IMG_C62_8	= 8,
	IMG_C62_9	= 9,
	IMG_C62_10	= 10,
	IMG_C62_11	= 11,
	IMG_C62_12	= 12,
	IMG_C62_13	= 13,
	IMG_C62_14	= 14,
	IMG_C62_15	= 15,
	IMG_C62_16	= 16,
	IMG_C62_17	= 17,
	IMG_C62_18	= 18,
	IMG_C62_19	= 19,
	IMG_C62_20	= 20,
	IMG_C62_21	= 21,
	IMG_C62_22	= 22,

	TOTALC62OFF	= 23
} C62_DEF;

#endif
