//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C66_DATA_H_
#define _C66_DATA_H_

//60프레임 대응 : 원본 키모션(0~7)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C66_DEF {
	//MOTION
	PO_C66_N0	= 0,
	PO_C66_N1	= 1,
	PO_C66_N2	= 2,
	PO_C66_N3	= 3,
	PO_C66_W0	= 4,
	PO_C66_W1	= 5,
	PO_C66_W2	= 6,
	PO_C66_W3	= 7,
	PO_C66_N0_1	= 8,
	PO_C66_N0_2	= 9,
	PO_C66_N0_3	= 10,
	PO_C66_N1_1	= 11,
	PO_C66_N1_2	= 12,
	PO_C66_N1_3	= 13,
	PO_C66_N2_1	= 14,
	PO_C66_N2_2	= 15,
	PO_C66_N2_3	= 16,
	PO_C66_N3_1	= 17,
	PO_C66_N3_2	= 18,
	PO_C66_N3_3	= 19,
	PO_C66_W0_1	= 20,
	PO_C66_W0_2	= 21,
	PO_C66_W0_3	= 22,
	PO_C66_W1_1	= 23,
	PO_C66_W1_2	= 24,
	PO_C66_W1_3	= 25,
	PO_C66_W2_1	= 26,
	PO_C66_W2_2	= 27,
	PO_C66_W2_3	= 28,
	PO_C66_W3_1	= 29,
	PO_C66_W3_2	= 30,
	PO_C66_W3_3	= 31,

	TOTALC66MOTION	= 32,

	//IMAGE
	IMG_C66_0	= 0,
	IMG_C66_1	= 1,
	IMG_C66_2	= 2,
	IMG_C66_3	= 3,
	IMG_C66_4	= 4,
	IMG_C66_5	= 5,
	IMG_C66_6	= 6,
	IMG_C66_7	= 7,
	IMG_C66_8	= 8,
	IMG_C66_9	= 9,
	IMG_C66_10	= 10,
	IMG_C66_11	= 11,
	IMG_C66_12	= 12,
	IMG_C66_13	= 13,
	IMG_C66_14	= 14,
	IMG_C66_15	= 15,

	TOTALC66OFF	= 16
} C66_DEF;

#endif
