//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C67_DATA_H_
#define _C67_DATA_H_

typedef enum _C67_DEF {
	//MOTION
	PO_C67_N0	= 0,
	PO_C67_N1	= 1,
	PO_C67_N2	= 2,
	PO_C67_N3	= 3,

	TOTALC67MOTION	= 4,

	//IMAGE
	IMG_C67_0	= 0,
	IMG_C67_1	= 1,
	IMG_C67_2	= 2,
	IMG_C67_3	= 3,
	IMG_C67_4	= 4,
	IMG_C67_5	= 5,
	IMG_C67_6	= 6,
	IMG_C67_7	= 7,
	IMG_C67_8	= 8,

	TOTALC67OFF	= 9
} C67_DEF;

static const unsigned short c67Off[] = {
	//BMP : C:\SktWipi\Projects\Mos5\Resource\cc.bmp
	114 * _2X, 58 * _2X, 12 * _2X, 11 * _2X,	//0
	76 * _2X, 82 * _2X, 28 * _2X, 1 * _2X,	//1
	51 * _2X, 39 * _2X, 40 * _2X, 20 * _2X,	//2
	91 * _2X, 12 * _2X, 24 * _2X, 12 * _2X,	//3
	91 * _2X, 0 * _2X, 24 * _2X, 12 * _2X,	//4
	0 * _2X, 0 * _2X, 51 * _2X, 49 * _2X,	//5
	51 * _2X, 0 * _2X, 40 * _2X, 39 * _2X,	//6
	0 * _2X, 49 * _2X, 35 * _2X, 34 * _2X,	//7

	//BMP : C:\SKTWIPI\Projects\Mos5\Resource\c67.bmp
	0 * _2X, 0 * _2X, 40 * _2X, 26 * _2X,	//8
};

static const signed short c67MI[] = {
	//PO_C67_N0
	IMG_C67_8, -19 * _2X, -26 * _2X, N00T0X1,	//0

	//PO_C67_N1
	IMG_C67_8, -19 * _2X, -26 * _2X, N00T0X1,	//1

	//PO_C67_N2
	IMG_C67_8, -19 * _2X, -26 * _2X, N00T0X1,	//2

	//PO_C67_N3
	IMG_C67_8, -19 * _2X, -26 * _2X, N00T0X1,	//3

};

static const unsigned short c67MIC[] = {
	0, 1,	//0
	1, 1,	//1
	2, 1,	//2
	3, 1,	//3
};

static const signed short c67MIS[] = {
	-19 * _2X, -26 * _2X, 40 * _2X, 26 * _2X,	//0
	-19 * _2X, -26 * _2X, 40 * _2X, 26 * _2X,	//1
	-19 * _2X, -26 * _2X, 40 * _2X, 26 * _2X,	//2
	-19 * _2X, -26 * _2X, 40 * _2X, 26 * _2X,	//3
};

static const signed short c67CS[] = {
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//0
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//1
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//2
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//3
};

#endif