//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C67_DATA_H_
#define _C67_DATA_H_

//60프레임 대응 : 원본 키모션(0~3)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C67_DEF {
	//MOTION
	PO_C67_N0	= 0,
	PO_C67_N1	= 1,
	PO_C67_N2	= 2,
	PO_C67_N3	= 3,
	PO_C67_N0_1	= 4,
	PO_C67_N0_2	= 5,
	PO_C67_N0_3	= 6,
	PO_C67_N1_1	= 7,
	PO_C67_N1_2	= 8,
	PO_C67_N1_3	= 9,
	PO_C67_N2_1	= 10,
	PO_C67_N2_2	= 11,
	PO_C67_N2_3	= 12,
	PO_C67_N3_1	= 13,
	PO_C67_N3_2	= 14,
	PO_C67_N3_3	= 15,

	TOTALC67MOTION	= 16,

	//IMAGE
	IMG_C67_0	= 0,
	IMG_C67_1	= 1,
	IMG_C67_2	= 2,
	IMG_C67_3	= 3,
	IMG_C67_4	= 4,
	IMG_C67_5	= 5,
	IMG_C67_6	= 6,
	IMG_C67_7	= 7,
	IMG_C67_8	= 8,

	TOTALC67OFF	= 9
} C67_DEF;

#endif
