//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C68_DATA_H_
#define _C68_DATA_H_

typedef enum _C68_DEF {
	//MOTION
	PO_C68_N0	= 0,
	PO_C68_N1	= 1,
	PO_C68_N2	= 2,
	PO_C68_N3	= 3,

	TOTALC68MOTION	= 4,

	//IMAGE
	IMG_C68_0	= 0,
	IMG_C68_1	= 1,
	IMG_C68_2	= 2,
	IMG_C68_3	= 3,
	IMG_C68_4	= 4,
	IMG_C68_5	= 5,
	IMG_C68_6	= 6,
	IMG_C68_7	= 7,
	IMG_C68_8	= 8,
	IMG_C68_9	= 9,
	IMG_C68_10	= 10,
	IMG_C68_11	= 11,
	IMG_C68_12	= 12,

	TOTALC68OFF	= 13
} C68_DEF;

static const unsigned short c68Off[] = {
	//BMP : C:\SktWipi\Projects\Mos5\Resource\cc.bmp
	114 * _2X, 58 * _2X, 12 * _2X, 11 * _2X,	//0
	76 * _2X, 82 * _2X, 28 * _2X, 1 * _2X,	//1
	51 * _2X, 39 * _2X, 40 * _2X, 20 * _2X,	//2
	91 * _2X, 12 * _2X, 24 * _2X, 12 * _2X,	//3
	91 * _2X, 0 * _2X, 24 * _2X, 12 * _2X,	//4
	0 * _2X, 0 * _2X, 51 * _2X, 49 * _2X,	//5
	51 * _2X, 0 * _2X, 40 * _2X, 39 * _2X,	//6
	0 * _2X, 49 * _2X, 35 * _2X, 34 * _2X,	//7

	//BMP : C:\SKTWIPI\Projects\Mos5\Resource\c68.bmp
	0 * _2X, 0 * _2X, 15 * _2X, 18 * _2X,	//8
	15 * _2X, 0 * _2X, 16 * _2X, 17 * _2X,	//9
	8 * _2X, 17 * _2X, 24 * _2X, 13 * _2X,	//10
	0 * _2X, 18 * _2X, 8 * _2X, 13 * _2X,	//11
	16 * _2X, 30 * _2X, 16 * _2X, 8 * _2X,	//12
};

static const signed short c68MI[] = {
	//PO_C68_N0
	IMG_C68_10, -12 * _2X, -27 * _2X, N00T0X1,	//0
	IMG_C68_12, -9 * _2X, -4 * _2X, N00T0X1,	//1
	IMG_C68_9, -7 * _2X, -20 * _2X, N00T0X1,	//2
	IMG_C68_8, -7 * _2X, -34 * _2X, N00T0X1,	//3
	IMG_C68_11, 5 * _2X, -19 * _2X, N00T0X1,	//4

	//PO_C68_N1
	IMG_C68_10, -12 * _2X, -27 * _2X, N00T0X1,	//5
	IMG_C68_12, -9 * _2X, -4 * _2X, N00T0X1,	//6
	IMG_C68_9, -7 * _2X, -20 * _2X, N00T0X1,	//7
	IMG_C68_8, -7 * _2X, -33 * _2X, N00T0X1,	//8
	IMG_C68_11, 5 * _2X, -20 * _2X, N00T0X1,	//9

	//PO_C68_N2
	IMG_C68_10, -13 * _2X, -26 * _2X, N00T0X1,	//10
	IMG_C68_12, -9 * _2X, -4 * _2X, N00T0X1,	//11
	IMG_C68_9, -7 * _2X, -19 * _2X, N00T0X1,	//12
	IMG_C68_8, -7 * _2X, -32 * _2X, N00T0X1,	//13
	IMG_C68_11, 5 * _2X, -19 * _2X, N00T0X1,	//14

	//PO_C68_N3
	IMG_C68_10, -12 * _2X, -26 * _2X, N00T0X1,	//15
	IMG_C68_12, -9 * _2X, -4 * _2X, N00T0X1,	//16
	IMG_C68_9, -7 * _2X, -19 * _2X, N00T0X1,	//17
	IMG_C68_8, -7 * _2X, -33 * _2X, N00T0X1,	//18
	IMG_C68_11, 5 * _2X, -18 * _2X, N00T0X1,	//19

};

static const unsigned short c68MIC[] = {
	0, 5,	//0
	5, 5,	//1
	10, 5,	//2
	15, 5,	//3
};

static const signed short c68MIS[] = {
	-12 * _2X, -34 * _2X, 25 * _2X, 38 * _2X,	//0
	-12 * _2X, -33 * _2X, 25 * _2X, 37 * _2X,	//1
	-13 * _2X, -32 * _2X, 26 * _2X, 36 * _2X,	//2
	-12 * _2X, -33 * _2X, 25 * _2X, 37 * _2X,	//3
};

static const signed short c68CS[] = {
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//0
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//1
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//2
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//3
};

#endif