//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C71_DATA_H_
#define _C71_DATA_H_

//60프레임 대응 : 원본 키모션(0~6)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C71_DEF {
	//MOTION
	PO_C71_N0	= 0,
	PO_C71_N1	= 1,
	PO_C71_N2	= 2,
	PO_C71_N3	= 3,
	PO_C71_W0	= 4,
	PO_C71_W1	= 5,
	PO_C71_W2	= 6,
	PO_C71_N0_1	= 7,
	PO_C71_N0_2	= 8,
	PO_C71_N0_3	= 9,
	PO_C71_N1_1	= 10,
	PO_C71_N1_2	= 11,
	PO_C71_N1_3	= 12,
	PO_C71_N2_1	= 13,
	PO_C71_N2_2	= 14,
	PO_C71_N2_3	= 15,
	PO_C71_N3_1	= 16,
	PO_C71_N3_2	= 17,
	PO_C71_N3_3	= 18,
	PO_C71_W0_1	= 19,
	PO_C71_W0_2	= 20,
	PO_C71_W0_3	= 21,
	PO_C71_W1_W2_1	= 22,
	PO_C71_W1_W2_2	= 23,
	PO_C71_W1_W2_3	= 24,
	PO_C71_W2_1	= 25,
	PO_C71_W2_2	= 26,
	PO_C71_W2_3	= 27,
	PO_C71_W1_W0_1	= 28,
	PO_C71_W1_W0_2	= 29,
	PO_C71_W1_W0_3	= 30,

	TOTALC71MOTION	= 31,

	//IMAGE
	IMG_C71_0	= 0,
	IMG_C71_1	= 1,
	IMG_C71_2	= 2,
	IMG_C71_3	= 3,
	IMG_C71_4	= 4,
	IMG_C71_5	= 5,
	IMG_C71_6	= 6,
	IMG_C71_7	= 7,
	IMG_C71_8	= 8,
	IMG_C71_9	= 9,
	IMG_C71_10	= 10,
	IMG_C71_11	= 11,
	IMG_C71_12	= 12,
	IMG_C71_13	= 13,
	IMG_C71_14	= 14,
	IMG_C71_15	= 15,
	IMG_C71_16	= 16,
	IMG_C71_17	= 17,
	IMG_C71_18	= 18,
	IMG_C71_19	= 19,
	IMG_C71_20	= 20,

	TOTALC71OFF	= 21
} C71_DEF;

#endif
