//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C74_DATA_H_
#define _C74_DATA_H_

typedef enum _C74_DEF {
	//MOTION
	PO_C74_N0	= 0,

	TOTALC74MOTION	= 1,

	//IMAGE
	IMG_C74_0	= 0,
	IMG_C74_1	= 1,
	IMG_C74_2	= 2,
	IMG_C74_3	= 3,
	IMG_C74_4	= 4,
	IMG_C74_5	= 5,
	IMG_C74_6	= 6,
	IMG_C74_7	= 7,
	IMG_C74_8	= 8,

	TOTALC74OFF	= 9
} C74_DEF;

static const unsigned short c74Off[] = {
	//BMP : C:\SktWipi\Projects\Mos5\Resource\cc.bmp
	114 * _2X, 58 * _2X, 12 * _2X, 11 * _2X,	//0
	76 * _2X, 82 * _2X, 28 * _2X, 1 * _2X,	//1
	51 * _2X, 39 * _2X, 40 * _2X, 20 * _2X,	//2
	91 * _2X, 12 * _2X, 24 * _2X, 12 * _2X,	//3
	91 * _2X, 0 * _2X, 24 * _2X, 12 * _2X,	//4
	0 * _2X, 0 * _2X, 51 * _2X, 49 * _2X,	//5
	51 * _2X, 0 * _2X, 40 * _2X, 39 * _2X,	//6
	0 * _2X, 49 * _2X, 35 * _2X, 34 * _2X,	//7

	//BMP : C:\SKTWIPI\Projects\Mos5\Resource\c74.bmp
	0 * _2X, 0 * _2X, 31 * _2X, 22 * _2X,	//8
};

static const signed short c74MI[] = {
	//PO_C74_N0
	IMG_C74_8, -13 * _2X, -22 * _2X, N00T0X1,	//0

};

static const unsigned short c74MIC[] = {
	0, 1,	//0
};

static const signed short c74MIS[] = {
	-13 * _2X, -22 * _2X, 31 * _2X, 22 * _2X,	//0
};

static const signed short c74CS[] = {
	-8 * _2X, -24 * _2X, 16 * _2X, 24 * _2X,		0 * _2X, 0 * _2X, 0 * _2X, 0 * _2X,	//0
};

#endif