//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C74_DATA_H_
#define _C74_DATA_H_

//60프레임 대응 : 원본 키모션(0~0)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C74_DEF {
	//MOTION
	PO_C74_N0	= 0,

	TOTALC74MOTION	= 1,

	//IMAGE
	IMG_C74_0	= 0,
	IMG_C74_1	= 1,
	IMG_C74_2	= 2,
	IMG_C74_3	= 3,
	IMG_C74_4	= 4,
	IMG_C74_5	= 5,
	IMG_C74_6	= 6,
	IMG_C74_7	= 7,
	IMG_C74_8	= 8,

	TOTALC74OFF	= 9
} C74_DEF;

#endif
