//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C80_DATA_H_
#define _C80_DATA_H_

typedef enum _C80_DEF {
	//MOTION
	PO_C80_N0	= 0,

	TOTALC80MOTION	= 1,

	//IMAGE
	IMG_C80_0	= 0,
	IMG_C80_1	= 1,
	IMG_C80_2	= 2,
	IMG_C80_3	= 3,
	IMG_C80_4	= 4,
	IMG_C80_5	= 5,
	IMG_C80_6	= 6,
	IMG_C80_7	= 7,
	IMG_C80_8	= 8,

	TOTALC80OFF	= 9
} C80_DEF;

static const unsigned short c80Off[] = {
	//BMP : C:\SktWipi\Projects\Mos5\Resource\cc.bmp
	114 * _2X, 58 * _2X, 12 * _2X, 11 * _2X,	//0
	76 * _2X, 82 * _2X, 28 * _2X, 1 * _2X,	//1
	51 * _2X, 39 * _2X, 40 * _2X, 20 * _2X,	//2
	91 * _2X, 12 * _2X, 24 * _2X, 12 * _2X,	//3
	91 * _2X, 0 * _2X, 24 * _2X, 12 * _2X,	//4
	0 * _2X, 0 * _2X, 51 * _2X, 49 * _2X,	//5
	51 * _2X, 0 * _2X, 40 * _2X, 39 * _2X,	//6
	0 * _2X, 49 * _2X, 35 * _2X, 34 * _2X,	//7

	//BMP : C:\SKTWIPI\Projects\Mos5\Resource\c80.bmp
	0 * _2X, 0 * _2X, 112 * _2X, 80 * _2X,	//8
};

static const signed short c80MI[] = {
	//PO_C80_N0
	IMG_C80_8, -56 * _2X, -80 * _2X, F00T0X1,	//0

};

static const unsigned short c80MIC[] = {
	0, 1,	//0
};

static const signed short c80MIS[] = {
	-56 * _2X, -80 * _2X, 112 * _2X, 80 * _2X,	//0
};

static const signed short c80CS[] = {
	-56 * _2X, -38 * _2X, 112 * _2X, 39 * _2X,		17 * _2X, 15 * _2X, 0 * _2X, 0 * _2X,	//0
};

#endif