//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C80_DATA_H_
#define _C80_DATA_H_

typedef enum _C80_DEF {
	//MOTION
	PO_C80_N0	= 0,

	TOTALC80MOTION	= 1,

	//IMAGE
	IMG_C80_0	= 0,
	IMG_C80_1	= 1,
	IMG_C80_2	= 2,
	IMG_C80_3	= 3,
	IMG_C80_4	= 4,
	IMG_C80_5	= 5,
	IMG_C80_6	= 6,
	IMG_C80_7	= 7,
	IMG_C80_8	= 8,

	TOTALC80OFF	= 9
} C80_DEF;

#endif