//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C82_DATA_H_
#define _C82_DATA_H_

//60프레임 대응 : 원본 키모션(0~3)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C82_DEF {
	//MOTION
	PO_C82_N0	= 0,
	PO_C82_N1	= 1,
	PO_C82_N2	= 2,
	PO_C82_N3	= 3,
	PO_C82_N0_1	= 4,
	PO_C82_N0_2	= 5,
	PO_C82_N0_3	= 6,
	PO_C82_N1_1	= 7,
	PO_C82_N1_2	= 8,
	PO_C82_N1_3	= 9,
	PO_C82_N2_1	= 10,
	PO_C82_N2_2	= 11,
	PO_C82_N2_3	= 12,
	PO_C82_N3_1	= 13,
	PO_C82_N3_2	= 14,
	PO_C82_N3_3	= 15,

	TOTALC82MOTION	= 16,

	//IMAGE
	IMG_C82_0	= 0,
	IMG_C82_1	= 1,
	IMG_C82_2	= 2,
	IMG_C82_3	= 3,
	IMG_C82_4	= 4,
	IMG_C82_5	= 5,
	IMG_C82_6	= 6,
	IMG_C82_7	= 7,
	IMG_C82_8	= 8,
	IMG_C82_9	= 9,
	IMG_C82_10	= 10,
	IMG_C82_11	= 11,
	IMG_C82_12	= 12,

	TOTALC82OFF	= 13
} C82_DEF;

#endif
