//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C87_DATA_H_
#define _C87_DATA_H_

//60프레임 대응 : 원본 키모션(0~7)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C87_DEF {
	//MOTION
	PO_C87_N0	= 0,
	PO_C87_N1	= 1,
	PO_C87_N2	= 2,
	PO_C87_N3	= 3,
	PO_C87_N4	= 4,
	PO_C87_N5	= 5,
	PO_C87_N6	= 6,
	PO_C87_N7	= 7,
	PO_C87_N4_1	= 8,
	PO_C87_N4_2	= 9,
	PO_C87_N4_3	= 10,
	PO_C87_N5_N4_1	= 11,
	PO_C87_N5_N4_2	= 12,
	PO_C87_N5_N4_3	= 13,
	PO_C87_N5_N6_1	= 14,
	PO_C87_N5_N6_2	= 15,
	PO_C87_N5_N6_3	= 16,
	PO_C87_N6_1	= 17,
	PO_C87_N6_2	= 18,
	PO_C87_N6_3	= 19,
	PO_C87_N7_N6_1	= 20,
	PO_C87_N7_N6_2	= 21,
	PO_C87_N7_N6_3	= 22,
	PO_C87_N7_N0_1	= 23,
	PO_C87_N7_N0_2	= 24,
	PO_C87_N7_N0_3	= 25,
	PO_C87_N0_1	= 26,
	PO_C87_N0_2	= 27,
	PO_C87_N0_3	= 28,
	PO_C87_N1_N0_1	= 29,
	PO_C87_N1_N0_2	= 30,
	PO_C87_N1_N0_3	= 31,
	PO_C87_N1_N2_1	= 32,
	PO_C87_N1_N2_2	= 33,
	PO_C87_N1_N2_3	= 34,
	PO_C87_N2_1	= 35,
	PO_C87_N2_2	= 36,
	PO_C87_N2_3	= 37,
	PO_C87_N3_N2_1	= 38,
	PO_C87_N3_N2_2	= 39,
	PO_C87_N3_N2_3	= 40,
	PO_C87_N3_N4_1	= 41,
	PO_C87_N3_N4_2	= 42,
	PO_C87_N3_N4_3	= 43,

	TOTALC87MOTION	= 44,

	//IMAGE
	IMG_C87_0	= 0,
	IMG_C87_1	= 1,
	IMG_C87_2	= 2,
	IMG_C87_3	= 3,
	IMG_C87_4	= 4,
	IMG_C87_5	= 5,
	IMG_C87_6	= 6,
	IMG_C87_7	= 7,
	IMG_C87_8	= 8,
	IMG_C87_9	= 9,
	IMG_C87_10	= 10,
	IMG_C87_11	= 11,
	IMG_C87_12	= 12,
	IMG_C87_13	= 13,
	IMG_C87_14	= 14,
	IMG_C87_15	= 15,
	IMG_C87_16	= 16,

	TOTALC87OFF	= 17
} C87_DEF;

#endif
