//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C9_DATA_H_
#define _C9_DATA_H_

//60프레임 대응 : 원본 키모션(0~4)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C9_DEF {
	//MOTION
	PO_C9_N0	= 0,
	PO_C9_D0	= 1,
	PO_C9_D1	= 2,
	PO_C9_U0	= 3,
	PO_C9_U1	= 4,
	PO_C9_D0_1	= 5,
	PO_C9_D0_2	= 6,
	PO_C9_D0_3	= 7,
	PO_C9_D1_D0_1	= 8,
	PO_C9_D1_D0_2	= 9,
	PO_C9_D1_D0_3	= 10,
	PO_C9_D1_U0_1	= 11,
	PO_C9_D1_U0_2	= 12,
	PO_C9_D1_U0_3	= 13,
	PO_C9_U0_1	= 14,
	PO_C9_U0_2	= 15,
	PO_C9_U0_3	= 16,
	PO_C9_U1_U0_1	= 17,
	PO_C9_U1_U0_2	= 18,
	PO_C9_U1_U0_3	= 19,
	PO_C9_U1_N0_1	= 20,
	PO_C9_U1_N0_2	= 21,
	PO_C9_U1_N0_3	= 22,
	PO_C9_N0_1	= 23,
	PO_C9_N0_2	= 24,
	PO_C9_N0_3	= 25,

	TOTALC9MOTION	= 26,

	//IMAGE
	IMG_C9_0	= 0,
	IMG_C9_1	= 1,
	IMG_C9_2	= 2,
	IMG_C9_3	= 3,
	IMG_C9_4	= 4,
	IMG_C9_5	= 5,
	IMG_C9_6	= 6,
	IMG_C9_7	= 7,
	IMG_C9_8	= 8,
	IMG_C9_9	= 9,
	IMG_C9_10	= 10,
	IMG_C9_11	= 11,
	IMG_C9_12	= 12,
	IMG_C9_13	= 13,

	TOTALC9OFF	= 14
} C9_DEF;

#endif
