//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C9_DATA_H_
#define _C9_DATA_H_

typedef enum _C9_DEF {
	//MOTION
	PO_C9_N0	= 0,
	PO_C9_D0	= 1,
	PO_C9_D1	= 2,
	PO_C9_U0	= 3,
	PO_C9_U1	= 4,

	TOTALC9MOTION	= 5,

	//IMAGE
	IMG_C9_0	= 0,
	IMG_C9_1	= 1,
	IMG_C9_2	= 2,
	IMG_C9_3	= 3,
	IMG_C9_4	= 4,
	IMG_C9_5	= 5,
	IMG_C9_6	= 6,
	IMG_C9_7	= 7,
	IMG_C9_8	= 8,
	IMG_C9_9	= 9,
	IMG_C9_10	= 10,
	IMG_C9_11	= 11,
	IMG_C9_12	= 12,
	IMG_C9_13	= 13,

	TOTALC9OFF	= 14
} C9_DEF;

static const unsigned short c9Off[] = {
	//BMP : C:\SktWipi\Projects\Mos5\Resource\cc.bmp
	114 * _2X, 58 * _2X, 12 * _2X, 11 * _2X,	//0
	76 * _2X, 82 * _2X, 28 * _2X, 1 * _2X,	//1
	51 * _2X, 39 * _2X, 40 * _2X, 20 * _2X,	//2
	91 * _2X, 12 * _2X, 24 * _2X, 12 * _2X,	//3
	91 * _2X, 0 * _2X, 24 * _2X, 12 * _2X,	//4
	0 * _2X, 0 * _2X, 51 * _2X, 49 * _2X,	//5
	51 * _2X, 0 * _2X, 40 * _2X, 39 * _2X,	//6
	0 * _2X, 49 * _2X, 35 * _2X, 34 * _2X,	//7

	//BMP : C:\SKTWIPI\Projects\Mos5\Resource\c9.bmp
	0 * _2X, 0 * _2X, 24 * _2X, 37 * _2X,	//8
	24 * _2X, 0 * _2X, 26 * _2X, 31 * _2X,	//9
	50 * _2X, 24 * _2X, 27 * _2X, 28 * _2X,	//10
	50 * _2X, 0 * _2X, 26 * _2X, 24 * _2X,	//11
	24 * _2X, 31 * _2X, 20 * _2X, 16 * _2X,	//12
	0 * _2X, 37 * _2X, 20 * _2X, 15 * _2X,	//13
};

static const signed short c9MI[] = {
	//PO_C9_N0
	IMG_C9_8, -12 * _2X, -33 * _2X, N00T0X1,	//0

	//PO_C9_D0
	IMG_C9_9, -13 * _2X, -27 * _2X, N00T0X1,	//1

	//PO_C9_D1
	IMG_C9_10, -13 * _2X, -24 * _2X, N00T0X1,	//2

	//PO_C9_U0
	IMG_C9_12, -10 * _2X, -12 * _2X, N00T0X1,	//3
	IMG_C9_11, -13 * _2X, -34 * _2X, N00T0X1,	//4

	//PO_C9_U1
	IMG_C9_13, -10 * _2X, -11 * _2X, N00T0X1,	//5
	IMG_C9_11, -13 * _2X, -33 * _2X, N00T0X1,	//6

};

static const unsigned short c9MIC[] = {
	0, 1,	//0
	1, 1,	//1
	2, 1,	//2
	3, 2,	//3
	5, 2,	//4
};

static const signed short c9MIS[] = {
	-12 * _2X, -33 * _2X, 24 * _2X, 37 * _2X,	//0
	-13 * _2X, -27 * _2X, 26 * _2X, 31 * _2X,	//1
	-13 * _2X, -24 * _2X, 27 * _2X, 28 * _2X,	//2
	-13 * _2X, -34 * _2X, 26 * _2X, 38 * _2X,	//3
	-13 * _2X, -33 * _2X, 26 * _2X, 37 * _2X,	//4
};

static const signed short c9CS[] = {
	-12 * _2X, -28 * _2X, 24 * _2X, 28 * _2X,		0, 0, 0, 0,	//0
	-12 * _2X, -28 * _2X, 24 * _2X, 28 * _2X,		0, 0, 0, 0,	//1
	-12 * _2X, -28 * _2X, 24 * _2X, 28 * _2X,		-12 * _2X, -28 * _2X, 24 * _2X, 28 * _2X,	//2
	-12 * _2X, -28 * _2X, 24 * _2X, 28 * _2X,		0, 0, 0, 0,	//3
	-12 * _2X, -28 * _2X, 24 * _2X, 28 * _2X,		-12 * _2X, -28 * _2X, 24 * _2X, 28 * _2X,	//4
};

#endif