//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C94_DATA_H_
#define _C94_DATA_H_

typedef enum _C94_DEF {
	//MOTION
	PO_C94_N0	= 0,
	PO_C94_N1	= 1,
	PO_C94_N2	= 2,
	PO_C94_N3	= 3,

	TOTALC94MOTION	= 4,

	//IMAGE
	IMG_C94_0	= 0,
	IMG_C94_1	= 1,
	IMG_C94_2	= 2,
	IMG_C94_3	= 3,
	IMG_C94_4	= 4,
	IMG_C94_5	= 5,
	IMG_C94_6	= 6,
	IMG_C94_7	= 7,
	IMG_C94_8	= 8,
	IMG_C94_9	= 9,
	IMG_C94_10	= 10,
	IMG_C94_11	= 11,
	IMG_C94_12	= 12,

	TOTALC94OFF	= 13
} C94_DEF;

static const unsigned short c94Off[] = {
	//BMP : C:\SktWipi\Projects\Mos5\Resource\cc.bmp
	114 * _2X,  58 * _2X,  12 * _2X,  11 * _2X, 	//0
	76 * _2X,  82 * _2X,  28 * _2X,  1 * _2X, 	//1
	51 * _2X,  39 * _2X,  40 * _2X,  20 * _2X, 	//2
	91 * _2X,  12 * _2X,  24 * _2X,  12 * _2X, 	//3
	91 * _2X,  0 * _2X,  24 * _2X,  12 * _2X, 	//4
	0 * _2X,  0 * _2X,  51 * _2X,  49 * _2X, 	//5
	51 * _2X,  0 * _2X,  40 * _2X,  39 * _2X, 	//6
	0 * _2X,  49 * _2X,  35 * _2X,  34 * _2X, 	//7

	//BMP : C:\SKTWIPI\Projects\Mos5\Resource\c94.bmp
	0 * _2X,  0 * _2X,  15 * _2X,  18 * _2X, 	//8
	15 * _2X,  0 * _2X,  15 * _2X,  16 * _2X, 	//9
	0 * _2X,  18 * _2X,  15 * _2X,  11 * _2X, 	//10
	15 * _2X,  18 * _2X,  10 * _2X,  11 * _2X, 	//11
	25 * _2X,  18 * _2X,  6 * _2X,  11 * _2X, 	//12
};

static const signed short c94MI[] = {
	//PO_C94_N0
	IMG_C94_10, -8 * _2X, -7 * _2X,  N00T0X1,	//0
	IMG_C94_9, -8 * _2X, -21 * _2X,  N00T0X1,	//1
	IMG_C94_8, -8 * _2X, -35 * _2X,  N00T0X1,	//2
	IMG_C94_11, -16 * _2X, -22 * _2X,  N00T0X1,	//3
	IMG_C94_12, 4 * _2X, -17 * _2X,  N00T0X1,	//4

	//PO_C94_N1
	IMG_C94_10, -8 * _2X, -7 * _2X,  N00T0X1,	//5
	IMG_C94_9, -8 * _2X, -21 * _2X,  N00T0X1,	//6
	IMG_C94_8, -8 * _2X, -34 * _2X,  N00T0X1,	//7
	IMG_C94_11, -16 * _2X, -23 * _2X,  N00T0X1,	//8
	IMG_C94_12, 4 * _2X, -18 * _2X,  N00T0X1,	//9

	//PO_C94_N2
	IMG_C94_10, -8 * _2X, -7 * _2X,  N00T0X1,	//10
	IMG_C94_9, -8 * _2X, -20 * _2X,  N00T0X1,	//11
	IMG_C94_8, -8 * _2X, -33 * _2X,  N00T0X1,	//12
	IMG_C94_11, -15 * _2X, -23 * _2X,  N00T0X1,	//13
	IMG_C94_12, 4 * _2X, -17 * _2X,  N00T0X1,	//14

	//PO_C94_N3
	IMG_C94_10, -8 * _2X, -7 * _2X,  N00T0X1,	//15
	IMG_C94_9, -8 * _2X, -20 * _2X,  N00T0X1,	//16
	IMG_C94_8, -8 * _2X, -34 * _2X,  N00T0X1,	//17
	IMG_C94_11, -15 * _2X, -22 * _2X,  N00T0X1,	//18
	IMG_C94_12, 4 * _2X, -16 * _2X,  N00T0X1,	//19

};

static const unsigned short c94MIC[] = {
	0, 5,	//0
	5, 5,	//1
	10, 5,	//2
	15, 5,	//3
};

static const signed short c94MIS[] = {
	-16 * _2X,  -35 * _2X,  26 * _2X,  39 * _2X, 	//0
	-16 * _2X,  -34 * _2X,  26 * _2X,  38 * _2X, 	//1
	-15 * _2X,  -33 * _2X,  25 * _2X,  37 * _2X, 	//2
	-15 * _2X,  -34 * _2X,  25 * _2X,  38 * _2X, 	//3
};

static const signed short c94CS[] = {
	-8 * _2X,  -24 * _2X,  16 * _2X,  24 * _2X, 		0 * _2X,  0 * _2X,  0 * _2X,  0 * _2X, 	//0
	-8 * _2X,  -24 * _2X,  16 * _2X,  24 * _2X, 		0 * _2X,  0 * _2X,  0 * _2X,  0 * _2X, 	//1
	-8 * _2X,  -24 * _2X,  16 * _2X,  24 * _2X, 		0 * _2X,  0 * _2X,  0 * _2X,  0 * _2X, 	//2
	-8 * _2X,  -24 * _2X,  16 * _2X,  24 * _2X, 		0 * _2X,  0 * _2X,  0 * _2X,  0 * _2X, 	//3
};

#endif