//*** Generated by Divider ***//
#pragma once
#include "../Def.h"

#ifndef _C97_DATA_H_
#define _C97_DATA_H_

//60프레임 대응 : 원본 키모션(0~11)은 그대로 두고
//뒤에 4분할 중간모션을 덧붙였다. 앞쪽 인덱스는 다른 cmf가 참조할 수 있다.
typedef enum _C97_DEF {
	//MOTION
	PO_C97_N0	= 0,
	PO_C97_N1	= 1,
	PO_C97_N2	= 2,
	PO_C97_N3	= 3,
	PO_C97_M0	= 4,
	PO_C97_M1	= 5,
	PO_C97_M2	= 6,
	PO_C97_M3	= 7,
	PO_C97_M4	= 8,
	PO_C97_M5	= 9,
	PO_C97_M6	= 10,
	PO_C97_M7	= 11,
	PO_C97_N0_1	= 12,
	PO_C97_N0_2	= 13,
	PO_C97_N0_3	= 14,
	PO_C97_N1_1	= 15,
	PO_C97_N1_2	= 16,
	PO_C97_N1_3	= 17,
	PO_C97_N2_1	= 18,
	PO_C97_N2_2	= 19,
	PO_C97_N2_3	= 20,
	PO_C97_N3_1	= 21,
	PO_C97_N3_2	= 22,
	PO_C97_N3_3	= 23,
	PO_C97_M0_1	= 24,
	PO_C97_M0_2	= 25,
	PO_C97_M0_3	= 26,
	PO_C97_M1_1	= 27,
	PO_C97_M1_2	= 28,
	PO_C97_M1_3	= 29,
	PO_C97_M2_1	= 30,
	PO_C97_M2_2	= 31,
	PO_C97_M2_3	= 32,
	PO_C97_M3_M0_1	= 33,
	PO_C97_M3_M0_2	= 34,
	PO_C97_M3_M0_3	= 35,
	PO_C97_M3_M4_1	= 36,
	PO_C97_M3_M4_2	= 37,
	PO_C97_M3_M4_3	= 38,
	PO_C97_M4_1	= 39,
	PO_C97_M4_2	= 40,
	PO_C97_M4_3	= 41,
	PO_C97_M5_1	= 42,
	PO_C97_M5_2	= 43,
	PO_C97_M5_3	= 44,
	PO_C97_M6_1	= 45,
	PO_C97_M6_2	= 46,
	PO_C97_M6_3	= 47,
	PO_C97_M7_M4_1	= 48,
	PO_C97_M7_M4_2	= 49,
	PO_C97_M7_M4_3	= 50,
	PO_C97_M7_M0_1	= 51,
	PO_C97_M7_M0_2	= 52,
	PO_C97_M7_M0_3	= 53,

	TOTALC97MOTION	= 54,

	//IMAGE
	IMG_C97_0	= 0,
	IMG_C97_1	= 1,
	IMG_C97_2	= 2,
	IMG_C97_3	= 3,
	IMG_C97_4	= 4,
	IMG_C97_5	= 5,
	IMG_C97_6	= 6,
	IMG_C97_7	= 7,
	IMG_C97_8	= 8,
	IMG_C97_9	= 9,
	IMG_C97_10	= 10,
	IMG_C97_11	= 11,
	IMG_C97_12	= 12,
	IMG_C97_13	= 13,
	IMG_C97_14	= 14,
	IMG_C97_15	= 15,
	IMG_C97_16	= 16,
	IMG_C97_17	= 17,
	IMG_C97_18	= 18,

	TOTALC97OFF	= 19
} C97_DEF;

#endif
