#pragma once
// =============================================================
// AUTO GENERATED - DO NOT EDIT
// Source : Definitions.xlsx
// Sheet  : GameConfig
// Date   : 2026-02-26 17:21
// =============================================================

typedef enum _gameConfig {
	TOTALRAIDBOX = 4,

	//상태 데이터 인덱스 디파인
	STATUS_CHANGE_BEFORE = 0,
	STATUS_CHANGE_AFTER,
	STATUS_CHANGE_CONDITION,
	STATUS_CHANGE_DATA1,
	STATUS_CHANGE_DATA2,
	STATUS_CHANGE_DATA3,
	STATUS_CHANGE_LENGTH,

	MAXSTATUS = 19,

	//초기화 플래그 디파인
	SET_DIR_PLAYER = 64,
	SET_DIR_RANDOM = 128,
	SET_DIR_OPPOSITE = 192,

	SET_MAINFRAME_RANDOM8 = 1,
	SET_MAINFRAME_RANDOM12,
	RECOVER_HP,

	//상태변경 조건의 유형
	DISTANCE_CHECK_XY = 1,
	DISTANCE_OUT_XY,
	ATTACK_CHECK,
	COMPARE_FRAME,
	COMPARE_LESSHP,
	COMPARE_MOREHP,
	COMPARE_LESSFRAME,
	DIR_SAME_PLAYER,
	DIR_DIFFER_PLAYER,
	RANDOM,
	LESS_SHIELD,

	LEFT_WALK = 0,
	RIGHT_WALK,
	ROOF_LEFT,
	ROOF_RIGHT,
	LEFT_SIDE_DOWN,
	RIGHT_SIDE_DOWN,
	LEFT_SIDE_UP,
	RIGHT_SIDE_UP,

	//조건 데이터 유형
	EQUAL_MAINFRAME = -1,

	MOTIONDIV = 1,
	ROULETTEDIV = 5,
	SPREADDIV = 4,

	TSIZE = 16 * _2X,

	MINCREW = 3,
	MAXCREW = 6,
	MAXMONCREW = 3,
	MAXHEROCREW = 2,


	//오브젝트
	OBJIMGGAP = 4 * _2X,

#ifdef MOTIONCAPTURE
	MAXPLAYER = 1,
#else
	//MAXPLAYER = 1,
	MAXPLAYER = 3,//TOTALCMF,//로빈 디아나, 맥스
#endif
	MAXPLAYEROBJ = 10,
	MAXENEMY = 50,//최대 적 개수
	ONEWAVEENEMY = 1,//웨이브당 3
	MAXENEMYOBJ = 5,//적 한마리가 사용하는 최대 오브젝트수
	MAXNEUTRAL = 20,
	MAXITEMOBJ = 50,
	MAXSOLDIER = 4,//하나는 무료, 나머지는 유료
	STAGEENEMY = 1,
	TOTALREEL = 3,

	TOTALMENUSTAT = 27,

	TOTALMENUOPTION = 27,
	CHARINFOPAGELINE = 10,

	CREW_BOY = 0,
	CREW_GIRL,
	CREW_MAID,
	CREW_SCHOLAR,
	CREW_GRANDMA,
	CREW_GRANDFA,
	CREW_MAN,
	CREW_WOMAN,
	CREW_UNCLE,
	CREW_AUNT,
	CREW_SEAUNCLE,
	CREW_SEASOLDIER,
	CREW_MILESE,
	CREW_ALMA,
	CREW_GALLAND,
	CREW_ELFUNCLE,
	CREW_ELFAUNT,
	CREW_ELFBOY,
	CREW_ELFGIRL,
	CREW_NOBLEMAN,
	CREW_SEBASTIAN,
	CREW_MONICA,
	CREW_FATMAN,
	CREW_SEABOY,
	CREW_LUISE,
	CREW_DOBEL,
	CREW_GAGEL,
	CREW_ADELKNIGHT,
	CREW_DOG,
	CREW_WITCH,
	CREW_BISTRO,
	CREW_CRAFTMAN,
	CREW_FISHING,
	CREW_ELFWOMAN,
	CREW_ELFMAN,
	CREW_FRAUD,
	CREW_ELFGRANDFA,
	CREW_ELFMAGIC,
	CREW_ELFDANCER,
	CREW_DARIAN,
	CREW_CREW,
	CREW_TRAVEL,
	CREW_ITEM,
	CREW_DONALD,
	CREW_DURAK,
	CREW_MAP,
	CREW_ELFDARK,
	CREW_NEZAR,
	CREW_KNIGHT,
	CREW_EVAN,
	CREW_WOMANGHOST,
	CREW_MANGHOST,
	CREW_AUSTIN,
	CREW_ELEIN,
	CREW_DELPIOS,
	CREW_CHEF,
	CREW_USERQUEST,
	CREW_NETITEM,
	CREW_CAPTAIN,
	CREW_BUNNyGIRL,
	CREW_ELKEIN,
	CREW_LABETH,
	CREW_LORA,
	CREW_KING,

	TOTAL_CREW,

	//SPECIAL	= 0,
	ROBIN = 0,
	DIANA,
	MAXX,
	TOTALCHAR,
	TOTALPLAYER = TOTALCHAR,
	PLAYER = ROBIN,
	CREW = PLAYER + MAXPLAYER,//솔저 몬스터는 3번칸에
	PLAYERALL = CREW + MAXCREW,//TOTALPLAYER
	CASTLEALL = CREW + TOTAL_CREW,
	SOLDIER = CREW + TOTAL_CREW,
	ITEMBOX = SOLDIER + MAXENEMYOBJ,//드래곤을 소환하는 경우
	NPC,//대화나 구해주리플렉터는 NPC나 이런애들
	BULLET,
	ENEMYUSEROBJ = BULLET + MAXPLAYER * MAXPLAYEROBJ,
	ENEMY,
	NEUTRAL = ENEMY + MAXENEMY * MAXENEMYOBJ,//PVP를 하는 대상 오브젝트
	ITEMOBJ = NEUTRAL + MAXNEUTRAL,
	TOTALOBJECT = ITEMOBJ + TOTAL_CREW + TOTALCHAR,

	//컨트롤마크
	TOTALCONTROLMARK = (TOTALCHAR + MAXCREW) * TOTALREEL,
	//카드마크
	TOTALCARDMARK = 20,
	//스킬마크
	TOTALSKILLMARK = 20,
	//장비마크
	TOTALEQUIPMARK = 20,
	//리워드마크
	TOTALREWARDMARK = 20,
	//보상상자마크
	TOTALBOXMARK = 20,
	//골드알파마크
	TOTALGOLDALPHAMARK = 30,

	TOTALBUBBLE = 41,

	OPENEDITEMCNT = 24,

	OPENEDMAXITEMCNT = 35,

	DROPITEMTYPE = 8,

	CREWMAXUPGRADELV = 5,
	CREWMAXLV = 10,

	CREWUPGRADEPER = 10,
	CREWREPAIRPER = 10,

	BATTLEREWARDGOLDDIV = 10,

	UPGRADEPIECECNT = 5,

	LV_COLLECTION = 100,

	ITEMDRAW_CURRENT = 0,
	ITEMDRAW_NEXTLV,
	ITEMDRAW_NEXTSTAR,
	ITEMDRAW_ARENA,

	GOLDRATIO = 10,
	EQUIPGEMRATIO = 1,
	STAGEGOLDRATIO = 10,
	SOCKETGOLDRATIO = 50,	//소켓장착시 골드 소모비율(보석 등급 비율 * SOCKETGOLDRATIO)
	ENCHANTGOLDRATIO = 8,	//강화시 골드 소모비율(아이템 가격 * 강화레벨 / ENCHANTGOLDRATIO)
	RECIPEGOLDRATIO = 2,	//제작시 골드 소모비율(아이템 가격 / RECIPEGOLDRATIO)

	ENCHANTSUCCESSRATE = 80,//강화성공 확률(%)
	ENCHANTITEMRATE = 12,	//강화시 재료비율 : (제작재료 * 강화레벨 / ENCHANTITEMRATE)
	RECIPEITEMRATE = 50,
	MAXENCHANT = 50,
	SOCKETPRICE = 10,

	GREATSUCESS = 100,
	NORMALSUCCESS = 10,

	MAXLOG = 100,
	MAXBATTLELOG = 100,

} GAMECONFIG;