param([string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path)

# Inventory-only silhouettes; original w2_N combat art is untouched.
Add-Type -AssemblyName System.Drawing
$outDir = Join-Path $Root 'Resources\res\inventory_boomerang'
New-Item -ItemType Directory -Path $outDir -Force | Out-Null
$records = [System.Collections.Generic.List[object]]::new()

for ($n = 1; $n -le 35; $n++) {
    $cols = if ($n -ge 30) { 3 } else { 2 }
    $rows = if ($n -le 10) { 2 } else { 3 }
    $sourcePath = if ($n -le 10) { Join-Path $PSScriptRoot "redrawn\$n.png" }
                  else { Join-Path $Root "Resources\res\w2_$n.png" }
    $source = [System.Drawing.Bitmap]::new($sourcePath)
    $target = [System.Drawing.Bitmap]::new(($cols * 32), ($rows * 32), [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $g = [System.Drawing.Graphics]::FromImage($target)
    $g.Clear([System.Drawing.Color]::Transparent)
    $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $g.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
    $g.CompositingMode = [System.Drawing.Drawing2D.CompositingMode]::SourceCopy
    $g.DrawImage($source, [System.Drawing.Rectangle]::new(2, 2, $target.Width - 4, $target.Height - 4))
    $g.Dispose()
    $source.Dispose()

    # Occupancy follows the visible weapon. A transparent corner stays empty,
    # but never punch a mandatory hole through the artwork itself.
    $mask = 0; $removedPixels = 0
    $minimum = if ($n -le 10) { 60 } else { 30 }
    for ($row = 0; $row -lt $rows; $row++) {
        for ($col = 0; $col -lt $cols; $col++) {
            $count = 0
            for ($y = ($rows - 1 - $row) * 32; $y -lt ($rows - $row) * 32; $y++) {
                for ($x = $col * 32; $x -lt ($col + 1) * 32; $x++) {
                    if ($target.GetPixel($x, $y).A -gt 16) { $count++ }
                }
            }
            if ($count -ge $minimum) { $mask = $mask -bor (1 -shl ($row * 4 + $col)) }
            else {
                $removedPixels += $count
                for ($y = ($rows - 1 - $row) * 32; $y -lt ($rows - $row) * 32; $y++) {
                    for ($x = $col * 32; $x -lt ($col + 1) * 32; $x++) {
                        $target.SetPixel($x, $y, [System.Drawing.Color]::Transparent)
                    }
                }
            }
        }
    }
    $target.Save((Join-Path $outDir "$n.png"), [System.Drawing.Imaging.ImageFormat]::Png)
    $target.Dispose()
    $records.Add([pscustomobject]@{ id=$n; cols=$cols; rows=$rows; cells=$mask; lostPixels=$removedPixels })
}

$header = [System.Collections.Generic.List[string]]::new()
$header.Add('// Generated by tools/boomerangs/build_inventory_boomerangs.ps1.')
$header.Add('#pragma once')
$header.Add('struct InventoryBoomerangShape { int cols, rows; unsigned short cells; };')
$header.Add('static const InventoryBoomerangShape kInventoryBoomerangShapes[35] = {')
foreach ($record in $records) {
    $hex = $record.cells.ToString('X')
    $header.Add("    {$($record.cols), $($record.rows), 0x$hex}, // w2_$($record.id)")
}
$header.Add('};')
[System.IO.File]::WriteAllLines((Join-Path $Root 'Classes\Data\InventoryBoomerangShapes.h'), $header, [System.Text.UTF8Encoding]::new($false))
$records | ConvertTo-Json -Depth 2 | Set-Content -LiteralPath (Join-Path $Root 'Resources\res\inventory_boomerang\manifest.json') -Encoding UTF8
Write-Output 'Built 35 inventory-only boomerang sprites'
