"""Bake an additive CMF sword track without changing the packed 4-short records.

The current CMF blob remains authoritative. Signatures reject stale sidecar rows.
Edit content/swords/pose_overrides.json to change handX/handY/angleDegrees/flipX.
"""
from pathlib import Path
import json
import math
import re

ROOT = Path(__file__).resolve().parents[2]


def array(text, name):
    body = re.search(re.escape(name) + r'_builtin\[\].*?\{(.*?)\};', text, re.S)[1]
    return [int(n) for n in re.findall(r'-?\d+', re.sub(r'//[^\n]*', '', body))]


def decode(part):
    img, x, y, flags = part
    diag = img == 108
    w, h, gx, gy = (380, 290, 18, 268) if diag else (410, 220, 16, 110)
    q, flip = (flags & 6) >> 1, bool(flags & 1)
    scale = (flags >> 6) + 1
    ax, ay = [(0, 0), ((w, 0) if flip else (0, h)), (w, h),
              ((0, h) if flip else (w, 0))][q]
    gx, gy = (w-gx if flip else gx)-ax, gy-ay
    r = math.radians((-1 if flip else 1)*q*90)
    return dict(handX=x+(gx*math.cos(r)-gy*math.sin(r))*scale,
                handY=y+(gx*math.sin(r)+gy*math.cos(r))*scale,
                angleDegrees=(-1 if flip else 1)*(q*90+(60 if diag else 90)),
                scale=scale, opacity=(4-((flags & 0x30) >> 4))/4, flipX=flip)


def signature(parts):
    h = 2166136261
    for part in parts:
        for v in part:
            h = ((h ^ (v & 65535))*16777619) & 0xffffffff
    return h


def build():
    blob = (ROOT/'Classes/Data/CmfBlob.cpp').read_text(encoding='utf-8-sig')
    header = (ROOT/'Classes/Cmf/c0.h').read_text(encoding='utf-8-sig')
    mi = array(blob, 'cmfMotionImgBlob')
    cnt = array(blob, 'cmfMotionImgCntBlob')
    names = {k:int(v) for k,v in re.findall(r'(PO_C0_\w+)\s*=\s*(\d+)',header)}
    count = max(names.values())+1
    motions = [[mi[i:i+4] for i in range(cnt[m*2]*4,(cnt[m*2]+cnt[m*2+1])*4,4)] for m in range(count)]
    poses = [next((decode(p) for p in parts if p[0] in (108,109)),None) for parts in motions]
    overrides = json.loads((ROOT/'content/swords/pose_overrides.json').read_text(encoding='utf-8'))
    def apply_overrides():
        for name, fields in overrides.items():
            assert name in names and poses[names[name]] is not None, name
            assert set(fields) <= {'handX','handY','angleDegrees','scale','opacity','flipX'}, name
            poses[names[name]].update(fields)
    apply_overrides()
    interpolated = set()
    body = re.search(r'\bc0Chain\[\]\s*=\s*\{(.*?)\};',header,re.S)[1]
    chains = [[names[n] for n in re.findall(r'PO_C0_\w+',group)]
              for group in re.split(r'//[^\n]*\n',body)]
    loops = array(blob, 'cmfHeroLoopBlob')[:64]
    sequences = chains + [loops[i:i+16]+[loops[i]] for i in range(0,64,16)]
    for seq in sequences:
        if seq:
            for i in range(0,len(seq)-4,4):
                a,b = poses[seq[i]],poses[seq[i+4]]
                if a is None or b is None: continue
                delta = (b['angleDegrees']-a['angleDegrees']+180)%360-180
                for step in (1,2,3):
                    mid = seq[i+step]
                    if poses[mid] is None: continue
                    t = step/4
                    p = {k:a[k]+(b[k]-a[k])*t for k in ('handX','handY','scale','opacity')}
                    p['angleDegrees'] = a['angleDegrees']+delta*t
                    p['flipX'] = a['flipX'] if t<.5 else b['flipX']
                    poses[mid]=p
                    interpolated.add(mid)
    apply_overrides()
    lines = ['// Generated by tools/swords/build_sword_poses.py.', '#pragma once',
             '#include "../CmfSwordTransform.h"',
             'struct CmfSwordTrackEntry { unsigned int signature; CmfSwordPose pose; };',
             'static const CmfSwordTrackEntry kRobinSwordTrack[] = {']
    inverse = {v:k for k,v in names.items()}
    review = []
    for m,p in enumerate(poses):
        if p is None:
            lines.append('    {0u, {}}, // '+inverse[m])
            continue
        sig = signature(motions[m])
        values = ', '.join(f'{p[k]:.4f}f' for k in ('handX','handY','angleDegrees','scale','opacity'))
        lines.append(f'    {{{sig}u, {{{values}, {str(p["flipX"]).lower()}, true}}}}, // {inverse[m]}')
        review.append(dict(motion=m,name=inverse[m],signature=sig,interpolated=m in interpolated,**p))
    lines += ['};','']
    (ROOT/'Classes/Data/RobinSwordTrack.h').write_text('\n'.join(lines),encoding='utf-8')
    (ROOT/'content/swords/poses.json').write_text(json.dumps(review,indent=2)+'\n',encoding='utf-8')
    print(f'{len(review)} sword poses, {len(interpolated)} interpolated; {count} total motions')


if __name__ == '__main__':
    build()
