param([string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path)

# Rebuild the 35 inventory/held sprites from the approved concept atlas.
# Tile pixels and hand anchors share one coordinate system with SwordSprites.h.
Add-Type -AssemblyName System.Drawing
$atlasPath = Join-Path $Root 'content\swords\remodel\source-atlas.png'
$atlas = [System.Drawing.Bitmap]::new($atlasPath)
$originalTree = [System.Drawing.Bitmap]::new((Join-Path $Root 'content\swords\remodel\tree21-original.png'))
$res = Join-Path $Root 'Resources\res'
$headerPath = Join-Path $Root 'Classes\Data\SwordSprites.h'
$manifestPath = Join-Path $Root 'content\swords\remodel\manifest.json'
$rowEdges = @(0, 280, 560, 850, 1172, 1516)

# Inventory progression: short, slim, broad, and the tree T silhouette.
$shapes = @(
    '1x2','1x2','1x2','2x2','1x3','2x2','2x2',
    '2x2','2x2','2x3','2x3','2x3','2x3','2x3',
    '2x3','2x3','2x3','1x4','2x3','2x3','Ttree',
    '2x3','2x3','2x3','2x3','2x4','2x3','2x3',
    '2x3','2x4','2x4','2x4','2x4','2x4','2x4'
)
if ($shapes.Count -ne 35) { throw 'Expected 35 sword shapes' }

$header = [System.Collections.Generic.List[string]]::new()
$header.Add('// Generated by tools/swords/build_remodeled_swords.ps1. Pixel coordinates: top-left origin.')
$header.Add('#pragma once')
$header.Add('enum { SWORD_TILE_SIZE = 32 };')
$header.Add('// Indexed by item detail: [detail * 2] columns, [detail * 2 + 1] rows.')
$header.Add('static const int swordTileSize[35 * 2] = {')
$records = [System.Collections.Generic.List[object]]::new()

try {
    for ($n = 1; $n -le 35; $n++) {
        $shape = $shapes[$n - 1]
        $cols = 2; $rows = 3; $cells = 0
        switch ($shape) {
            '1x2' { $cols = 1; $rows = 2 }
            '1x3' { $cols = 1; $rows = 3 }
            '1x4' { $cols = 1; $rows = 4 }
            '2x2' { $cols = 2; $rows = 2 }
            '2x4' { $cols = 2; $rows = 4 }
            'Ttree' { $cols = 3; $rows = 4; $cells = 0x7722 }
        }
        $width = $cols * 32; $height = $rows * 32
        $row = [int][Math]::Floor(($n - 1) / 7)
        $col = ($n - 1) % 7
        $left = [int][Math]::Floor($col * $atlas.Width / 7)
        $right = [int][Math]::Floor(($col + 1) * $atlas.Width / 7)
        $top = $rowEdges[$row]
        $bottom = $rowEdges[$row + 1]
        $minX = $right; $minY = $bottom; $maxX = -1; $maxY = -1
        for ($y = $top; $y -lt $bottom; $y++) {
            for ($x = $left; $x -lt $right; $x++) {
                if ($atlas.GetPixel($x, $y).A -gt 24) {
                    $minX = [Math]::Min($minX, $x)
                    $minY = [Math]::Min($minY, $y)
                    $maxX = [Math]::Max($maxX, $x)
                    $maxY = [Math]::Max($maxY, $y)
                }
            }
        }
        if ($maxX -lt $minX) { throw "Missing atlas sword $n" }
        $source = [System.Drawing.Rectangle]::new($minX, $minY, $maxX - $minX + 1, $maxY - $minY + 1)
        $out = [System.Drawing.Bitmap]::new($width, $height, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
        $g = [System.Drawing.Graphics]::FromImage($out)
        $g.Clear([System.Drawing.Color]::Transparent)
        $g.CompositingMode = [System.Drawing.Drawing2D.CompositingMode]::SourceCopy
        $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $g.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
        $pixelOverride = Join-Path $Root "content\swords\remodel\pixel_overrides\w0_$n.png"
        if (Test-Path -LiteralPath $pixelOverride) {
            $override = [System.Drawing.Bitmap]::FromFile($pixelOverride)
            try {
                if ($override.Width -ne $width -or $override.Height -ne $height) {
                    throw "Sword override $n must be ${width}x${height}"
                }
                $g.DrawImageUnscaled($override, 0, 0)
            } finally { $override.Dispose() }
        } elseif ($n -eq 21) {
            # Widen only the original foliage by 50%. The trunk and grip keep
            # their exact original vertical coordinates and proportions.
            for ($sy = 0; $sy -lt $originalTree.Height; $sy++) {
                $factor = if ($sy -le 45) { 1.5 } elseif ($sy -ge 65) { 1.0 } else { 1.5 - 0.5 * ($sy - 45) / 20.0 }
                $rowWidth = [int][Math]::Round($originalTree.Width * $factor)
                $dx = [int][Math]::Floor(($width - $rowWidth) / 2)
                $g.DrawImage($originalTree, [System.Drawing.Rectangle]::new($dx, $sy, $rowWidth, 1),
                    [System.Drawing.Rectangle]::new(0, $sy, $originalTree.Width, 1), [System.Drawing.GraphicsUnit]::Pixel)
            }
        } else {
            $artHeight = if ($n -eq 18 -or $n -eq 26) { [int][Math]::Round(96 * 1.2) } else { $height - 4 }
            $artY = if ($n -eq 18 -or $n -eq 26) { [int][Math]::Floor(($height - $artHeight) / 2) } else { 2 }
            # Sword 32's opaque blade is left of the generated canvas centre.
            # Fit a slightly narrower image so its blade, not its glow margin,
            # lands on the centre line without clipping the opposite edge.
            $artX = if ($n -eq 32) { 13 } else { 2 }
            $artWidth = if ($n -eq 32) { 50 } else { $width - 4 }
            $g.DrawImage($atlas, [System.Drawing.Rectangle]::new($artX, $artY, $artWidth, $artHeight), $source, [System.Drawing.GraphicsUnit]::Pixel)
        }
        $g.Dispose()
        $bestScore = [double]::PositiveInfinity
        $pivotX = [double]$width / 2
        $pivotY = $height - 7.0
        for ($py = [int]($height / 2); $py -lt $height; $py++) {
            for ($px = 0; $px -lt $width; $px++) {
                if ($out.GetPixel($px, $py).A -le 32) { continue }
                $score = [Math]::Abs($px + 0.5 - $width / 2.0) * 2.0 + [Math]::Abs($py + 0.5 - ($height - 7.0))
                if ($score -lt $bestScore) {
                    $bestScore = $score
                    $pivotX = $px + 0.5
                    $pivotY = $py + 0.5
                }
            }
        }
        $path = Join-Path $res "w0_$n.png"
        $out.Save($path, [System.Drawing.Imaging.ImageFormat]::Png)
        $out.Dispose()

        $baselineHeight = if ($n -le 5) { 64 } elseif ($n -le 18) { 96 } else { 128 }
        $handScale = [Math]::Min(1.4, $baselineHeight / [double]$height)
        if ($n -eq 18 -or $n -eq 26) { $handScale = 1.0 }
        $handScaleText = $handScale.ToString('0.000', [cultureinfo]::InvariantCulture)
        $records.Add([pscustomobject]@{
            id = $n; shape = $shape; cols = $cols; rows = $rows; cells = $cells
            width = $width; height = $height; pivotX = $pivotX; pivotY = $pivotY
            handScale = $handScale
        })
        $header.Add("    $cols, $rows, //w0_$n")
    }
    $header.Add('};')
    $header.Add('struct SwordSpriteInfo {')
    $header.Add('    int cols, rows, width, height;')
    $header.Add('    float pivotX, pivotY;')
    $header.Add('    unsigned short cells; // bottom row first; 0 means full rectangle')
    $header.Add('    float handScale; // compensates for inventory remodelling in hero poses')
    $header.Add('};')
    $header.Add('static const SwordSpriteInfo kSwordSprites[36] = {')
    $header.Add('    {0, 0, 0, 0, 0, 0, 0, 1.0f},')
    foreach ($record in $records) {
        $at = ($record.id - 1) * 2
        $scale = $record.handScale.ToString('0.000', [cultureinfo]::InvariantCulture)
        $px = $record.pivotX.ToString('0.0', [cultureinfo]::InvariantCulture)
        $py = $record.pivotY.ToString('0.0', [cultureinfo]::InvariantCulture)
        $header.Add("    {swordTileSize[$at], swordTileSize[$($at+1)], $($record.width), $($record.height), ${px}f, ${py}f, $($record.cells), ${scale}f}, // w0_$($record.id)")
    }
    $header.Add('};')
    $header.Add('inline const SwordSpriteInfo* GetSwordSpriteInfo(int detail) {')
    $header.Add('    return detail >= 0 && detail < 35 ? &kSwordSprites[detail + 1] : 0;')
    $header.Add('}')
    [System.IO.File]::WriteAllLines($headerPath, $header, [System.Text.UTF8Encoding]::new($false))
    $records | ConvertTo-Json -Depth 3 | Set-Content -LiteralPath $manifestPath -Encoding UTF8
    Write-Output "Remodelled $($records.Count) swords"
} finally {
    $atlas.Dispose()
    $originalTree.Dispose()
}
