"""Preserve source pixels: extract the lower pose, turn 90 degrees, pad to cells.

Run from any directory. Original sheets are retained in content/swords/source.
The grip coordinates in profiles.json are measured in the original sheet.
"""
from pathlib import Path
import hashlib
import json
import math
import shutil
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[2]
CONTENT = ROOT / 'content/swords'
CELL = 32


def build():
    profiles = json.loads((CONTENT / 'profiles.json').read_text(encoding='utf-8'))
    source = CONTENT / 'source'
    source.mkdir(parents=True, exist_ok=True)
    records = []
    preview = Image.new('RGB', (7 * 210, 5 * 430), '#262a32')
    draw = ImageDraw.Draw(preview)
    for spec in profiles:
        n = spec['id']
        filename = f'w0_{n}.png'
        original = source / filename
        target = ROOT / 'Resources/res' / filename
        if not original.exists():
            with Image.open(target) as existing:
                if existing.size != (410, 510):
                    raise ValueError(f'{filename}: original sheet is missing')
            shutil.copy2(target, original)
        im = Image.open(original).convert('RGBA')
        alpha = im.getchannel('A')
        # The upper copy can extend past the old CMF rectangle at y=290.
        # Find the transparent gap; never cut at that legacy rectangle boundary.
        empty = [y for y in range(290, 380)
                 if alpha.crop((0, y, im.width, y + 1)).getbbox() is None]
        split = max(empty) + 1
        lower = im.crop((0, split, im.width, im.height))
        box = lower.getbbox()
        left, top, right, bottom = box
        top += split
        bottom += split
        crop = im.crop((left, top, right, bottom))
        upright = crop.transpose(Image.Transpose.ROTATE_90)
        cols = math.ceil(upright.width / CELL)
        rows = math.ceil(upright.height / CELL)
        width, height = cols * CELL, rows * CELL
        assert upright.width <= width and upright.height <= height
        ox, oy = (width - upright.width) // 2, (height - upright.height) // 2
        result = Image.new('RGBA', (width, height))
        # No alpha compositing: preserve even partially transparent edge pixels exactly.
        result.paste(upright, (ox, oy))
        gx, gy = spec['grip']
        px, py = ox + gy + 0.5 - top, oy + right - gx - 0.5
        assert 0 <= px <= width and 0 <= py <= height
        result.save(target, optimize=True)
        records.append(dict(id=n, cols=cols, rows=rows, width=width, height=height,
                            pivotX=px, pivotY=py, sourceRect=[left, top, right, bottom],
                            contentRect=[ox, oy, upright.width, upright.height],
                            sha256=hashlib.sha256(target.read_bytes()).hexdigest()))
        x, y = ((n - 1) % 7) * 210, ((n - 1) // 7) * 430
        for cx in range(cols + 1):
            draw.line((x + cx * CELL, y + 26, x + cx * CELL, y + 26 + height), fill='#414957')
        for cy in range(rows + 1):
            draw.line((x, y + 26 + cy * CELL, x + width, y + 26 + cy * CELL), fill='#414957')
        preview.paste(result, (x, y + 26), result)
        draw.text((x + 4, y + 5), f'w0_{n}  {cols}x{rows}', fill='white')
        draw.ellipse((x+px-2, y+26+py-2, x+px+2, y+26+py+2), fill='#ff6060')
    (CONTENT / 'sprites.json').write_text(json.dumps(records, indent=2) + '\n', encoding='utf-8')
    header = ['// Generated by tools/swords/prepare_swords.py. Pixel coordinates: top-left origin.',
              '#pragma once', f'enum {{ SWORD_TILE_SIZE = {CELL} }};',
              '// Indexed by item detail: [detail * 2] columns, [detail * 2 + 1] rows.',
              'static const int swordTileSize[35 * 2] = {']
    for r in records:
        header.append('    %d, %d, //w0_%d' % (r['cols'], r['rows'], r['id']))
    header += ['};', 'struct SwordSpriteInfo {',
              '    int cols, rows, width, height;', '    float pivotX, pivotY;', '};',
              'static const SwordSpriteInfo kSwordSprites[36] = {', '    {0, 0, 0, 0, 0, 0},']
    for r in records:
        at = (r['id'] - 1) * 2
        header.append('    {swordTileSize[%d], swordTileSize[%d], %d, %d, %.1ff, %.1ff}, // w0_%d' %
                      (at, at + 1, *(r[k] for k in ('width','height','pivotX','pivotY','id'))))
    header += ['};', 'inline const SwordSpriteInfo* GetSwordSpriteInfo(int detail) {',
               '    return detail >= 0 && detail < 35 ? &kSwordSprites[detail + 1] : 0;', '}', '']
    (ROOT / 'Classes/Data/SwordSprites.h').write_text('\n'.join(header), encoding='utf-8')
    out = ROOT / 'output/swords'
    out.mkdir(parents=True, exist_ok=True)
    preview.save(out / 'upright-review.png')
    print(f'Converted {len(records)} swords; originals: {source}')


if __name__ == '__main__':
    build()
